### PR TITLE
Fix macro template

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Review by MaxDesiatov — COMMENTED** [review]
Is there anything that was broken by the lack of this line? If this code didn't compile, couldn't we detect it with an end-to-end test that runs `package init` with this template and then `swift build`?

**Comment by neonichu** [comment]
> Is there anything that was broken by the lack of this line? 

Yes, we were generating the `import XCTest` without any whitespace between it and the previous statement, leading to broken code.

> If this code didn't compile, couldn't we detect it with an end-to-end test that runs package init with this template and then swift build?

In theory yes, in practice we cannot end-to-end test macros today because we can't download swift-syntax on CI and we also don't have all the necessary components in the toolchain to attempt to use that as a replacement.

**Review by MaxDesiatov — APPROVED** [review]

**Comment by neonichu** [comment]
```
[8/20] Testing IntegrationTests.SwiftPMTests/testBinaryTargets
Cancelling nested steps due to timeout
Sending interrupt signal to process
script returned exit code 143
```

**Comment by neonichu** [comment]
@swift-ci please test linux

**Comment by neonichu** [comment]
Looks like macOS self-hosted is also hanging?

**Comment by neonichu** [comment]
My guess would be that it's related to #7269?

**Comment by neonichu** [comment]
> My guess would be that it's related to https://github.com/apple/swift-package-manager/pull/7269?

Actually, all tests should have individual scratch directories, so it doesn't seem super likely for this to be the cause. Can't repro locally, either.

**Comment by neonichu** [comment]
@swift-ci please test linux

**Comment by neonichu** [comment]
@swift-ci please test macOS

**Pull request merged**
