### PR TITLE
Cherry-pick approved fixes into swift-3.0-branch for next bugfix release

### PR DESCRIPTION
**Pull request by abertelrud**
The commits in the pull request are being cherry-picked onto the swift-3.0-branch to be included in the next bugfix release.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
Linux failure is independent of SwiftPM.  Will try to do manual Linux testing of this PR.

**Comment by abertelrud** [comment]
Updates the merge list.  Local tests pass on macOS 10.12 and Ubuntu 10.04 LTS.

**Comment by abertelrud** [comment]
@swift-ci Please test

**Comment by abertelrud** [comment]
Linux failure seems to be unrelated, in building swift-corelibs-libdispatch

**Comment by abertelrud** [comment]
I would like to get a clean Linux build before landing this, though local testing on 14.04 and 15.10 passes.  I'm going to make sure that the Linux issue is known.

**Comment by abertelrud** [comment]
@swift-ci please test linux

**Comment by abertelrud** [comment]
Closed by mistake (hit the wrong button) but reopened — one more try with Linux testing before merging.  All local testing works.

**Comment by abertelrud** [comment]
@swift-ci please test linux

**Comment by abertelrud** [comment]
Linux test passes now (it was always unrelated, but merging the diffs feels better with it resolved).

**Comment by aciidb0mb3r** [comment]
oh wow, great

**Pull request merged**
