### PR TITLE
Migrate Workspace delegate warnings to diagnostics

### PR DESCRIPTION
**Pull request by hartbit**

### CODE REVIEW

**Comment by hartbit** [comment]
@aciidb0mb3r I've done all but one warning. I've left it because I'm not 100% sure when and how it happens so can't find a good name for it. Can you elaborate on it?

https://github.com/apple/swift-package-manager/pull/1148/files#diff-16a17153d6f335742f5d4039edf8be5eL900

Thanks!

**Comment by aciidb0mb3r** [comment]
It is when we do dependency resolution and a package is removed but is still in edited mode. I am fine with having a FIXME there because we need to rework that part with the new proposal

**Comment by aciidb0mb3r** [comment]
This is great, thanks! We will need to update tests I think.

**Comment by hartbit** [comment]
@aciidb0mb3r Yep, my next commit will fix the tests. But I think we may be missing a few tests actually. To be honest, I think we may even be missing a few tests for some errors too.

**Comment by aciidb0mb3r** [comment]
Oh? It will be nice to get tests for them (considering we won't lose them with the upcoming proposal)

**Comment by hartbit** [comment]
@aciidb0mb3r Ready for review :)

**Comment by aciidb0mb3r** [comment]
LGTM, thanks!

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Pull request merged**
