### PR TITLE
[PackageDescription] Add missing relative SDK rpath to libPackageDescription.so shared libraries

### PR DESCRIPTION
**Pull request by buttaface**
Without this, both the latest official master and 5.2 snapshots for linux show the following toolchain rpath from the build CI instead:
```
readelf -d swift-DEVELOPMENT-SNAPSHOT-2020-03-19-a-ubuntu18.04/usr/lib/swift/pm/4*/libPackageDescription.so | ag "File:|runpath"
File: swift-DEVELOPMENT-SNAPSHOT-2020-03-19-a-ubuntu18.04/usr/lib/swift/pm/4/libPackageDescription.so
 0x000000000000001d (RUNPATH)            Library runpath: [/home/buildnode/jenkins/workspace/oss-swift-package-linux-ubuntu-18_04/swift-nightly-install/usr/lib/swift/linux]
File: swift-DEVELOPMENT-SNAPSHOT-2020-03-19-a-ubuntu18.04/usr/lib/swift/pm/4_2/libPackageDescription.so
 0x000000000000001d (RUNPATH)            Library runpath: [/home/buildnode/jenkins/workspace/oss-swift-package-linux-ubuntu-18_04/swift-nightly-install/usr/lib/swift/linux]
```
That won't work on any hosts other than the build CI servers, I used a version of this patch for [my latest Android packaging script for Swift 5.2](https://github.com/buttaface/termux-packages/commit/886cc62e728081b059bec6fa89541475d0d5b735#diff-49d3fe0505b12cff1f474dc64b78d001R14).

Running some tests on a different CI server with the release builds would likely catch issues like this.

### CODE REVIEW

**Comment by buttaface** [comment]
I looked into this a bit more, by building and running SwiftPM and its tests both with a recent official 5.2 snapshot release for linux and by building the 3/6 snapshot on Android, both with and without this patch and removing the toolchain rpath, and then building and running SwiftPM and its tests with SwiftPM. I saw no difference without this pull, so it looks like it makes no difference for SwiftPM.

However, if something else links against `libPackageDescription.so`, particularly C code, I think this wrong rpath will matter. [This relative rpath was added before but removed with the switch to the new bootstrap script](https://github.com/apple/swift-package-manager/commit/cc396d0142896cd69074743d7b0c7741fe23567e#diff-296aa080a049a48a75c47e0a2926fde0L689), but the CMake build that replaced it didn't include it. This pull fixes that.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by buttaface** [comment]
The two CI failures appear spurious.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
We're holding this PR until the Swift 5.3 branch gets created.

**Comment by buttaface** [comment]
I don't understand: if it goes into master now, it will get into the 5.3 branch too, right? You mean you don't want it in the 5.3 branch?

**Comment by neonichu** [comment]
Yah, exactly, we don't want any changes that aren't strictly necessary for it to end up in the 5.3 branch right now.

**Comment by buttaface** [comment]
OK, but just to let you know, this relative rpath was there till 5.1, 5.2 is the only release not to have it.

**Pull request merged**
