### PR TITLE
[ResolveTool] Add an json dumping option

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This adds option to to dump resolution information in JSON format in the
hidden resolve tool.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@ddunbar mind if I add this mode? Looks like resolve tool is hidden anyway
This will help in extracting and saving dependency data from real world repos.

**Comment by ddunbar** [comment]
LGTM

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Pull request merged**
