### PR TITLE
[Build] Consider Swift on Clang Modules as build order dependency

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Currently swiftpm fatalError() when some swift package is dependency
on a package containing c languages or mixed languages. This shouldn't
error out. Swift will not be importable to c modules but there could be
swift modules in that package which want to use some external deps.
Considering it as a build order dependency should be ok.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
I am also fine with not considering it as build order dependency and just ignore it in general for clang modules but in any case erroring or rather `fatalError()` out seems wrong.

**Comment by ddunbar** [comment]
I agree with not `fatalError`-ing out, but I don't understand this comment:

> Swift will not be importable to c modules but there could be swift modules in that package which want to use some external deps.

You mean the C target might want to use some of the external dependencies declared only on the Swift target?

**Comment by aciidb0mb3r** [comment]
Yes, consider this Package with two modules A(ClangModule) and B(SwiftModule)
```
├── Package.swift
└── Sources
    ├── A
    │   ├── clib.c
    │   └── include
    │       └── clib.h
    └── B
        └── main.swift
```

so this package fatalErrors if you declare a (swift) dependency in Package.swift

**Comment by ddunbar** [comment]
Oooooh, that seems horrible.

**Comment by ddunbar** [comment]
Yes, for now let us just fix it to consider a build order dependency.

**Comment by ddunbar** [comment]
Can we get a test case here?

Also, are you sure we don't need to do something special in `Build` to avoid making the C target link against the Swift target (which I'm not sure makes sense). It is unfortunate we don't explicitly model the build order vs link inclusion requirement internally.

**Comment by aciidb0mb3r** [comment]
Done. It won't try to link with the ClangModule because we filter the modules before making a product.
Yea all this is very fragile right now ☹️

**Comment by ddunbar** [comment]
Can we not test this without fixtures?

**Comment by ddunbar** [comment]
(the problem with the fixtures test is it isn't obvious anywhere in the test code what is trying to be tested, would be very easy to drop that part when refactoring tests)

**Comment by aciidb0mb3r** [comment]
Added but it isn't a good one, this was best I could do right now...

**Comment by abertelrud** [comment]
Sounds like a great improvement.  Thanks @aciidb0mb3r

**Comment by abertelrud** [comment]
What's the next step here?  I'm fine with this since it is definite progress, even if not ideal.  @ddunbar ?

**Comment by ddunbar** [comment]
I agree. I think we should track improving our test infrastructure for this situation somewhere else, it seems useful to be able to test this on a pseudo-package layout.

**Pull request merged**
