### PR TITLE
replace custom downloader with http-client

### PR DESCRIPTION
**Pull request by tomerd**
motivation: SwiftPM now has an http client with additional features and that is designed to work across the platforms more robustly. the downloader used to download XCFrameworks is in TSC and hard wired to Founddation.Networking. this replaces the downloader with the http client

changes:
* add downloading functionality into http-client by introducing "request kind" enum: generic or download
* update workspace to use the http-client instead of the downloader
* migrate downloader unit tests to http-client to confirm behavior
* adjust workspace tests

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by sstadelman** [comment]
@tomerd is this new client compatible with the netrc authentication feature:  https://github.com/apple/swift-package-manager/pull/3015?

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
> @tomerd is this new client compatible with the netrc authentication feature: #3015?

thanks for bringing this up @sstadelman, yes it's feature compatible: https://github.com/apple/swift-package-manager/pull/3303/files#diff-134223fe78a1e46f08f8c1e9d166408b7105f941cb2cc4e844ebceb87a8f4ec8R1603

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Review by neonichu — APPROVED** [review]
LGTM, but effectively we are still using `FoundationNetworking`, right?

**Comment by tomerd** [comment]
> LGTM, but effectively we are still using FoundationNetworking, right?

that is correct, but this is something we can now change for non-darwin and have it take effect over the entire system

**Review by abertelrud — APPROVED** [review]
LGTM

**Pull request merged**
