### PR TITLE
update min version of swift-system

### PR DESCRIPTION
**Pull request by tomerd**
motivation: use the correct minimum version of swift-system

changes: update min version of swift-system to 1.1.1

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
cc @neonichu

**Comment by tomerd** [comment]
https://github.com/apple/swift-tools-support-core/pull/270

@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
ci failures addressed in https://github.com/apple/swift-package-manager/pull/3951

**Comment by tomerd** [comment]
apple/swift-tools-support-core#270

@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
