### PR TITLE
Changing recursive implementation of graph algorithms to iterative

### PR DESCRIPTION
**Pull request by mattapet**
`topologicalSort` and `findCycle` function from the `Basic` module has `FIXME`s saying the needed to be converted to use stack instead of recursion.

Both algorithms have pretty much the same implementation. System stack and recursion is emulated using `OrderedDictionary` collection which key-value pair represents a single stack frame. The key is a node that is being traversed and the value is an array slice of its successors.

### CODE REVIEW

**Comment by tomerd** [comment]
@mattapet sorry about the slow response. is this something you still want to pursue? needs a rebase

**Comment by mattapet** [comment]
No worries @tomerd. I definitely would like to pursue this forward. I should have some time this weekend to rebase and fix issues that may arise.

Thanks!

**Comment by mattapet** [comment]
Sorry @tomerd for almost two week delay, but I've rebased it and it shoud be ready now.

**Comment by abertelrud** [comment]
This looks like a good improvement, @mattapet.  Thanks contributing this fix!

I'm not sure why there were originally two separate implementations -- I'm guessing it was to avoid keeping the information that would be needed to report a cycle in the common case of there not being a cycle.  Since the stack is now available as part of the main algorithm, the new implementation also looks as if it brings us closer to being to unify them (and include the cycle information in the thrown error).  Is that your assessment as well?  Certainly not needed for this PR, but that would be another great improvement eventually.

Thanks!

**Review by abertelrud — APPROVED** [review]

**Comment by abertelrud** [comment]
@swift-ci  please smoke test

**Comment by mattapet** [comment]
Thanks a lot @abertelrud! I was actually thinking about looking into it after this one would have been done. So if you guys think that unification of the two would be something that the project would benefit, I would be more than happy to investigate it further.

**Comment by abertelrud** [comment]
Yes, I think that would be great — I am not the original author of this code and don't know what the original intent was, but it looks as if the new implementation is very similar between the two, and so unifying them would be a good thing.  It doesn't have to be done as part of this PR, of course, so I can merge this when the tests are done if you feel it's ready.

**Comment by abertelrud** [comment]
@swift-ci  please test

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by mattapet** [comment]
I see a few thing that might have been done a bit differently, but since now it would require pretty much duplicating the code, I'd rather keep those changes for the next unifying PR. I'll try find the use cases of the `findCycle` func and investigate potential replacement options.

So if the tests pass, I'd be more than happy if you could merge 😊

**Comment by abertelrud** [comment]
Sounds good.  Thanks again for your work here!

**Pull request merged**
