### PR TITLE
Move `makeDirectories()` down from Utility to Basics

### PR DESCRIPTION
**Pull request by abertelrud**
Move `makeDirectories()` down from Utility to Basics, also changing String to AbsolutePath, which means that all the call sites can remove the `.asString` references.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
This PR is based on #503, so the Linux failure is the same as in #503.

**Comment by abertelrud** [comment]
So it will get fixed automatically here when I fix it there.

**Comment by ddunbar** [comment]
LGTM

**Comment by abertelrud** [comment]
Local test on Ubuntu 15.10 succeeds, and the test failures on the bot seemed unrelated.  Merging.

**Pull request merged**
