### PR TITLE
PackageModel: correct and improve XCTest location on Windows

### PR DESCRIPTION
**Pull request by compnerd**
This corrects a long standing issue in locating XCTest on Windows.  We
erroneously assumed that we could use `DEVELOPER_DIR` to construct a
path to XCTest.  However, this is not correct for two reasons:

  1. We may be targeting something other than Windows
  2. We may have passed `-sdk` explicitly, which would move the
     location of the SDK to something that no longer is relative
     to `DEVELOPER_DIR`.

Instead, we now construct the path relative to `SDKROOT` OR the explicit
SDK specified.  This reduces the dependency on the environment, and
makes `SDKROOT` behave as intended as well as completely drops the need
for `DEVELOPER_DIR` within SPM.

This will also restore the ability for us to have relocatable SDK
installations on Windows which eases some local testing for parallel SDK
installations.

_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Review by abertelrud — APPROVED** [review]

**Review by neonichu — APPROVED** [review]

**Comment by compnerd** [comment]
@abertelrud - is this okay to merge?  (If so, I'd likely do it over the weekend after I give this a tad bit more testing)

**Comment by abertelrud** [comment]
> @abertelrud - is this okay to merge? (If so, I'd likely do it over the weekend after I give this a tad bit more testing)

Yes, this looks good to me.  Thanks @compnerd!

**Comment by abertelrud** [comment]
Hi @compnerd — I just wanted to make sure you're not waiting for me to merge this.  Happy to leave it open if you're planning to do so later; no hurry, just figured I'd check.

**Comment by compnerd** [comment]
There were some things that came up.  I want to wait until we have a green CI on the toolchain before merging this.

**Pull request merged**
