### PR TITLE
Bring PkgConfig parsing to greater parity with pkg-config

### PR DESCRIPTION
**Pull request by aemino**
This PR includes two main changes:
- Parses `Required.private` dependencies in `pc` files and adds their `cFlags` to the main `PkgConfig` instance. The `pkg-config` command line tool seems to add only private `cFlags` (not `libs`) when using the `--cflags` flag.
- Adds the `pc_sysrootdir` global variable to `PkgConfigParser`. This is simply a global variable that `pkg-config` includes but the parser does not.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Thanks for the PR. Do you have use cases where this is required for Swift packages?

**Comment by aemino** [comment]
@aciidb0mb3r Yeah, the reason that I made this PR was because I was trying to develop a systemLibrary wrapper package, but I couldn't get it to compile because it was missing header search paths. Eventually I realized that `pkg-config` was showing these header search paths with `--cflags`, but SPM was not using these, and the reason that this was occurring was because `pkg-config` includes private cflags when using `--cflags`, whereas SPM does not when aggregating these flags.

**Comment by aemino** [comment]
Hi @aciidb0mb3r, just a friendly request to review this PR. Thanks! :smile:

**Comment by aciidb0mb3r** [comment]
Sorry, this slipped my mind. You're always free to ping me after a few days of inactivity!

This PR looks good! Can you add a unit test? Look at PkgConfigTests.swift for existing pkgconfig parser tests.

**Comment by aemino** [comment]
@aciidb0mb3r I added two very simple tests to PkgConfigParserTests. Let me know if more in-depth tests are needed or if it's sufficient as is.

**Comment by aciidb0mb3r** [comment]
Looks great! Thanks!

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aemino** [comment]
It seems there was a test failure because some of the tests require every pkg-config variable to be accounted for. Is the best solution here to add that variable to all of the checks?

**Comment by aemino** [comment]
@aciidb0mb3r Friendly ping :)

**Comment by aciidb0mb3r** [comment]
I think so? Unless you think that won't be valuable.

**Comment by aemino** [comment]
Well, I don't think that it will be very valuable as a test. The implementation I added for the one instance of variable checking is already rather useless; it just replicates the functionality of the code it is testing. That said, it would be out of the scope of this PR to refactor the code such that it doesn't need to check for the environment variable that's being added.

I'm not even certain what the `PKG_CONFIG_PATH` env variable would be... If I just assume that it isn't set, then I can add `"pc_sysrootdir": "/"` to every `parser.variables` assertion.

**Comment by aciidb0mb3r** [comment]
Is using `PKG_CONFIG_PATH` even right? That is supposed to contain a colon separated list of paths, how will that work as a sysroot?

**Comment by aemino** [comment]
Ah! I have no idea how that slipped past me. It should be `PKG_CONFIG_SYSROOT_DIR`. I have made that change locally, but I'm still not sure what to do about the tests.

**Comment by aemino** [comment]
@aciidb0mb3r Ignoring the gaffe with `PKG_CONFIG_SYSROOT_DIR`, I'm not sure what to do about the tests... should the `parser.variables` assertion always expect `pc_sysrootdir` to be `"/"`?

**Comment by aciidb0mb3r** [comment]
We can create an extension in the test code that has a computed property of all the variables without the `pc_sysrootdir` key and we assert that in the tests?

**Comment by aemino** [comment]
I've attempted to fix the pkgconfig tests and (rather messily) resolved the conflicts created by the TSC restructure.

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aemino** [comment]
@aciidb0mb3r The smoke tests seem to have completed.

**Pull request merged**
