### PR TITLE
Warn the user about potential test bundle failures

### PR DESCRIPTION
**Pull request by neonichu**
On Linux, there is no test bundle, but an executable. This leads to cryptic errors when sharing the `.build` folder, e.g. when using Docker. This provides the user with some more actionable output.

Alternatively, we could also just remove the offending file/directory since that would be happening anyway if the file type would be what we expected.

### CODE REVIEW

**Comment by ddunbar** [comment]
This is for cases when you are switching between building on macOS and building on Linux? Do we even want that to work this way -- as implemented it is going to do a full rebuild each time you switch, right?

If that is desirable behavior, it seems we would be better off by segregating the build artifacts by platform -- what do you think?

**Comment by neonichu** [comment]
Yah, that was exactly the case where I was running into it. Separating the artefacts per platform sounds like a much better solution, though.

**Comment by ddunbar** [comment]
@aciidb0mb3r should we close this?

**Comment by aciidb0mb3r** [comment]
Yup, tracking here: https://bugs.swift.org/browse/SR-3583

**Pull request closed without merging**
