### PR TITLE
Remove old Workspace errors

### PR DESCRIPTION
**Pull request by hartbit**
The old `WorkspaceError` enum is not used anymore.

### CODE REVIEW

**Comment by hartbit** [comment]
@swift-ci please smoke test

**Comment by hartbit** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
👏

**Comment by hartbit** [comment]
@swift-ci please smoke test

**Comment by hartbit** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
It is very annoying

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Pull request merged**
