### PR TITLE
Revert "Update to swift-certificates 0.4.0"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift-package-manager#6316

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
We can't revert just the SwiftPM PR. It requires corresponding update-checkout changes as well.

I will look into patching `swift-certificates`.

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/6465 updates `swift-certificates` to `0.4.1` which contains the patch required.

**Comment by MaxDesiatov** [comment]
Can this be closed now that https://github.com/apple/swift-package-manager/pull/6465 is merged?

**Pull request closed without merging**
