### PR TITLE
[Basic] Add await() to convert async methods to sync

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This is a common pattern used in some of the places, this utility will
avoid the repititive code.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
Do you know if there is existing precedent for this API and name in any other commonly used Swift library?

Seems ok to me but would like to make sure it is consistent.

**Comment by aciidb0mb3r** [comment]
Hm, I haven't seen any mass usage of such APIs in Swift community

**Pull request merged**
