### PR TITLE
[SR-4195] non throwing whitelist

### PR DESCRIPTION
**Pull request by tanner0101**
Changes the `whitelist` method to filter out non whitelisted flags instead of throwing when a non-whitelisted flag is found.

## Background

Currently Vapor is using a custom pkgconfig-like system to gather and apply build flags. This works through a `vapor.json` file at the root of the repository (e.g, [mysql](https://github.com/vapor/mysql/blob/1.1.2/vapor.json)) that the Vapor toolbox can then parse and use to apply flags.

Obviously this solution only works if the end user is using the Vapor toolbox, and has made it difficult for Vapor developers to use native SPM (`swift build`, `swift test`, etc) commands. 

In Vapor 2, we were hoping to move to the pkg-config system to remove the need for build flags in native SPM and the custom Toolbox build flag system.

This has worked so far really well except for one blocking issue [[SR-4195]](https://bugs.swift.org/browse/SR-4195). 

### Issue

Build flags not whitelisted by SPM are failing the builds. So common `.pc` files like MySQL's which has some additional build flags prevent SPM from compiling. 

#### Discard

Discarding any non-whitelisted build flags and warning that they've been discarded would allow many more `.pc` files to be compatible with the SPM build system.

This is the approach taken in this PR.

#### Add Specific Flags

The flags causing MySQL's `.pc` file to fail could be added to a "discardable" list of flags.

- `-fabi-version=2`
- `-fno-omit-frame-pointer`

This solution still has the potential issue of breaking builds for some `.pc` files we may not yet know about.

#### Manually Modify `.pc` files

We could distribute commands to remove these non-whitelisted flags from the `.pc`  files themselves such as:

```sh
# linux
sudo sed -i 's/-fabi-version=2 -fno-omit-frame-pointer/ /g' /usr/lib/x86_64-linux-gnu/pkgconfig/mysqlclient.pc
# macos
sudo sed -i '.bak' 's/-fno-omit-frame-pointer/ /g' /usr/local/opt/mysql/lib/pkgconfig/mysqlclient.pc 
```

This solution is not ideal since it creates extra steps for the end user and could create issues elsewhere.

### Swift 3.1

This issue will make or break Vapor's ability to use the pkgConfig system in Swift 3.1 (which Vapor 2 will be relying on). As such, we would greatly appreciate this issue being viewed as a bug and to help patch it in time for Swift 3.1.

### CODE REVIEW

**Comment by rballard** [comment]
Thanks for the clear and detailed explanation, Tanner. Unfortunately I think it's too late to get further fixes into Swift 3.1. I'll double-check with Ted before closing this PR, however. In the meantime, you should definitely get this into master. I'm not sure if we're going to do a 3.1.1, but if we did this would also be a good candidate fix to pull in at that time.

**Comment by tkremenek** [comment]
As @rballard says this is very late for 3.1.  Let's take for the 3.1 branch as there is always the possibility of minor updates to 3.1 (which will be assessed based on the changes driving an update).

**Comment by tkremenek** [comment]
This should go into `master` first, however.   All changes should be staged that way.   We should never propose a change for the release branch until it is already on `master`.

**Comment by tanner0101** [comment]
@tkremenek @rballard that's understandable. I've re-opened this PR against the master branch. https://github.com/apple/swift-package-manager/pull/1010

**Pull request closed without merging**
