### PR TITLE
cleanup force unwraps in a test utillity

### PR DESCRIPTION
**Pull request by tomerd**
motivation: easier to debug test failures

changes: replace force unwraps in InMemoryGitRepository with explcity exception that provide more detailed error message

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
