### PR TITLE
begin to integrate SwiftSystem

### PR DESCRIPTION
**Pull request by tomerd**
motivation: SwiftSystem provides infra that can replace some bespoke implementations in TSC and SwiftPM, improving the cross-platform support

changes: add SwiftPM and CMake setup for including SwiftSystem as a dependency

### CODE REVIEW

**Comment by tomerd** [comment]
requires:
* https://github.com/apple/swift-system#73
* https://github.com/apple/swift-tools-support-core/pull/262
* https://github.com/apple/swift-driver/pull/915
* https://github.com/apple/sourcekit-lsp/pull/437

**Comment by tomerd** [comment]
cc @compnerd

**Review by abertelrud — APPROVED** [review]

**Comment by compnerd** [comment]
This needs accompanying changes to swift-installer-scripts to package up the new dependencies into the installer.  I'll need to adjust the Windows builds on Azure accordingly for the nightlies, and we should also update the scripts in apple/swift at utils/build-windows-toolchain.bat (this is in preparation for migrating the windows release/nightlies to swift.org, and is actually currently in use at https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/)

**Review by compnerd — CHANGES_REQUESTED** [review]
This needs accompanying changes to swift-installer-scripts to package up the new dependencies into the installer. I'll need to adjust the Windows builds on Azure accordingly for the nightlies, and we should also update the scripts in apple/swift at utils/build-windows-toolchain.bat (this is in preparation for migrating the windows release/nightlies to swift.org, and is actually currently in use at https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/)

**Comment by tomerd** [comment]
https://github.com/apple/swift-tools-support-core/pull/262
https://github.com/apple/swift-driver/pull/915
https://github.com/apple/sourcekit-lsp/pull/437

@swift-ci please smoke test

**Comment by tomerd** [comment]
apple/swift-tools-support-core#262
apple/swift-driver#915
apple/sourcekit-lsp#437

@swift-ci please smoke test

**Comment by tomerd** [comment]
apple/swift-tools-support-core#262
apple/swift-driver#915
apple/sourcekit-lsp#437

@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]
I think that nearly everything should be in place for this now.

**Review by neonichu — APPROVED** [review]

**Pull request merged**
