### PR TITLE
[5.5] Fix crash with absolute path to binary artifact

### PR DESCRIPTION
**Pull request by neonichu**
5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3737

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
```
17:12:21 Testing Time: 463.01s
17:12:21   Unsupported        :  1698
17:12:21   Passed             : 12887
17:12:21   Expectedly Failed  :    26
17:12:21   Unexpectedly Passed:     1
```

🤣

**Comment by neonichu** [comment]
@swift-ci please test linux

**Comment by neonichu** [comment]
Seems like that failure is persistent.

**Review by tomerd — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
```
20:05:12 
/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swiftpm/Tests/WorkspaceTests/WorkspaceTests.swift:6782:60: error: cannot find 'ToolchainConfiguration' in scope
20:05:12             let manifestLoader = ManifestLoader(toolchain: ToolchainConfiguration.default)
20:05:12                                                            ^~~~~~~~~~~~~~~~~~~~~~
20:05:12 /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swiftpm/Tests/WorkspaceTests/WorkspaceTests.swift:6786:28: error: extra argument 'location' in call
20:05:12                 location: .init(forRootPackage: sandbox, fileSystem: fs),
20:05:12                           ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Possibly a mismatched ToolsSupportCore?

**Comment by abertelrud** [comment]
Oh wait, no of course, ToolchainConfiguration is a `main` thing, not in 5.5.  The patch will need to be updated.

**Comment by abertelrud** [comment]
Pushed a change to adapt the unit test back to the 5.5 APIs.

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Pull request merged**
