### PR TITLE
Gate new tests on `supportsSDKDependentTests()`

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
```
Failed Tests (1):
  Swift(windows-x86_64) :: SourceKit/CompileNotifications/enable-disable.swift
```

**Comment by neonichu** [comment]
@swift-ci please test windows

**Review by bnbarham — APPROVED** [review]
I really think we need to get to the bottom of the flakiness here, but approving to unblock PRs 👍

**Pull request merged**
