### PR TITLE
[RFC] Infrastructure for line/column numbers in manifest diagnostics

### PR DESCRIPTION
**Pull request by owenv**
This builds on #3034 , so only the very last commit has the relevant changes.

### Motivation:

Support reporting line numbers for manifest diagnostics emitted by SwiftPM for display on the command line/IDEs. 

### Modifications:

- Added a new DiagnosticLocation type, DependencyDeclSourceLoc. If we adopt this approach, this can be expanded to include TargetDeclSourceLoc, ProductDeclSourceLoc, ProductTargetsListSourceLoc, etc.
- The PackageSyntax module conforms DependencyDeclSourceLoc to ManifestSourceLocation, using SwiftSyntax to determine the location in the manifest to emit the diagnostic at
- If built with SPM_ENABLE_PACKAGE_SYNTAX, the default diagnostic engine will dynamically check for the ManifestSourceLocation conformance and perform resolution if possible

The extra indirection preserves the PackageSyntax bootstrapping introduced in  #3034, preserving the ability to build SwiftPM without a full checkout of the compiler, swift-syntax, etc.

I'd be interested in hearing people's thoughts on the approach here. Rolling this infrastructure out across SwiftPM would take a decent amount of effort, so I want to make sure everyone's happy with the approach first.

### Result:

If SwiftPM is built with SPM_ENABLE_PACKAGE_SYNTAX, eligible errors will be reported with line and column numbers

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Thanks for taking the initiative for this, @owenv!  It would really improve the diagnostics.

One concern I do have is that, if I understand correctly, it would only work for manifests that are purely declarative (since it uses SwiftSyntax).  There is also some risk that any future changes to the package manifest would require matching changes to the parsing logic here.

I've been thinking along the lines of runtime collection of this information, by capturing a backtrace from the point in libPackageDescription at which the issue is detected, and then using debug information to determine the source line (and maybe also column).  This would have the advantage of working for any kind of package manifest, though it would require the manifest to be compiled with debug symbols enabled.  I also don't know how cross-platform this could be, but I'm thinking it might potentially be a bit more robust, since it would work for any manifest and would be immune to package description API changes.  WDYT?

**Comment by abertelrud** [comment]
An alternative approach, which would be a bit messier and also only produce line information, would be to add `line: Int = #line` annotations to all the declarations.

**Comment by owenv** [comment]
@abertelrud thanks for taking a look!

You're right that this won't work for non-declarative manifests, and it would require more ongoing maintenance than the alternatives. However it does provide more detailed source location information, which has a couple advantages IMO:

- Many calls to PackageDescription functions span multiple lines, for example target dependency lists. If we want to emit a diagnostic for a specific target dependency entry, the SwiftSyntax approach is likely to be more accurate than a line/column from a backtrace because it can point to the string literal inside the array literal argument, which might be several lines down from the start of the function call for a more complicated package.
- Similarly, because SwiftSyntax can locate individual arguments, it makes fix-its that rewrite them possible for a lot of common errors

I think the second could maybe be accomplished using debug info with some new runtime support, but I'm not sure about the first. That said, any of the solutions proposed would be a massive improvement over the status quo, so I'd have no problem dropping this if the tradeoffs don't seem worth it.

**Comment by owenv** [comment]
I'm going to close this for now rather than try to keep it up to date with the other syntax PRs, it can always be revisited later

**Pull request closed without merging**
