### PR TITLE
[PackageLoading] declare built-in file rules with `let` instead of `var`

### PR DESCRIPTION
**Pull request by YuAo**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by YuAo** [comment]
@aciidb0mb3r Any idea why the tests on linux failed? Seems unrelated to this PR.

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by aciidb0mb3r** [comment]
There's a flaky issue that's haunt the CI bots :(

**Pull request merged**
