### PR TITLE
Update Process to add workingDir and stderr redirect support.

### PR DESCRIPTION
**Pull request by sergiocampama**
Brings back the following PRs from TSC:

https://github.com/apple/swift-tools-support-core/pull/69
https://github.com/apple/swift-tools-support-core/pull/74
https://github.com/apple/swift-tools-support-core/pull/75

### CODE REVIEW

**Comment by sergiocampama** [comment]
@swift-ci test

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by sergiocampama** [comment]
@swift-ci smoke test

**Comment by sergiocampama** [comment]
@swift-ci test

**Comment by sergiocampama** [comment]
@swift-ci test

**Comment by aciidb0mb3r** [comment]
I did a TSC sync recently

**Pull request closed without merging**
