### PR TITLE
[5.10] Fix non-tarballed SDK installation with remote URL (#7312)

### PR DESCRIPTION
**Pull request by kateinoigakukun**
🍒 https://github.com/apple/swift-package-manager/pull/7312

* **Explanation**:  https://github.com/apple/swift-package-manager/commit/4714ea92ad268f4b586a545df2b16bda1c697a26 introduced a regression where non-tarball SDKs could not be installed from a remote URL due to the wrong assumption that the downloaded file would always be a tarball.
* **Scope**: Experimental Swift SDK installation
* **Risk**: Low, only affects to `swift experimental-sdk` command, which is still experimental. Also doesn't impact other binaries or SwiftPM clients/libraries.
* **Testing**: Some new unit tests are added in this change.
* **Reviewer**: @MaxDesiatov 
* **Main branch PR**: https://github.com/apple/swift-package-manager/pull/7312

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci Please test

**Comment by MaxDesiatov** [comment]
@kateinoigakukun would you mind adding a filled in form to the PR description with Explanation/Scope/Risk/Testing etc fields matching recent 5.10 PRs, like this one for example? https://github.com/apple/swift-package-manager/pull/7308

**Comment by kateinoigakukun** [comment]
Gentle ping :)

**Comment by MaxDesiatov** [comment]
Unfortunately, it doesn't look this will make it in time for 5.10.0 as the bar for that is very high. It may still be eligible for subsequent patch 5.10.x releases if those happen, so I'll keep this PR open for now.

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Review by airspeedswift — APPROVED** [review]

**Review by MaxDesiatov — DISMISSED** [review]

**Review by MaxDesiatov — COMMENTED** [review]
We need to hold off merging this unfortunately for a bit more time. There are infrastructure changes requires for this to land correctly post 5.10.0

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
