### PR TITLE
update ProcessInfo.processInfo() on Linux to match Darwin version

### PR DESCRIPTION
**Pull request by jpsim**
Fixes https://ci.swift.org//job/oss-swift-incremental-RA-linux-ubuntu-15_10/7280/consoleFull#1050104696ee1a197b-acac-4b17-83cf-a53b95139a76 /cc @ddunbar

### CODE REVIEW

**Comment by jpsim** [comment]
Sorry should've pinged @parkera

**Comment by parkera** [comment]
Sorry, I missed this - I just merged a different PR #602.

**Comment by parkera** [comment]
I think we had the same diff. I'll go ahead and close this. Let me know if I missed something.

**Comment by jpsim** [comment]
No problem, same effect as far as I'm concerned.

**Pull request closed without merging**
