### PR TITLE
Revert "Avoid use of `temp_await` in `PackageRegistryToolTests.swift`"

### PR DESCRIPTION
**Pull request by neonichu**
Reverts apple/swift-package-manager#7015

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by drexin** [comment]
@swift-ci test windows

**Review by kavon — APPROVED** [review]

**Comment by kavon** [comment]
Merging to unblock CI.

**Comment by MaxDesiatov** [comment]
Thanks! Apologies I didn't retrigger CI on the original PR.

**Pull request merged**
