### PR TITLE
Switch to swift-crypto v2.x

### PR DESCRIPTION
**Pull request by yim-lee**
rdar://82934196

Update to swift-crypto ~~2.2.1~~ ~~2.2.2~~ 2.2.3

### CODE REVIEW

**Comment by yim-lee** [comment]
**TODO**: I will work on the update-checkout changes next week.

**Review by neonichu — APPROVED** [review]

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289

@swift-ci smoke test

**Comment by yim-lee** [comment]
Opened https://github.com/apple/swift-crypto/pull/136 in attempt to address Windows build failure.

**Comment by neonichu** [comment]
side-note: #5917 will help with this type of failure as well since the CMake build won't build the (unused on Windows) collections stuff anymore

**Comment by yim-lee** [comment]
@neonichu Yeah, I suppose another option is for this to wait for merging of https://github.com/apple/swift-package-manager/pull/5917 if that happens sooner.

**Comment by yim-lee** [comment]
Testing https://github.com/apple/swift-crypto/pull/136

https://github.com/apple/swift/pull/62320
@swift-ci smoke test

**Comment by yim-lee** [comment]
https://ci-external.swift.org/job/swiftpm-PR-windows/596/

```
Error on repo "C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift-crypto": Traceback (most recent call last):
  File "C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift\utils\update_checkout\update_checkout\update_checkout.py", line 167, in update_single_repository
    config, repo_name, scheme_name, scheme_map, cross_repos_pr)
  File "C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift\utils\update_checkout\update_checkout\update_checkout.py", line 140, in get_branch_for_repo
    echo=True)
  File "C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift\utils\swift_build_support\swift_build_support\shell.py", line 255, in run
    raise eout
Exception: ['git', 'checkout', 'yim-lee-patch-1']
```

Pretty sure the branch `yim-lee-patch-1` exists in `swift-crypto` (https://github.com/apple/swift-crypto/pull/136). Am I missing something obvious? 👀 @shahmishal @neonichu

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62320
@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289

@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62320

@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289

@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289

@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289

@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289

@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62320

@swift-ci smoke test

**Comment by yim-lee** [comment]
Test swift-crypto 2.2.2

https://github.com/apple/swift/pull/62289
@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci please smoke test Linux

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289

@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
I've fixed Windows build issues, I'll kick off a new build for that.

@swift-ci please test Windows

**Comment by yim-lee** [comment]
@swift-ci please test Linux

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289

@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289

@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci please test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci smoke test windows

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci smoke test windows

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci smoke test windows

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci smoke test windows

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci smoke test windows

**Comment by yim-lee** [comment]
@compnerd @buttaface Do you have any concerns / comments on this PR?

**Comment by buttaface** [comment]
None on my end, just happy to see this moving forward.

**Review by compnerd — APPROVED** [review]
This is great!  It should help get builds of SPM on Windows ARM64!

**Comment by yim-lee** [comment]
Will need a swift-crypto release that includes https://github.com/apple/swift-crypto/pull/137

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62289
@swift-ci please smoke test windows

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62890
@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62890
@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62890
@swift-ci please smoke test linux

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62890
@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62890
@swift-ci please smoke test windows

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62890
@swift-ci please smoke test windows

**Review by tomerd — APPROVED** [review]

**Pull request merged**
