### PR TITLE
[main] Enable `-user-module-version` for 6.0

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Summary:
`#if canImport(LibFoo, _version: "1.2.3")` is not currently supported by SwiftPM, as this feature was gated on `.vNext`, even though it landed before SwiftPM 5.10 branched off.

Steps To Reproduce:
1. Build a package with `// swift-tools-version: 6.0` and try to use `#if canImport(LibFoo, _version: "1.2.3")` for a dependency LibFoo.

Results:
The availability check won't work because `-user-module-version` option is not passed correctly to the build system.
rdar://121124842 fixed.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by bnbarham — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test Windows platform

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test linux

**Pull request merged**
