### PR TITLE
[PackageLoading] Handle duplicated declared sources

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
A single source file can be declared multiple times in the manifest so
we need to handle those cases.

<rdar://problem/59356544>

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test self hosted

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Review by SaintPatricksCoin — APPROVED** [review]
:P

**Comment by SaintPatricksCoin** [comment]
@SaintPatricksCoin
[IMG_20200611_110728.jpg](https://user-images.githubusercontent.com/63454224/114753448-52d82f00-9d0c-11eb-8d9e-d4dcf9a2349d.jpg)

**Pull request merged**
