### PR TITLE
Fix path-related deprecation warnings

### PR DESCRIPTION
**Pull request by neonichu**
Looks like I missed a few here.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please smoke test Windows

**Comment by neonichu** [comment]
@swift-ci please smoke test Windows

**Comment by neonichu** [comment]
Don't understand how the Windows failure is related to my changes, but it seems consistent

**Comment by abertelrud** [comment]
Merging since the required tests pass. @compnerd the Windows failure looks like a compiler crash (Swift compiler).

**Comment by compnerd** [comment]
@abertelrud please consider the Windows tests as required.  The SILOpt issue was fixed as of this morning and more regressions have crept into swift-syntax and sourcekit-lsp because people were ignoring the checks.

CC: @tomerd @shahmishal

@shahmishal can we mark the windows tests as blocking?

**Pull request merged**
