### PR TITLE
Fix SR-7830: move output from `loadPackageGraph()` to stderr for 'describe' subcommand

### PR DESCRIPTION
**Pull request by MattLewin**
This fix passes all tests in the test suite on both MacOS and Ubuntu. The test suite does not, however, sufficiently exercise the changes. I have, of course, manually confirmed that it works. Ironically, writing an effective test for these changes is substantially more difficult than making the changes themselves.

I expect to submit a PR with a new or updated test separately in the next few days.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Hey @MattLewin, thanks for taking up this bug. This PR seems to be a dupe of https://github.com/apple/swift-package-manager/pull/1603 but it seems like the other PR hasn't been updated in a while. Can you go through the comments there?

**Comment by MattLewin** [comment]
Ankit-

In some sense, my PR *is* a dupe of 1603 <https://github.com/apple/swift-package-manager/pull/1603>. I noticed that it hadn’t been moved forward, bur for some reasons did not see all those comments. I submitted my PR because #1603 prevents the loadPackageGraph output (using a “quiet” mode) rather than directing it to stderr, as requested in the bug report (SR-7830 <https://bugs.swift.org/browse/SR-7830>).

Reviewing the comments at 1603, and then subsequently, 1599 <https://github.com/apple/swift-package-manager/pull/1599>, it seems as though this PR may have been held up by a question whether the output should go to stderr or suppressed, or possibly a question whether the describe action should call loadRootManifests (describe just the root package) instead of loadPackageGraph (describe the dependencies).

I do not know enough about the Swift PM to know what the right answer is to that second question.

Do we want it to simple load (and describe) the root package?  If so, I can turn around that PR very quickly.

thanks.

-Matt

**Comment by aciidb0mb3r** [comment]
The describe functionality works on top of the `Package` model. We should be able to construct the Package object using the `PackageBuilder` helper which is present in the `PackageLoading` target. Let me know if that makes sense, or if you need more directions!

**Comment by MattLewin** [comment]
Ankit-

After rereading your message and digging through the code several times, I *do* think this makes sense to me.

Gimme a couple days.

Thanks!

-Matt

**Comment by MattLewin** [comment]
Ankit-

Take a look at https://github.com/apple/swift-package-manager/pull/1599/commits/4a6268c4b52f40b0a3d9d6babb8f06c23bb9bd18 <https://github.com/apple/swift-package-manager/pull/1599/commits/4a6268c4b52f40b0a3d9d6babb8f06c23bb9bd18>

It seems like the changes there should just be applied to those for SR-7830, and we should forget about moving the output of loadPackageGraph to stderr altogether.

You are obviously aware of that change, what am I missing that makes us not want to go that route?

Thanks.

-Matt

**Comment by aciidb0mb3r** [comment]
The approach I mentioned in https://github.com/apple/swift-package-manager/pull/1627#issuecomment-401177772 will allow us to create a Package object without going through loadPackageGraph, thus avoiding the need to redirect output to stderr. https://github.com/apple/swift-package-manager/pull/1599/commits/4a6268c4b52f40b0a3d9d6babb8f06c23bb9bd18 is a bit different than this PR in the sense that it needs the `Manifest` object. But this PR requires the `Package` object which can be created using `PackageBuilder` helper without fetching any dependency.

**Comment by aciidb0mb3r** [comment]
Opened a PR with fix: https://github.com/apple/swift-package-manager/pull/1691

**Pull request closed without merging**
