### PR TITLE
[5.9] pass -fno-omit-frame-pointer in support of new backtracer (#7042)

### PR DESCRIPTION
**Pull request by tomerd**
5.9 cherry pick of #7042

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci test

**Comment by tomerd** [comment]
cc @al45tair @compnerd

**Comment by tomerd** [comment]
@swift-ci test

**Comment by tomerd** [comment]
@swift-ci test windows

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
