### PR TITLE
Merge `main` into `release/5.10`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
There were a few conflicts accumulated, which are resolved manually in this PR.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by neonichu — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by tomerd — APPROVED** [review]

**Pull request merged**
