### PR TITLE
bootstrap: check the new Foundation layout

### PR DESCRIPTION
**Pull request by compnerd**
Ensure that we check the new Foundation location for the paths to the
libraries.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@compnerd this is getting a bit messier. Do you think you can also clean up once staging is complete? There have been several such staging, maybe we can already clean up some things?

**Comment by compnerd** [comment]
@aciidb0mb3r - yeah, Im going through and starting to remove the paths ... I think that we are nearly at the point where we should be able to build all of this in a much cleaner way now, Im finding more ways that the entire build is super complicated :-(

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Pull request merged**
