### PR TITLE
reduce concurrent manifest loading test contention

### PR DESCRIPTION
**Pull request by tomerd**
motivation: with manfiest loading async, the concurrent loading tests introduce significant contention on cpu since the underlying queue in unbounded

changes: use semaphore to limit the concurrency to max active cpus

### CODE REVIEW

**Comment by tomerd** [comment]
cc @pcbeard

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Comment by abertelrud** [comment]
This only affects `main`, is that correct?  (not 5.6)

**Comment by tomerd** [comment]
> This problem being fixed here only affects main, is that correct? (not 5.6)

at this point yes, #3940 will bring async manifest loading into 5.6

**Comment by tomerd** [comment]
@pcbeard should we pull this into the #3940 cherry-pick?

**Pull request merged**
