### PR TITLE
NFC: Add `Sendable` annotations to PackageDescription APIs

### PR DESCRIPTION
**Pull request by xedin**

### CODE REVIEW

**Comment by xedin** [comment]
Cherry-picked from https://github.com/apple/swift-package-manager/pull/7469

**Review by MaxDesiatov — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
