### PR TITLE
[swift-build] Add --update mode

### PR DESCRIPTION
**Pull request by JPMartha**
It is the same as #234, but #234 has conflicts.
So, I tried to rewrite.
I just added `--update` as I was told at #233.

### CODE REVIEW

**Comment by JPMartha** [comment]
I'm really sorry that I deleted by mistake. 🙇

**Comment by mxcl** [comment]
Cute. I guess this is good enough for now.

@swift-ci Please test and merge

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Comment by JPMartha** [comment]
@mxcl Thank you for the quick review! ☺️

**Pull request merged**
