### PR TITLE
Replace 5.11 version with 6.0 in the code base

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This is a follow up to a corresponding toolchain PR https://github.com/apple/swift/pull/71707.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
