### PR TITLE
[Basic] Add a generic topologicalSort algorithm.

### PR DESCRIPTION
**Pull request by ddunbar**
This depends on #427.

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
Linux test failures are unrelated.

**Comment by tfiala** [comment]
Why are you merging these if they're failing the packaging tests, Daniel?

**Comment by ddunbar** [comment]
Because the packaging test failure is unrelated to these commits, as best I could tell. It has been failing for a day or so, and it is an LLDB issue as best I can tell, not a SwiftPM one? Do you know what the cause is?
```
Command 2 Stderr:
Traceback (most recent call last):
  File "/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux@2/swift-integration-tests/repl/test-repl-glibc.py", line 51, in <module>
    repl.expect("init")
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1418, in expect
    timeout, searchwindowsize)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1433, in expect_list
    timeout, searchwindowsize)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1535, in expect_loop
    raise TIMEOUT(str(err) + '\n' + str(self))
pexpect.TIMEOUT: Timeout exceeded.
<pexpect.spawn object at 0x7f7d74954910>
```

**Comment by tfiala** [comment]
> It has been failing for a day or so
But not on the pristine (master) builders unless I'm missing something on ci.swift.org.

These are Mish's packaging tests (end-to-end verification of the Swift packaging).  The fact that they're timing out means something about the verification is failing.  The trace above doesn't really tell us anything useful other than whatever it was testing isn't happening within the timeout.

That could be caused by:
(1) a change in output - if expected, the test(s) need to be updated.  If unexpected, it's catching a regression in one of the PRs in the dependency chain here.
(2) a change in performance that makes the repl on Ubuntu take long enough that it is not producing output in time.  If this is the case, that seems like something to investigate.
(3) Somehow this PR bot is in a funky state.

BTW I'm only seeing this failure on a few of the PR checks on the package manager PR - definitely not all.  So it looks like it is potentially specific to something in one of the PRs, or it is intermittent.

We'll want to drill into this.

**Comment by ddunbar** [comment]
All of our other tests are passing, and the SwiftPM PRs coming in are mostly not behavioral changes (some aren't even used yet), and are not taking down the main CI when they land.

It sounds like something is weird on the PR builder, but I don't know what and I don't know this specific test (which is LLDB specific). Can someone on the LLDB team drive resolving this? /cc @shahmishal 

Maybe the PR builders have less resources and the timeout just needs to be bumped? Or maybe the workspace needs to be cleared?

**Comment by tfiala** [comment]
The owner of those tests is no longer present and came from a different team.  I'm working on finding out who is going to own them.  This would be a good exercise for them to track down.  I agree they look totally unrelated to anything you're doing here.

**Comment by tfiala** [comment]
> Maybe the PR builders have less resources and the timeout just needs to be bumped? Or maybe the workspace needs to be cleared?

I think the PR checkers always clean since it is not valid to assume an incremental state is consistent from PR to PR, so that probably isn't the issue.

**Comment by tfiala** [comment]
I'm attempting to replicate that test issue on an Ubuntu system.  Hopefully I can catch it happening or at least get a sense of what might have been failing.  The pexpect-style test failures are not very informative.

**Pull request merged**
