### PR TITLE
[wip] unwind target based dependencies 

### PR DESCRIPTION
**Pull request by tomerd**
motivation: target based dependencies implementation of unused products never materialized. we need to revisit this topic, but until then we would like to simplify the codebase by removing the partial implementation

changes:
* undo changes from https://github.com/apple/swift-package-manager/pull/2749
* adjust call-sites and test which were added or modified after #2749 was merged

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please test package compatibility

**Comment by tomerd** [comment]
@abertelrud @neonichu with package compatibility test suite passing, do we feel the approach here is good and we should take this change? if so, I can clean up the PR and get it ready for merging

**Comment by SDGGiesbrecht** [comment]
Has anyone tested it again since identities were overhauled?

I repeat that I would be happy to do the debugging if you can provide a concrete failing package.

**Comment by tomerd** [comment]
@SDGGiesbrech before opening this PR I spent some time trying to get the implementation to work by removing the `ENABLE_TARGET_BASED_DEPENDENCY_RESOLUTION` gate but could not get the tests gated by this flag to pass. maybe too much has changed in main? 

an alternative PR that restores this functionality could be a good comparison, my goal win this one was to "reset" the state before taking another stab at this, or iow to reduce complexity / remove unused code branches before we attempt this again

wdyt?

**Comment by SDGGiesbrecht** [comment]
If main has changed that much, then go ahead with this PR if it simplifies other work.

In the next few days I will try reverting to debug the failing tests, but I don’t need it to be present in `main` to do that. If I can figure out what is wrong and get them passing again, then I will send a new PR, and you can use that to try it on whatever your top secret packages are.

Feel free to try to beat me to it and implement it yourself. I just want this feature to finally be available.

**Pull request closed without merging**
