### PR TITLE
6.0: [SE-0301] Implement package manifest editing command-line options

### PR DESCRIPTION
**Pull request by DougGregor**
* **Explanation**: Implement package manifest editing commands (`swift package add-dependency`, `swift package add-target`, `swift package add-product`) described in [SE-0301](https://github.com/apple/swift-evolution/blob/main/proposals/0301-package-editing-commands.md), using swift-syntax under the hood to perform the edits. 
* **Original PR**: https://github.com/apple/swift-package-manager/pull/7467, https://github.com/apple/swift-package-manager/pull/7476, https://github.com/apple/swift-package-manager/pull/7477
* **Risk**: Very low. All new code for new commands.
* **Reviewed by**: @ahoppen , @bnbarham , @owenv , @MaxDesiatov 
* **Testing**: New tests.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
I'd also like to pick up https://github.com/apple/swift-package-manager/pull/7486 in this PR once it's ready

**Review by MaxDesiatov — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Pull request merged**
