### PR TITLE
Migrate entirely to new color-diagnostics flag

### PR DESCRIPTION
**Pull request by keith**
https://github.com/apple/swift-package-manager/pull/2103

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci test

**Comment by keith** [comment]
Looks like clang crashed on macOS at least, unrelated to this change ofc

**Comment by keith** [comment]
Thanks!

**Pull request merged**
