### PR TITLE
Revert "Clean up the code and some of the API of compiling plugins, and improve persistence of cached compiler outputs"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift-package-manager#4290

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @abertelrud @tomerd - the change regressed on Windows, which has been broken multiple times in the past week.  I'd like to revert rather than fix forward, and then retry with testing.

**Comment by tomerd** [comment]
@abertelrud @compnerd can we fix this forward easily? if not, we should revert

**Comment by compnerd** [comment]
I can't test it locally atm, can you test and merge this quickly?  I think it is better to revert and then fix.

**Comment by abertelrud** [comment]
@compnerd  What's the failure?  I understand wanting to revert, but will need to fix it.

**Comment by compnerd** [comment]
@abertelrud https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/509/console

**Comment by tomerd** [comment]
```
I C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-toolchain-x86_64-vs2019\swift-corelibs-libdispatch\src\BlocksRuntime -I T:\13\swift @CMakeFiles\Workspace.rsp    -Xlinker -implib:lib\Workspace.lib  && cd ."
C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-toolchain-x86_64-vs2019\swiftpm\Sources\Workspace\DefaultPluginScriptRunner.swift:250:27: error: type 'ProcessResult.ExitStatus' has no member 'signalled'

                    case .signalled(let signal):

                         ~^~~~~~~~~
```

**Comment by abertelrud** [comment]
> @abertelrud https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/509/console

Thanks for the reference.  Let's revert for now and I'll put up a fixed PR.  Is there any way to run the Windows build against CI so I can tell if I'm breaking it again?

**Review by abertelrud — APPROVED** [review]

**Comment by abertelrud** [comment]
Or probably better I can just #if out that part.

**Comment by abertelrud** [comment]
Put up https://github.com/apple/swift-package-manager/pull/4299.  Can we test that on Windows somehow?  Would hate to go back and forth on this.

**Comment by compnerd** [comment]
It is possible to do cross-repository testing - that is the only option atm

**Comment by compnerd** [comment]
More specifically you need to build a full toolchain for Windows ("@swift-ci please build toolchain Windows platform") with the associated PR

**Comment by abertelrud** [comment]
Great, I'll give that a try.  Thanks @compnerd

**Comment by abertelrud** [comment]
> Great, I'll give that a try. Thanks @compnerd

Oh but I'd have to do that from within a PR in the Swift compiler I guess.

**Comment by abertelrud** [comment]
In this case I'd prefer to merge the fix in order to make progress.  If needed we can revert this and then I'll put up a PR to put it back with the fix, but there's still the question of testing that.  I never was able to get SwiftPM on a local Windows VM to work.

**Comment by compnerd** [comment]
Right, until we get the CI setup on this repo, it would need to be done on that repo (and why it requires a full toolchain build)

**Comment by abertelrud** [comment]
Meanwhile, I'm preparing a cross-repo test run with a DNM branch in the Swift repo to test #4299. If we must revert quickly we can do that, then I would convert #4299 to putting the code back with the fix.

**Comment by abertelrud** [comment]
https://github.com/apple/swift/pull/42405

**Pull request closed without merging**
