### PR TITLE
build: remove `USE_CMAKE_INSTALL` option

### PR DESCRIPTION
**Pull request by compnerd**
These option provides no value.  The installation rules can be generated and not used if the user does not wish to install the products.  This simplifies the CMake logic.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Pull request merged**
