### PR TITLE
[DO NOT MERGE] Update swift-argument-parser

### PR DESCRIPTION
**Pull request by jakepetroules**

### CODE REVIEW

**Comment by jakepetroules** [comment]
apple/swift-package-manager#3843
apple/sourcekit-lsp#434
apple/swift-driver#899
apple/swift#40103

@swift-ci Please test

**Review by buttaface — APPROVED** [review]

**Comment by jakepetroules** [comment]
#3843
apple/sourcekit-lsp#434
apple/swift-driver#899
apple/swift#40103

@swift-ci Please smoke test

**Comment by neonichu** [comment]
It is expected that the self-hosted tests would fail, because they don't support cross-repo testing.

**Review by neonichu — APPROVED** [review]

**Comment by jakepetroules** [comment]
DO NOT MERGE. This is waiting for @shahmishal.

**Pull request merged**
