### PR TITLE
Rename systém function to loggedSystem

### PR DESCRIPTION
**Pull request by bjtitus**
A small little change for renaming `systém` to `loggedSystem`, which seems like a more descriptive function name and is easier to type.

### CODE REVIEW

**Comment by mxcl** [comment]
I agree the name is cutesy. I'm not sure `loggedSystem` expresses what happens however.

**Comment by mxcl** [comment]
I think: `func system(args: String..., message: String)` is adequate.

**Comment by bjtitus** [comment]
Just updated with that change, including the change to non-optional message. Thanks for taking a look!

**Comment by mxcl** [comment]
This changes the behavior for the `fetch` since now it outputs all its stdout and stderr to the tty.

Can we make `message:` take a `String?` so that the fetch can be silent unless it errors as before?

**Comment by mxcl** [comment]
I'll pull locally and make this modification.

**Comment by bjtitus** [comment]
@mxcl Sorry about that. Just updated with the nil message and making sure the version with message is being called in `fetch`.

**Comment by mxcl** [comment]
Merged: 63e0e79e0c0ab370c12895d51031217284ead35f

**Pull request closed without merging**
