### PR TITLE
Compile the package manifest properly on Windows

### PR DESCRIPTION
**Pull request by egorzhdan**
Currently SwiftPM compiles the package manifest with an `-rpath` linker argument which is not supported on Windows.
On Windows it should instead execute the compiled manifest with an additional `PATH` component representing the `PackageDescription.dll` location.

This implementation relies on https://github.com/apple/swift-tools-support-core/pull/92 to pass the `PATH` environment variable to the manifest executable, but these PRs can be merged in any order.

After this change the compiled manifests can be executed manually by running `id-manifest.exe -fileno 1` 
– it prints the package manifest JSON to stdout.
(Execution by SwiftPM itself still fails because of a different issue: the file descriptor of the JSON output is not shared properly with the child process)

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
I don't have the knowledge to review the Windows side of the branches, but the non-Windows cases look to preserve the existing behavior as far as I can see.  Is there someone else who should review the Windows side?  Since AFAIK the Windows support is still being brought up, I'm inclined to merge even if it turns out that the Window branches end up needing further adjustments.

**Comment by MaxDesiatov** [comment]
CC @compnerd

**Comment by egorzhdan** [comment]
Hmm, the test failure seems to be unrelated to these changes...
Perhaps the CI picks fresh tests from master for this slightly outdated branch (created before 933c5d70c1cba4d096953769466cd3056f39ca03)?
Can't say for sure since I don't have access to the `swift-continuous-integration` repo.

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
I think that the commit the branch was created off shouldn't matter as it should run CI as if the branch is merged into `master`. At least that's how GitHub Actions does it, and I hope that Swift CI does it too. Retriggering the build should help if that's the case, if not, I apologize if triggering the CI wasted any resources.

**Comment by egorzhdan** [comment]
Rerunning the build helped, thanks!
**Swift Test Linux Platform (self hosted)** [failed](https://ci.swift.org/job/swift-package-manager-self-hosted-Linux-smoke-test/588/) during the previous run but [passed](https://ci.swift.org/job/swift-package-manager-self-hosted-Linux-smoke-test/589/) successfully now.

**Comment by egorzhdan** [comment]
Could this PR be merged if there are no issues with the changes?

**Pull request merged**
