### PR TITLE
[PackageLoading] Fix linux XCTest module name

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This was colliding with main package module name if there is only one
module. It got broken during the transition from `TestSuite` to `Tests`
suffix.

Fixes SR-2244

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
...all the more reason to have some functional test for swifttest on linux

**Comment by aciidb0mb3r** [comment]
can we create a symlink to xctest during bootstrap and then pass it when running swift test from tests?

**Comment by ddunbar** [comment]
@aciidb0mb3r Is it possible to at least test the module names don't collide at the `PackageBuilder` or `PackageGraph` level?

**Comment by aciidb0mb3r** [comment]
@ddunbar ah I think it should be, will check and add test case

**Comment by aciidb0mb3r** [comment]
added

**Comment by ddunbar** [comment]
I think something needs to be normalized, I get:
```
/home/ddunbar/public/swift-project/swiftpm/Tests/PackageLoadingTests/ConventionTests.swift:657: error: ConventionTests.testTestsProduct : XCTAssertEqual failed: ("["BarTests", "FooTests"]") is not equal to ("["FooTests", "BarTests"]") - 
```

**Comment by aciidb0mb3r** [comment]
fixed

**Comment by abertelrud** [comment]
Thanks @aciidb0mb3r.  I don't fully understand what's going on here, because I also did Linux tests of the PR before landing it.  Is this a collision that happens all the time or just some times?

**Comment by ddunbar** [comment]
It only happens when the package has a target with the same name as the package, I think.

**Pull request merged**
