### PR TITLE
Search through PATH instead of calling "which"

### PR DESCRIPTION
**Pull request by troughton**
On non-macOS platforms, use the PATH environment variable to find programs rather than deferring to `which` (which is unavailable on Windows).

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by jakepetroules** [comment]
The roughly equivalent command on Windows is `where`; you could consider using that.

**Comment by troughton** [comment]
Based off what @compnerd said about the limitations of `where` in https://forums.swift.org/t/swift-soars-ever-higher/34036/11 I thought this seemed a better approach.

**Comment by buttaface** [comment]
Btw, I noticed something recently when building SPM from master, there was a weird issue where it invoked the Swift 5.1.4 SPM I had installed in the system path, instead of master SPM just bootstrapping itself. I don't know if this is a known issue, but I hope that can be fixed too.

**Pull request merged**
