### PR TITLE
Update to 5.1 tools version 

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by SDGGiesbrecht** [comment]
It seems straightforward. Is there something specific you wanted my thoughts on?

**Comment by SDGGiesbrecht** [comment]
I think the JSON mapper one could simply be `return try? get(key) as T`, but it isn’t all that important. (The compiler is conflating the `as T` and `as T?` variants, since they now both result in `T?` once `try?` is applied. It used to reject `as T?` because it produced `T??`, which wasn’t returnable.)

**Comment by aciidb0mb3r** [comment]
>  Is there something specific you wanted my thoughts on?

Mainly wanted to notify you since you have some tooling on top of SwiftPM and I am bumping versions here.

> I think the JSON mapper one could simply be return try? get(key) as T

Ah, thanks. I think I want to move away from these APIs since they're a pain to use with type inference. Specifying the type explicitly seems like the way to go: https://github.com/apple/swift-package-manager/blob/master/Sources/TSCBasic/JSONMapper.swift#L37

**Pull request merged**
