### PR TITLE
Copy edited error message

### PR DESCRIPTION
**Pull request by pcantrell**
- grammar fix: “unversioned” instead of “unversion”
- edited for clarity

### CODE REVIEW

**Comment by abertelrud** [comment]
Thanks for the fix!

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by pcantrell** [comment]
Looks like a test mentions the error message I changed? Want me to add that to the PR? (I confess I just made the edit straight off of GitHub & didn't even clone locally.)

**Comment by abertelrud** [comment]
Yes, the unit test would need to updated as part of the PR.  I didn't realize that this message was being mentioned in a test, so this is good catch by the smoke tests that every PR requires.

As for testing locally, the `Documentation/Development.md` document inside the repository contains information about how to run the tests locally.  In particular, I always do a `Utilities/bootstrap test` before putting up a PR (step 5).

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@pcantrell Thanks again for fixing the diagnostic message here.  If the wording in the unit tests can be updated so that the tests pass, we can merge this.  Thanks!

**Comment by tomerd** [comment]
Hi Mishal,

I noticed you closed this PR, could you provide background on why it was closed?
	
— Tom

**Comment by shahmishal** [comment]
We moved our default branch to `main` and deleted `master` branch, GitHub automatically closed the PR. Please update the base branch to `main`.  More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Comment by tomerd** [comment]
Hi @pcantrell, the Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please rebase on top of the `main` and we can reopen.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
