### PR TITLE
Run clean before --fetch

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by JPMartha** [comment]
Hi, I'm @JPMartha.

I should run `--fetch` twice with this.

By the way, I have concerns about the SwiftPM design.

I understand the SwiftPM is still in early design and development.
The way I see the current implementation, it seems to be designed to be available for running `--fetch` again.

> https://github.com/apple/swift-package-manager/blob/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a/Sources/Get/Fetcher.swift#L78-L86

But, I have no objection to that if acceptable.

**Comment by mxcl** [comment]
I don't think this is desired. The real solution is that `--update` should exist and `--fetch` should error properly if deps have already been fetched.

**Comment by JPMartha** [comment]
I have some questions.

Let's suppose the following situation:
- `MyApp` depends on `PackageA` and `B`.
- `PackageB` depends on `C`.

```
MyApp
├── Package A
└── Package B
    └── Package C
```

#### Questions

1. If `PackageA` requires update, then SwitPM should fetch `PackageA` only, or all packages?
2. If `PackageB` requires update, then SwitPM should fetch both `PackageB` and `C`?
3. if `PackageA-1.0.0` requires update to `2.0.0`, then SwiftPM shoud remain `PackageA-1.0.0` directory, or override?

**Comment by JPMartha** [comment]
I send the questions to the mailing lists again.
Because I feel questions might be mentioned on the mailing list better than GitHub PR. 🙏

**Pull request closed without merging**
