### PR TITLE
refactor resource localization model

### PR DESCRIPTION
**Pull request by tomerd**
motivation: while looking to eliminate preconditions from the code, noticed the resource localization model could be improved to better use the type system

changes:
* move localization from a floating optional attribute to the process rule enum case
* adjust call sites and tests

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test Linux

**Comment by tomerd** [comment]
@swift-ci please smoke test Linux

**Comment by tomerd** [comment]
@swift-ci please smoke test Linux

**Comment by tomerd** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
