### PR TITLE
[Build] Include OSX sdk platform path in framework search paths

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This will allow importing frameworks like XCTest in targets.

### CODE REVIEW

**Comment by ddunbar** [comment]
A couple notes on this change:

1. Note that targets that *actually* use XCTest aren't going to be able to run, by default, because they are linking against a library inside the Xcode.app, but that library won't be found at runtime. I am ok with this, for now, because in general such targets are mostly useful as "test support infrastructure", and will be linked by a test module which *does* have access to XCTest. Fixing this in general probably would require us to have some kind of annotation for targets which were only "designed for testing" -- if we had that it would be ok to add an `RPATH` entry allowing XCTest to be found. Adding that in general isn't acceptable, though.

2. The bootstrap script will eventually need the same changes, if we start using this for targets in SwiftPM itself (or the bootstrap script will need to know to skip such targets).

**Comment by ddunbar** [comment]
If we do this, we should support it for C language targets as well.

**Comment by aciidb0mb3r** [comment]
> If we do this, we should support it for C language targets as well.
Yeah I was just wondering about that...will add

**Comment by aciidb0mb3r** [comment]
@ddunbar Added to C languages

**Comment by ddunbar** [comment]
This still doesn't work for C language targets... I think it only was added to the link line. Also, we should make sure the same behavior also works in Xcode (we can use the `$(PLATFORM_DEVELOPER_LIBRARY_DIR)` build setting to derive the right path to add to the `FRAMEWORKS_SEARCH_PATHS`).

**Comment by aciidb0mb3r** [comment]
Done. Used `PLATFORM_DIR` variable for Xcode instead because `PLATFORM_DEVELOPER_LIBRARY_DIR` provides different path.
Tested using this fixture: https://github.com/aciidb0mb3r/framework-search-path

---

ObjC executable seems to be broken on Xcode :(

**Comment by ddunbar** [comment]
LGTM

**Pull request merged**
