### PR TITLE
Remove the vendored copy of TSC

### PR DESCRIPTION
**Pull request by neonichu**
Supersedes #2898

https://github.com/apple/swift-tools-support-core/pull/148 adds a workspace for testing TSC changes together with SwiftPM and SourceKit-LSP. That will be used for PR testing in the future.

### CODE REVIEW

**Comment by neonichu** [comment]
apple/sourcekit-lsp#305
@swift-ci please smoke test

**Comment by neonichu** [comment]
The LSP PR got deleted in the move to "main", I'll open a new one.

**Comment by neonichu** [comment]
apple/sourcekit-lsp#338
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
We can land the SourceKit-LSP PR and this once https://github.com/apple/swift-tools-support-core/pull/148 has landed.

**Review by federicobucchi — APPROVED** [review]

**Comment by neonichu** [comment]
We need to work through some issues with the extended CI of TSC, happening on this PR: https://github.com/apple/swift-tools-support-core/pull/150

In the meantime, we have switched the CI to using a workspace, but are still only running the TSC unit tests.

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
CI works now and is using the same setup as SwiftPM itself, in addition to running TSC tests. That way it also supports cross-repository testing etc. I'll update this PR and then merge this and the SourceKitLSP one.

**Comment by neonichu** [comment]
apple/sourcekit-lsp#338
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]
Nice!  Thanks!

**Pull request merged**
