### PR TITLE
[5.5][Collections] Better handling of spaces in collection file path

### PR DESCRIPTION
**Pull request by yim-lee**
This is https://github.com/apple/swift-package-manager/pull/3412 for 5.5.

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please smoke test Linux

**Comment by tomerd** [comment]
linux failure expected since toolchain download is not available yet

**Comment by tomerd** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please test linux

**Pull request merged**
