### PR TITLE
Use Product API for C language targets

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Depends on https://github.com/apple/swift-package-manager/pull/387 merge.
This is the last piece of puzzle after which the C language in Test targets can be supported.

### CODE REVIEW

**Comment by ddunbar** [comment]
Can you explain at a high level what this resolves? Is it just that it allows declaring products for C language targets, or is it something more fundamental?

The entire products API never really went through a design process, and as your commits note in this case we _have_ to create a library for Swift interoperability to do what we want. So I want to understand how this fits into the larger scheme of things.

**Comment by aciidb0mb3r** [comment]
This will resolve two things -
1. Allow user to declare products for a C language target. (This will currently only work for executables and dynamic libraries, will abort for other cases.)
2. Decouple the compiling and linking of ClangModules.

Since we _have_ to always create a dynamic lib, we can use the product API internally to always create dylibs along with user defined products for eg a static lib.

Then for tests we can probably link all the clang modules (which are tests) together to create a single dylib or create different dylibs for each. Either way this will give us flexibility.

**Comment by ddunbar** [comment]
Ok, sounds reasonable to me. I'm still not sure how this all should be organized, but this at least seems to make the code base more consistent w.r.t. where this is handled.

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test linux

**Comment by aciidb0mb3r** [comment]
@swift-ci please test linux

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Pull request merged**
