### PR TITLE
add supported platforms to the main README

### PR DESCRIPTION
**Pull request by ehuynh**
As a potential user, I wanted to see quickly whether I could use SPM for the platform I was developing for. It wasn't immediately clear if I could use it for iOS, so I had to go searching for this information in the documentation folder, which took some time before I could find the answer.

I think this information is important enough for it to be on the main README, as it is probably one of the first things users want to know about SPM.

Note: The text comes from https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md#depending-on-apple-modules

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
We should clarify this and say something like: Package Manager cannot build iOS, tvOS... apps using `swift build` however right now there is limited support for building these platforms by generating a Xcode project with custom xcconfig file.
<example commands which shows how to do that and a sample xcconfig>

**Comment by ehuynh** [comment]
its not just apps right? My understanding is that it currently can't build for any products on those platforms

maybe it is easier to say that it only builds macOS/OSX products

**Comment by aciidb0mb3r** [comment]
It's correct to say that but I think we should get the part about iOS in readme because we get a lot of queries about iOS.

**Comment by aciidb0mb3r** [comment]
on the other hand I don't think we should promote the current method...

**Comment by ddunbar** [comment]
I think this is reasonable to add to the main README.

**Comment by ehuynh** [comment]
Should we leave as is? Or should we emphasis the "apps" part of it? I think 

> Note that at this time the Package Manager has no support for iOS, watchOS, or tvOS platforms

is clear enough. And it mentions iOS.

**Pull request merged**
