### PR TITLE
Workspace: handle `/MT`, `/MTd`, `/MD`, `/MDd` for C/C++

### PR DESCRIPTION
**Pull request by compnerd**
Since the C runtime must match in the entire address space, when
building with `/MD` or `/MDd` we know that the C/C++ code must match the
configuration of the runtime.  With static linking, there can be only a
single C runtime in the address space, and so we know that the C/C++
code must match the configuration as well.  We can derive the C/C++
flags for the compiler driver and transliterate them to the clang
spelling rather than the `cl` spelling.

The C/C++ compiler flags being added here map directly to the behaviour
of the associated `cl` flag.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by neonichu — DISMISSED** [review]

**Comment by compnerd** [comment]
Bleh, this doesn't apply to pure C libraries that are sub-libraries.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
Okay, this time verified with a clean build

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by abertelrud** [comment]
Looks good as bringup.  When things settle, it would be fantastic if the mapping of runtime model identifiers to required compiler flags could also come from a plist.  But for now this looks fine, though because I’m not familiar with Windows I can’t tell whether the flags themselves look correct.

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
