### PR TITLE
[Build] Sort the command inputs before writing

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This sometimes causes things to rebuild on linux when nothing has changed.

- https://bugs.swift.org/browse/SR-4034

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Omitting test because there is no easy way to do that in the old build module.. This isn't a problem in master because of how we compute inputs.

**Comment by aciidb0mb3r** [comment]
Filed: https://bugs.swift.org/browse/SR-4045

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by rballard** [comment]
Approved for the Swift 3.1 branch.

**Pull request merged**
