### PR TITLE
[5.6] Cherry-pick TOFU changes from main branch

### PR DESCRIPTION
**Pull request by yim-lee**
Cherry-pick https://github.com/apple/swift-package-manager/pull/3928, https://github.com/apple/swift-package-manager/pull/3936, https://github.com/apple/swift-package-manager/pull/3932, https://github.com/apple/swift-package-manager/pull/3941 to 5.6

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
@swift-ci please test linux

**Comment by yim-lee** [comment]
@swift-ci please test

**Comment by yim-lee** [comment]
@swift-ci please test

**Pull request merged**
