### PR TITLE
[PackageDescription] Use a dedicated type for target dependency condi…

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
…tion

<rdar://problem/59563902>

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by tonyarnold** [comment]
Did this PR deliberately elide the `.when(configuration: .release)` syntax? 

I could really use that functionality, and it's in the proposal for SE-0273.

**Comment by aciidb0mb3r** [comment]
yah, configuration conditionals aren't implemented yet at the build system level but SE-0273 should state that explicitly instead of saying "Implemented (Swift 5.3)".

**Comment by tonyarnold** [comment]
Ok, great to know - thanks, Ankit! 

Do the changes need to happen in llbuild? Is there an SR I can watch (or create) to add this support?

**Pull request merged**
