### PR TITLE
[Basic] Add a KeyedPair type.

### PR DESCRIPTION
**Pull request by ddunbar**
- See doc comments...

### CODE REVIEW

**Comment by ddunbar** [comment]
@abertelrud FYI, Ankit and I discussed the name here at length, and couldn't come up with a better option. I'm going with this for now in order to make progress on actual code, but I'm open to suggestions...

Also /cc @dabrahams & @gribozavr I'm curious what the standard library perspective is on this problem, the intent here is to allow things similar to, e.g., Python's `sorted(key:)` functionality by exposing a `Hashable` wrapper instead of by imposing it on the implementation of each such algorithm.

**Comment by dabrahams** [comment]
> On Aug 14, 2016, at 12:30 PM, Daniel Dunbar <notifications@github.com> wrote:
> Also /cc @dabrahams & @gribozavr I'm curious what the standard library perspective is on this problem, the intent here is to allow things similar to, e.g., Python's sorted(key:) functionality by exposing a Hashable wrapper instead of by imposing it on the implementation of each such algorithm.
> 
I'm afraid I don't understand the use case.  What does hashing have to do with sorting?

**Comment by ddunbar** [comment]
@dabrahams 

> I'm afraid I don't understand the use case.  What does hashing have to do with sorting?

Let me elaborate: Hashing doesn't have anything to do with sorting -- but we can define a similar kind of wrapper to support only Equatable and not just Hashable.

The basic question is when we have a generic algorithm like `sorted<T: Equatable>([T]) -> [T]` it is sometimes useful to be able to sort an array of `T`s based on some property other than the equability of the object itself. We can do that by making `sorted` take additional arguments for the comparator *or* we can use a wrapper type like the one here to provide a particular `Equatable` view of the collection. Python's `key:` parameter to `sorted` is an example of the former approach. The benefit of the latter approach is that the same wrapper works for all such algorithms, without modification.

I'm curious if there has been discussion around this problem for the stdlib.

**Comment by dabrahams** [comment]
on Mon Aug 15 2016, Daniel Dunbar <notifications-AT-github.com> wrote:

> @dabrahams 
>
>> I'm afraid I don't understand the use case.  What does hashing have to do with sorting?
>
> Let me elaborate: Hashing doesn't have anything to do with sorting --
> but we can define a similar kind of wrapper to support only Equatable
> and not just Hashable.

I have the same question: what does Equatable have to do with sorting?
Sorting requires an ordering relation, so when you don't pass a
predicate closure it requires Comparable.  If you want to sort on
something else, you can pass a predicate closure.  I'd like to add
overloads that let you pass a projection instead of a predicate, so you
can say:

    people.sorted(by: {$0.lastName})

> The basic question is when we have a generic algorithm like `sorted<T:
> Equatable>([T]) -> [T]` it is sometimes useful to be able to sort an
> array of `T`s based on some property other than the equability of the
> object itself. We can do that by making `sorted` take additional
> arguments for the comparator *or* we can use a wrapper type like the
> one here to provide a particular `Equatable` view of the collection.
> Python's `key:` parameter to `sorted` is an example of the former
> approach. The benefit of the latter approach is that the same wrapper
> works for all such algorithms, without modification.
>
> I'm curious if there has been discussion around this problem for the
> stdlib.

For individual algorithms, no.  For hashed/sorted collections, yes.
Creating a wrapper around a T that also stores a key (or a closure for
projecting the key from the T) is a really expensive way to do this, as
it bloats the storage required and incurs needless copying costs.  If
you want to go this way efficiently, you really need a custom wrapper
for each such projection, which means it can't be generic.

For individual algorithms I am reasonably happy with the closure
approach, but for hashed/sorted collections, you either *need* a custom
wrapper, or you need a specialized version of the collection where the
hashing/ordering is parameterized.  The latter approach raises
frightening semantic questions, so I would have to see some pretty
compelling use cases before going down that path.

-- 
-Dave

**Comment by ddunbar** [comment]
> Creating a wrapper around a T that also stores a key (or a closure for
projecting the key from the T) is a really expensive way to do this, as

It depends; for super-linear algorithms it is a space/time tradeoff w.r.t. the cost of the projection function...

> I'd like to add
> overloads that let you pass a projection instead of a predicate, so you
> can say:

Ok, thanks... this basically answers my question. We will probably end up with going with the closure approach eventually esp. because it makes the API so much nicer.

**Pull request merged**
