### PR TITLE
Deconflict multiple tests by using package name

### PR DESCRIPTION
**Pull request by hpux735**
rather than "Package" in the construction of "Package.test"

### CODE REVIEW

**Comment by mxcl** [comment]
@swift-ci please test.

This will fail since there's a few places the name of the test package is checked in the tests.

**Comment by hpux735** [comment]
@mxcl Were there results from the CI test?  Trying to run the SwiftPM tests fails in my development environment for unknown reasons, so I'm not sure what will break.

**Comment by aciidb0mb3r** [comment]
@hpux735 this might be why all tests are failing https://github.com/apple/swift-package-manager/pull/158#issuecomment-191324013

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
https://github.com/apple/swift-package-manager/commit/e702428922a83dbe1a53367fec8b4ecbd9acc5a2

**Pull request closed without merging**
