### PR TITLE
update CommandTaskTracker to match llbuild's reporting of CustomTasks

### PR DESCRIPTION
**Pull request by tomerd**
motivation: adjust SwiftPM to llbuild reporting of task progress, which now includes custom tasks

changes: increment finished tasks count based on the commandStatusChanged event instead of the commandFinished event

rdar://84883732

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
cc @BenchR267

**Review by abertelrud — APPROVED** [review]
Looks reasonable to me, though I would not want just my review on this as I'm not that familiar with the llbuild callbacks.  This seems like it's predicated on having the `.isComplete` status be true for both the `.succeeded` and `.skipped` results — if so, then this makes sense.

**Comment by tomerd** [comment]
this was suggested by @BenchR267 based on changes done to llbuild

**Review by BenchR267 — APPROVED** [review]

**Pull request merged**
