### PR TITLE
[5.3] Fix cross-compile bootstrap

### PR DESCRIPTION
**Pull request by neonichu**
5.3 cherry-pick of https://github.com/apple/swift-package-manager/pull/2916 and #2918

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Review by abertelrud — APPROVED** [review]
The change makes sense to me, but I don't know where we are in terms of being able to merge to the 5.3 branch right now.

**Comment by abertelrud** [comment]
Adding "[5.3]" prefix to PR name to make it clear that this intended for `release/5.3` branch.

**Comment by abertelrud** [comment]
This will need release manager approval.

**Comment by neonichu** [comment]
@swift-ci please test

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
