### PR TITLE
Remove build-using-cmake script

### PR DESCRIPTION
**Pull request by keith**
This seems to be unused and outdated https://github.com/apple/swift-package-manager/pull/5653

### CODE REVIEW

**Comment by tomerd** [comment]
thanks @Keith, sorry about the hassle on this :(

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by tomerd — APPROVED** [review]

**Comment by keith** [comment]
no prob, thanks

**Review by compnerd — APPROVED** [review]
Nope; I'm not using this.  Removing this seems fine if no one is using it.

**Pull request merged**
