### PR TITLE
Update the allTests declarations for compatibility with the latest Corelibs XCTest

### PR DESCRIPTION
**Pull request by briancroom**
This includes the necessary changes for the test suite to build and run with the `swift-corelibs-xctest` changes proposed in https://github.com/apple/swift-corelibs-xctest/pull/40 and should be merged in coordination with that PR.

### CODE REVIEW

**Comment by mxcl** [comment]
Oh man. Revlock… :D

**Comment by mxcl** [comment]
👍🏻

**Comment by mxcl** [comment]
👍🏻

**Comment by mxcl** [comment]
👍🏻

**Comment by aciidb0mb3r** [comment]
this is breaking with latest tool chain
```
/home/aciid/swift/swift-package-manager/Tests/PackageType/PackageNameTests.swift:14:7: error: type 'PackageTests' does not conform to protocol 'XCTestCaseProvider'
class PackageTests: XCTestCase {
      ^
XCTest.XCTestCaseProvider:2:16: note: protocol requires property 'allTests' with type '[(String, () throws -> Void)]'
    public var allTests: [(String, () throws -> Void)] { get }
               ^
/home/aciid/swift/swift-package-manager/Tests/PackageType/PackageNameTests.swift:39:16: note: candidate operates on a type, not an instance as required
    static var allTests : [(String, PackageTests -> () throws -> Void)] {
               ^
Compiling Swift Module 'PackageDescriptiontest' (2 sources)
/home/aciid/swift/swift-package-manager/Tests/Build/DescribeTests.swift:14:13: error: type 'DescribeTests' does not conform to protocol 'XCTestCaseProvider'
final class DescribeTests: XCTestCase {
            ^
XCTest.XCTestCaseProvider:2:16: note: protocol requires property 'allTests' with type '[(String, () throws -> Void)]'
    public var allTests: [(String, () throws -> Void)] { get }
               ^
/home/aciid/swift/swift-package-manager/Tests/Build/DescribeTests.swift:28:16: note: candidate operates on a type, not an instance as required
    static var allTests: [(String, DescribeTests -> () throws -> Void)] {
               ^
Compiling Swift Module 'Utilitytest' (6 sources)
/home/aciid/swift/swift-package-manager/Tests/Utility/MiscTests.swift:15:7: error: type 'RmtreeTests' does not conform to protocol 'XCTestCaseProvider'
class RmtreeTests: XCTestCase {
```

**Comment by briancroom** [comment]
@aciidb0mb3r with this having been merged, the SwiftPM tests will need to be built against the master branch of corelibs-xctest rather than the version included in the toolchain. SwiftPM's `bootstrap` script accepts an `--xctest` parameter which allows specifying the directory containing the corelibs-xctest library you want to use.

It's slightly unfortunate that this got merged in so shortly after a toolchain snapshot was released since it will presumably be at least a week until the snapshots catch up. On the plus side, however, we don't foresee needing to make any more breaking changes like this as a result of working towards API compatibility with Apple XCTest.

**Comment by mike-ferris-apple** [comment]
Ug, yeah. I didn't really think about coordinating with the snapshot dates...

**Comment by aciidb0mb3r** [comment]
Posting this for other's reference
```
$ git clone https://github.com/apple/swift-corelibs-xctest
$ cd swift-corelibs-xctest
$ ./build_script.py \
    --swiftc="/home/aciid/swift/swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10/usr/bin/swiftc" \
    --build-dir=".build" \
    --library-install-path="/home/aciid/swift/swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10/usr/lib/swift/linux" \
    --module-install-path="/home/aciid/swift/swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10/usr/lib/swift/linux//x86_64"
```

**Comment by aciidb0mb3r** [comment]
@briancroom the `--xctest` built all test modules successfully but with undefined symbols when trying to execute tests, installing the newer xctest into the toolchain worked

**Comment by briancroom** [comment]
@aciidb0mb3r hmm yeah, it seems that the linker is finding the snapshot's `libXCTest.so` first, regardless of where the extra linker search paths are placed on the command line. I'm not seeing a way to fix that issue properly right now.

@mike-ferris-apple neither did I! Hopefully another one will be posted early next week already, though.

**Pull request merged**
