### PR TITLE
Use working directory when constructing the host toolchain

### PR DESCRIPTION
**Pull request by neonichu**
This has not made it from `SwiftTool` to `SwiftBootstrapBuildTool` but is likely required for toolchain builds since we are seeing issues with the wrong compiler being used.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Failures in linux self-hosted are expected, trying to fix in https://github.com/apple/swift-package-manager/pull/5952

**Review by tomerd — APPROVED** [review]
thank you

**Comment by neonichu** [comment]
@swift-ci please smoke test linux

**Comment by neonichu** [comment]
Converting to draft, we should bring this back when we're re-landing "simplify bootstrap build"

**Pull request closed without merging**
