### PR TITLE
better diagnostics for networking errors

### PR DESCRIPTION
**Pull request by tomerd**
motivation: improved user experience

change: override the default description of nserror (in registry client only) and produce a more user friendly diagnostics

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci smoke test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by tomerd** [comment]
windows failure unrelated - @compnerd aware

**Comment by compnerd** [comment]
CC: @etcwilde

**Pull request merged**
