### PR TITLE
Revert "Initial implementation of Command Plugins"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift-package-manager#3855

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
@compnerd Is there a log where I can see how this failed?  It should be possible to fix this forward.

**Comment by tomerd** [comment]
@abertelrud @compnerd is this addressed by #3888 and can be close?

**Comment by compnerd** [comment]
@tomerd - I want to keep this open until we know that it does fix the build, otherwise, I think that we should roll back to get the builds green again - they have been broken for ~12 hours now.

**Comment by abertelrud** [comment]
> @abertelrud @compnerd is this addressed by #3888 and can be close?

In my view we can close this, since I'm confident that we can fix this forward.  We are still testing #3888 but I don't see a circumstance in which we'd need to revert this commit.

**Pull request closed without merging**
