### PR TITLE
Update tools-version for `-user-module-version`

### PR DESCRIPTION
**Pull request by neonichu**
We are not shipping this in 5.9, so we need to tweak this.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by ole** [comment]
@neonichu I noticed the tools version gate for this is still set to `.vNext` in the current main (https://github.com/apple/swift-package-manager/blob/0d1f3708e24d1160724fc8ed20f1cb11858db44b/Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift#L630) and release/5.10 branches.

Is there anything blocking this from making it into Swift 5.10?

**Comment by MaxDesiatov** [comment]
I've changed it to 5.10 in https://github.com/apple/swift-package-manager/pull/7261

**Comment by ole** [comment]
@MaxDesiatov Thanks!

**Pull request merged**
