### PR TITLE
Update for changes made in SE-0036

### PR DESCRIPTION
**Pull request by ahoppen**
Updated the code to reflect the changes made in [SE-0036](https://github.com/apple/swift-evolution/blob/master/proposals/0036-enum-dot.md)

The pull request in the Swift compiler is currently pending: [#2224](https://github.com/apple/swift/pull/2224)

### CODE REVIEW

**Comment by jrose-apple** [comment]
Note that these changes are not revlocked; the package manager should be able to take this patch whenever you want.

**Comment by ddunbar** [comment]
@swift-ci please test and merge

**Comment by mxcl** [comment]
@swift-ci please test and merge

**Comment by DougGregor** [comment]
@swift-ci please test and merge

**Comment by ddunbar** [comment]
@swift-ci please test and merge

**Pull request merged**
