### PR TITLE
audit and use abstract FileSystem instead of localFileSystem where possible

### PR DESCRIPTION
**Pull request by tomerd**
motivation: using the FileSystem helps testing and robustness

changes: review all use sites of localFileSystem and replace them with abstract FileSystem where possible

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test macOS

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Pull request merged**
