### PR TITLE
Avoid new-line on progress when never updated

### PR DESCRIPTION
**Pull request by hartbit**
While adding a test that verifies the fix, I refactored the progress tests to avoid repetition.

### CODE REVIEW

**Comment by hartbit** [comment]
@swift-ci please smoke test and merge

**Comment by hartbit** [comment]
@swift-ci please smoke test and merge

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
failure looks related

**Comment by hartbit** [comment]
Yeah, I keep forgetting to regenerate LinuxMain 😞 What I wouldn't give to have tests auto-detected on Linux

**Comment by hartbit** [comment]
@swift-ci please smoke test

**Pull request merged**
