### PR TITLE
Increment SwiftPM tools version to 5.5 and minimum deployment target to 10.15.4 on macOS

### PR DESCRIPTION
**Pull request by abertelrud**
Increment SwiftPM tools version to 5.5 and minimum deployment target to 10.15.4 on macOS

### Motivation:

Allow use of Swift 5.5 features such as automatic `Codable` synthesis.  Minimum deployment target of 10.15.4 allows use of FileHandle improvements such as `read(upToCount:)`.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@benlangmuir would it be possible also for SourceKit-LSP to require 10.15.4 on macOS?  Seems like a small change compared with 10.15, and the reason was to allow the new Swift-friendlier FileHandle APIs (that throw Swift.Errors instead of raising ObjC exceptions).

I can open a SourceKit-LSP PR if that isn't a no-go.

**Comment by benlangmuir** [comment]
> @benlangmuir would it be possible also for SourceKit-LSP to require 10.15.4 on macOS? Seems like a small change compared with 10.15, and the reason was to allow the new Swift-friendlier FileHandle APIs (that throw Swift.Errors instead of raising ObjC exceptions).

No concerns from me, we've generally bumped our deployment target whenever swiftpm decides to, I think.  CCing @akyrtzi  and @ahoppen in case they want to protest.

**Comment by akyrtzi** [comment]
We can follow swiftpm on this, I don't have any concern.

**Comment by abertelrud** [comment]
Great, thanks all for the comments.

**Comment by abertelrud** [comment]
https://github.com/apple/sourcekit-lsp/pull/436
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Review by neonichu — APPROVED** [review]

**Pull request merged**
