### PR TITLE
Patch `*.sdk` paths from pkgConfig files to the current SDK

### LINKED ISSUE #6439: Duplicate includes between CLI tools and macOS SDK with `.systemLibrary` targets and Homebrew-installed libraries
### Description

This is kind of a strange issue that sits somewhere at the intersection between SwiftPM, pkg-config and the way Homebrew packages certain libraries.

See also the discussion in https://github.com/orgs/Homebrew/discussions/4025

### Actual behavior

Building a minimal `.systemLibrary` wrapper around Cairo:

```swift
// swift-tools-version:5.2
import PackageDescription

let package = Package(
    name: "swift-systemlib-demo",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "SystemlibDemo",
            targets: ["SystemlibDemo"]
        ),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "SystemlibDemo",
            dependencies: ["CCairo"]
        ),
        .systemLibrary(name: "CCairo", pkgConfig: "cairo", providers: [.brew(["cairo"])]),
    ]
)
```

...causes both Xcode macOS SDK headers and CLI tools headers to get included:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/ffi/module.modulemap:1:8: error: redefinition of module 'FFI'
module FFI [system] [extern_c] {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi/module.modulemap:1:8: note: previously defined here
module FFI [system] [extern_c] {
```

The problematic invocation can be inspected with `swift build -v` (pretty-printed for readability):

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend
  -frontend
  -c
  -primary-file /Users/<user>/git/swift-systemlib-demo/Sources/SystemlibDemo/SystemlibDemo.swift
  -emit-dependencies-path /Users/<user>/git/swift-systemlib-demo/.build/arm64-apple-macosx/debug/SystemlibDemo.build/SystemlibDemo.d
  -emit-reference-dependencies-path /Users/<user>/git/swift-systemlib-demo/.build/arm64-apple-macosx/debug/SystemlibDemo.build/SystemlibDemo.swiftdeps
  -target arm64-apple-macosx10.13
  -Xllvm
  -aarch64-use-tbi
  -enable-objc-interop
  -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk
  -I /Users/<user>/git/swift-systemlib-demo/.build/arm64-apple-macosx/debug
  -I /opt/homebrew/Cellar/cairo/1.16.0_5/include/cairo
  -I /opt/homebrew/Cellar/glib/2.76.1/include
  -I /opt/homebrew/Cellar/glib/2.76.1/include/glib-2.0
  -I /opt/homebrew/Cellar/glib/2.76.1/lib/glib-2.0/include
  -I /opt/homebrew/opt/gettext/include
  -I /opt/homebrew/Cellar/pcre2/10.42/include
  -I /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi
  -I /opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1
  -I /opt/homebrew/Cellar/fontconfig/2.14.2/include
  -I /opt/homebrew/opt/freetype/include/freetype2
  -I /opt/homebrew/Cellar/libpng/1.6.39/include/libpng16
  -I /opt/homebrew/Cellar/libxcb/1.15_1/include
  -I /opt/homebrew/Cellar/libxau/1.0.11/include
  -I /opt/homebrew/Cellar/xorgproto/2022.2/include
  -I /opt/homebrew/Cellar/libxdmcp/1.1.4/include
  -I /opt/homebrew/Cellar/libxrender/0.9.11/include
  -I /opt/homebrew/Cellar/libx11/1.8.4/include
  -I /opt/homebrew/Cellar/libxext/1.3.5/include
  -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib
  -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
  -color-diagnostics
  -enable-testing
  -g
  -module-cache-path /Users/<user>/git/swift-systemlib-demo/.build/arm64-apple-macosx/debug/ModuleCache
  -swift-version 5
  -Onone
  -D SWIFT_PACKAGE
  -D DEBUG
  -new-driver-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver
  -empty-abi-descriptor
  -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift
  -enable-anonymous-context-mangled-names
  -Xcc
  -fmodule-map-file=/Users/<user>/git/swift-systemlib-demo/Sources/CCairo/module.modulemap
  -module-name SystemlibDemo
  -disable-clang-spi
  -target-sdk-version 13.1
  -parse-as-library
  -o /Users/<user>/git/swift-systemlib-demo/.build/arm64-apple-macosx/debug/SystemlibDemo.build/SystemlibDemo.swift.o
  -index-store-path /Users/<user>/git/swift-systemlib-demo/.build/arm64-apple-macosx/debug/index/store
  -index-system-modules
```

### Expected behavior

The FFI headers shouldn't be included twice, in this case, the likely culprit is the inclusion of

```
-I /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi
```

which likely originates from (the transitively included?) pkg-config for `libffi`, `/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/13/libffi.pc`:

```
homebrew_sdkroot=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
prefix=${homebrew_sdkroot}/usr
exec_prefix=/usr
libdir=${exec_prefix}/lib
toolexeclibdir=${libdir}
includedir=${prefix}/include/ffi

Name: libffi
Description: Library supporting Foreign Function Interfaces
Version: 3.4-rc1
Libs: -L${toolexeclibdir} -lffi
Cflags: -I${includedir}
```

I've had trouble pinpointing the exact issue though.

### Steps to reproduce

- `brew install cairo`
- Clone https://github.com/fwcd/swift-systemlib-demo
- Run `swift build`

As the GitHub Actions workflows show, the issue seems to be limited to macOS and is therefore likely related to the way Homebrew packages its `pkg-config` files for `cairo`.

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.7.1

### Swift & OS version (output of `swift --version && uname -a`)

```
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
Darwin <computer name> 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
```

(running macOS 13.3.1)

### PR DESCRIPTION
**Pull request by fwcd**
This fixes #6439 by replacing all `*.sdk` paths obtained from pkgConfigs with the current SDK.

### Motivation:

Using Homebrew-packaged libraries such as Cairo in a system library target on macOS currently causes build failures if the user compiles the Swift package with an Xcode toolchain (see [`swift-systemlib-demo`](https://github.com/fwcd/swift-systemlib-demo/tree/bb30a9ce6205a503ad85fc112b0e60a4c3a450c4) and its CI builds for a minimal example), the build output often looks similar to this:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/ffi/module.modulemap:1:8: error: redefinition of module 'FFI'
module FFI [system] [extern_c] {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi/module.modulemap:1:8: note: previously defined here
module FFI [system] [extern_c] {
```

The problem is that Homebrew's pre-compiled libraries sometimes bake the Command Line Tools-paths (`/Library/Developer/CommandLineTools/SDKs/...`) into their `pkgConfig` files, which can clash with the current SDK's headers.

See #6439 for details.

### Modifications:

As per @neonichu's suggestion in https://github.com/apple/swift-package-manager/issues/6439#issuecomment-1511658768, this patches the include (`-I`) and library (`-L`) paths parsed from pkgConfig files by replacing any `*.sdk` path with the current SDK.

Thus a flag such as

```
-I/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi
```

would be mapped to

```
-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk
```

when compiling with the macOS 13.3 SDK.

### Result:

The [`swift-systemlib-demo`](https://github.com/fwcd/swift-systemlib-demo/tree/bb30a9ce6205a503ad85fc112b0e60a4c3a450c4) package now compiles on macOS.

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@fwcd sorry about the delay with the review, would you mind resolving the conflicts?

**Comment by fwcd** [comment]
Sure, I've rebased it onto main!

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
