### PR TITLE
command plugins: Inherit SwiftPM's --configuration flag in packageManager.build

### PR DESCRIPTION
**Pull request by euanh**
This commit makes it possible for a build run on behalf of a command plugin to inherit the build configuration (debug or release) set for the whole `swift package` run using the `--configuration` flag.

 ### Motivation:

When a command plugin asks for a target to be built by calling `packageManager.build`, it must specify a release or debug build.  If no configuration is given, debug is the default.   This overrides any configuration specified by the user with `swift package -c <debug|release>`.

A command plugin might often be used as an alterative entry point to Swift PM, responsible for building a target and then processing it in some way to generate the final product.   The user might run `swift package -c release some-plugin --target some-target`, expecting a release build of target to be made, but currently the result will be a debug binary if the plugin uses the default options.

 ### Modifications:

* Added a new `.inherit` option for packageManager.build's `configuration` argument.;  `.debug` remains the default, as before.
* Added a test to verify that plugin-initiated builds are of the correct type.

 ### Result:

A command plugin can request a target build matching the configuration specified on the SwiftPM command line.   The default is still to make a debug build, however in future we might change this to inherit the overall SwiftPM configuration.

 ### Alternatives:

A command plugin does not currently seem to have access to SwiftPM's build configuration.   We could pass this information to the plugin, allowing the plugin author to pass it back in the `packageManager.build` call.   This would be a less invasive change to SwiftPM, however the approach in this commit makes it easier to change the default to `.inherit` in the future.

### CODE REVIEW

**Comment by euanh** [comment]
Please let me know if I missed an existing way to do this.

**Review by MaxDesiatov — APPROVED** [review]
This is great, thanks!

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by neonichu — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
One of the tests [is failing](https://ci.swift.org/job/swift-package-manager-self-hosted-Linux-smoke-test/3353/console) with this error:

```
/home/build-user/swiftpm/Tests/CommandsTests/PackageToolTests.swift:2027: error: PackageToolTests.testCommandPluginTargetBuilds : failed - No such fixture: /home/build-user/swiftpm/Fixtures/Miscellaneous/Plugins/CommandPluginDiagnosticsStub
<EXPR>:0: error: PackageToolTests.testCommandPluginTargetBuilds : threw error "packagePathNotFound"
```

**Comment by euanh** [comment]
> One of the tests [is failing](https://ci.swift.org/job/swift-package-manager-self-hosted-Linux-smoke-test/3353/console) with this error:
> 
> ```
> /home/build-user/swiftpm/Tests/CommandsTests/PackageToolTests.swift:2027: error: PackageToolTests.testCommandPluginTargetBuilds : failed - No such fixture: /home/build-user/swiftpm/Fixtures/Miscellaneous/Plugins/CommandPluginDiagnosticsStub
> <EXPR>:0: error: PackageToolTests.testCommandPluginTargetBuilds : threw error "packagePathNotFound"
> ```

Thanks, I missed these in a rebase. :(

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by euanh** [comment]
@swift-ci please smoke test self hosted

**Comment by MaxDesiatov** [comment]
@swift-ci test linux

**Comment by euanh** [comment]
@MaxDesiatov It looks like the Linux smoke test might have hit https://github.com/apple/sourcekit-lsp/pull/1025
```
/home/build-user/sourcekit-lsp/Sources/SKSwiftPMWorkspace/SwiftPMWorkspace.swift:212:20: warning: 'init(buildParameters:graph:additionalFileRules:buildToolPluginInvocationResults:prebuildCommandResults:fileSystem:observabilityScope:)' is deprecated: replaced by 'init(productsBuildParameters:toolsBuildParameters:graph:)'
    let plan = try BuildPlan(
                   ^
/home/build-user/sourcekit-lsp/Sources/SKSwiftPMWorkspace/SwiftPMWorkspace.swift:212:20: note: use 'init(productsBuildParameters:toolsBuildParameters:graph:)' instead
    let plan = try BuildPlan(
                   ^
/home/build-user/sourcekit-lsp/Sources/SKSwiftPMWorkspace/SwiftPMWorkspace.swift:227:40: error: subscript 'subscript(_:)' requires that 'ResolvedTarget' conform to 'RangeExpression'
          guard let td = plan.targetMap[target] else {
                                       ^
Swift.Collection:2:23: note: where 'R' = 'ResolvedTarget'
    @inlinable public subscript<R>(r: R) -> Self.SubSequence where R : RangeExpression, Self.Index == R.Bound { get }
                      ^
/home/build-user/sourcekit-lsp/Sources/SKSwiftPMWorkspace/SwiftPMWorkspace.swift:241:38: error: subscript 'subscript(_:)' requires that 'ResolvedTarget' conform to 'RangeExpression'
        guard let td = plan.targetMap[target] else {
                                     ^
Swift.Collection:2:23: note: where 'R' = 'ResolvedTarget'
    @inlinable public subscript<R>(r: R) -> Self.SubSequence where R : RangeExpression, Self.Index == R.Bound { get }
                      ^
```
Could you please trigger the smoke test run again?

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
