### PR TITLE
[WIP][SR-7832] Default executable SwiftPM package should have tests

### PR DESCRIPTION
**Pull request by karaiskc**
This PR modifies the default executable package type to include tests ([SR-7832](https://bugs.swift.org/browse/SR-7832)). 

I started working on this task with the assistance of @hartbit during try!Swift San Jose and this is my first attempt to contribute. I would like to request feedback in the overall structure and further changes that should be performed. I tested Linux using docker-utils on macOS but I would appreciate feedback on the correctness of finding the path of the executable in that case.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Oh no, I didn't realize you were working on this :( I landed this recently with https://github.com/apple/swift-package-manager/pull/1610

Sorry about that, please feel free to pick another starter bug!

**Comment by karaiskc** [comment]
@aciidb0mb3r I had the JIRA task assigned to myself since the conference, I guess my mistake was that I did not open a WIP PR immediately then? Just asking so that I can avoid this happening in the future. Will try to find another, thanks!

**Comment by aciidb0mb3r** [comment]
@karaiskc No, you did the right thing. It was completely my fault :( I should have checked the JIRA bug before starting to work on it. Apologies!

**Comment by karaiskc** [comment]
@aciidb0mb3r No worries! Learned quite a lot from working on this, it was a good chance to start getting to know the project.

**Pull request closed without merging**
