### PR TITLE
Bump minimum required tools-version to 5.7

### PR DESCRIPTION
**Pull request by neonichu**
This will require the CI to update the installed tools to at least 5.7

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
```
<unknown>:0: error: missing required module 'ucrt'
```

cc @shahmishal @compnerd is this an infra failure?

**Comment by compnerd** [comment]
@neonichu no, that is a change that went in today; it sounds like there is a sync issue?  We now need to pass in `-vfsoverlay ...` as we are no longer modifying the Visual Studio installation.

**Comment by compnerd** [comment]
@neonichu ugh, I think that the merge dropped some of the changes?  The ASN1 and certificates builds are missing the flags I think.

**Comment by compnerd** [comment]
https://github.com/apple/swift/pull/64157 should fix that, sorry about that!

**Comment by neonichu** [comment]
@swift-ci please smoke test windows

**Review by tomerd — APPROVED** [review]

**Pull request merged**
