### PR TITLE
adopt swift-collections

### PR DESCRIPTION
**Pull request by tomerd**
brings back https://github.com/apple/swift-package-manager/pull/3595

### CODE REVIEW

**Comment by tomerd** [comment]
cc @neonichu

**Comment by tomerd** [comment]
holding on to this one until we understand CI linkage failures

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
pending: https://github.com/apple/swift-driver/pull/773 (or alternative) and https://github.com/apple/swift-collections/pull/64

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
requires https://github.com/apple/swift/pull/38881

**Review by neonichu — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
