### PR TITLE
Restore visibility of APIs that have been made `package`

### PR DESCRIPTION
**Pull request by xedin**
This change reverts the following PRs and makes it possible to use public and @_spi APIs again.

- https://github.com/apple/swift-package-manager/pull/7365
- https://github.com/apple/swift-package-manager/pull/7372
- https://github.com/apple/swift-package-manager/pull/7381
- https://github.com/apple/swift-package-manager/pull/7387
- https://github.com/apple/swift-package-manager/pull/7434

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Review by bnbarham — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Pull request merged**
