### PR TITLE
[SR-1555] Temporarily disable whole-module optimization to avoid SR-1457

### PR DESCRIPTION
**Pull request by abertelrud**
This is a workaround for SR-1457. SR-1556 tracks removing the workaround.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
I think we'll need to disable -O flag too iirc.

**Comment by abertelrud** [comment]
Actually, just disabling seems WMO do the trick.  Are you seeing different results w.r.t. SR-1475?

**Comment by aciidb0mb3r** [comment]
I am not sure, re-checking

**Comment by ddunbar** [comment]
Looks reasonable to me... I wonder if we have any tests this will break when using the bootstrap workflow?

**Comment by abertelrud** [comment]
I ran the regular test suite and all the tests passed (using bootstrap test).  Does that test the release build in addition to debug?  I saw log messages that suggests that it does.

**Comment by abertelrud** [comment]
Note, by the way, that this just affects how swiftpm itself gets built during bootstrapping.  This does not automatically disable whole-module-optimization when swiftpm is building a package (doing so might mask the original problem).

**Comment by aciidb0mb3r** [comment]
Ah... looks like it persists if you don't clean build and I probably did not do a clean build after changing wmo to false and did after removing `-O`

**Comment by abertelrud** [comment]
Not rebuilding sounds like a problem with the bootstrap script.  Nonetheless, does that resolve the concern about WMO vs -O?

**Comment by aciidb0mb3r** [comment]
Yup

**Comment by abertelrud** [comment]
Great; thanks.

**Pull request merged**
