### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by anayini**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Thanks!

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by anayini** [comment]
@aciidb0mb3r - Np.  Not a very useful PR, but just wanted to get the dev environment setup.  Hopefully more to come soon!

**Comment by aciidb0mb3r** [comment]
Great, let me know if you need any help!

**Pull request merged**
