### PR TITLE
[Resolver] Turn on parallel cloning by default

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
-- <rdar://problem/32286386> Turn on parallel cloning by default

(cherry picked from commit db90b80e7362c42e089e1d093fa97dc21f9cb2a3)

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
Weird that it is failing on CI..

**Comment by aciidb0mb3r** [comment]
Ah, our in memory git repository is not thread safe. I am going to enable this at tool level then.

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by rballard** [comment]
Approved for the swift 4.0 branch.

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Pull request merged**
