### PR TITLE
[5.2] Disable failing test PackageDescription5LoadingTests.testSerializedDi…

### PR DESCRIPTION
**Pull request by drexin**
…agnostics

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Comment by abertelrud** [comment]
Thanks for the fix.  Is the reason the underlying test is failing understood, and tracked by a bug report?

**Comment by drexin** [comment]
Ah, no. We are still investigating this. I meant to close this PR, as we decided that disabling the test is not the right thing to do here.

**Pull request closed without merging**
