### PR TITLE
[5.6] Simplify the command plugin method to get all the inputs in `arguments` instead of a specific targets parameter  (#4055)

### PR DESCRIPTION
**Pull request by abertelrud**
This is a 5.6 cherry-pick of #4055. Details in that PR. Motivation: This improves package plugins, a new feature in SwiftPM 5.6

This PR builds on #4064 because waiting for each full build before opening the next PR would take a long time. All the diffs have already been reviewed in the original PR on main.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by abertelrud** [comment]
Rebased and restarting tests since the GitHub UI sees a conflict with the previously merged PR though the file contents have no conflict (probably due to squash merge).

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
@swift-ci please test linux

**Pull request merged**
