### PR TITLE
[5.4] identity collisions diagnostics test and fixes

### PR DESCRIPTION
**Pull request by tomerd**
same as #3171

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
```
19:11:21 ******************** TEST 'Swift(linux-x86_64) :: Driver/static-executable.swift' FAILED ********************
19:11:21 Script:
19:11:21 --
19:11:21 : 'RUN: at line 5';   rm -rf "/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable.swift.tmp" && mkdir -p "/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable.swift.tmp"
19:11:21 : 'RUN: at line 6';   /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/swift-linux-x86_64/bin/swiftc -target x86_64-unknown-linux-gnu -toolchain-stdlib-rpath  -module-cache-path /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache  -Xfrontend -ignore-module-source-info -static-executable -o /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable.swift.tmp/static-executable /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swift/test/Driver/static-executable.swift
19:11:21 : 'RUN: at line 7';   /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable.swift.tmp/static-executable | /usr/bin/python3.5 /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swift/utils/PathSanitizingFileCheck --sanitize BUILD_DIR=/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/swift-linux-x86_64 --sanitize SOURCE_DIR=/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swift --use-filecheck /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/llvm-linux-x86_64/bin/FileCheck  /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swift/test/Driver/static-executable.swift
19:11:21 : 'RUN: at line 8';   /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/llvm-linux-x86_64/bin/llvm-readelf -program-headers /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable.swift.tmp/static-executable | /usr/bin/python3.5 /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swift/utils/PathSanitizingFileCheck --sanitize BUILD_DIR=/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/swift-linux-x86_64 --sanitize SOURCE_DIR=/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swift --use-filecheck /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/llvm-linux-x86_64/bin/FileCheck  /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swift/test/Driver/static-executable.swift --check-prefix=ELF
19:11:21 --
19:11:21 Exit Code: 1
19:11:21 
19:11:21 Command Output (stderr):
19:11:21 --
19:11:21 
<unknown>:0: error: compiled module was created by an older version of the compiler; rebuild 'Swift' and try again: /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/swift-linux-x86_64/lib/swift_static/linux/Swift.swiftmodule/x86_64-unknown-linux-gnu.swiftmodule
```

@shahmishal is this a known issue?

**Comment by tomerd** [comment]
@swift-ci please test

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
