### PR TITLE
improve  test discovery to include inherited tests

### PR DESCRIPTION
**Pull request by tomerd**
motivation: test discovery on linux depends on index store test listing

changes:
* use new API from TSC that fixes the issue
* adjust test
* add docker setup for 5.7

rdar://59655518

### CODE REVIEW

**Comment by tomerd** [comment]
https://github.com/apple/swift-tools-support-core/pull/335

@swift-ci smoke test

**Comment by tomerd** [comment]
https://github.com/apple/swift-tools-support-core/pull/335

@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
self hosted test expected to fails since they do not support cross repo testing (@shahmishal can that be fixed?)

**Comment by neonichu** [comment]
> self hosted test expected to fails since they do not support cross repo testing (@shahmishal can that be fixed?)

I think that's something we would need to work on -- the self-hosted tests use the regular package manifest and we would need a way to override the dependencies there in a clean way. Maybe something that could be feasible once we have explicit overrides?

**Comment by tomerd** [comment]
https://github.com/apple/swift-tools-support-core/pull/335

@swift-ci smoke test

**Comment by tomerd** [comment]
https://github.com/apple/swift-tools-support-core/pull/335

@swift-ci smoke test

**Pull request merged**
