### PR TITLE
[Bootstrap] Bootstrap & test with the integrated Swift driver.

### PR DESCRIPTION
**Pull request by DougGregor**
As part of bootstrapping, also run tests with the integrated Swift
driver.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Linux failure is:
```
23:30:29 Fatal error: unableToFind(tool: "swift"): file /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/swiftpm/Sources/Build/ManifestBuilder.swift, line 300
23:30:29 Current stack trace:
23:30:29 0    libswiftCore.so                    0x00007fb9ea1c4e40 swift_reportError + 50
23:30:29 1    libswiftCore.so                    0x00007fb9ea22e1d0 _swift_stdlib_reportFatalErrorInFile + 115
23:30:29 2    libswiftCore.so                    0x00007fb9e9eb8565 <unavailable> + 1471845
23:30:29 3    libswiftCore.so                    0x00007fb9e9eb8137 <unavailable> + 1470775
23:30:29 4    libswiftCore.so                    0x00007fb9e9eb878f <unavailable> + 1472399
23:30:29 5    libswiftCore.so                    0x00007fb9e9eb6890 _assertionFailure(_:_:file:line:flags:) + 552
23:30:29 6    libBuild.so                        0x00007fb9ebedeb46 <unavailable> + 478022
23:30:29 7    libBuild.so                        0x00007fb9ebed4d6c <unavailable> + 437612
23:30:29 8    libBuild.so                        0x00007fb9ebed3910 LLBuildManifestBuilder.generateManifest(at:) + 1256
23:30:29 9    libBuild.so                        0x00007fb9ebea3ae1 <unavailable> + 236257
23:30:29 10   libBuild.so                        0x00007fb9ebea1079 <unavailable> + 225401
23:30:29 11   libBuild.so                        0x00007fb9ebea08b0 <unavailable> + 223408
23:30:29 12   libBuild.so                        0x00007fb9ebea0c6f <unavailable> + 224367
23:30:29 13   libBuild.so                        0x00007fb9ebea119a <unavailable> + 225690
23:30:29 14   libBuild.so                        0x00007fb9ebea1204 <unavailable> + 225796
23:30:29 15   libTSCBasic.so                     0x00007fb9eaa61eb0 memoize<A>(to:build:) + 490
23:30:29 16   libBuild.so                        0x00007fb9ebe9fd40 BuildOperation.getBuildDescription() + 181
23:30:29 17   libBuild.so                        0x00007fb9ebea1420 BuildOperation.build(subset:) + 112
23:30:29 18   libBuild.so                        0x00007fb9ebea4786 <unavailable> + 239494
23:30:29 19   libCommands.so                     0x00007fb9ebf8b632 <unavailable> + 312882
23:30:29 20   libCommands.so                     0x00007fb9ebfe3170 SwiftTool.run() + 543
23:30:29 21   swift-build                        0x000055918d5612a9 <unavailable> + 4777
23:30:29 22   libc.so.6                          0x00007fb9e8561740 __libc_start_main + 240
23:30:29 23   swift-build                        0x000055918d560ef9 <unavailable> + 3833
```

Not sure if that's related to this change or an independent issue.

**Comment by DougGregor** [comment]
I'm fairly certainly this is an existing issue. SwiftPM isn't communicating to SwiftDriver which "swift" frontend executable to use, so SwiftDriver is looking for it relative to the just-built SwiftPM and not finding it. Fixing the hack I put in at https://github.com/apple/swift-package-manager/blob/3f55ea6d555ee8a73013eea44a50567fb69e9f41/Sources/Build/ManifestBuilder.swift#L208-L222 should address this... I think...

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci smoke test

**Comment by DougGregor** [comment]
@swift-ci test macOS

**Comment by DougGregor** [comment]
@swift-ci smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci test macOS

**Comment by DougGregor** [comment]
@swift-ci test platform macOS

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci test OSX

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
That macOS failure is bogus, but I can't seem to get CI to trigger :(

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci clean test

**Comment by DougGregor** [comment]
@swift-ci clean test macOS

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci test macOS

**Comment by DougGregor** [comment]
@swift-ci test

**Pull request merged**
