### PR TITLE
Stop build if there were build-tool plugin failures

### PR DESCRIPTION
**Pull request by neonichu**
rdar://102989296

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
`PackageToolTests.testBuildToolPluginFailure` needs an update (it is not failing for macOS on CI since we can't run the plugin tests there because of lack of concurrency support).

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please smoke test linux

**Comment by neonichu** [comment]
@swift-ci please smoke test linux

**Pull request merged**
