### PR TITLE
Unblock SwiftPM's build

### PR DESCRIPTION
**Pull request by neonichu**
This fixes two issues:
- First one is the same as #2875
- Second one is a crash related to build conditionals which looks like a
longer standing bug that was triggered by https://github.com/apple/swift-llbuild/pull/681
Unforunately, llbuild CI doesn't test the package, so it slipped through
and now causes SwiftPM to crash when building itself

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
> ./swiftpm/Utilities/build-using-self: line 16: 79151 Illegal instruction: 4  swift build -c $CONFIGURATION

This is still here, so I guess this is actually using the superior? Let's disable for now.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Oh I get it now, the self-hosting bot uses the superior to build itself, so this PR can't fix it.

**Comment by neonichu** [comment]
> /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/swiftpm/Sources/Workspace/Workspace.swift:1421:24: error: type of expression is ambiguous without more context

This might be an issue with the vendored copy of TSC not being synced up.

**Comment by abertelrud** [comment]
Yes, most likely.  You could just remove the `withAuthorizationProvider` thing, right?

**Comment by neonichu** [comment]
Yah, but then the self-hosted bots will be broken for future PRs.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Right, I just realized that.  Syncing is the right way to go.

Is there a follow-on fix for llbuild here after things get unbroken (again, many thanks for your work on that!).

**Comment by neonichu** [comment]
Not sure yet, I haven't looked in detail at the llbuild change and if there might be issues with it.

**Comment by neonichu** [comment]
Ugh, my sync was incomplete, I forgot new files.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
cc @compnerd

**Pull request merged**
