### PR TITLE
Check for failure on dupicate external target names [SR-4859]

### PR DESCRIPTION
**Pull request by therealbnut**
From [SR-4859](https://bugs.swift.org/browse/SR-4859):
> I suspect our logic for finding duplicate target name across the package graph is broken. We should be able to find the duplicate target names in the following graph:
> 
> Root:
> &nbsp;&nbsp;&nbsp;&nbsp;Tagets: Foo Bar
> &nbsp;&nbsp;&nbsp;&nbsp;Dependencies: Dep1
>
> Dep1:
> &nbsp;&nbsp;&nbsp;&nbsp;Targets: Baz
> &nbsp;&nbsp;&nbsp;&nbsp;Dependencies: Dep2
>
> Dep2:
> &nbsp;&nbsp;&nbsp;&nbsp;Targets: Foo, Bam
> &nbsp;&nbsp;&nbsp;&nbsp;Dependencies: []
>
> If this is in fact broken, we need to fix this in PackageGraphLoader and add appropriate test case.

I don't think there actually is a bug, it outputs as expected. Perhaps there is an alternative test case @aciidb0mb3r ?

### CODE REVIEW

**Comment by therealbnut** [comment]
Thanks for the feedback, I'll hopefully get to it this weekend or before if I have time

**Comment by therealbnut** [comment]
Nice, thanks @aciidb0mb3r - the `DiagnosticsEngine` makes for a much cleaner test, good to know!

**Comment by therealbnut** [comment]
Maybe also duplicates https://bugs.swift.org/browse/SR-1402 and https://bugs.swift.org/browse/SR-1168

**Comment by aciidb0mb3r** [comment]
Thanks!

**Comment by aciidb0mb3r** [comment]
Hey @therealbnut, can you fix conflicts and squash into one commit?

**Comment by therealbnut** [comment]
@aciidb0mb3r squashed, thanks

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Pull request merged**
