### PR TITLE
[Pubgrub] Further improvements and fixes

### PR DESCRIPTION
**Pull request by kiliankoe**
Improvements and fixes for several minor issues including conflict resolution not coming to the correct root incompatibility, normalization of terms in incompatibilities not working and how decisions were being handled in general in the partial solution.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@kiliankoe can you check the linux failures

**Comment by aciidb0mb3r** [comment]
/home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/swiftpm/Tests/PackageGraphTests/XCTestManifests.swift:66:40: error: use of unresolved identifier 'testSolutionFindSatisfiers'
19:00:20         ("testSolutionFindSatisfiers", testSolutionFindSatisfiers),
19:00:20                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
1

**Comment by kiliankoe** [comment]
Argh, every time 🙈

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Pull request merged**
