### PR TITLE
Removing the TextOutputStreamable typealias...

### PR DESCRIPTION
**Pull request by moiseev**
...as it is now available as a type in swift/swift-3.0-branch.

Needed to unblock the https://github.com/apple/swift/pull/4361

### CODE REVIEW

**Comment by ddunbar** [comment]
LGTM, please merge whenever you are ready to land #4361.

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by moiseev** [comment]
Build failures are due to this PR depending on the changes in apple/swift#4361, that cannot be merged because these changes are not in =)
FWIW: I built it successfully locally, so merging to break the loop.

**Comment by gparker42** [comment]
Reverted in #610. Try again tomorrow.

**Comment by moiseev** [comment]
Thanks @gparker42. Sorry for the mess.

**Pull request merged**
