### PR TITLE
PackageLoading: enable the manifest VFS on Windows

### PR DESCRIPTION
**Pull request by compnerd**
Ensure that the path string is escaped when emitting the paths. The VFS paths are serialised as either JSON or YAML, both of which require the path string be escaped.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
this seems fine to me, although the increased usage of `_nativePathString` is a growing concern

**Comment by tomerd** [comment]
@neonichu?

**Comment by compnerd** [comment]
> this seems fine to me, although the increased usage of `_nativePathString` is a growing concern

Would you prefer a different name and function composition?  The default string representation uses `/` for separators which is part of the problem.  We should use `\` always - which then needs to be escaped.  We could have `path.native().escaped()` if that is better (as a follow up).

**Comment by tomerd** [comment]
not concerned about the name, concerned about the need to rely on platform specific representation

**Comment by neonichu** [comment]
I think it's correct for this to rely on platform-specific representation, because that's what the Swift compiler expects. If we want our output to be something different, we would have to change what the compiler expects as input.

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
okay! lets do that

**Comment by compnerd** [comment]
It might be interesting to change the compiler to take an encoding which doesn't require escaping, but that is beyond the scope of this change.  I think that we could do something like INI files for the VFS definition that could then be re-encoded to JSON or YAML as the LLVM layer doesn't accept anything but those two encodings and would require the transliteration (I'm not sure if upstream would be too happy about adding yet another file format to support) and the VFS needs to be wired up that layer.  Ultimately, the strings need to be escaped and the platform specific path representation is mandatory when interacting with other tools.

**Pull request merged**
