### PR TITLE
[5.5] Ignore .docc files rather than emitting warnings, since it's useful to have them in packages without warnings

### PR DESCRIPTION
**Pull request by abertelrud**
This is the 5.5 nomination of https://github.com/apple/swift-package-manager/pull/3609.  Same motivation and changes as in that PR.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci test

**Comment by abertelrud** [comment]
The full test failure looks unrelated:
```
/Users/buildnode/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.5/swiftpm/Sources/Commands/SwiftBuildTool.swift:86:35: error: argument passed to call that takes no arguments
21:11:34     @OptionGroup(_hiddenFromHelp: true)
21:11:34                                   ^~~~
21:11:34 /Users/buildnode/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.5/swiftpm/Sources/Commands/SwiftBuildTool.swift:87:9: note: cannot automatically synthesize 'Decodable' because '<<error type>>' does not conform to 'Decodable'
21:11:34     var swiftOptions: SwiftToolOptions
21:11:34         ^
21:11:34 /Users/buildnode/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.5/swiftpm/Sources/Commands/SwiftBuildTool.swift:77:15: error: type 'SwiftBuildTool' does not conform to protocol 'Decodable'
21:11:34 public struct SwiftBuildTool: SwiftCommand {
21:11:34               ^
21:11:34 Swift.Decodable:2:5: note: protocol requires initializer 'init(from:)' with type 'Decodable'
21:11:34     init(from decoder: Decoder) throws
21:11:34     ^
21:11:34 ninja: build stopped: subcommand failed.
```

**Comment by abertelrud** [comment]
In fact that looks like an issue with the swift-argument-parser version being used.

**Comment by abertelrud** [comment]
Ah yes, that is mentioned in other PRs.  Running the smoke test again, since it should have been cleared up based on comments I see in other PRs.

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci test

**Comment by abertelrud** [comment]
Looks like the smoke test is using swift-argument-parser 0.4.1 but swift-package-manager needs 0.4.3.  But that's not a new requirement in this PR.  That was added in 1a361f768 on July 8.

@shahmishal or @neonichu do you know why the smoke test here used 0.4.1?  Or to whom would I need to talk to get that updated?

I this case I think that as long as the full test passes, we can merge, since the smoke test isn't required and the failure is a configuration and not a code issue.  But it would be good to update the swift-argument-parser version that's used.

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
Updated with the refinement in https://github.com/apple/swift-package-manager/pull/3620.

**Pull request merged**
