### PR TITLE
Support additional dependencies in forced resolution mode

### PR DESCRIPTION
**Pull request by neonichu**
rdar://115630439

### CODE REVIEW

**Comment by neonichu** [comment]
Seems like adding to managed dependencies isn't the only missing piece here, so more work is required for this.

**Comment by neonichu** [comment]
Ah the issue with this PR is actually pretty simple: we need to prepopulate managed dependencies a bit earlier, at the point where I am doing it, they have already been dropped from the equation.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by shahmishal** [comment]
@swift-ci please test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by MaxDesiatov — APPROVED** [review]
Do we have the terminology documented anywhere in the codebase? What's the best place to check what a managed dependency or a root is?

**Comment by neonichu** [comment]
> Do we have the terminology documented anywhere in the codebase? What's the best place to check what a managed dependency or a root is?

Don't think we have any meaningful docs for this.

**Pull request merged**
