### PR TITLE
Fetch Pre-release version SR-1039

### PR DESCRIPTION
**Pull request by kostiakoval**
## Problem
We need to fetch a specific Pre-release version tag [SR-1039](https://bugs.swift.org/browse/SR-1039)
```swift
import PackageDescription

let package = Package(
    dependencies: [
        .Package(url: "../Foo",  "0.1.0-a")
    ]
)
```

Currently we store all `Version` information in a `Range `. 
`Version` type iterates over a range by increasing `major`, `minor`, or `patch` part.
```swift
"0.1.0".successor() //  "0.1.1"
"0.1.0-a".successor() //  "0.1.1"
```
Because of that when we store `Version` with Pre-release identifiers in a range, we lose precision information. 
**Example:**
```swift
"0.1.0-a"..."0.1.0-a"  //"0.1.0-a"..< "0.1.1"
```

## Solution
As a solution I propose to make own `VersionRange` type and store start and end elements of the range.
In that case we have all precision information.

**Example:**
```swift
let versionRange = "0.1.0-a"..."0.1.0-a"  
versionRange.start //"0.1.0-a" 
versionRange.end //"0.1.0-a"
versionRange.range //"0.1.0-a"..< "0.1.1"
```

Looking for feedback and ideas :) 
If you approve that idea I'm going to continue implementing **SR-1039** with using `VersionRange` type

### CODE REVIEW

**Comment by kostiakoval** [comment]
@mxcl Done. Please review and test  :)

**Comment by mxcl** [comment]
I have concerns about our approach here.

A principle we have decided on is: the package graph should *never* contain pre-releases, that is pre 1.0 or `> 1` pre-release-indentifiers. This is because unstable APIs in a regular package graph will make packaging with our tool unreliable.

So with this in mind, we should not allow pre-release identifiers in a `Package.swift`.

So how should we approach this?

I think the use case is important. *Who* wants pre-release identifiers? IMO it is package developers, they are supporting a new API early so their packages can be ready when the final release occurs.

Package developers probably want more control over these situations than others, so it may be acceptable to just bump this feature to the lockfiles proposal. In that situation the developer can make a pre-release branch, set the lock to the pre-release for the dependency they are interested in, and develop in the topic branch.

Let me know your thoughts on this topic.

**Comment by JPMartha** [comment]
Hi, I'm JPMarha.

> I think the use case is important. 

Yeah, good point.

> Who wants pre-release identifiers? 

I think it is package developers, too.

But I don't understand who the SPM uses expept package developers.

**Comment by mxcl** [comment]
IMO, the vast majority of people using CocoaPods and Carthage are making apps that consume packages.

**Comment by kostiakoval** [comment]
I agree with all the point, they make sense.

> I think the use case is important. Who wants pre-release identifiers?

Both app and package developers.
- App devs. Lock file solves theirs issue.
- package devs. 

Use case - I need to fix bug in my package dependency and publish my fixed package.  
- Fix already exist in the dependency I use. I just need to fetch pre-release or commit. 
- I need to fix it myself. Fork, fix, publish

  
> So with this in mind, we should not allow pre-release identifiers in a Package.swift. 

I would love to keep dependency graph simple with only released tags.
Then we should not allow people specifying pre-release tags. Now it's very common issue.

****

As a developer if I don't have 100% control over my decencies (with using some dependency manager tool), that scares me because I could get in a locked situation. 
If SwiftPM wouldn't support that, that could stop me from using SwifrPM.

When using CocoaPods or Carthage I almost never use pre-release tags. 
But I know that they both support it and in case I need it, it's there. As example when Swift 1.0 came out, there was big demand for that feature because all packages were in pre-release for Swift

Maybe it would be better to solve Lock file first.

**Comment by JPMartha** [comment]
> IMO, the vast majority of people using CocoaPods and Carthage are making apps that consume packages.

I think so, too.

I'm really sorry that I couldn't explain that the difference between apps developers and package developers well. 🙏

**Comment by mxcl** [comment]
Just to clarify what I have said:

> the package graph should never contain pre-releases

I meant, it should never have pre-releases unless the end-user explicitly opts-in.

**Comment by norio-nomura** [comment]
I noticed that we can fetch pre-release version by using following:
```swift
import PackageDescription

let package = Package(
    name: "Quick",
    // TODO: Once the `test` command has been implemented in the Swift Package Manager, this should be changed to
    // be `testDependencies:` instead. For now it has to be done like this for the library to get linked with the test targets.
    // See: https://github.com/apple/swift-evolution/blob/master/proposals/0019-package-manager-testing.md
    dependencies: [
        .Package(url: "https://github.com/norio-nomura/Nimble", "5.0.0-alpha.3020160412a")
    ]
)
```

Maybe it affected by [SE-0065](https://github.com/apple/swift-evolution/blob/master/proposals/0065-collections-move-indices.md).

**Comment by aciidb0mb3r** [comment]
Tracking efforts for this here https://bugs.swift.org/browse/SR-2917

**Pull request closed without merging**
