### PR TITLE
Basics: vendor `Triple`, reduce dependency on TSC

### PR DESCRIPTION
**Pull request by MaxDesiatov**
As we want to reduce our dependency on TSC, it makes sense to move `Triple` to our codebase and deprecate it in TSC.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test Linux

**Review by tomerd — APPROVED** [review]
lgtm

**Comment by neonichu** [comment]
Does swift-driver have their own triple type?

**Comment by MaxDesiatov** [comment]
Yes, it does. I will only need to update SourceKit-LSP after this is merged.

**Pull request merged**
