### PR TITLE
[5.9] Update to swift-certificates 0.4.0

### PR DESCRIPTION
**Pull request by yim-lee**
Cherry-pick https://github.com/apple/swift-package-manager/pull/6316 to 5.9

---

- Adjust code
- Re-enable `SigningTests.testCMSCheckCertificateRevocationStatus`
- Implement `SignatureProvider.extractSigningEntity`
- Rework disabling of certificate expiry check
- Update `OCSPPolicy` usage

### CODE REVIEW

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65229

@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65229

@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65229

@swift-ci please test Windows platform

**Pull request merged**
