### PR TITLE
NFC: cleanup usage of URL in tests

### PR DESCRIPTION
**Pull request by tomerd**
motivation: test code that is easier to reason about

changes:
* in test code, conform URL to ExpressibleByStringLiteral and ExpressibleByStringInterpolation
* update call sites (test) to use simple string instead of initializing and unwrapping URL

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
cc @yim-lee

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by yim-lee — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-ci please smoke test Windows

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Pull request merged**
