### PR TITLE
[WIP] Add thread sanitizer support

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
- [ ] Make it work for parallel test runner
- [ ] Add tests
- [ ] Test on linux
- [ ] Cleanup and documentation

### CODE REVIEW

**Comment by ddunbar** [comment]
In keeping with how this is exposed in the compiler, I would prefer to expose this as —sanitize=thread (and to pave the way for all the other sanitizers)

**Comment by felix91gr** [comment]
Hi! It’s awesome to see SPM integrating with TSan.
In [this Swift PR](https://github.com/apple/swift/pull/6446), Carl Brown added support for the Sanitizer on Linux. If you have any trouble with the Linux tests, maybe you can ask him for help. He’s the most knowledgable user of TSan on Linux that I know of ^^

**Comment by aciidb0mb3r** [comment]
Closing until I get time to work on this.

**Comment by andrewtheis** [comment]
@aciidb0mb3r Did Apple resolve this issue?

**Pull request closed without merging**
