### PR TITLE
PackageDescription: repair the build after #3635

### PR DESCRIPTION
**Pull request by compnerd**
The C imports are important, particularly on Windows, where `HANDLE` is
not available without the platform SDK (`WinSDK` is roughly synonymous
to `Darwin`).

_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Review by drexin — APPROVED** [review]
👍

**Review by abertelrud — APPROVED** [review]
LGTM.  FWIW, in the next week or two I also plan to clean up the package manifest output so we can get rid of some of these platform-specifics (at least the writing out of the JSON on a separate pipe) by reusing some of the code that's used for package plugins.  But of course this should be put back meanwhile; I only mention it to point out that we should be able to get rid of some of this again soonish.

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Started the smoke test, which is what's required for main.

**Comment by tomerd** [comment]
@compnerd @shahmishal I would love to be able to test Windows in CI, what need to be done to get there?

**Pull request merged**
