### PR TITLE
Update the Swift version to 5.6.1

### PR DESCRIPTION
**Pull request by shahmishal**
_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Review by abertelrud — APPROVED** [review]

**Comment by abertelrud** [comment]
Thanks @shahmishal.  Ready to merge?

**Comment by shahmishal** [comment]
Yes

**Comment by GMinzolt** [comment]
- [ ]

**Pull request merged**
