### PR TITLE
Update build-using-cmake script

### PR DESCRIPTION
**Pull request by keith**
This was missing some required deps

### CODE REVIEW

**Review by neonichu — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
I wonder if we should retire this tbh? @tomerd 

@keith Curious what your use case for these is that wouldn't be served by the bootstrap script as well

**Comment by keith** [comment]
FWIW building with the boostrap script currently fails for me, but I haven't debugged yet:

```
Building for debugging...
ld: file not found: /Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/debug/PackagePlugin.build/ArgumentExtractor.swift.o
ld: file not found: /Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/debug/PackageDescription.build/BuildSettings.swift.o
[144/645] Linking libPackageDescription.dylib
--- bootstrap: error: Command '['env', 'SDKROOT=/Applications/Xcode-13.4.0-RC1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk', 'SWIFTCI_USE_LOCAL_DEPS=1', 'SWIFTPM_MACOS_DEPLOYMENT_TARGET=10.15', 'DYLD_LIBRARY_PATH=/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/bootstrap/lib:/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/tsc/lib:/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/llbuild/lib:/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/yams/lib:/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/swift-argument-parser/lib:/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/swift-driver/lib:/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/swift-crypto/lib:/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/swift-system/lib:/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/swift-collections/lib:/Applications/Xcode-13.4.0-RC1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx:/usr/lib/swift', 'SWIFT_EXEC=/Applications/Xcode-13.4.0-RC1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc', 'SWIFT_DRIVER_SWIFT_EXEC=/Applications/Xcode-13.4.0-RC1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc', 'SWIFTPM_CUSTOM_LIBS_DIR=/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/bootstrap/pm', '/Users/ksmiley/dev/oss-swift/swiftpm/.build/arm64-apple-macosx/bootstrap/bin/swift-build', '--disable-sandbox', '--force-resolved-versions', '--build-path', '/Users/ksmiley/dev/oss-swift/swiftpm/.build', '-Xlinker', '-rpath', '-Xlinker', '@executable_path/../lib/swift/macosx', '-Xswiftc', '-module-cache-path', '-Xswiftc', '/Users/ksmiley/dev/oss-swift/swiftpm/.build/module-cache', '-Xmanifest', '-module-cache-path', '-Xmanifest', '/Users/ksmiley/dev/oss-swift/swiftpm/.build/module-cache']' returned non-zero exit status 1.
```

**Comment by neonichu** [comment]
Ah I see. The CI uses the `bootstrap` script, my guess would be that `build-using-cmake` is what we may have used prior to that.

**Comment by tomerd** [comment]
I am not aware of any usage of `build-using-cmake`, so yes we should probably retire it (sorry about the hassle).

**Comment by keith** [comment]
https://github.com/apple/swift-package-manager/pull/5655

**Comment by keith** [comment]
should we remove the one in TSC as well then?

**Comment by tomerd** [comment]
> should we remove the one in TSC as well then?

I am not aware of any usage of it either. @compnerd are you using it by any chance?

**Comment by compnerd** [comment]
Nope, this wouldn't be used on Windows (bash and all).  On Linux, I would simply build the same way as Windows (directly invoking CMake).

**Comment by tomerd** [comment]
closing in favor of https://github.com/apple/swift-package-manager/pull/5655

**Pull request closed without merging**
