### PR TITLE
manifest loading performance

### PR DESCRIPTION
**Pull request by tomerd**
motivation: improve dependency resolution performance

changes: use semaphore instead of operation queue when loading manifests which has lower overhead and allows us to manage the concurrency more accurately as the operation queue syle did not wait for the loading to complete

### CODE REVIEW

**Comment by tomerd** [comment]
cc @pcbeard

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
ci infra issues failing PRs cc @shahmishal

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]
LTGM!

**Pull request merged**
