### PR TITLE
[6.0] Support macros when cross-compiling

### PR DESCRIPTION
**Pull request by MaxDesiatov**
**Explanation**: Macros cross-compiled by SwiftPM with Swift SDKs should be correctly built, loaded, and evaluated for the host triple.
**Scope**: isolated to modules dependency resolution and llbuild, does not impact code related to XCBuild.
**Risk**: medium, known issues were addressed on `main` and are cherry-picked here, with no new issues reported for a few weeks now.
**Testing**: added unit tests, manual end-to-end testing done with existing Swift SDKs.
**Issue**: rdar://105991372
**Reviewers**: @bnbarham @xedin @neonichu

(cherry picked from commit cb3b0856f3616e9a505c94d2c7958b83ab32f9f6, https://github.com/apple/swift-package-manager/pull/7353)

```
# Conflicts:
#	CHANGELOG.md
#	Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
#	Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
#	Sources/Build/BuildPlan/BuildPlan.swift
#	Sources/Commands/SwiftTestCommand.swift
#	Sources/Commands/Utilities/PluginDelegate.swift
#	Sources/Commands/Utilities/TestingSupport.swift
#	Sources/PackageGraph/ModulesGraph+Loading.swift
#	Sources/PackageGraph/ModulesGraph.swift
#	Sources/SPMTestSupport/MockBuildTestHelper.swift
#	Sources/SPMTestSupport/MockPackageGraphs.swift
#	Sources/SPMTestSupport/PackageGraphTester.swift
#	Sources/SPMTestSupport/ResolvedTarget+Mock.swift
#	Tests/BuildTests/ClangTargetBuildDescriptionTests.swift
#	Tests/BuildTests/CrossCompilationBuildPlanTests.swift
#	Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
```

(cherry picked from commit b9eb3c138ec681d8858de4d8bf7d179758490ba1, https://github.com/apple/swift-package-manager/pull/7493)

```
# Conflicts:
#	Sources/PackageGraph/ModulesGraph+Loading.swift
#	Sources/PackageGraph/Resolution/ResolvedPackage.swift
```
(cherry picked from commit 5a4c0240c771db9dab8b5b264a9d368dfe11f0fc, https://github.com/apple/swift-package-manager/pull/7508)

```
# Conflicts:
#	Sources/Commands/SwiftBuildCommand.swift
#	Sources/Commands/SwiftTestCommand.swift
#	Sources/Commands/Utilities/TestingSupport.swift
```

(cherry picked from commit 8db240186de97b01c2d2fb351b367bbdd43fe6b6, https://github.com/apple/swift-package-manager/pull/7519)

```
# Conflicts:
#	Tests/BuildTests/CrossCompilationBuildPlanTests.swift
```

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by DougGregor — APPROVED** [review]
Thank you for bringing this into 6.0!

**Comment by rauhul** [comment]
I think you might also want this change: https://github.com/apple/swift-package-manager/pull/7629

**Comment by xedin** [comment]
I cherry-picked:

 - https://github.com/apple/swift-package-manager/pull/7471
- https://github.com/apple/swift-package-manager/pull/7593
 - https://github.com/apple/swift-package-manager/pull/7619
 - https://github.com/apple/swift-package-manager/pull/7646 (this supersedes https://github.com/apple/swift-package-manager/pull/7629)

And opened an aligned sourcekit-lsp PR - https://github.com/apple/sourcekit-lsp/pull/1454

**Comment by xedin** [comment]
https://github.com/apple/sourcekit-lsp/pull/1454
@swift-ci please test

**Comment by xedin** [comment]
https://github.com/apple/sourcekit-lsp/pull/1454
@swift-ci please test Windows platform

**Comment by xedin** [comment]
https://github.com/apple/sourcekit-lsp/pull/1454
@swift-ci please test

**Comment by xedin** [comment]
https://github.com/apple/sourcekit-lsp/pull/1454
@swift-ci please test Windows platform

**Comment by xedin** [comment]
https://github.com/apple/sourcekit-lsp/pull/1454
@swift-ci please test macOS platform

**Comment by xedin** [comment]
https://github.com/apple/sourcekit-lsp/pull/1454
@swift-ci please test Linux platform

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
