### PR TITLE
[5.8] Swift to swift-crypto v2.x

### PR DESCRIPTION
**Pull request by yim-lee**
Cherry-pick https://github.com/apple/swift-package-manager/pull/5920 to 5.8

rdar://82934196

### CODE REVIEW

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/62894
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by buttaface** [comment]
I think this version bump [broke cross-compiling the latest Jan. 10 5.8 snapshot of SPM on my Android CI](https://github.com/buttaface/swift-android-sdk/actions/runs/3891267478/jobs/6641306418#step:6:7480), will look into it and let you know.

**Comment by yim-lee** [comment]
@buttaface Looks like swift-crypto 1.x is being used? The code uses `OpaquePointer` for swift-crypto v2 and `UnsafeMutablePointer<X509*>` for v1.

**Comment by buttaface** [comment]
@yim-lee, yep, that's it, dumb mistake on my part. 😮

**Comment by yim-lee** [comment]
@compnerd Yes: https://github.com/apple/swift/pull/62894

**Pull request merged**
