### PR TITLE
[5.9] Change TargetGroup enum param to packageAccess bool in target declaration

### PR DESCRIPTION
**Pull request by elsh**
Target declaration now contains packageAccess bool param instead of enum group param
Resolves rdar://108361064

### CODE REVIEW

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
main https://github.com/apple/swift-package-manager/pull/6463

**Review by MaxDesiatov — APPROVED** [review]

**Review by tomerd — CHANGES_REQUESTED** [review]
did not have a chance to review the PR on "main" before it was merged, but left a few comments there. the change set may needs to be amended before taking to 5.9

**Comment by tomerd** [comment]
@elsh please refrain from setting auto-merge on PRs. The SwiftPM team prefers to be the one merging based PRs on the time that works best for the release and other PRs in flight

**Comment by elsh** [comment]
> did not have a chance to review the PR on "main" before it was merged, but left a few comments there. the change set may needs to be amended before taking to 5.9

Replied to the comments on https://github.com/apple/swift-package-manager/pull/6463

**Comment by elsh** [comment]
This PR includes https://github.com/apple/swift-package-manager/pull/6473

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test windows

**Comment by elsh** [comment]
@tomerd Should we not merge this PR this week? FYI the feature is still not enabled for 5.9. After the proposal is accepted, a separate PR will be created to enable it.

**Comment by tomerd** [comment]
@elsh this be updated to include all the recent changes on the main branch

**Comment by elsh** [comment]
> @elsh this be updated to include all the recent changes to this feature (eg default) that went on the main branch

It includes them as posted in the earlier comment.

**Review by tomerd — APPROVED** [review]

**Pull request merged**
