### PR TITLE
Refactor publication signing into PackagePublication module

### PR DESCRIPTION
**Pull request by yim-lee**

### CODE REVIEW

**Review by tomerd — APPROVED** [review]
nice

**Comment by tomerd** [comment]
maybe also presents an opportunity to do more unit level testing

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Pull request closed without merging**
