### PR TITLE
Rename xctest executable to avoid inferring it as module name

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Fixes https://bugs.swift.org/browse/SR-1243

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
or should it be called <name>TestSuite.xctest ?

**Comment by czechboy0** [comment]
I'm having the issue that this fixes here: https://github.com/czechboy0/Redbird
Just clone, run swift build & test on Linux and you should see it. Would really appreciate this fix making it into the next toolchain!

**Comment by aciidb0mb3r** [comment]
Now I am wondering if its better to pass explicit `-module-name` flag instead as we try to find this executable via swift-test, will need to append name there too.

**Comment by rolivieri** [comment]
Is there an ETA for when this fix will be merged? This is a critical issue as described in https://bugs.swift.org/browse/SR-1243.

**Comment by aciidb0mb3r** [comment]
@rolivieri I need a confirmation from @mxcl or @ddunbar which way is better here `-module-name` or renaming the executable, then CI and then we can merge it.

**Comment by czechboy0** [comment]
+1, it's breaking several of my projects too. I'm available to help.

**Comment by ddunbar** [comment]
I think that we should do both:
 - Pass `-module-name` explicitly.
 - Rename the built bundle. I think the name should be `<name>Tests` (note plural) for consistency with existing Xcode behavior.

We should also:
 - [ ] Have a follow on bug for a verification step in SwiftPM that there is no module name collision across the entire package graph. This is probably even a StarterBug.
 - [ ] Figure out why our CI didn't catch this.

**Comment by czechboy0** [comment]
@ddunbar I think there are two reasons why CI didn't catch this.
1. This fails under special circumstances, namely (from the SR bug description)

> A helper function is defined inside a class that extends XCTestCase and receives as a parameter a structure defined in the Swift module that is being tested. If the helper function is commented out or the parameter type of the function is changed to, say String, then 'swift test' executes with no errors.

And
2. There still isn't a way to run `swift test` on a fixture in tests, something that #266 would help with. This is also not the first time that `swift build` succeeded on a fixture, but `swift test` failed. I think we should have a way to run `swift test` on a fixture to prevent bugs like these from sneaking in.

**Comment by ddunbar** [comment]
Agreed, can you open an SR on the missing coverage for `swift test`?

**Comment by aciidb0mb3r** [comment]
@ddunbar  Updated the PR, will file a bug for collision check

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by czechboy0** [comment]
@ddunbar Here's a SR for running swift-test on fixtures: https://bugs.swift.org/browse/SR-1351

**Pull request merged**
