### PR TITLE
Basics: make `ObservabilityScope` conform to `Sendable`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Depends on https://github.com/apple/swift-package-manager/pull/6022.

### Motivation:

New `actor HTTPClient` can't take `ObservabilityScope` as an argument to its functions as it's not `Sendable`. This is the only major API difference between `HTTPClient` and `LegacyHTTPClient`, which we'd like to resolve.

### Modifications:

Marked `SwiftToolObservabilityHandler.OutputHandler`, `ThreadSafeBox`, `ThreadSafeArrayStore`, and `ThreadSafeKeyValueStore` either `UnsafeSendable` or `@unchecked Sendable`, depending on Swift version. Made `ObservabilityMetadata: Sendable` by requiring its keys and values to be sendable. Added additional `Sendable` requirement on `DiagnosticsHandler`.

### Result:

This allows passing `ObservabilityScope` instances to `HTTPClient/execute`.

### CODE REVIEW

**Review by neonichu — DISMISSED** [review]

**Review by tomerd — APPROVED** [review]

**Review by tomerd — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
I'm pretty sure stacked/chained PRs no longer either in this repository or GitHub altogether. It no longer automatically changes base branches if those were already merged, and dismisses reviews if a base branch is changed manually. @neonichu sorry about re-requesting your review because of this.

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4683
@swift-ci smoke test macOS

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test macOS

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test macOS

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test macOS

**Comment by MaxDesiatov** [comment]
@swift-ci clean test

**Comment by MaxDesiatov** [comment]
@swift-ci clean smoke test

**Comment by MaxDesiatov** [comment]
Not sure how to fix the macOS self-hosted job error with old Xcode on CI, and it isn't reproducible locally with newer Xcode. Putting this into a draft state until macOS CI nodes are updated to newer Xcode and Swift.

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@cis

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci test Windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test Windows

**Pull request merged**
