### PR TITLE
Change to using AbsolutePath-based `isDirectory`, `isFile`, `isSymlink` et.al.

### PR DESCRIPTION
**Pull request by abertelrud**
Change to using AbsolutePath-based `isDirectory`, `isFile`, `isSymlink`, and `exists` checks.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
Any reason not to use API on FileSystem? then isFile etc can become internal to Basic

**Comment by abertelrud** [comment]
The reason is to minimize risk by doing this in stages, and also for staging reasons (as I'll explain below).  I have been switching the string-based accessors over to the ones in `PathShims`.  Of course it will transition to FileSystem at some point, but I wanted to complete the transition I had started rather than change it to now use FileSystem.  It will be easy to syntactically change the free functions to use the file system, but instead of blindly switching to `localFileSystem.isFile()` etc, I would want that transition to involve some analysis of which pieces of code should really take a reference to a `FileSystem` object and which should always use `localFileSystem`.  I didn't want to delay the deprecation and removal of `Utility.Path` by blocking it on those kinds of API changes.  And if I switched everything to `localFileSystem.isFile()` for now, then it would become difficult later to see which ones still needed to be converted to be abstract and which ones should really be using `localFileSystem`.  This way, you know that when you see `isFile(path)` (the free function) it's a place that needs to be considered in terms of how generic of a FileSystem API it should have.

Hopefully that makes sense.  One can of course argue about the approach, but for the reason above I thought it best to complete the transition as originally planned.

**Comment by aciidb0mb3r** [comment]
thanks for the explaining, I think it makes sense 👍

**Comment by abertelrud** [comment]
Just so you know, the plan is that after removing `Utility.Path`, I'll move on to other code changes and then whoever of us gets to it first can do the transition to `FileSystem` (which will likely be done in stages and take some discussion).

**Comment by abertelrud** [comment]
So the goal right now is to finish the transition by removing `Utility.Path`.  `PathShims` will have to stay for a little while but at least it's in the right module then.  Oh, and before being done with this phase, I'll do the `AbsolutePath` -> `Path` renaming that was always planned.

**Comment by abertelrud** [comment]
But I have to remove `Utility.Path` (as well as the badly misnamed one in `Options`) before doing that.

**Comment by aciidb0mb3r** [comment]
Ah cool! Sounds good
I didn't know that AbsolutePath is planned to be renamed to Path. Will it be Path and RelativePath then?

**Comment by abertelrud** [comment]
That's the idea.  I wasn't originally too keen on it, but it has been pointed out to me that the vast majority of time, what you really want to operate on is an absolute path, so why keep repeating that word.  I'm still not 100% about it but am willing to give it a try.

**Comment by ddunbar** [comment]
LGTM

**Pull request merged**
