### PR TITLE
Add flag to skip signature validation

### PR DESCRIPTION
**Pull request by yim-lee**
Motivation:
Need a way to disable signature validation

Modifications:
Add `--enable-signature-validation`/`--disable-signature-validation` flag to security options. Default is enabled.

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Review by neonichu — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
@swift-ci pleases test Windows platform

**Comment by yim-lee** [comment]
@swift-ci pleases test Windows platform

**Comment by yim-lee** [comment]
@swift-ci pleases test Windows platform

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Pull request merged**
