### PR TITLE
Update help message in `InstalledPackages.swift`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Cleaned up the help message to make it clear what executable products are uninstalled.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test linux

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test linux

**Review by tomerd — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test macos

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test macos

**Pull request merged**
