### PR TITLE
[Init] Handle case when directory name and c99name are not same.

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Bug: https://bugs.swift.org/browse/SR-1862

### CODE REVIEW

**Comment by kostiakoval** [comment]
I think it should be possible to create packages with non `c99name`

The `pkgname` and `moduleName` would be different it that case. it could be potentially confusing to users what is the `pkgname` and `moduleName` when to use them and what is the difference.

I've seen many people struggling with issue in Xcode when you name a Swift project and with `-` and it transforms it to "_" and you have to know it when importing it.

**Comment by ddunbar** [comment]
@kostiakoval I think the only case this fails is if c99name would throw because of an empty name, for example a directory called "-".

**Comment by ddunbar** [comment]
@aciidb0mb3r Can we get a test case?

**Comment by aciidb0mb3r** [comment]
Added test case, dependant on #430 merge

**Comment by ddunbar** [comment]
LGTM

**Comment by ddunbar** [comment]
@swift-ci please test

**Pull request merged**
