### PR TITLE
[Build] Fix up the cmake build after swift-syntax was added

### PR DESCRIPTION
**Pull request by bnbarham**
Doesn't FetchContent when it isn't available right now, but we don't fetch any of the other required dependencies either. Can fix that when we fix them all.

### CODE REVIEW

**Comment by bnbarham** [comment]
https://github.com/apple/swift/pull/73267

@swift-ci please test

**Review by DougGregor — APPROVED** [review]
This definitely looks simpler

**Comment by bnbarham** [comment]
https://github.com/apple/swift/pull/73267

@swift-ci please test

**Comment by bnbarham** [comment]
I forgot we bootstrap with CMake even outside of Windows :(

**Pull request closed without merging**
