### PR TITLE
explicitly indicate the TSCUtility interfaces used

### PR DESCRIPTION
**Pull request by compnerd**
This explicitly identifies the TSCUtility interfaces that SPM depends
on. This helps identify a "burn down list" of interfaces that remain in
TSC(Utility) which are in use. As these interfaces are replaced, we can
easily monitor the remaining interfaces that are in use.

_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @tomerd

**Comment by tomerd** [comment]
this is great @compnerd but has some conflicts now (crunch time ;p). mind rebasing so we can get it merged?

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Pull request merged**
