### PR TITLE
Set CLANG_ENABLE_MODULES to YES when generating projects

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
I think this was kept intentionally off because we have non-modular includes in swiftpm packages and it caused issues with autocompletion when a clang module is present. Can you check if autocomplete still works (in packages with Clang and Swift targets) after turning this on?

**Comment by yonaskolb** [comment]
@keith any updates?

**Comment by keith** [comment]
I haven't had a chance to check this yet. If anyone has a chance to try and get a project that fails for this issue that'd be awesome! Otherwise I will try to soon

**Comment by aciidb0mb3r** [comment]
I just checked this and autocomplete still falls over if this setting turned on. https://github.com/apple/swift-package-manager/pull/1406 seems like a better solution but needs verification.

**Comment by keith** [comment]
I'll close this one then

**Pull request closed without merging**
