### PR TITLE
Synthesize Equatable where possible

### PR DESCRIPTION
**Pull request by mdiep**
While looking through the source, I noticed that some of these could be removed.

### CODE REVIEW

**Comment by hartbit** [comment]
@swift-ci please smoke test

**Comment by hartbit** [comment]
@aciidb0mb3r this LGTM. Ok if I merge once tests pass?

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
Yep, this looks great. Thanks!

**Comment by mdiep** [comment]
_bump_

**Pull request merged**
