### PR TITLE
use newer testing conventions in plugin tests 

### PR DESCRIPTION
**Pull request by tomerd**
motivation: cleaner code

changes
* use string form of writeFileContents
* do not wrap fixtures with try/catch

### CODE REVIEW

**Comment by tomerd** [comment]
needs #4156  first

**Comment by abertelrud** [comment]
Thanks!

**Review by abertelrud — APPROVED** [review]
Thanks!

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Pull request merged**
