### PR TITLE
Added option to enable CMake Install

### PR DESCRIPTION
**Pull request by gmittert**
Since SwiftPM does its own installation using the bootstrap script, it
hides the CMake install target to only be enabled on Windows which
doesn't use the bootstrap script. But when bootstrapping using CMake on
non Windows platforms, it would be nice to be able to enable them.

### CODE REVIEW

**Comment by gmittert** [comment]
@swift-ci please test

**Comment by gmittert** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Yep, I think @compnerd mentioned that he also wanted this for the Windows port.

(great branch name btw)

**Comment by neonichu** [comment]
macOS failure seems unrelated:

> Build timed out (after 45 minutes). Marking the build as failed.

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
> - Multiple (2) `Option` or `Flag` arguments are named "--enable-code-coverage".

**Comment by neonichu** [comment]
Can definitely reproduce locally with `swift test --parallel` and this assertion is coming from "/Users/neonacho1/Projects/swiftpm-public/.build/checkouts/swift-argument-parser/Sources/ArgumentParser/Parsable Types/ParsableArguments.swift".

@natecook1000 would you be able to take a look?

**Comment by natecook1000** [comment]
I'm seeing this in `master` with ArgumentParser version 0.3.1, as well — looks like it's an actual ambiguity that the new version diagnoses between these two declarations:

https://github.com/apple/swift-package-manager/blob/master/Sources/Commands/SwiftPackageTool.swift#L543-L546
https://github.com/apple/swift-package-manager/blob/master/Sources/Commands/Options.swift#L191-L193

Quickest way to resolve is to version lock ArgumentParser at 0.3.0, but ultimately it'd be great to resolve that ambiguity (there are probably way too many things declared in `SwiftOptions`).

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Pull request merged**
