### PR TITLE
[PackageBuilder] Create modules in a package in reverse topological o…

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
…rder

This way we don't need to set dependencies after creating the modules.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
OSX CI has problems, I tested this locally.

**Comment by neonichu** [comment]
LGTM ✅

**Pull request merged**
