### PR TITLE
Get rid of `Utility.Path`

### PR DESCRIPTION
**Pull request by abertelrud**
Get rid of `Utility.Path` by switching the last clients of the last
methods over to other code.  This means that we are down to just the
AbsolutePath and RelativePath types (plus a misnamed struct in the
`Options` class which will soon get renamed).

As part of this removal, the computed property `prettypath` has been
moved onto AbsolutePath in `Basic.PathShims`.  I would like to see us
use a Path->String formatter instead, but all of that can be discussed
after this lands.

Apart from renaming `AbsolutePath` to `Path` after an appropriate amount
of discussion about whether or not that is wise, this completes the path
transition.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
awesome!

**Comment by abertelrud** [comment]
Fixed a Linux build failure found in local testing on Ubuntu 15.10

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
Awesome!

**Pull request merged**
