### PR TITLE
#4701 - Resolves SR-10803

### PR DESCRIPTION
**Pull request by Overcot**
Added additional description for swift-package init -help command explaining what each type means

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

I added description using swift-argument-parser @Option which was discussed in #4701. Also added several small unit tests on this behaviour
### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by tomerd** [comment]
cc @natecook1000 0 would be nice to do this in a structured way, i.e. if the enum confirm to a protocol providing the help string per case and the help builder iterates and builds the helps for the cases

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
thanks @Overcot! could you please fix the indention to be consistent with the rest of the code? it seems a bit off

**Comment by Overcot** [comment]
> thanks @Overcot! could you please fix the indention to be consistent with the rest of the code? it seems a bit off

Yeah, sure. Just used indention which was used by swiftformat which was decribed in a contributing guide. Also, do you prefer rebase and force-push new commit or create additional commit for required change?

**Comment by tomerd** [comment]
> Also, do you prefer rebase and force-push new commit or create additional commit for required change?

your call, we normally squash into one commit when merging

**Comment by Overcot** [comment]
@tomerd could you please run tests?)

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — COMMENTED** [review]
thanks @Overcot looks like indentation is still off compared
to the other lines, maybe your IDE settings are not the default?

**Comment by Overcot** [comment]
> thanks @Overcot looks like indentation is still off compared
> to the other lines, maybe your IDE settings are not the default?

@tomerd thanks for feedback. found that i don't need extra line for a bracket and was using tabs instead of spaces. Also changed layout of properties a little bit. Everything else seems to be the same (in Xcode widths & indents as 4).

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
thanks @Overcot

**Pull request merged**
