### PR TITLE
Cherry-picks to `release/6.0` for sourcekit-lsp update

### PR DESCRIPTION
**Pull request by ahoppen**
- **Explanation**: Cherry-pick the following to PRs which are companions of https://github.com/apple/sourcekit-lsp/pull/1213
  - https://github.com/apple/swift-package-manager/pull/7505
  - https://github.com/apple/swift-package-manager/pull/7492
- **Scope**: CMake build and SourceKit-LSP API
- **Risk**: Low, the SourceKit-LSP API is only used by SourceKit-LSP and the CMake build changes will all be caught at build-time
- **Testing**: n/a
- **Issue**: n/a
- **Reviewer**:   @DougGregor and @MaxDesiatov on https://github.com/apple/swift-package-manager/pull/7505 and https://github.com/apple/swift-package-manager/pull/7492

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift-package-manager/pull/7520
https://github.com/apple/sourcekit-lsp/pull/1213

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2637
https://github.com/apple/sourcekit-lsp/pull/1213

@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
Windows failure is:
```
-- Installing: T:/Program Files/Swift/Toolchains/0.0.0+Asserts/usr/lib/swift/host/SwiftIDEUtils.swiftmodule/x86_64-unknown-windows-msvc.swiftinterface
CMake Error at _deps/swiftsyntax-build/Sources/SwiftCompilerPlugin/cmake_install.cmake:45 (file):
  file INSTALL cannot find "T:/12/bin/SwiftCompilerPlugin.dll": No such file
  or directory.
Call Stack (most recent call first):
  _deps/swiftsyntax-build/Sources/cmake_install.cmake:107 (include)
  _deps/swiftsyntax-build/cmake_install.cmake:42 (include)
  BuildSupport/SwiftSyntax/cmake_install.cmake:42 (include)
  cmake_install.cmake:42 (include)
```

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/73392
https://github.com/apple/swift-syntax/pull/2637
https://github.com/apple/sourcekit-lsp/pull/1213

@swift-ci Please test

**Pull request merged**
