### PR TITLE
[SR-2142] Shell completion scripts

### PR DESCRIPTION
**Pull request by Bouke**
# How / why

My initial attempt was rather focused on how bash performs auto completions. I added a package command "completions" which received some context about the cursor. However this doesn't work for zsh, which has a richer completion system.

In order to accomodate for the different shells, I have written two separate terminal completion scripts. Each tailored to the specific needs of bash and zsh. The ticket also mentions the fish shell, but I don't have experience with that shell.

# Demo

ZSH:
zsh demo

BASH:
bash demo

# Instructions

For bash, add the following to your ``~/.bash_profile``:

    source /path/to/Utilities/bash/completion

For zsh, add the following line to your ``~/.zshrc``:

    fpath=(/path/to/Utilities/zsh $fpath)
    autoload -U compinit && compinit

# Room for improvement

* I don't have much experience writing shell scripts, it took me quite a while to get this somewhat working. The code might be brittle. However I think it is good to have initial support for shell completion, and the scripts would be improved over time.
* Currently there is no completion for ``swift test -s`` which would be very nice. 
* How would these scripts be published with the toolchains?

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
this is awesome! is it possible to maybe generate these from the options parser?

**Comment by Bouke** [comment]
Some of the arguments might be generated from SwiftPM's options. However for the ZSH there's also some documentation included for all options/arguments, which is currently only available in the semi-structured usage ``-h`` doc. So we would need to store the options with their arguments + flags + etc in a more structured manner. This would also allow to generate the usage doc. Also, a lot of the options are related to the compiler itself. Those options are currently not available from SwiftPM's sources I think?

However I think that's quite a major refactor to land; I'd rather land this PR first.

**Comment by ddunbar** [comment]
This is awesome!

I agree with @aciidb0mb3r that we do need to be concerned about the maintainability.

Here is my proposal:
1. I think we should go ahead and take this, since it clearly adds value.
2. I think we should refactor the shell script so that most of the logic is done via indirecting to `swift package` (either the tools individually, or one tool specifically which has the "autocomplete hook expansion" logic). The first version of this could just be taking the existing logic which is in shell and rewriting it in Swift.
3. We should then refactor that Swift code to use the actual options structs, so things stay in sync.

While we are doing those steps it would be good to get some more comments in the code explaining exactly what is happening for people who are unfamiliar with how shell completion works.

@aciidb0mb3r, @Bouke how does this sound?

**Comment by aciidb0mb3r** [comment]
SGTM

**Comment by abertelrud** [comment]
I agree that this is a useful improvement to take, but we really do need a way to have a single source of truth for these settings.  Please file a JIRA for adding some way to generate these options based on a single specification.

**Comment by abertelrud** [comment]
@Bouke Yes, I don't have a good idea of how that would be implemented either; I was thinking of something along the lines of comparing the --help output with the zsh scripts in some way, or at least detecting that something was added to --help but not to the scripts, but I admit there's a lot of handwaving in that wish.  And to be clear, that would only be as a stopgap until we had a real OptionParser.

So I agree, the better option is to make OptionParser real.  I almost took the time to do this when first normalizing the options among the three subcommands that make up SwiftPM, but didn't have the time.  But I was thinking exactly along the same lines as you outline.  In particular, being able to chain together option parsers for each subcommand it finds.  It would also be good to be able to reuse option definitions, e.g. those for -Xcc flags between the package and build subcommands.  And it should certainly have enough information to know the closure of all valid forms of input, which means that it can be run in reverse to emit the completion scripts.

**Comment by jtomanik** [comment]
Maybe we could use any of the swift template engines (Moustache or Stencil) and have templates to generate those shell files from single source of truth?

**Comment by ddunbar** [comment]
I'm going to go ahead and merge this.

I don't think we should start publishing it in the actual toolchains (i.e. installing it), though, until we a good strategy for maintaining it w.r.t. the option parser. Let's see how we can best iterate on migrating it to that strategy incrementally once it is in...

**Comment by thomaspaulmann** [comment]
Wow, this is awesome! @Bouke great work!

I wanted to build something similar as a plugin for [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh). That would make it a lot easier to setup the completions. Does it make sense to integrate the completions as a plugin to oh-my-zsh? If so, I would be more than happy to do that.

To concern:
* As @ddunbar mentioned, you want start publishing it with the actual toolchain until the strategy for maintaining is clear. What is the state of the iterative migration f.e. the option parser?
* How manage the maintenance of the plugin in the "oh-my-zsh"-Repository?

**Comment by aciidb0mb3r** [comment]
@thomaspaulmann SwiftPM has a new, very extensible, argument parser.(https://github.com/apple/swift-package-manager/blob/master/Sources/Utility/ArgumentParser.swift)

What we should do is: generate the scripts from the parser itself so we don't have to maintain a bunch of these autocomplete scripts. However, AFAIK there is no one actively working on it. 
Contributions welcomed!

I think we can discuss the submission to zsh repository (on swift-build-dev) once we have a working script generator.

**Comment by thomaspaulmann** [comment]
@aciidb0mb3r Thanks for the further information.

Do you have anything in mind how to implement it? I would build a swift script that's generates the zsh completions. The script should use capabilities of the [argument parser](https://github.com/apple/swift-package-manager/blob/master/Sources/Utility/ArgumentParser.swift).

**Comment by Bouke** [comment]
@thomaspaulmann thanks! My goal is to write a shell generation script that's available as a sub command of `swift package`. The current scripts were created by hand and have a few flaws in them.

Once the script is released as part of a next swift release, your oh-my-zsh plugin would be able to take advantage of it. Or you could include the scripts output in the plugin, however that would tie the plugin to a specific release of swift, possibly mismatching the one installed.

**Comment by aciidb0mb3r** [comment]
what we want is some infrastructure built into the argument parser itself (and not a separate script). It should be possible to extend the support for different types of shells (bash, zsh, fish etc) in the parser itself.

**Comment by aciidb0mb3r** [comment]
Maybe something on the lines of:
```swift
parser.generateAutocompleteScript(shell: .bash)
```
Then we can generate these for the shells we support and put them into toolchain during build process

**Pull request merged**
