### PR TITLE
Add new errors to `FileSystemError.description`

### PR DESCRIPTION
**Pull request by neonichu**
Needed for https://github.com/apple/swift-tools-support-core/pull/276

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test
https://github.com/apple/swift-tools-support-core/pull/276

**Comment by neonichu** [comment]
@swift-ci please smoke test
apple/swift-tools-support-core#276

**Comment by neonichu** [comment]
apple/swift-tools-support-core#276
@swift-ci please smoke test

**Comment by neonichu** [comment]
https://github.com/apple/swift-tools-support-core/pull/276
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
Since this is a cross-repo testing PR, it is expected that the self-hosted jobs would fail.

**Review by tomerd — APPROVED** [review]

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
