### PR TITLE
DNM: test 5.8 PR

### PR DESCRIPTION
**Pull request by tomerd**
test 5.8 branch

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by buttaface** [comment]
Yep, same test failed.

**Comment by tomerd** [comment]
@neonichu @abertelrud is this test expected to fail on 5.8. should we xfail it on this branch?

**Comment by neonichu** [comment]
xfail sounds reasonable

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/6458

**Pull request closed without merging**
