### PR TITLE
Remove dependency on swift-system

### PR DESCRIPTION
**Pull request by neonichu**
This dependency is unused and just unnecessarily complicates things.

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]

**Comment by neonichu** [comment]
Hoping I found all remnants of swift-system here. I tested `swift build` and bootstrap locally. There may be clients of SwiftPM in the toolchain that also need updates to their CMake-based builds.

**Comment by neonichu** [comment]
@tomerd from our offline discussion today, it sounds like you don't want us to do this because we anticipate to eventually use this dependency? But we can do it for TSC, is that a correct summary?

**Comment by tomerd** [comment]
@neonichu correct

**Comment by neonichu** [comment]
OK, so let's close this PR.

**Pull request closed without merging**
