### PR TITLE
[5.6] Compile plugins defined in a package when building the package (#4080)

### PR DESCRIPTION
**Pull request by abertelrud**
This is the 5.6 cherry-pick of #4080.  Please see that PR for details.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by abertelrud** [comment]
Looking at the Linux failure in Docker, not sure yet if there's some platform difference or something flaky going on.

**Comment by abertelrud** [comment]
Looks like some kind of race condition, will fix and bring back a PR to fix mainline too.

**Comment by abertelrud** [comment]
Pulled in the fix from https://github.com/apple/swift-package-manager/pull/4091 to address the nondeterministic failure.

**Comment by abertelrud** [comment]
@swift-ci please test

**Pull request merged**
