### PR TITLE
Sync latest TSC changes from main

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]
Thanks!

**Comment by neonichu** [comment]
> 11:22:49 + git checkout master
> 11:22:49 error: pathspec 'master' did not match any file(s) known to git

I reached out to Mishal, since it seems like an infra issue.

**Comment by compnerd** [comment]
Ah, yes, that is fallout of the branch renaming.

**Comment by neonichu** [comment]
> /Users/buildnode/jenkins/workspace/swift-package-manager-PR-osx-smoke-test/branch-main/swiftpm/swift-tools-support-core/Sources/TSCBasic/Process.swift:354: error: -[TSCBasicTests.ProcessTests testStdin] : failed: caught error: "could not find executable for '/Users/buildnode/jenkins/workspace/swift-package-manager-PR-osx-smoke-test/branch-main/swiftpm/swift-tools-support-core/Tests/TSCBasicTests/processInputs/in-to-out'"

Looks like that's a new file I didn't add as part of the sync.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Looks like SourceKit-LSP might need an update following the TSC change.

**Comment by compnerd** [comment]
@neonichu https://github.com/apple/sourcekit-lsp/pull/325 should fix that (and is what uncovered this in the first place)

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/sourcekit-lsp/pull/325

@swift-ci please smoke test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/sourcekit-lsp#325

@swift-ci please smoke test

**Comment by neonichu** [comment]
> <EXPR>:0: error: PackageDescription4_2LoadingTests.testVersionSpecificLoading : threw error "invalidManifestFormat("<unknown>:0: error: module file \'/home/buildnode/.cache/clang/ModuleCache/1CE4HQWUXOEPN/SwiftGlibc-3BGMLFUATR4HM.pcm\' is out of date and needs to be rebuilt: signature mismatch\n<unknown>:0: note: imported by module \'SwiftOverlayShims\' in \'/home/buildnode/.cache/clang/ModuleCache/1CE4HQWUXOEPN/SwiftOverlayShims-28NZTBX7HPMYG.pcm\'\n<unknown>:0: error: missing required module \'SwiftOverlayShims\'", diagnosticFile: nil)"

Seems as if that's just some flakiness and not an issue with the PR.

**Comment by neonichu** [comment]
Please test with following PRs:
apple/sourcekit-lsp#325

@swift-ci please smoke test

**Comment by compnerd** [comment]
@neonichu - can we get this merged?  the windows enumerated value is in the version of TSC that LSP is now building against.

**Comment by benlangmuir** [comment]
Please test with following PRs:
apple/sourcekit-lsp#325

@swift-ci please smoke test

**Pull request merged**
