### PR TITLE
Rename `-enable-future-feature` to `-enable-upcoming-feature` (#6084)

### PR DESCRIPTION
**Pull request by DougGregor**
Align with the compiler flag. Fixes rdar://104718540

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci smoke test

**Comment by neonichu** [comment]
```
C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swiftpm\Sources\PackageCollectionsSigning\Certificate\CertificatePolicy.swift:108:84: error: cannot find type 'X509_STORE_CTX' in scope

    typealias BoringSSLVerifyCallback = @convention(c) (CInt, UnsafeMutablePointer<X509_STORE_CTX>?) -> CInt

                                                                                   ^~~~~~~~~~~~~~
```

Not related to this PR, but does this look familiar, @compnerd or @yim-lee?

**Comment by neonichu** [comment]
@swift-ci smoke test windows

**Comment by compnerd** [comment]
@neonichu that is a mismatch between swift-crypto and SPM.  Do you need to define `-DSWIFT_CRYPTO_V2`?

**Comment by neonichu** [comment]
My guess is that this is fallout from #6078, I don't see any Windows builds on that one

**Comment by neonichu** [comment]
Going to merge this, but we should sort this out separately, cc @compnerd

**Comment by compnerd** [comment]
@neonichu that is not fallout from #6078, that is related to the version of swift-crypto that is being checked out.  We should fix that before merging this.

**Comment by yim-lee** [comment]
> that is related to the version of swift-crypto that is being checked out

+1. But `release/5.8` should be using swift-crypto v2 already: https://github.com/apple/swift-package-manager/pull/6029

**Comment by compnerd** [comment]
@yim-lee do you have the associated change for apple/swift?  This is going to require an update to update-checkout-config.json.

**Comment by yim-lee** [comment]
@compnerd Yes: https://github.com/apple/swift/pull/62894

**Comment by neonichu** [comment]
`PackageCollectionsSigning` wasn't building on Windows at all prior to #6078, right?

**Comment by compnerd** [comment]
It checked out apple/swift-crypto@9cc89f0170308b813af05dadcd26f9a2dee47713 so that matches.

Looking at the build:
```
cmd.exe /C "cd . && T:\1\bin\swiftc.exe -output-file-map Sources\PackageCollectionsSigning\CMakeFiles\PackageCollectionsSigning.dir\Release\output-file-map.json -incremental -j 36 -emit-library -static -o lib\PackageCollectionsSigning.lib -module-name PackageCollectionsSigning -module-link-name PackageCollectionsSigning -emit-module -emit-module-path swift\PackageCollectionsSigning.swiftmodule -emit-dependencies  -O -swift-version 5 -libc MD -Xcc -FT:/4 -Xcc -D_CRT_SECURE_NO_WARNINGS -autolink-force-load -Xfrontend -validate-tbd-against-ir=none -I swift -I C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swiftpm\Sources\PackageCollectionsSigningLibc\include -I T:\3 -I C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift-corelibs-libdispatch -I C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift-corelibs-libdispatch\src -I T:\3\src -I C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift-corelibs-libdispatch\src\BlocksRuntime -I T:\4\swift -I T:\3\src\swift\swift -I T:\13\swift -I T:\6\swift -I C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift-system\Sources\CSystem\include -I T:\7\swift -I C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift-crypto\Sources\CCryptoBoringSSL\include -I T:\12\swift @CMakeFiles\PackageCollectionsSigning.rsp   && cd ."
```

Seems that we are not passing in `-DSWIFT_CRYPTO_V2`.

**Comment by yim-lee** [comment]
There is logic in `Package.swift` to define `CRYPTO_v2` based on env var `SWIFTPM_USE_SWIFT_CRYPTO_V1`. Do we need to do that manually for Windows build?

**Comment by neonichu** [comment]
> There is logic in Package.swift to define CRYPTO_v2 based on env var SWIFTPM_USE_SWIFT_CRYPTO_V1. Do we need to do that manually for Windows build?

Yep, since we're currently doing a plain CMake build there

**Pull request merged**
