### PR TITLE
Update cross compilation SDK builder to handle Swift 4.

### PR DESCRIPTION
**Pull request by gmilos**

### CODE REVIEW

**Comment by alblue** [comment]
@swift-ci please test

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by alblue** [comment]
@swift-ci please smoke test

**Pull request merged**
