### PR TITLE
[testing] Remove guard, document FIXME

### PR DESCRIPTION
**Pull request by modocache**
Replace a double-negative condition (`guard !cond else { ... }`) with an `if` condition. Add documentation on the nature of the hack that needs a "FIXME".

---

I tried removing the condition altogether, but `Utilities/bootstrap test` still passed. Are there automated tests for the swiftpm testing support, or is that something that I can help out with?

### CODE REVIEW

**Comment by modocache** [comment]
Oh, I think I'm beginning to get it--the swiftpm uses the new testing support to run its own tests. I am still perplexed that `Utilities/bootstrap test` passes on OS X, even with the following change:

```diff
diff --git a/Sources/Transmute/transmute().swift b/Sources/Transmute/transmute().swift
index 414817d..faf7ad7 100644
--- a/Sources/Transmute/transmute().swift
+++ b/Sources/Transmute/transmute().swift
@@ -22,13 +22,6 @@ public func transmute(packages: [Package]) throws -> ([Module], [Product]) {
         products += try package.products(modules, tests: testModules)

         for testModule in testModules {
-
-            guard testModule.basename != "Functional" else {
-                //FIXME HACK
-                testModule.dependencies = modules.filter{ $0.name == "Utility" }
-                continue
-            }
-
             testModule.dependencies = modules.filter{ $0.name == testModule.basename }
         }
```

I must be missing something. I'll keep poking around, but advice appreciated! :bow:

**Comment by mxcl** [comment]
It passes because Utility was built. Currently, dependencies only need to be specified in order to ensure build-order is correct. However we intend to make it so imports of modules that aren't specified as deps fail in the near future, so then it will be more important.

**Comment by mxcl** [comment]
I understand double negative guards are bad, but for me since this is a HACK I want it to be super clear it is not the normal code path, and thus I prefer `guard` here.

**Comment by mxcl** [comment]
We should add the comment though for sure. And well I'm not too fussed, this should be temporary code.

**Comment by modocache** [comment]
Awesome, thanks! Yeah, I can understand using `guard` here. Glad to have the comment in, though!

**Pull request merged**
