### PR TITLE
[Workspace] Fix indentation in test file generated for libraries

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
(cherry picked from commit 15c0035987f9fc927248e08deffa2188e42481a1)

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci test

**Comment by abertelrud** [comment]
Linux test failure seems to be an unrelated problem in CFString.c.

**Comment by aciidb0mb3r** [comment]
Going to merge this since the linux smoke test failure is unrelated and "Swift Test Linux Platform" is the actual requirement here (which builds and tests more than the smoke test job).

**Pull request merged**
