### PR TITLE
[Swift 4.0] Add host target triple for s390x

### PR DESCRIPTION
**Pull request by vivkong**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Hi, thanks for working on this! Please raise this PR to master branch and once that is merged, you can nominate this change for the swift 4 branch. Note that swift 4 branch nominations need to be approved the corresponding release manager.

**Comment by vivkong** [comment]
@aciidb0mb3r, I've created a PR (https://github.com/apple/swift-package-manager/pull/1386) for master branch.

Thanks.

**Comment by vivkong** [comment]
Now that #1386 is merged, how do I nominate this for Swift 4 branch?

**Comment by vivkong** [comment]
Now that #1386 is merged, how do I nominate this for Swift 4 branch?

**Comment by aciidb0mb3r** [comment]
Sorry for the delay. The swift-4.0-branch is not really being used for anything now, so I'll just close this PR.

**Pull request closed without merging**
