### PR TITLE
Allow v-prefixed version string in Package.swift

### PR DESCRIPTION
**Pull request by norio-nomura**
e.g.
```swift
import PackageDescription

let package = Package(
    name: "Quick",
    dependencies: [
        .Package(url: "https://github.com/norio-nomura/Nimble", "v5.0.0-alpha.3020160412a")
    ]
)
```

### CODE REVIEW

**Comment by ddunbar** [comment]
Thanks for the patch!

I am planning a batch of work on dependency resolution, I am going to hold off on taking this until then... hopefully won't be too long from now.

**Comment by abertelrud** [comment]
Is this really a change that we want?  In general, do we want to add various heuristics to these tag names, or expect them to follow certain conventions?

**Comment by ddunbar** [comment]
I'm not sure, but I was pending thinking about it until current work on dependency resolution was complete.

**Comment by norio-nomura** [comment]
On searching version of dependencies, current implementation allows "v" prefixed Git tag.
I think that allowing "v" prefix in `Package.swift` is straightforward.

**Comment by ddunbar** [comment]
I'm closing this out, we allow the "v" prefix in *tags*, but the mapping in Package.swift is purely about *versions*. For that, I think we want to stick to the semver.org standard for now.

**Pull request closed without merging**
