### PR TITLE
build: clean up some CMake usage

### PR DESCRIPTION
**Pull request by compnerd**
Prefer to use `add_compile_definitions` to `add_compile_options` to add a definition.  Since the option is applied to the directory and below, sink it into `Sources`.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by MaxDesiatov** [comment]
"macOS (self hosted)" CI will fail until https://github.com/apple/swift-package-manager/pull/7196 is merged. Review on that appreciated 🙂

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Pull request merged**
