### PR TITLE
add missing CMake setup for Basics and PackageCollections

### PR DESCRIPTION
**Pull request by tomerd**
motivation: modules are not available for bootstrap

changes: add missing CMake indexes

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Pull request merged**
