### PR TITLE
Format args to module-aliases as a list of key/value strings before passing to llbuild 

### PR DESCRIPTION
**Pull request by elsh**
Resolves rdar://91060527

### CODE REVIEW

**Review by neonichu — APPROVED** [review]

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
pending https://github.com/apple/swift-llbuild/pull/772

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test linux

**Pull request merged**
