### PR TITLE
[5.5] Avoid calling `supportedFrontendFlags` on Windows

### PR DESCRIPTION
**Pull request by neonichu**
5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3521

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
```
13:40:01 Cloning 'cmark'
13:40:01 /Users/buildnode/jenkins/workspace/swift-package-manager-PR-macos
13:40:01 Cloning into 'cmark'...
13:40:01 ssh: connect to host github.com port 22: Operation timed out
13:40:01 fatal: Could not read from remote repository.
13:40:01 
13:40:01 Please make sure you have the correct access rights
13:40:01 and the repository exists.
```

Looks like an intermittent issue.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Looks like the macOS job failed for intermittent infra reasons:

> 10:43:58 Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- git@github.com:apple/swift-continuous-integration.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
> 10:43:58 stdout: 
> 10:43:58 stderr: ssh: connect to host github.com port 22: Operation timed out
> 10:43:58 fatal: Could not read from remote repository.

**Comment by neonichu** [comment]
@swift-ci please test macOS

**Comment by tomerd** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
Looks as if the GH connection continues to be problematic:

> 12:57:02 Cloning into 'yams'...
> 12:57:02 ssh: connect to host github.com port 22: Operation timed out
> 12:57:02 fatal: Could not read from remote repository.

**Comment by neonichu** [comment]
@swift-ci please test macOS

**Comment by tomerd** [comment]
@shahmishal many (all?) of our macOS PRs are failing on accessing GirHub.com, is there a known issue?

**Comment by shahmishal** [comment]
Yes, this is known issue. However, it's resolved now.

**Comment by neonichu** [comment]
@swift-ci please test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
