### PR TITLE
Emit underlying error code when pretty-printing I/O errors

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
> /Users/buildnode/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/swiftpm/Tests/FunctionalTests/ModuleAliasingTests.swift:26: error: -[FunctionalTests.ModuleAliasingTests testModuleRenaming] : failed - XCTSkip(skippedTestContext: <XCTSkippedTestContext: 0x7f978ed0c050>, errorCode: 106)

**Comment by tomerd** [comment]
@neonichu CI issue should be addressed by https://github.com/apple/swift-package-manager/pull/4124

**Comment by tomerd** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
