### PR TITLE
do not export modules from workspace

### PR DESCRIPTION
**Pull request by tomerd**
motivation: exporting modules is noisy and can easily lead to name conflicts

changes:
* remove the exports from the worksapce module
* adjust downstream modules to explicitly imprt the modules they need

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
need https://github.com/apple/sourcekit-lsp/pull/427 first

**Review by mattt — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]
Looks like good cleanup

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Pull request merged**
