### PR TITLE
Rename Utility to SPMUtility

### PR DESCRIPTION
**Pull request by jakepetroules**
The former is very likely to conflict with targets in other packages,
preventing users from importing them in conjunction with SwiftPM.

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by hartbit** [comment]
Perhaps the linux tests need to be re-generated

**Comment by aciidb0mb3r** [comment]
@ddunbar any objections here?

**Comment by ddunbar** [comment]
I’m fine with it

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Pull request merged**
