### PR TITLE
Conditionally import FoundationXML for upcoming Foundation changes

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
Given our limited use case, I wonder if a dependency on FoundationXML (and thus libxml2) is worth it. Maybe I should just use regex instead.

**Comment by jakepetroules** [comment]
> Maybe I should just use regex instead.

NO, please don't. If we're parsing XML, let's use an actual XML parser.

**Pull request merged**
