### PR TITLE
[5.5] Do not crash on relative file URLs in a dependency

### PR DESCRIPTION
**Pull request by neonichu**
5.5 cherry-pick of #3603

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Comment by karwa** [comment]
I just happened to spot this by accident, but it doesn’t look correct - in the URL `file://../best`, the `..` is in the host position, and is not part of the path.

Personally, I don’t agree that this syntax should be supported. Relative file URLs are not a thing. Even [RFC-8089](https://datatracker.ietf.org/doc/html/rfc8089#section-2) says:

> The path component represents the absolute path to the file in the
   file system.

The reason is that, with the proper 3 slashes (`file:///../best`), the path would be `/../best`, which is an absolute path identical to `/best` on a POSIX system. Removing the leasing slash in the path doesn’t make it relative - it just breaks the URL by putting data in the wrong section.

**Comment by neonichu** [comment]
Thanks, @karwa, looks like you're right and `Foundation.URL` also behaves exactly like that:

```swift
import Foundation

let url = URL(string: "file://../best")!
print("host: \(url.host ?? "<empty>")")
print("path: \(url.path)")
```

prints 

```
host: ..
path: /best
```

Based on that, it seems appropriate to change this to checking whether there's a host component and rejecting the URL if that is the case.

**Comment by neonichu** [comment]
Amended with cherry-pick of #3625

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
> <unknown>:0: error: module file '/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/build/buildbot_linux/foundation_static-linux-x86_64/module-cache/1O5EHM9AO5UP2/SwiftShims-5INC0PO62ITL.pcm' is out of date and needs to be rebuilt: signature mismatch

**Comment by neonichu** [comment]
@swift-ci please test linux

**Comment by neonichu** [comment]
Let's see how https://github.com/apple/swift-package-manager/pull/3630 shakes out before merging this.

**Comment by neonichu** [comment]
Actually, let's get this merged. We are getting closer to the 5.5 release and this diagnostic is already a big improvement over crashing. If there's time, we can make another cherry pick of a refined diagnostic.

**Pull request merged**
