### PR TITLE
Update Code Copyright to 2020

### PR DESCRIPTION
**Pull request by federicobucchi**

### CODE REVIEW

**Comment by federicobucchi** [comment]
@swift-ci smoke test please

**Comment by CodaFi** [comment]
Hello!

The years in the license text only have to be updated on a per-file basis as those files are edited. A change like this that touched a large number of files can be somewhat cumbersome to review and integrate otherwise.

**Comment by federicobucchi** [comment]
@CodaFi Ah ok!  So the years need to be updated only if the file is changed right?

**Comment by CodaFi** [comment]
Yeah. E.g. if you add a comment to `BuildDelegate.swift`, then updating the license text would be appropriate.

**Comment by federicobucchi** [comment]
@CodaFi thank you!  I am going to do that for my other PR!

**Pull request closed without merging**
