### PR TITLE
add TOMLable protocol

### PR DESCRIPTION
**Pull request by kostiakoval**
Add `TOMLable` protocol and move functions for covering an element to TOML format to it.

### CODE REVIEW

**Comment by onevcat** [comment]
I believe TOMLConvertible might be a better name for this situation. How do you think about it? 

And I suggest you do a rebase instead of merge master into you branch, which might make the merging graph a bit messy.

**Comment by kostiakoval** [comment]
Yes `TOMLConvertible` sound better

**Comment by kostiakoval** [comment]
I've squashed the commits as you have asked @ddunbar

**Comment by ddunbar** [comment]
LGTM, thanks!

**Pull request merged**
