### PR TITLE
update use of argument parser to latest API

### PR DESCRIPTION
**Pull request by tomerd**
motivation: Address warnings

changes: use newer API for retrieving unparsed arguments

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
@natecook1000 this is an attempt to update the new `allUnrecognized` API but `testCommandPluginArgumentsNotSwallowed` which worked previously is failing with this, basically seems like the `--help` and `--version` arguments get swallowed again. any advise?

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
🤔 Although, thinking of it now, using `.allUnrecognized` to re-parse will probably ditch when it sees the help flags. You'll want to add this to the `PluginArguments` type so that it doesn't try to parse any help flags:

```swift
struct PluginArguments: ParsableCommand {
    static var configuration: CommandConfiguration {
        .init(helpNames: [])
    }
    // etc...
}
```

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Pull request merged**
