### PR TITLE
[5.9] Remove `swiftpm-xctest-helper`

### PR DESCRIPTION
**Pull request by neonichu**
A while ago, the canonical version of the helper tool was moved to Xcode itself, but in OSS toolchains and local builds, we were still using the prior version of the tool. This removes the previous tool and adjusts the code for finding the correct tool in the user's Xcode installation.

rdar://74658052
rdar://114629436

(cherry picked from commit b7116db81df9058ad1555eeab8a76be7ddc49e19)

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please test windows

**Review by tomerd — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]

**Comment by neonichu** [comment]
Hm, this doesn't look like anything to me:

```
[1119/1387][ 80%][312.902s] /opt/swift/5.8.1/usr/bin/clang++ -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -DSWIFT_ENABLE_RUNTIME_FUNCTION_COUNTERS -DSWIFT_LLVM_SUPPORT_IS_AVAILABLE -DSWIFT_THREADING_LINUX -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_ENABLE_ASSERTIONS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/SILOptimizer -I/home/build-user/swift/lib/SILOptimizer -I/home/build-user/swift/stdlib/public/SwiftShims -Iinclude -I/home/build-user/swift/include -I/home/build-user/llvm-project/llvm/include -I/home/build-user/build/buildbot_incremental/llvm-linux-x86_64/include -I/home/build-user/llvm-project/clang/include -I/home/build-user/build/buildbot_incremental/llvm-linux-x86_64/tools/clang/include -I/home/build-user/cmark/src/include -I/home/build-user/build/buildbot_incremental/cmark-linux-x86_64/src -I/home/build-user/swift-corelibs-libdispatch/src/BlocksRuntime -I/home/build-user/swift-corelibs-libdispatch -Wno-unknown-warning-option -Werror=unguarded-availability-new -fno-stack-protector -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -O3 -DNDEBUG  -fno-exceptions -fno-rtti -Werror=gnu -Werror=c++98-compat-extra-semi -UNDEBUG -target x86_64-unknown-linux-gnu -O2 -g0 -march=core2 -std=c++17 -MD -MT lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/Utils/StackNesting.cpp.o -MF lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/Utils/StackNesting.cpp.o.d -o lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/Utils/StackNesting.cpp.o -c /home/build-user/swift/lib/SILOptimizer/Utils/StackNesting.cpp
In file included from /home/build-user/swift/lib/SILOptimizer/Utils/StackNesting.cpp:13:
In file included from /home/build-user/swift/include/swift/SILOptimizer/Utils/StackNesting.h:16:
In file included from /home/build-user/swift/include/swift/SIL/SILFunction.h:21:
In file included from /home/build-user/swift/include/swift/AST/Availability.h:20:
In file included from /home/build-user/swift/include/swift/AST/Type.h:23:
In file included from /home/build-user/swift/include/swift/AST/LayoutConstraint.h:22:
/home/build-user/swift/include/swift/AST/PrintOptions.h:585:33: warning: '\c' command does not have a valid word argument [-Wdocumentation]
  /// Whether or not to print \c @attached(extension) attributes on
                              ~~^
1 warning generated.
script returned exit code 143
```

**Comment by neonichu** [comment]
macOS smoke test issue is different, but also doesn't really look related to SwiftPM: 

```
/bin/sh: line 1: 37999 Terminated: 15          /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/swift/utils/line-directive @/Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/swift-macosx-x86_64/stdlib/public/core/3416d16eda117fb7934e99416820b74602c9b803.txt -- /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/swift-macosx-x86_64/./bin/swiftc -emit-module -o /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/swift-macosx-x86_64/./lib/swift/macosx/Swift.swiftmodule/arm64-apple-macos.swiftmodule -avoid-emit-module-source-info -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -target arm64-apple-macosx10.13 -resource-dir /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/swift-macosx-x86_64/./lib/swift -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/../../../Developer/Library/Frameworks -O -D INTERNAL_CHECKS_ENABLED -D SWIFT_ENABLE_EXPERIMENTAL_CONCURRENCY -D SWIFT_ENABLE_EXPERIMENTAL_DISTRIBUTED -D SWIFT_ENABLE_RUNTIME_FUNCTION_COUNTERS -D SWIFT_ENABLE_EXPERIMENTAL_DIFFERENTIABLE_PROGRAMMING -D SWIFT_ENABLE_EXPERIMENTAL_STRING_PROCESSING -D SWIFT_ENABLE_EXPERIMENTAL_OBSERVATION -D SWIFT_RUNTIME_OS_VERSIONING -D SWIFT_STDLIB_ENABLE_UNICODE_DATA -D SWIFT_STDLIB_ENABLE_VECTOR_TYPES -D SWIFT_STDLIB_HAS_COMMANDLINE -D SWIFT_STDLIB_HAS_STDIN -D SWIFT_STDLIB_HAS_ENVIRON -Xcc -DSWIFT_STDLIB_HAS_ENVIRON -D SWIFT_THREADING_DARWIN -tools-directory /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/llvm-macosx-x86_64/./bin -module-cache-path /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/swift-macosx-x86_64/./module-cache -no-link-objc-runtime -enable-library-evolution -library-level api -Xfrontend -require-explicit-availability=ignore -Xfrontend -enforce-exclusivity=unchecked -D SWIFT_ENABLE_REFLECTION -nostdimport -parse-stdlib -module-name Swift -Xfrontend -group-info-path -Xfrontend /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/swift/stdlib/public/core/GroupInfo.json -swift-version 5 -runtime-compatibility-version none -disable-autolinking-runtime-compatibility-dynamic-replacements -Xfrontend -disable-autolinking-runtime-compatibility-concurrency -warn-swift3-objc-inference-complete -diagnostic-style swift -Xllvm -sil-inline-generics -Xllvm -sil-partial-specialization -Xfrontend -enable-experimental-concise-pound-file -enable-experimental-feature Macros -enable-experimental-feature FreestandingMacros -Xcc -DswiftCore_EXPORTS -warn-implicit-overrides -Xfrontend -enable-ossa-modules -Xfrontend -enable-lexical-lifetimes=false -Xfrontend -disable-implicit-concurrency-module-import -Xfrontend -disable-implicit-string-processing-module-import -Xfrontend -prespecialize-generic-metadata -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 9999:macOS\ 9999,\ iOS\ 9999,\ watchOS\ 9999,\ tvOS\ 9999 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.0:macOS\ 10.14.4,\ iOS\ 12.2,\ watchOS\ 5.2,\ tvOS\ 12.2 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.1:macOS\ 10.15,\ iOS\ 13.0,\ watchOS\ 6.0,\ tvOS\ 13.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.2:macOS\ 10.15.4,\ iOS\ 13.4,\ watchOS\ 6.2,\ tvOS\ 13.4 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.3:macOS\ 11.0,\ iOS\ 14.0,\ watchOS\ 7.0,\ tvOS\ 14.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.4:macOS\ 11.3,\ iOS\ 14.5,\ watchOS\ 7.4,\ tvOS\ 14.5 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.5:macOS\ 12.0,\ iOS\ 15.0,\ watchOS\ 8.0,\ tvOS\ 15.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.6:macOS\ 12.3,\ iOS\ 15.4,\ watchOS\ 8.5,\ tvOS\ 15.4 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.7:macOS\ 13.0,\ iOS\ 16.0,\ watchOS\ 9.0,\ tvOS\ 16.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.8:macOS\ 13.3,\ iOS\ 16.4,\ watchOS\ 9.4,\ tvOS\ 16.4 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.9:macOS\ 14.0,\ iOS\ 17.0,\ watchOS\ 10.0,\ tvOS\ 17.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.10:macOS\ 9999,\ iOS\ 9999,\ watchOS\ 9999,\ tvOS\ 9999 -Xfrontend -target-min-inlining-version -Xfrontend min -module-link-name swiftCore -whole-module-optimization -save-optimization-record=bitstream -color-diagnostics -parse-as-library -resource-dir /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/swift-macosx-x86_64/./lib/swift -I /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/swift-macosx-x86_64/./lib/swift/macosx -emit-module-interface-path /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/swift-macosx-x86_64/./lib/swift/macosx/Swift.swiftmodule/arm64-apple-macos.swiftinterface -emit-private-module-interface-path /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/swift-macosx-x86_64/./lib/swift/macosx/Swift.swiftmodule/arm64-apple-macos.private.swiftinterface @/Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/build/buildbot_incremental/swift-macosx-x86_64/stdlib/public/core/3416d16eda117fb7934e99416820b74602c9b803.txt
ninja: build stopped: subcommand failed.
/Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-release/5.9/swift/utils/build-script-impl: line 308: 32402 Terminated: 15          "$@"
script returned exit code 1
```

**Comment by MaxDesiatov** [comment]
Looks like CI is all green now. This is blocking a CI job on a different repository that utilizes parallel tests with 5.9 snapshots. Is this ready to be merged?

**Pull request merged**
