### PR TITLE
[Build] Pass object files via a file to Swift compiler

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
<rdar://problem/38803919> Unable to compile the code via terminal using swift test

This is required for packages with large number of dependencies which
may cause the command line invocation to surpass the arg max limit. The
previous commit was reverted because the response file is supposed to be
space separated and not new line separated. I also updated our
in-repository test that checks spaces to actually build a product.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
It still seems nice to use newline separation, since that's a little easier to read. But the shell-escaping is the important part!

**Comment by aciidb0mb3r** [comment]
Ah, I wasn't sure if new line separation is "supported". I'll add that back.

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Pull request merged**
