### PR TITLE
Gave package manager a proper name

### PR DESCRIPTION
**Pull request by pascoej**

### CODE REVIEW

**Comment by yuvadm** [comment]
allow-it

**Comment by kostiakoval** [comment]
"Swift Package Manager" is perfect name as for me

**Comment by yask123** [comment]
+1

**Comment by Nelyus** [comment]
+1

**Comment by jsmont** [comment]
+1

**Comment by brettneese** [comment]
+1

**Comment by ScottehMax** [comment]
:+1:

**Comment by a--hoang** [comment]
+1

**Comment by misingnoglic** [comment]
Big TSwift fan (and swift fan) so this gets all of my support.

**Comment by Nelyus** [comment]
The joke is kind of funny, but it will stale.

**Comment by twof** [comment]
The last instance of Taylor in the commit should be capitalized. Once that's been fixed, I'm in full support.
+1

**Comment by pascoej** [comment]
Fixed!

**Comment by mxcl** [comment]
I just got off the phone with Taylor Swift’s lawyer, sorry, she owns the copypatentymark on the word “Taylor” in the contexts of food, bar-fights and software.

**Comment by tjhorner** [comment]
>I just got off the phone with Taylor Swift’s lawyer, sorry, she owns the copypatentymark on the word “Taylor” in the contexts of food, bar-fights and software.
Darn.

**Pull request closed without merging**
