### PR TITLE
[Xcodeproj] Remove serializeArray method, use joined(separator:) instead

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Fixes https://bugs.swift.org/browse/SR-1441

### CODE REVIEW

**Comment by czechboy0** [comment]
Awesome, just hit this today too!

**Comment by dsperling** [comment]
Confirmed that SR-1441 is fixed.  Thanks.

Another problem in Kitura has been uncovered with this swift-build update with the use of PRODUCT_MODULE_NAME = '$(TARGET_NAME:c99extidentifier)';"

This causes a swift compile error with "import KituraTemplateEngine" as the xcodeproj creates the module name as "Kitura_TemplateEngine".  This is a separate issue so I will open a new ticket once it can be determined if the issue is in Package Manager or Kitura-TemplateEngine-0.9.0.

**Comment by aciidb0mb3r** [comment]
@ddunbar I don't think this one requires CI either but upto you.
@dsperling I ran into that issue today with your sample package, its most certainly swiftpm's bug, I didn't have enough time to fix it today but will do soon! please file a bug if you have time.

**Comment by dsperling** [comment]
Created this ticket for the "Kitura_TemplateEngine" issue.
https://bugs.swift.org/browse/SR-1444

**Comment by ddunbar** [comment]
LGTM, but I think we should have test coverage of the basic scenario in play here.

**Comment by aciidb0mb3r** [comment]
is it fine if tests for few of the fixes recently come together in a separate PR ?

**Comment by ddunbar** [comment]
Yeah, that is fine with me. For things like this, I often try and ensure one simple test which covers "basic sanity" and then extend with specific tests for regressions as they appear.

**Pull request merged**
