### PR TITLE
Allow build & run to reference unreachable targets

### PR DESCRIPTION
**Pull request by hartbit**

### CODE REVIEW

**Comment by hartbit** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@rballard Please approve this for Swift 4 branch.

**Comment by hartbit** [comment]
The build failure seems completely unrelated

**Comment by aciidb0mb3r** [comment]
@hartbit Can you email swift-dev about this failure?

**Comment by rballard** [comment]
Approved for the Swift-4.0 branch (once CI passes).

**Comment by harlanhaskins** [comment]
@swift-ci please clean smoke test

**Pull request merged**
