### PR TITLE
[NFC] Rename `Destination` type to `SwiftSDK`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
### Motivation:

With the cross-compilation proposal accepted in principle, I think it's time to move over to the new nomenclature altogether.

### Modifications:

Renamed `Destination` type to `SwiftSDK`. Also renamed mentions of "destination" in declarations to "Swift SDK" and cleaned up usage of `triple` where it was actually referring to the target triple.

### Result:

Naming is consistent across the codebase. This is an NFC.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by rauhul** [comment]
I had made the same changes locally just for clarity when reading. Very happy to see this :)

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
