### PR TITLE
[Explicit Module Builds] De-duplicate dependency build jobs before adding them to LLBuild manifest

### PR DESCRIPTION
**Pull request by artemcm**
This avoids adding duplicate entries to the LLBuild manifest in explicit module builds by de-duplicating explicit dependency pre-build jobs based on their unique output filename.

### CODE REVIEW

**Comment by artemcm** [comment]
`testExplicitSwiftPackageBuild` is passing with this change, but it is currently skipped due to rdar://82053045.
I'm looking into what it'll take to re-enable it.

**Comment by tomerd** [comment]
sry @artemcm I just renamed this file, please rebase

**Comment by artemcm** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Comment by abertelrud** [comment]
Thanks, @artemcm!  This should make https://github.com/apple/swift-package-manager/pull/3587 pass, I think.  I will try a cross-PR build.

**Comment by abertelrud** [comment]
Verified that https://github.com/apple/swift-package-manager/pull/3587 now passes with a cross-PR test with this one.  Thanks @artemcm!

**Comment by abertelrud** [comment]
Merging.

**Pull request merged**
