### PR TITLE
[5.7] set `relatedDependenciesBranch` to `release/5.7`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This allows packages depending on SwiftPM to correctly resolve dependencies.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-driver/pull/1104
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
https://github.com/apple/swift-driver/pull/1104
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
Would self-hosted failures disappear after driver PR is merged?

**Comment by neonichu** [comment]
> Would self-hosted failures disappear after driver PR is merged?

Yah, but I think we want to avoid having a broken SwiftPM 5.7 branch for as long as it takes to re-run the tests.

**Pull request merged**
