### PR TITLE
Copy swiftdoc with swiftmodule [SR-5802]

### PR DESCRIPTION
**Pull request by therealbnut**
[SR-5802](https://bugs.swift.org/browse/SR-5802)

> SwiftPM should ship PackageDescription's swiftdoc in the toolchain

### CODE REVIEW

**Comment by therealbnut** [comment]
@aciidb0mb3r I wasn't entirely sure exactly what was intended, I may need more details to verify this on the ticket if this wasn't correct :)

**Comment by aciidb0mb3r** [comment]
Thanks for working on this! The bug here refers to installing PackageDescription's swiftdoc files in the toolchain along with the swiftmodule files. Look at these lines in the bootstrap script:

```
               # Install module.
                cmd = ["install", "-m", "0644",
                       runtime_module_path, install_path]
                note("installing %s: %s" % (
                    os.path.basename(runtime_module_path), ' '.join(cmd)))

```

We are only installing swiftmodule and need to expand this logic to also install the swiftdoc file.

**Comment by therealbnut** [comment]
Thanks for the update :)

**Comment by therealbnut** [comment]
@aciidb0mb3r I've updated the PR.

I'm not 100% sure how to verify the changes, it does install the swiftdoc to `/usr/local/lib/swift/pm/4` with 0644, was there anything else?

**Comment by aciidb0mb3r** [comment]
Thanks, this looks good!

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Pull request merged**
