### PR TITLE
Print warning if a module not present for a product, error out if zer…

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
…o modules in a product

Fixes https://bugs.swift.org/browse/SR-1064

### CODE REVIEW

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
Needs a regression test at least.

**Comment by aciidb0mb3r** [comment]
> Needs a regression test at least.
Will add

**Comment by aciidb0mb3r** [comment]
@mxcl Rebased and added tests

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by aciidb0mb3r** [comment]
OSX failed for some reason, @mxcl CI again?

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@mxcl @ddunbar tests passed, review please

**Comment by ddunbar** [comment]
Seems reasonable to me but @mxcl's area...

**Comment by aciidb0mb3r** [comment]
@mxcl please review before this gets conflicted :joy:

**Pull request merged**
