### PR TITLE
Unicode‐Heavy Test Fixture

### PR DESCRIPTION
**Pull request by SDGGiesbrecht**
This idea originated on the forums [here](https://forums.swift.org/t/are-there-open-source-swiftpm-integration-tests-that-xcode-runs-too/29328).

It puts all sorts of weird Unicode to use. The package manager handles all of it just fine at the moment. (On macOS at least; I guess CI will tell us how well Linux does.)

But it currently trips Xcode 11(.0) in at least three ways:

1. The package name causes Xcode to crash when tests complete. (FB7328781)
2. The dependency URL prevents Xcode from loading the manifest. (Paths don’t trigger this.)
3. The nested package causes Xcode to crash while loading dependencies.

Likely Xcode isn’t the only client that can benefit from having this this fixture available to test itself against.

***

P.S. SwiftPM’s test manifests seem to out of date, as `--generate-linuxmain` tried to add other new tests. This PR only adds the test it creates to the test manifest, so as to avoid merge conflicts.

### CODE REVIEW

**Comment by jakepetroules** [comment]
This is awesome! You could also throw in some [long sequences](http://www.unicode.org/review/pri215/pri215-background.html) of [regional indicator symbols](https://en.wikipedia.org/wiki/Regional_Indicator_Symbol) in there for good measure :)

**Comment by SDGGiesbrecht** [comment]
@jakepetroules, is that a serious request or just humour? A single regional indicator is already in there (the UN flag) as the representative for multi‐scalar emoji, but I can string a few more on if you really want. (Such sequences bode trouble for slicing and wrapping, but are nothing special for equivalence, encoding or escaping, which are what matter to SwiftPM.)

P.S. The PRI (Public Review Issue) you linked was for Unicode 6.2.0 and it was never accepted in that form. (See the modifications log at the bottom of [what was accepted](https://www.unicode.org/reports/tr29/tr29-21.html).) Instead, no breaks are allowed between any two halves, and where line wrapping is desired in between flags, they can be grouped [half][half][ZWSP][half][half]. We are now at Unicode 12.1.0.

**Comment by jakepetroules** [comment]
Serious request, and thanks for the corrected link - I was trying to find one which succinctly described the original core issue, i.e. "_Unfortunately, in a sequence of more than two of these characters, it is unclear where the segmentation boundaries lie_".

"🇺🇸🇺🇸🇺🇸🇺🇸🇺🇸🇺🇸🇺🇸🇺🇸🇺🇸🇺🇸", for example, would have been interpreted as a single grapheme cluster (not 10) prior to changes to the [grapheme break rules](https://unicode.org/reports/tr29/#GB12) in Unicode 9 so it's another of those weird edge cases which could conceivably trip something up.

SwiftPM may use Swift.String but that's not guaranteed for clients like Xcode so it's a useful addition for something meant as an integration test, IMO.

**Comment by SDGGiesbrecht** [comment]
I added a consecutive regional indicator. (The smiley face was why I wasn’t sure if the statement was serious.)

**Comment by aciidb0mb3r** [comment]
Thanks a lot, @SDGGiesbrecht!

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by SDGGiesbrecht** [comment]
I don’t understand the CI result on Linux. I cannot even find the stuff I added in the output (I searched for the test name, test case name, directory name, etc. with ⌘F). Do you think the presence of weird file names is confounding CMake and Ninja, or does none of it have anything to do with this PR?

**Comment by aciidb0mb3r** [comment]
Seems like this failed in dispatch (which is built before swiftpm).

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by SDGGiesbrecht** [comment]
> Tests/FunctionalTests/MiscellaneousTests.swift:442: error: MiscellaneousTestCase.testUnicode : failed - Error Domain=NSCocoaErrorDomain Code=260 "The file doesn’t exist."

Should we `#if !os(Linux)` with a `TODO` for now so we can merge? I don’t have my Linux machine with me right now to debug it, but I can look into it more later when I do.

**Comment by aciidb0mb3r** [comment]
That's fine with me!

**Comment by SDGGiesbrecht** [comment]
Done.

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Pull request merged**
