### PR TITLE
[5.1] Compile manifests instead of interpreting them

### PR DESCRIPTION
**Pull request by hartbit**
<rdar://problem/58028627>

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by hartbit** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci clean smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci clean smoke test Linux

**Comment by aciidb0mb3r** [comment]
https://github.com/apple/swift-package-manager/pull/2577

**Pull request closed without merging**
