### PR TITLE
Tests: cover testing multiple async executable targets

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Test [apple/swift#69113: \[Concurrency\] Hide async_Main from other object files](https://github.com/apple/swift/pull/69113)

Merge after the above fix will be merged 

### Motivation:

To verify that multiple executable targets with async entrypoints can be linked within a single test executable 

Resolves rdar://114231968

### Modifications:

Added a new test case

### CODE REVIEW

**Comment by neonichu** [comment]
Thanks!

**Comment by kateinoigakukun** [comment]
@swift-ci Please smoke test

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by neonichu** [comment]
I guess we need some way to skip these tests in the self-hosted environment, because they won't have a new enough compiler any time soon.

**Comment by kateinoigakukun** [comment]
@neonichu I don't have a good and stable idea to detect if the given swift-frontend has the fix or not 🤔  I think we can wait to merge this until the next nightly toolchain will be shipped.

**Comment by kateinoigakukun** [comment]
Ah, it looks like macOS self-hosted CI uses Xcode toolchain, so just waiting the next nightly doesn't work.

**Comment by MaxDesiatov** [comment]
Yeah, "next" here means next version of Xcode, for which we can't provide a schedule.

**Comment by MaxDesiatov** [comment]
Maybe tests could be gated on the version of Swift, 5.10 I guess?

**Comment by kateinoigakukun** [comment]
The async version test is split out from the sync version and guarded by `#if compiler(<5.10)`. I think this should work without waiting for the next Xcode update in the CI and just need to wait for the next Linux nightly toolchain.

**Comment by neonichu** [comment]
@swift-ci test

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Comment by neonichu** [comment]
I believe Linux self-hosted uses a nightly toolchain, so we have to wait until that contains the compiler changes.

**Pull request merged**
