### PR TITLE
[5.5] Android: add cross-compilation configuration file flag

### PR DESCRIPTION
**Pull request by buttaface**
This is a cherry-pick of 38df7c3.
```
In addition to '--cross-compile-hosts', add a new bootstrap flag, '--cross-compile-config', that will
pass in a JSON file with the destination cross-compilation flags.
```

### CODE REVIEW

**Review by abertelrud — APPROVED** [review]

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by buttaface** [comment]
Passed CI, ready for merge.

**Comment by buttaface** [comment]
Thanks, this will allow me to remove [another patch from my upcoming Swift 5.5 toolchain for Android](https://github.com/buttaface/termux-packages/tree/swift55/packages/swift).

**Comment by tomerd** [comment]
@buttaface thank you for all your contributions!

**Pull request merged**
