### PR TITLE
[5.10] Update related dependencies branch to release/5.10

### PR DESCRIPTION
**Pull request by ahoppen**
We cut `release/5.10`.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by neonichu** [comment]
Thanks!

**Comment by neonichu** [comment]
> error: swift-llbuild is required using two different revision-based requirements (release/5.10 and main), which is not supported

We need to update swift-driver simultaneously, I guess.

**Comment by ahoppen** [comment]
https://github.com/apple/swift-driver/pull/1440

@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by neonichu — APPROVED** [review]

**Pull request merged**
