### PR TITLE
adjust tests to changes from TSC

### PR DESCRIPTION
**Pull request by tomerd**
motivation: TSC had some test API changes that break SwiftPM tests

changes: adjust test code to nwe TSC Test aPI

### CODE REVIEW

**Comment by tomerd** [comment]
@abertelrud ptal

**Comment by tomerd** [comment]
@swift-ci please test

**Review by abertelrud — APPROVED** [review]
Looks good to me

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
https://ci.swift.org iis busted. since these are test only changes the standalone tests suffice.

**Pull request merged**
