### PR TITLE
Refactor Build/describe() with Buildable protocol

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by mxcl** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
Any reason why it is setup to run All the tests and not only swiftpm tests?

**Comment by aciidb0mb3r** [comment]
@mxcl can you run CI again on this, it should pass now

**Comment by mxcl** [comment]
@swift-ci please test

**Comment by mxcl** [comment]
@shahmishal is there a way to get @Swift-CI to only run SwiftPM tests? Sorry if you documented this, I cannot find the docs.

**Comment by modocache** [comment]
This would save a massive amount of time for swift-corelibs-xctest as well.

**Comment by shahmishal** [comment]
@mxcl Yes, I can update the job to use specific preset for swiftPM. Please email me the preset (build-script) Jenkins job should use for testing PR for swiftPM on OS X and Linux. Thanks! 

@modocache We could also do the same thing for swift-corelibs-xctest. Thanks!

**Comment by modocache** [comment]
@shahmishal The preset I added in #1533 is perfect for XCTest--it skips the CMark and Swift tests, so it's pretty fast. Thanks anyway, though!

**Pull request merged**
