### PR TITLE
Allow Static Libraries

### PR DESCRIPTION
**Pull request by mxcl**
This allows Static library products to be created again.

### CODE REVIEW

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by aciidb0mb3r** [comment]
😍😍👏👏👏👏

**Comment by mxcl** [comment]
FYI I am also testing an additional patch to this that adds a static archive tool to llbuild.

**Comment by mxcl** [comment]
I'll probably merge this before that and make that a separate PR though.

**Comment by aciidb0mb3r** [comment]
These test are failing on OSX 
```
FunctionalTestSuite.InvalidLayoutsTestCase/testInvalidLayout4
FunctionalTestSuite.ValidLayoutsTestCase/testMultipleModulesLibraries
```

**Comment by aciidb0mb3r** [comment]
@mxcl Is this a valid layout?
```
├── Foo
│   └── Bar
│       └── Foo.swift
└── Package.swift
```

**Comment by mxcl** [comment]
My tests pass.

> Is this a valid layout?

No. We have a test that ensures it is *not*.

**Comment by aciidb0mb3r** [comment]
`testInvalidLayout4` is
```
├── Foo
│   └── Bar
│       └── Foo.swift
├── Package.swift
└── main.swift
```

```swift
fixture(name: "InvalidLayouts/Generic4") { prefix in
        XCTAssertBuildFails(prefix)
        try POSIX.unlink("\(prefix)/main.swift")
        XCTAssertBuilds(prefix)
}
```
It removes `main.swift` and tries to build that which is again invalid package

**Comment by mxcl** [comment]
K well, we should have another test for the other.

**Comment by mxcl** [comment]
K, well in that case it is a valid layout. Though honestly I'd prefer it would be not, I have a variety of modifications to our rules I would like to propose when things are quieter.

**Comment by aciidb0mb3r** [comment]
how about for now I make it a "valid" layout post removal of `main.swift`?

**Pull request merged**
