### PR TITLE
Build resources for ObjC targets

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@benlangmuir Do you know what's going on with SourceKit-LSP:

```
15:54:01 Test Case 'LocalSwiftTests.testEditing' passed (0.129 seconds)
15:54:01 Test Case 'LocalSwiftTests.testEditorPlaceholderParsing' started at 2019-10-28 22:54:01.935
15:54:01 Test Case 'LocalSwiftTests.testEditorPlaceholderParsing' passed (0.001 seconds)
15:54:01 2019-10-28 22:54:01.935 SourceKitLSPPackageTests.xctest[16767:da7fc700] no workspace found
15:54:01 Test Case 'LocalSwiftTests.testHover' started at 2019-10-28 22:54:01.935
15:54:01 2019-10-28 22:54:01.936 SourceKitLSPPackageTests.xctest[16767:da7fc700] no workspace found
15:54:02 E[22:54:02.167] Transport error: Input/output error
15:54:02 Exited with signal code 11
15:54:02 E[22:54:02.169] Transport error: Input/output error
15:54:02 E[22:54:02.171] Transport error: Input/output error
1
```

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test Linux

**Comment by benlangmuir** [comment]
I'm currently investigating the crash.  Sorry for the spurious failure.

**Pull request merged**
