### PR TITLE
Update generated gitignore

### PR DESCRIPTION
**Pull request by 0xTim**
This PR updates the generated `.gitignore` file to add relative derived data and Xcode 11's `.swiftpm` directory

### CODE REVIEW

**Comment by neonichu** [comment]
I don't think we should be ignoring `.swiftpm` wholesale, for example, manually created shared schemes will be in there which people will most likely check in. I think it could be fine to ignore `.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata` explicitly which should have a similar outcome. @abertelrud what do you think?

As for ignoring `DerivedData`, I'm ambivalent. On the one hand, it won't do any harm, on the other hand, there's the ability to chose the name as well right?

**Comment by 0xTim** [comment]
@neonichu yeah you can change the name but it defaults to `DerivedData/`. Happy to change/remove it though, just something I noticed when creating lots of new SwiftPM projects.

Will wait to hear the best solution for `.swiftpm`

**Comment by abertelrud** [comment]
I agree that it's a good idea to ignore `DerivedData`, since that's the default.

For the workspace, I think you make a good point about shared scheme, and so I agree that ignoring `contents.xcworkspacedata` seems like the right thing to do there.

**Comment by 0xTim** [comment]
Ok, thanks @neonichu and @abertelrud - I've updated the PR to only ignore contents.xcworkspacedata

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by 0xTim** [comment]
As an aside @neonichu @abertelrud, it turns out that XPM _really_ doesn't like having a relative derived data directory - see FB7601309

**Pull request merged**
