### PR TITLE
[5.6] Fix SIGINT handling during `swift run` (Cherry-pick of #4224, #4235, #4250)

### PR DESCRIPTION
**Pull request by kkk669**
This is a cherry-pick PR of #4224, #4235, and #4250 for Swift 5.6.

(CC: @tomerd)

rdar://90574791

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by tomerd — APPROVED** [review]

**Comment by kkk669** [comment]
I also cherry-picked #4235 that contains fixing of Windows build.

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by tomerd — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Comment by tomerd** [comment]
test added in main: https://github.com/apple/swift-package-manager/pull/4250

**Comment by kkk669** [comment]
@tomerd Thank you for adding the test case. I cherry-picked #4250.

**Comment by tomerd** [comment]
@swift-ci smoke test

**Pull request merged**
