### PR TITLE
[Pubgrub] Refactor intersect(withRequirement:)

### PR DESCRIPTION
**Pull request by kiliankoe**
It's a lot easier to understand now. I will add more tests for this in a future PR.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
great!

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@kiliankoe this is in conflict

**Comment by kiliankoe** [comment]
rebased on current master

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Pull request merged**
