### PR TITLE
Add SimpleProgressBar for dumb terminals

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
IDK, don't think it matters a lot. We display the output of test failures anyway.

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
One place it tends to matter is when running things on CI, where it can be nice to see the names of tests scroll by, and there is little value in compressing onto a single line.

**Comment by aciidb0mb3r** [comment]
Hm, how about SingleLine when its a dumb TERM and SimpleProgress when its a non-tty?

**Comment by ddunbar** [comment]
@aciidb0mb3r yeah exactly

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Pull request merged**
