### PR TITLE
Test sanitizers with build plans.

### PR DESCRIPTION
**Pull request by Lukasa**
The current tests for sanitizers in SwiftPM are essentially "live": they
build a package that will do something to trigger a sanitizer, and then
run it and confirm it fails. This is a pretty fragile way to test, and
it exposes SwiftPM to a number of possible test failures that don't
have anything to do with the core mission (exposing the sanitizer).

This patch replaces those tests with build plan tests that validate that
SwiftPM correctly invokes swiftc and clang. These tests are acceptable
because for now SwiftPM doesn't have any smarts with the sanitizers: it
just passes them all through to swiftc and clang.

This patch also deletes the current live tests, as they are no longer
necessary.

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-ci please smoke test

**Comment by Lukasa** [comment]
@swift-ci please smoke test

**Comment by Lukasa** [comment]
@swift-ci please smoke test

**Comment by Lukasa** [comment]
@swift-ci please smoke test

**Comment by Lukasa** [comment]
@swift-ci please smoke test

**Comment by Lukasa** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
Thanks for reworking these tests, Cory!  In general, this (checking that SwiftPM is passing along the right sanitizer flag to the compiler) is definitely the right approach.

One thing I'm slightly worried about is that the test seems to capture a lot of the current flags being passed to the compiler and linker, and I'm wondering if this test will frequently have to end up being modified when the generated command lines evolve over time.  On one hand, because the tests specify a specific version of a manifest (v4 in this case), the semantics should stay the same even if there are changes to newer versions... but on the other hand, those semantics might in future versions be achieved through other combinations of flags.

So I guess I'm wondering if there's a way to be less specific about the various flags that are getting passed (e.g. the `-fobjc-arc` on macOS) that would still test that the right sanitizer flags are being passed?

**Comment by Lukasa** [comment]
Yeah, we can use a Swift contains operation instead if you'd like. Would that be preferable?

**Comment by abertelrud** [comment]
I think so, since that seems a bit more robust in the face of future changes.  Otherwise I suspect that there will need to be repeated fixes to this test over time as unrelated things change.  Thanks!

**Comment by Lukasa** [comment]
@swift-ci please smoke test

**Pull request merged**
