### PR TITLE
Use map instead of flatMap

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@aciidb0mb3r please take a look.

**Comment by aciidb0mb3r** [comment]
Looks good, thanks!

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by moiseev** [comment]
... it does not make sense... I need to think =) And build locally, obviously.

**Comment by ikesyo** [comment]
The initializer is failable so `flatMap` should be  appropriate.

**Comment by moiseev** [comment]
@ikesyo Yeah, I figured. Thanks! I was confused by [this build error](https://ci.swift.org/job/swift-PR-compiler-performance-smoke-test-macOS/67/consoleFull#12040643823122a513-f36a-4c87-8ed7-cbc36a1ec144).

**Pull request closed without merging**
