### PR TITLE
bootstrap: update for foundation layout

### PR DESCRIPTION
**Pull request by compnerd**
Update the bootstrap script for the new Foundation build layout.

### CODE REVIEW

**Comment by gottesmm** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift#20032
apple/swift-package-manager#1833
apple/swift-llvm#121
apple/swift-corelibs-xctest#230

@swift-ci please smoke test

**Comment by gottesmm** [comment]
... *sigh* ...

**Comment by gottesmm** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833
apple/swift-llvm#121
apple/swift-corelibs-xctest#230
apple/swift#20032

@swift-ci please test

**Comment by gottesmm** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-llvm#121
apple/swift-corelibs-xctest#230
apple/swift#20032

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift#20032
apple/swift-corelibs-xctest#230

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833
apple/swift-llvm#121
apple/swift-corelibs-xctest#230

@swift-ci please smoke test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift#20032
apple/swift-corelibs-xctest#230

@swift-ci please smoke test

**Pull request merged**
