### PR TITLE
[Basic] Add wait(until:) to Condition wrapper

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
OSX CI stuck on llbuild, @neonichu do you know if this happened before?

@swift-ci please test OS X

**Comment by aciidb0mb3r** [comment]
@swift-ci please test OS X

**Comment by neonichu** [comment]
The test hang was most likely apple/swift-llbuild#53

**Pull request merged**
