### PR TITLE
Migrate entirely to new color-diagnostics flag

### PR DESCRIPTION
**Pull request by keith**
This is a follow up because of the discussion here https://github.com/apple/swift-package-manager/pull/2099

### CODE REVIEW

**Comment by keith** [comment]
@aciidb0mb3r should we merge this soon?

**Comment by keith** [comment]
@aciidb0mb3r any chance this can make it for 5.1?

**Comment by aciidb0mb3r** [comment]
The driver change didn't land in the Swift 5.1 compiler. Unfortunately, we'll have to wait for the next complier release.

**Comment by keith** [comment]
Ah sorry, I've lost track since it's been so long

**Comment by gonsolo** [comment]
> The driver change didn't land in the Swift 5.1 compiler. Unfortunately, we'll have to wait for the next complier release.

From April 2018:
"I will make sure that this isn't forgotten but I am fine with landing this change behind an env variable for now."

Can we make sure it is not forgotten for 5.2?

**Comment by gonsolo** [comment]
>
>
> @gonsolo <https://github.com/gonsolo> I haven’t forgotten about this. I
> am waiting for the compiler change to be in an Xcode build. AFAIK the
> compiler change is only on master branch right now.
>

Ok, thanks.

g

**Comment by keith** [comment]
@aciidb0mb3r can we merge this now

**Comment by aciidb0mb3r** [comment]
Let's try!

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test self hosted

**Comment by aciidb0mb3r** [comment]
I suppose the CI won't really catch if this flag is in the latest Xcode because it's not TTY. Let me check locally.

**Comment by aciidb0mb3r** [comment]
Doesn't look like it's present in Xcode 11.3 GM (11C29) :/

```
<unknown>:0: error: unknown argument: '-color-diagnostics'
```

**Comment by keith** [comment]
Ah yes, so I guess this made the compiler 5.2 branch. Sorry this has been so long and I've gotten confused about where the change is. So I guess this would be nice to have in the 5.2 branch of SwiftPM at some point?

**Comment by aciidb0mb3r** [comment]
yep

**Comment by keith** [comment]
@aciidb0mb3r now that the 11.4 beta is out are we good to merge this into 5.2?

**Comment by aciidb0mb3r** [comment]
Yup! Can you cherry-pick?

**Comment by keith** [comment]
https://github.com/apple/swift-package-manager/pull/2549

**Comment by gonsolo** [comment]
This still doesn't seem to work with Swift 5.2 on macOS:
make - Merging module
make - Nothing
vim and :make - Merging module again

**Comment by keith** [comment]
@aciidb0mb3r does this one need to be merged or does it make it back some other way?

**Comment by keith** [comment]
@aciidb0mb3r it looks like this one does actually need to be merged to master as well? Are we good to do that now?

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@keith we should also put this patch in 5.3 since the previous cherry-pick was for 5.2 and we're no longer automergering to 5.3

**Comment by keith** [comment]
Here's the cherry pick for 5.3 https://github.com/apple/swift-package-manager/pull/2771

**Pull request merged**
