### PR TITLE
Support for specifying a branch for a dependency.

### PR DESCRIPTION
**Pull request by ulrikdamm**
In a Package dependency, you can now specify an optional branch, and this branch will get cloned when getting dependencies.
It currently defaults to "master" if not specified (and will use 'git clone -b master').
Currently the branch will not influence the package name, but the name and tag should be enough that it doesn't conflict.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
I don't know if this is desirable....have you looked at the ongoing lockfile proposal which will solves problems like this?

**Comment by kostiakoval** [comment]
This will be solved with Lock file. Please have a look at Lock proposal draft. 
https://github.com/mxcl/swift-evolution/blob/lockfiles/proposals/NNNN-swiftpm-dependency-lockfiles.md

**Comment by ulrikdamm** [comment]
Most package managers seems to have a feature like this. I needed it myself to use the Swift 3.0 branch of a library.
It's not immediately clear to me how the current lockfile proposal solves this issue, but if it does, then I guess there's no need for this.

**Comment by aciidb0mb3r** [comment]
Under current proposal once you add a dependency, you can go into that package and git checkout the branch you want to use and "lock" it in order to propagate the changed branch to other users of your package.

**Pull request closed without merging**
