### PR TITLE
adding support for custom platforms

### PR DESCRIPTION
**Pull request by bflanagan-apple**
Allow Package.swift specification of minimum SDK version for unknown platforms by using new "custom" platform with platform name string, and version string.

### Motivation:

Currently, platforms in SwiftPM have to always be hard-coded and we should get to a more flexible model here. As a first step, this PR adds the ability to declare custom platform deployment versions in the package manifest, which won’t be handled by SwiftPM’s own build system, but will be part of the package model, so that they can be utilized when using libSwiftPM together with another build system.

### Modifications:

Added a new API, custom() to each of Platform and SupportedPlatform.  Added fall back while reading manifest to create a custom platform where the platform is not recognized.  Tests were added for Package Loading and Building.

### Result:

From now on, anyone in the community who wishes to target a new platform for development without having to wait to add to the OSS, can do so in development by simply adding a '.custom("<new platform>", "new platform version>")' to their Package.swift, and then adding the appropriate changes in their builder to recognize their new platform.  They can then add the new platform and supported platform to the OSS for "official" support if the community needs/requires it.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by abertelrud** [comment]
Looks good; thanks for this change!  One more place that would need a change in order to be complete would be in ManifestSourceGeneration.swift, where the line:
```
    self.init(enum: platform.platformName, string: platform.version)
```
would change to something like:
```
    self.init(enum: "custom", subnodes: [ .init(string: platform.platformName), .init(key: "versionString", string: platform.version) ]
```
to emit the right source.

**Comment by bflanagan-apple** [comment]
@swift-ci please smoke test

**Comment by bflanagan-apple** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Comment by bflanagan-apple** [comment]
@swift-ci please smoke test

**Review by jakepetroules — APPROVED** [review]

**Pull request merged**
