### PR TITLE
Bring back `swift-bootstrap` command

### PR DESCRIPTION
**Pull request by neonichu**
Bring back the previously reverted `swift-bootstrap` command. It now supports XCBuild because that is required if the second stage of bootstrapping is supposed to be build for multiple architectures on macOS.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please test package compatibility

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
> common.ExecuteCommandFailure: ExecuteCommandFailure(command="git clone https://github.com/mac-cain13/R.swift.git /Users/ec2-user/jenkins/workspace/swift-package-manager-source-compat-suite-PR-macos/swift-source-compat-suite/project_cache/R.swift", returncode=128)

**Comment by neonichu** [comment]
@swift-ci please test package compatibility

**Pull request merged**
