### PR TITLE
Rename "extension" to "plugin" in the implementation of SE-0303 to align with the proposal

### PR DESCRIPTION
**Pull request by abertelrud**
Rename "extension" to "plugin" to align with the proposal SE-0303.

This is a fairly large diff but is just the renaming from "extension" to "plugin" and the related variables and comments.  The name of the runtime library changes too, and some of the methods use different verbs that work better with the noun "plugin".  In some cases there are temporary typealiases to ease transition for clients.

No change in functionality.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
😅

**Comment by abertelrud** [comment]
:)  This was a big one.  Once the tests pass and this is merged, I'll move https://github.com/apple/swift-package-manager/pull/3312 out of Draft since it will be much easier to review.  That one and the upcoming PRs all stack on top of this one.

**Pull request merged**
