### PR TITLE
Mark all current vNext functionality as 5.3

### PR DESCRIPTION
**Pull request by hartbit**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@hartbit I think we'll need to update some text fixtures.

**Comment by hartbit** [comment]
I had indeed missed some. Thanks for the catch!

**Comment by hartbit** [comment]
swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
Can you also cherry-pick to 5.3 branch and set development = false in Versioning.swift?

**Comment by hartbit** [comment]
@swift-ci smoke test

**Comment by hartbit** [comment]
@aciidb0mb3r `testTargetBasedDependency` is now failing because of https://github.com/apple/swift-package-manager/blob/master/Sources/PackageLoading/ToolsVersionLoader.swift#L110

Did you have any ideas how you wanted to fix that?

**Comment by aciidb0mb3r** [comment]
I think we can fix that test by laying down Package.swift with just the tools version in test's in-memory file system

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test self hosted

**Pull request merged**
