### PR TITLE
add support for registry availability endpoint

### PR DESCRIPTION
**Pull request by tomerd**
motivation: check registry availability before assuming it is ready to use

changes:
* add API in registry client to support  new availability endpoint
* add tests
* remove dead code

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by neonichu** [comment]
This isn't actually doing yet what the PR says, right? As far as I can see `checkAvailability()` is only called from tests.

**Comment by tomerd** [comment]
@neonichu correct, it is phase 1 of this change

**Comment by tomerd** [comment]
cc @palleas

**Comment by Palleas** [comment]
Is that something we want to include in the registry spec as well as part of a separate pull request?

**Comment by tomerd** [comment]
@Palleas it is an optional endpoint, so maybe?

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Pull request merged**
