### PR TITLE
Simplified Package Loading API

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This is a re‐working of #2166, but branched from the tip of master.

One static function each has been added to Manifest, Package and
PackageGraph that allows them to be loaded by supplying only the
location of swift and the location of the package to load.  This
necessitated some minor refactoring of Workspace internals, so that code
could be shared instead of duplicated.  The package-info example has
been updated to use the simpler APIs.  For package clients, this amounts
to an ergonomic reduction of about 45 lines down to 1, whenever no
customization is needed.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@SDGGiesbrecht I fixed the CI failure and made a couple of minor changes:

- Labels in the APIs are explicit and closer to API guidelines (e.g., "packagePath" instead of "from" since the type doesn't make it clear that it's expecting a package path).
- Removed default value for DiagnosticEngine. This should be passed in by the client so they get the warnings, errors and notes.

**Comment by SDGGiesbrecht** [comment]
The API tweaks look good. 👍

The example client needs to be updated to match though. 😉

Thank you for figuring out CI.

**Comment by aciidb0mb3r** [comment]
> The example client needs to be updated to match though. 😉

Aah, thanks! I'll do that

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by SDGGiesbrecht** [comment]
The checks passed, but it’s still sitting here. Are you waiting for something else, @aciidb0mb3r?

**Comment by aciidb0mb3r** [comment]
Nope, landing it now

**Comment by SDGGiesbrecht** [comment]
🎉

**Comment by krzyzanowskim** [comment]
Q: Did it address manifest swiftc issue https://github.com/apple/swift-package-manager/pull/2117 ?

**Comment by SDGGiesbrecht** [comment]
It was not on my mind, so I doubt it. This PR didn’t semantically change any existing implementations, it only added new, functions with simpler signatures that call into the older ones.

The only refactoring it did was factor out [this line](https://github.com/apple/swift-package-manager/pull/2201/files#diff-36309c5a61d54931f5e256402f92668bL234)...

```swift
var pdLibDir = binDir.parentDirectory.appending(components: "lib", "swift", "pm")
```

...to move it verbatim [into `UserManifestResources`](https://github.com/apple/swift-package-manager/pull/2201/files#diff-83573466f782b2cfeb9f24f3088ccd50R29)...

```swift
public static func libDir(forBinDir binDir: AbsolutePath) -> AbsolutePath {
    return binDir.parentDirectory.appending(components: "lib", "swift", "pm")
}
```

...so that it can also be used in the [simplified initializer](https://github.com/apple/swift-package-manager/pull/2201/files#diff-83573466f782b2cfeb9f24f3088ccd50R37).

If it was being fed the wrong `binDir` before, then it still is.

There are only two call sites for the factored‐out function.

1. Yours can simply pass the other `binDir` and it will have the same effect as your original #2117 (i.e. the [result of your merging master](https://github.com/apple/swift-package-manager/pull/2117/files#diff-36309c5a61d54931f5e256402f92668bR217) is already correct).

2. The new call site is a part of the API which selects the manifest resources associated with a particular compiler anyway, and that compiler is received directly from the external client. (The client likely gets it with `which swift` or similar.) So I don’t think you need to change anything on that side.

**Pull request merged**
