### PR TITLE
Revert "Fix `disableSandboxForPluginCommands`"

### PR DESCRIPTION
**Pull request by DougGregor**
Reverts apple/swift-package-manager#5855

### CODE REVIEW

**Comment by tomerd** [comment]
@neonichu

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Just a note, if we revert this we'll break the package compatibility suite again.

**Comment by DougGregor** [comment]
Closing this PR; it does not appear to be related to the CI failures we're seeing.

**Pull request closed without merging**
