### PR TITLE
[Basic] Rename FSProxy to FileSystem.

### PR DESCRIPTION
**Pull request by ddunbar**
- This is more appropriate given that we want it to be our pervasive, uniform
   API for accessing the file system. I'm not sure why I didn't just call it
   that in the first place...

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
Yay!

**Comment by abertelrud** [comment]
I saw the same OS X failure in another PR, it's in the Swift compiler itself.  But unfortunately that means it doesn't get as far as actually testing SwiftPM.

**Comment by ddunbar** [comment]
Yup, since Linux passed I will test and merge manually.

**Comment by abertelrud** [comment]
BTW, I like the change from `localFS` to `localFileSystem` more than I expected I would, even though it's longer.   Reads better.

**Pull request merged**
