### PR TITLE
[GitRepository] Do actual checkout in checkout methods

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Currently it just hard resets which keeps the HEAD on master branch

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@ddunbar was there a reason to not do actual checkout?

**Comment by ddunbar** [comment]
I was worried about the management of the underlying branch state... we aren't really interested in git's features around branches in this use case, we just want to be at a particular revision. I was worried if we do checkouts and things that it would be easier for things to break in subtle ways if we reuse the repo, it checks out A, then checks out B, then goes back to A but maybe not at the right place.

Maybe we should checkout a new, fake, "working branch" and then reset it?

Put another way `reset --hard` will basically never fail (that I know of), but `checkout` can fail for all sorts of reasons.

**Comment by aciidb0mb3r** [comment]
> Maybe we should checkout a new, fake, "working branch" and then reset it?
and then again checkout to the "revision"?
The use case for real checkout right now is that if user wants to checkout to a revision without a branch name, it would leave him on the master branch which was reset to that revision.

**Comment by ddunbar** [comment]
Yeah, that behavior was only designed for the internal checkouts, not the editable ones. I agree it is really wrong for the editable ones, and maybe we should just make sure the API is reliable and use the same API for both cases... but do you understand what my concern was?

**Comment by aciidb0mb3r** [comment]
Yea I think so. So we can change checkout to 
checkout to some random unique branch (do we need random() here?) -> reset -> checkout to the detached head -> delete that working branch
does that sound ok?

**Comment by aciidb0mb3r** [comment]
I just realised that there is a `-f` option in checkout which removes any unmerged changes, I updated PR with that. Do think that'll work ?

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
Tests are failing:
```
Test Case '-[CommandsTests.WorkspaceTests testPackageGraphLoadingWithCloning]' passed (0.483 seconds).
Test Case '-[CommandsTests.WorkspaceTests testUneditDependencyAndReturnError:]' started.
From /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/spm-tests-testUneditDependency().I9iSbF/A
 * branch            HEAD       -> FETCH_HEAD
From /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/spm-tests-testUneditDependency().I9iSbF/A
 * branch            HEAD       -> FETCH_HEAD
Note: checking out '97dfd00c1788693222aadea7b35e546b27d1738c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 97dfd00... msg
From /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/spm-tests-testUneditDependency().I9iSbF/A
 * branch            HEAD       -> FETCH_HEAD
From /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/spm-tests-testUneditDependency().I9iSbF/A
 * [new branch]      master     -> origin/master
Note: checking out '97dfd00c1788693222aadea7b35e546b27d1738c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 97dfd00... msg
/Users/buildnode/jenkins/workspace/swift-package-manager-PR-osx/swiftpm/Tests/CommandsTests/WorkspaceTests.swift:544: error: -[CommandsTests.WorkspaceTests testUneditDependencyAndReturnError:] : failed - Unexpected edit success
```

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
Tracking the reason for test failure here: https://bugs.swift.org/browse/SR-2815 
changed the test to edit on a branch for now

**Comment by aciidb0mb3r** [comment]
linux tested locally

**Pull request merged**
