### PR TITLE
Add completions directly to bash

### PR DESCRIPTION
**Pull request by ascarter**
Completions can be loaded directly instead of using a second file.
This also has the advantage of updating automatically when completions change
with updates.

### CODE REVIEW

**Comment by BenchR267** [comment]
Nice, thank you! Is the same also possible for the zsh-completions? Also: could you please squash your commits into one to keep the history as clean as possible? Thanks for the contribution!

**Comment by ascarter** [comment]
Let me look up the zsh syntax...

**Comment by BenchR267** [comment]
Ok, thanks for looking into it!

**Comment by BenchR267** [comment]
@swift-ci please smoke test and merge

**Comment by BenchR267** [comment]
@swift-ci please smoke test and merge

**Comment by BenchR267** [comment]
@swift-ci please smoke test and merge

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Pull request merged**
