### PR TITLE
[Build] Use list of arguments for clang tool

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This will solve the issue where spaces in path failed to build for clang
modules.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
looks like generated xcodeproj is invalid if there is spaces in paths but that should be a separate bug, will put a different testcase for this instead.

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
We just need to quote the paths in the Xcodeproj I think

**Comment by aciidb0mb3r** [comment]
It wasn't the path, it was the target name causing pbx file to become invalid.
opened a fix here: https://github.com/apple/swift-package-manager/pull/466

**Comment by ddunbar** [comment]
LGTM, thanks!

**Pull request merged**
