### PR TITLE
Use structured concurrency in `PackageLoadingTests`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This is a stripped down version of https://github.com/apple/swift-package-manager/pull/6624 that modifies only the test suite and doesn't make any substantial to `ManifestLoader.swift` other than providing an `async` overload in `extension ManifestLoaderProtocol` that uses `withCheckedThrowingContinuation` to bridge into the existing implementation.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by weissi — APPROVED** [review]
lgtm!

**Pull request merged**
