### PR TITLE
Add products to package collections CLI

### PR DESCRIPTION
**Pull request by neonichu**
The `describe` command for a package version was printing modules, but not products.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Review by yim-lee — APPROVED** [review]

**Review by federicobucchi — APPROVED** [review]

**Comment by federicobucchi** [comment]
After conflict solved: `Sources/Commands/SwiftPackageCollectionsTool.swift`

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
> 10:20:26 Test Case 'PackageCollectionsTests.testBrokenRefresh' started at 2021-01-14 12:19:57.754
> 10:20:26 Exited with signal code 11

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
> 10:20:26 Test Case 'PackageCollectionsTests.testBrokenRefresh' started at 2021-01-14 12:19:57.754
10:20:26 Exited with signal code 11

@neonichu plz let me know if you see it again so I can examine the log

**Pull request merged**
