### PR TITLE
First round of adjustments to proposal review feedback

### PR DESCRIPTION
**Pull request by abertelrud**
This implements feedback from the proposal review.

### Motivation:

Based on the feedback of SE-0303 there were certain suggestions, and this starts to bring the implementation in line with the revisions being made to the proposal.

### Modifications:

- fold `prebuild` into `buildTool` capability, using CommandConstructor API to distinguish
- keep the inputFiles and outputFiles properties with build commands and outputDirectory with prebuild commands
- remove postbuild capability and associated commands
- simplify internal implementation now that there are only two fairly similar build commands
- adjust unit tests

An upcoming round of revisions will adjust the path API available to the plugin.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift please smoke test linux

**Comment by abertelrud** [comment]
@swift-ci please smoke test linux

**Comment by abertelrud** [comment]
@swift-ci please smoke test macos

**Review by tomerd — APPROVED** [review]

**Pull request merged**
