### PR TITLE
add soundness script

### PR DESCRIPTION
**Pull request by tomerd**
motivation: help ensure soundness of changes, including license headers and appropriate language

changes:
* add script to test soundness of changes, including license headers and appropriate language
* update license headers to match more conventional style

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
@swift-ci smoke test macOS

**Comment by tomerd** [comment]
@swift-ci smoke test macOS

**Comment by tomerd** [comment]
@swift-ci please smoke test macOS

**Comment by tomerd** [comment]
@swift-ci please smoke test macOS

**Comment by tomerd** [comment]
@swift-ci please smoke test macOS

**Review by abertelrud — APPROVED** [review]
This is great!

**Pull request merged**
