### PR TITLE
[SwiftPackageTool] add doctor command to usage

### PR DESCRIPTION
**Pull request by kostiakoval**
Add doctor command to help text.

### CODE REVIEW

**Comment by ddunbar** [comment]
I'm not convinced we want to keep the doctor command... it doesn't really do much currently, and I'd rather we put energy into making good diagnostics when things go wrong than users needing to actually run some separate command.

**Comment by kostiakoval** [comment]
I just run into a small problem. After running `git pull` some files were deleted and as result I my package has empty folders. When i ran `swift build` I got an error. 

My idea was to add cleanup command to doctor, so it can remove empty folders. 

And if something goes wrong, like founding empty module folder, would we give users interactive options directly into command line, like `remove folder - YES, NO` or does user need to do it by himself?

Ideas about it?

**Comment by abertelrud** [comment]
The problem with having features like `doctor` is that it becomes tempting to rely on them instead of making the other features robust enough.  And then users, in turn, come to rely on having to invoke these features periodically, whenever they run into an error that they don't understand (features like this easily become the "rebuild desktop" cure-all of our time).

Also, the best place to report relevant details is usually at the point at which a problem is detected.  That's when there is enough context, and it might be difficult to reliably recreate the same context in a `doctor` command, especially when the problem arises from a combination of the package and options passed on the command line during the build.

As for empty folders, it seems to me that the build shouldn't fail when it finds an empty folder.  At most it should emit a warning.

I don't mean to sound dismissive of the intent here — we should absolutely have detailed and accurate diagnostics, ideally with "fix-it" information when possible, and adding infrastructure for easy state capture and reporting of such problems would be great.  Fix-its could then be surfaced in an IDE, for example, in the manner of the `swift` compiler itself, or possibly on the command line in "interactive" mode.

I see a parallel here with how the `clang` compiler significantly improved the state-of-the-art of error reporting for C-like compilers, and did so through excellent diagnostics and resolution information rather than taking the approach of adding a `lint` type of command.

**Comment by ddunbar** [comment]
I agree with @abertelrud, let's try to tackle specific failures like that through actual features at the site of a failure, not through an interactive `doctor` type command. I would actually rather we just remove the `doctor` functionality we have versus this PR.

**Comment by kostiakoval** [comment]
I agree. 👍

**Pull request closed without merging**
