### PR TITLE
[Basic] Remove unused OptionParser module

### PR DESCRIPTION
**Pull request by sora0077**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@sora0077 Thank you!
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@ddunbar What do you think? Should we move ArgumentParser to basic?

**Comment by ddunbar** [comment]
I'd probably vote to leave it in Utility for now unless we have a reason to need it in Basic? I'm otherwise fine with moving it...

**Comment by aciidb0mb3r** [comment]
Works for me

**Comment by aciidb0mb3r** [comment]
@swift-ci please test OS X

**Comment by shahmishal** [comment]
@swift-ci please test OS X

**Comment by aciidb0mb3r** [comment]
CI passed but github status wasn't updated:
```
Setting commit status on GitHub for https://github.com/apple/swift-package-manager/commit/074413217ba773b088174510a579daff16ba896b
Setting status of d68e85a8b9cedd5ef659a966c0bcc9ae970b1c7c to SUCCESS with url https://ci.swift.org/job/swift-package-manager-PR-osx/741/ and message: 'Build finished. '
Using context: Swift Test OS X Platform
Could not update commit status of the Pull Request on GitHub.
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at org.kohsuke.github.Requester.buildRequest(Requester.java:327)
	at org.kohsuke.github.Requester._to(Requester.java:248)
	at org.kohsuke.github.Requester.to(Requester.java:213)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:932)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:273)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:232)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:194)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:17)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1783)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Finished: SUCCESS
```

**Pull request merged**
