### PR TITLE
Rename modules. Add prefixes. 

### PR DESCRIPTION
**Pull request by krzyzanowskim**
For: https://bugs.swift.org/browse/SR-11151

Basic -> SPMBasic
SourceControl -> SPMSourceControl
Build -> SPMBuild
Workspace -> SPMWorkspace

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Thanks. Seems good but can you revert the whitespace diffs?

**Comment by krzyzanowskim** [comment]
gosh, I don't even know how it happened (VSCode magic I guess)

**Comment by krzyzanowskim** [comment]
@aciidb0mb3r updated.

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
We'll probably need changes in sourcekit-lsp too /cc @benlangmuir

**Comment by benlangmuir** [comment]
And https://github.com/apple/swift-stress-tester /cc @nathawes

**Comment by aciidb0mb3r** [comment]
stress tester seems to be using exact version of SwiftPM

**Comment by jakepetroules** [comment]
👍

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by krzyzanowskim** [comment]
never happened. closing.

**Pull request closed without merging**
