### PR TITLE
Remove the vendored copy of TSC

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
> 15:53:17 /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/build/buildbot_incremental/toolchain-linux-x86_64/usr/bin/swiftc -L /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/build/buildbot_incremental/toolchain-linux-x86_64/usr/lib/swift/pm/4_2 -lPackageDescription -Xlinker -rpath -Xlinker /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/build/buildbot_incremental/toolchain-linux-x86_64/usr/lib/swift/pm/4_2 -swift-version 5 -I /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/build/buildbot_incremental/toolchain-linux-x86_64/usr/lib/swift/pm/4_2 -package-description-version 5.1.0 -module-cache-path /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/tmp_swiftpm/ModuleCache /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/tmp/TemporaryFile.j6ln3r.swift -o /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/tmp/TemporaryDirectory.zS6aRd/swiftpm-manifest
15:53:17 /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/tmp/TemporaryDirectory.zS6aRd/swiftpm-manifest -fileno 10
15:53:17 error: Error Domain=NSCocoaErrorDomain Code=260 "The file doesn’t exist."

**Comment by neonichu** [comment]
> 15:56:07 error: Error Domain=NSCocoaErrorDomain Code=260 "The folder “swift-tools-support-core” doesn’t exist." UserInfo={NSFilePath=/Users/buildnode/jenkins/workspace/swift-package-manager-PR-osx-smoke-test/branch-master/swiftpm/swift-tools-support-core, NSUserStringVariant=(
15:56:07     Folder
15:56:07 ), NSUnderlyingError=0x7fe5ae4300f0 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}

**Comment by neonichu** [comment]
Seems like this error happens as part of LSP: `15:53:16 + /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/sourcekit-lsp/Utilities/build-script-helper.py build --package-path /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/sourcekit-lsp --build-path /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/build/buildbot_incremental/sourcekitlsp-linux-x86_64 --configuration release --toolchain /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/build/buildbot_incremental/toolchain-linux-x86_64/usr --ninja-bin /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/build/buildbot_incremental/ninja-build/ninja --verbose`

**Comment by neonichu** [comment]
@benlangmuir is it possible that SourceKit-LSP relies on the vendored copy here?

**Comment by benlangmuir** [comment]
@neonichu yes, when building in CI we use a relative path

```
.package(path: "../swiftpm/swift-tools-support-core"),
```

But before we change that, TSC does not seem to be testing swiftpm nor sourcekit-lsp in its own PR testing.  I think that is a prerequisite for switching away from the vendored copy.

**Comment by neonichu** [comment]
> But before we change that, TSC does not seem to be testing swiftpm nor sourcekit-lsp in its own PR testing. I think that is a prerequisite for switching away from the vendored copy.

Absolutely, I'm working on that as well, but also want to explore the kinks of making the change already.

**Comment by benlangmuir** [comment]
https://github.com/apple/sourcekit-lsp/pull/305
@swift-ci please smoke test

**Comment by tomerd** [comment]
Screen Shot 2020-09-02 at 5 54 57 PM

 <3

**Comment by neonichu** [comment]
Looks like this works in conjunction with the @benlangmuir's sourcekit-lsp PR, so once I have amended TSC's PR testing, we can land this.

**Comment by shahmishal** [comment]
We moved our default branch to `main` and deleted `master` branch, GitHub automatically closed the PR. Please update the base branch to `main`.  More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
