### PR TITLE
pass fd to PackageDescription while parsing manifests instead of using SWIFT_DUMP_PACKAGE

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by mxcl** [comment]
Looks good. I am currently waiting on the swift-3-api-guidelines merge before merging anything new.

**Comment by mxcl** [comment]
@swift-ci please test

**Comment by mxcl** [comment]
I'm going to start merging everything, as I hoped the swift 3 apis would be merged this week, but it looks like it will be longer.

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by aciidb0mb3r** [comment]
```
/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swiftpm/Sources/ManifestParser/Manifest+parse.swift:74:13: error: use of unresolved identifier 'fclose'
    defer { fclose(fp) }
            ^~~~~~
<unknown>:0: error: build had 1 command failures
```

This did not error for me on OSX and Ubuntu 15.10
CI looks like to be on 14.04, will check.

**Comment by aciidb0mb3r** [comment]
This is weird, It works for me on Ubuntu 14.04 too. 
Latest toolchain
```
Swift version 3.0-dev (LLVM b361b0fc05, Clang 11493b0f62, Swift 24a0c3de75)
Target: x86_64-unknown-linux-gnu
```

**Comment by mxcl** [comment]
Probably would be fixed if you `import func libc.fclose`

**Comment by aciidb0mb3r** [comment]
I figured but weird that CI errors out where as nothing on local

**Comment by aciidb0mb3r** [comment]
@mxcl trigger CI please

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by aciidb0mb3r** [comment]
CI succeeded merging

**Pull request merged**
