### PR TITLE
Add Dispatch to the library list and library search path when

### PR DESCRIPTION
**Pull request by vivkong**
linking

While building on s390x, the linker cannot find the symbols from libdispatch so I'd like to add libdispatch to the library list and search path for linking.

### CODE REVIEW

**Comment by ddunbar** [comment]
Is this because auto-linking doesn't work on s390x? If so, how are Foundation and XCTest working?

**Comment by vivkong** [comment]
I guess so.  I had to make a change in Foundation as well: https://github.com/apple/swift-corelibs-foundation/pull/606

**Comment by ddunbar** [comment]
My question was why don't we need the same thing for the Foundation libraries?

**Comment by vivkong** [comment]
Oh oops my bad for misunderstanding.  The build started failing for us now that libdispatch will always get built with Foundation.  But yes we didn't have to explicitly include -lFoundation or -lXCTest.  Is there a way to check if auto-linking is doing the correct thing?

**Comment by ddunbar** [comment]
I don't know the details of how auto-linking is implemented on s390x, but if it follows the Linux model then you can run with the build with `-v` to see the full list of commands, then extract the command used to link (should be a swift driver invocation), then pass `-v` to that to see exactly what the Swift driver is doing.

In any case, before merging I think we should understand why s390x is behaving differently than other platforms here.

**Comment by vivkong** [comment]
Thanks for your suggestion and I totally understand that why we can't merge this right away.  I was comparing the verbose output and it looks like for some reason on s390x it wasn't using the gold linker to link.  I'll continue to trace back to see what's going on.

**Comment by vivkong** [comment]
Thanks for all your help @ddunbar!  The linker error was caused by not using the gold linker.  I have a fix and I'll create a pull request for Swift.

**Pull request closed without merging**
