### PR TITLE
[PackageGraph] Disallow unsafe build flags in dependencies

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by pschuh** [comment]
Hi, could you update this with more motivation for why this was committed? It basically makes these unsafe features unusable for anything but leaf projects. I would like a "yes, I know what I'm doing" way of importing these packages again.

**Comment by SDGGiesbrecht** [comment]
@pschuh, it was part of the final [proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0238-package-manager-build-settings.md#unsafe-flags-all) and mandated as a result of [review](https://forums.swift.org/t/se-0238-package-manager-target-specific-build-settings/18341/4).

**Comment by pschuh** [comment]
@SDGGiesbrecht Thanks for the reply, is there anything that can be done about it? I don't see a way in the code to circumvent this check from the depending package. Am I missing something?

**Comment by SDGGiesbrecht** [comment]
I don’t think there is a way to circumvent it. See [this post](https://forums.swift.org/t/se-0238-package-manager-target-specific-build-settings/18341/10) in particular.

My advice would be to [pitch](https://forums.swift.org/c/evolution/pitches) a dedicated, safe API to handle whatever your use case is.

**Comment by pschuh** [comment]
Hmm, Sorry for being so dense on this, I'm not sure it is possible to pitch APIs for all possible flags. For example, there are a lot of different warnings flags in clang that you may want to spot-disable when compiling external code. Even the simplest thing of a whitelist could be hard to maintain.

I also don't think a pitch for a safe API would work for my particular use case, I have some internal compiler flags that I want to set on a branched version of the compiler to experiment with things while doing compiler development. Since these flags are for experimental compiler development, but I want to enable them for some targets in a project that is using multiple swift packages, and this requirement is limiting that. Please advise.

**Comment by SDGGiesbrecht** [comment]
> I'm not sure it is possible to pitch APIs for all possible flags.

Many “possible” flags are a bad idea anyway. The current setup provides package clients some level of assurance that their dependencies are only doing supported things.

> there are a lot of different warnings flags in clang that you may want to spot-disable when compiling external code.

Warning suppression would be a reasonable thing to pitch. I would even support automatic suppression of all warnings that occur when compiling dependencies—especially deprecation warnings—, since they are out of your hands to do anything about anyway.

> I have some internal compiler flags that I want to set on a branched version of the compiler to experiment with things while doing compiler development.

This sort of experimentation is why this escape hatch exists. I don’t imagine you plan to publish a release with your package in that state, so can you use branch or revision dependencies? Those allow unsafe flags, at least according to post I linked above. (Or, if you are using a development fork of Swift anyway, you can just temporarily modify the package manager if it helps your current experiments.)

If you have more to discuss, the forums would be the place for it. This pull request is almost a year old and already included in stable releases.

**Comment by aciidb0mb3r** [comment]
Thanks for the discussion @pschuh and @SDGGiesbrecht and thanks for continuing the discussion on the [forums](https://forums.swift.org/t/confused-by-unsafe-flags-being-disallowed-in-dependencies/27359).

**Pull request merged**
