### PR TITLE
Revert "Support experimental test summary on non-Darwin (#6878)"

### PR DESCRIPTION
**Pull request by compnerd**
This reverts commit ca45050cd409de7e746006c9602db0076df8fe70.

Tests on Windows do not function after this change:
```
[388/392] Emitting module SwiftWin32PackageTests
C:\a\swift-build\swift-build\SourceCache\swift-win32\.build\x86_64-unknown-windows-msvc\debug\SwiftWin32PackageTests.derived\runner.swift:13:20: error: invalid escape sequence in literal

        return "C:\a\swift-build\swift-build\SourceCache\swift-win32\.build\x86_64-unknown-windows-msvc\debug\testOutput.txt"
```

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
The issue probably lies [here](https://github.com/apple/swift-package-manager/blob/main/Sources/Build/TestObservation.swift#L30):

```
var testOutputPath: String {
    return "\(buildParameters.testOutputPath)"
}
```

Maybe using `._nativePathString(escaped: true)` would do the right thing?

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
We recently asked @shahmishal for aliasing "test" to "smoke test" but I guess this made "smoke test" non-functional except for Windows?

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@shahmishal @compnerd, @neonichu and myself were just chatting about windows CI for SwiftPM and not clear to us why it is only building and not running any of the tests (we were not involved in how it was set up). are we in a position to run the tests as well?

**Comment by compnerd** [comment]
I'm going to merge this for now as this is actively blocking the use of SPM on Windows. Lets figure out how to get testing enabled to avoid this in the future.

**Pull request merged**
