### PR TITLE
testTarget method's description of parameter path

### PR DESCRIPTION
**Pull request by hellomsg**
the description of parameter path is not right

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Good catch; thank you for the fix!

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by abertelrud** [comment]
The test failure doesn't make sense to me, but I do notice that the swift-argument-parser dependency was checked out at 0.3.1.  I saw from https://github.com/apple/swift-package-manager/pull/2909 that we're pinning to 0.3.0 to avoid an assertion failure apparently caused by 0.3.1, so once that lands, we should rerun the test here.

**Pull request merged**
