### PR TITLE
[swift-3.0-branch] Removing the usage of a private API

### PR DESCRIPTION
**Pull request by moiseev**
Required for https://github.com/apple/swift/pull/4753

rdar://problem/28289426

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by abertelrud** [comment]
It's unfortunate that we don't have a performance test for the previous implementation.  It would be very interesting to know what kind of performance hit we're looking at (if any) by simplifying the code in this way.  Presumably the complexity of the code was incurred because of real performance issues.

**Comment by abertelrud** [comment]
(Obviously, I'm not at all arguing against removing the use of private API — that's both good and necessary).

**Comment by moiseev** [comment]
FWIW: here are the original PRs against master branch for this change.
https://github.com/apple/swift-package-manager/pull/634
https://github.com/apple/swift-package-manager/pull/647

**Comment by abertelrud** [comment]
Thanks @moiseev!  I hadn't seen the earlier conversation.  I also didn't realize (but should have) that this was just the branch PR for a previous master PR.

**Comment by abertelrud** [comment]
The Linux failure looks unrelated.  Do you want me to go ahead and merge this PR or should we try to get a clean Linux run?

**Comment by abertelrud** [comment]
Actually, as this is under CCC, I guess Ted would be the one to merge to the branch.

**Comment by moiseev** [comment]
Closing without merging: see justification [here](https://github.com/apple/swift/pull/4753#issuecomment-247237974).

**Pull request closed without merging**
