### PR TITLE
Fix most "target"/"module" internal naming inconsistencies

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Cleaning up `PackageGraph` and `Build` code naming inconsistencies after `ResolvedTarget` to `ResolvedModule` renaming. User-visible strings and symbols still reference it as "target", but at least it's easier to navigate for contributors. `public` symbols gained deprecation notices where this was possible and easy to add.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test linux

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by xedin — APPROVED** [review]
:shipit:

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
