### PR TITLE
Prevent unused dynamic libraries from blocking WASI build

### PR DESCRIPTION
**Pull request by SDGGiesbrecht**
This prevents SwiftPM from hitting [a fatal error in TSC](https://github.com/apple/swift-tools-support-core/blob/a365934c148d061e40028b7617a05a00925786bd/Sources/TSCUtility/Triple.swift#L227) until _after_ it is known whether a dynamic product is actually used.

@MaxDesiatov

### Motivation:

Right now, if any package in the graph contains a dynamic library product, SwiftPM crashes when building for WASI, even if the product is not used by any target. This happens because SwiftPM attempts to compute the path of the resulting dynamic library before it checks whether it will actually need to build it or not.

### Modifications:

This PR takes every query of the dynamic library path that happens early enough to cause problems, and skips it if the destination is WASI.

Queries of the same property that occur _after_ unused products have been filtered out remain as they were, and so the fate is unchanged if you actually attempt to _build_ a dynamic library product.

A test has been added to detect any future regressions; it fails without the rest of the changes.

### Result:

Unused dynamic libraries no longer block WASI builds.

### CODE REVIEW

**Comment by neonichu** [comment]
This seems pretty ugly to me. 

I think we should instead find a way to filter out dynamic products entirely when producing the build plan.

**Comment by SDGGiesbrecht** [comment]
That is what I though at first too; the downside turned out to be that its complete absence starts chain reaction of other breakage, particularly regarding diagnostics. In a perfect world, `Triple`’s `dynamicLibraryExtension` would have been optional, but to make that change now would be colossally invasive.

I am not sure why this sort of information is being computed greedily in the first place only to be discarded later. Maybe that is the real issue here, but I have not yet been able to fully unwind in my head what is happening when and why for that part of the loading process.

I suppose alternatively, if @MaxDesiatov knows what the hypothetical extension would eventually be, then we could specify it in TSC instead of the `fatalError` error and the problem would just vanish.

**Comment by SDGGiesbrecht** [comment]
Hmm... While the [official status](https://github.com/WebAssembly/tool-conventions/blob/main/DynamicLinking.md#webassembly-dynamic-linking) appears to be about equivalent to an underscored feature in Swift, Emscripten’s documentation [recommends the extension `.wasm`](https://emscripten.org/docs/compiling/Dynamic-Linking.html?highlight=dlopen#load-time-dynamic-linking). And at least one blogger uses that [in his raw `clang` example](https://iandouglasscott.com/2019/07/18/experimenting-with-webassembly-dynamic-linking-with-clang/) too. Could we just use that [in TSC](https://github.com/apple/swift-tools-support-core/blob/a365934c148d061e40028b7617a05a00925786bd/Sources/TSCUtility/Triple.swift#L226-L227), @MaxDesiatov? We can easily change it later, but having *something* right now would be helpful.

**Comment by SDGGiesbrecht** [comment]
I have tested SwiftPM on top of apple/swift-tools-support-core#311, and can confirm that it completely solves the problem on its own. So if that PR is accepted, this one becomes moot.

**Comment by MaxDesiatov** [comment]
CC @kateinoigakukun

**Comment by MaxDesiatov** [comment]
Specifying `.wasm` extension in TSC seems like a reasonable solution to me.

**Comment by kateinoigakukun** [comment]
> Specifying .wasm extension in TSC seems like a reasonable solution to me.

I agree. c.f. rustc also uses `.wasm` as dll suffix https://github.com/rust-lang/rust/blob/a8272f23cc121cc3e98f3148c8dab532decc7b90/compiler/rustc_target/src/spec/wasm_base.rs#L78

**Comment by SDGGiesbrecht** [comment]
apple/swift-tools-support-core#311 was merged instead.

**Pull request closed without merging**
