### PR TITLE
Do not pollute home directory with test data

### PR DESCRIPTION
**Pull request by neonichu**
We can just write those files into /tmp

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
macOS CI seems consistently broken, cc @shahmishal

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test macos

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
