### PR TITLE
[Basic] Add a Sequence.makeNestedIterator().

### PR DESCRIPTION
**Pull request by ddunbar**
- This is a utility for getting a flattened iterator over all the elements in
   nested sequences in some other sequence.

### CODE REVIEW

**Comment by ddunbar** [comment]
/cc @abertelrud @aciidb0mb3r @gribozavr Curious if anyone has opinion/feedback here (on the name or otherwise).

I'm going to merge as soon is tested though because I need it.

**Comment by gribozavr** [comment]
It seems to be the same as `flatMap()` on collections, so I'd probably call it that.  LGTM otherwise.

**Comment by abertelrud** [comment]
I have no great ideas for a name, though Dmitri makes a good point I think.

**Comment by ddunbar** [comment]
I was just insufficiently familiar with the `lazy` corner of the stdlib, I don't think there is a need for this anymore.

**Pull request closed without merging**
