### PR TITLE
[Docs] Added information about building toolchains

### PR DESCRIPTION
**Pull request by wokalski**
It took me a long time to find this information and I feel like it has to be better documented. If it is not an appropriate place, let me know.

### CODE REVIEW

**Comment by mxcl** [comment]
We don't really expect people to build their own, we release them as often as possible. Why did you feel the need to build your own?

**Comment by ketzusaka** [comment]
Would building your own help a contributor make contributions?

**Comment by aciidb0mb3r** [comment]
Building toolchain has been helpful recently due to breaking change in XCTests and the swift-3-api-guidelines merge but I think this should be in swift repo docs and not here

**Comment by wokalski** [comment]
@mxcl excellent question. I was pondering in SPM and tried to build my package with a local version of SPM but got an error that my `swiftc` is not compatible (I installed the latest development snapshot). 

I also built Swift locally but had no luck using it. I could symlink to it from `/usr/bin`, but I'd rather have this structured workflow where I build a local toolchain and have it there, and can always switch from/to it.

Maybe I did something wrong, I would be glad to document "the correct process" if you can point me in the right direction. Obviously somewhere where it fits.

@aciidb0mb3r Well, I thought so, intuitively. However the only place which mentions managing toolchains is this one. AFAIK, there's no documentation for `build-script` in the main repo either. This is why I decided to add it here.

**Comment by mxcl** [comment]
Building your own is not necessary here. The problem is that `swift build` must be run with the version of swift it is built with and probably it was using the version built with Xcode.

You can set `SWIFT_EXEC` to work around this.

Probably we should document that part. Building the toolchain is not something to be documented here.

**Comment by wokalski** [comment]
@mxcl Thanks! Setting `SWIFT_EXEC` fixed this. It was exactly what I hoped would exist but couldn't find.

I can either create a new document in `Documentation/Internals` or add a note in the README in Documentation section but long term it will get messy. 

I can create a document called `EnvironmentVariables.md` and document it there. Does it sound good? Are there any others you'd like to be documented?

**Comment by mxcl** [comment]
I think the `README` can mention this. It may get a bit messy, but we should clean it up at some point soon.

**Pull request closed without merging**
