### PR TITLE
[XCBuildSupport] Use .withoutEscapingSlashes when emitting PIF

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by hartbit** [comment]
smoke test macOS

**Comment by hartbit** [comment]
smoke test OS X

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test macOS

**Comment by aciidb0mb3r** [comment]
I think it's failing on CI because Foundation overlay is actually missing the  `withoutEscapingSlashes` case. 

https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/JSONEncoder.swift#L63

**Comment by abertelrud** [comment]
> I think it's failing on CI because Foundation overlay is actually missing the `withoutEscapingSlashes` case.
> 
> https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/JSONEncoder.swift#L63

Looks as if it's there now.  Trying again.

**Comment by abertelrud** [comment]
@swift-ci smoke test

**Pull request merged**
