### PR TITLE
Sync latest TSC changes from `main`

### PR DESCRIPTION
**Pull request by abertelrud**
Syncs the latest tools support core changes into SwiftPM.  This will need to be done periodically until TSC is no longer vendored.

This is currently done by copying the files from a checkout of TSC into SwiftPM, which doesn't preserve the commit history.  This is hopefully not going to be a problem once https://github.com/apple/swift-package-manager/pull/2991 is merged.  Per the comment in that PR, there are currently some remaining CI issues to work through before it can be merged.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]
lgtm. hopefully we can remove the vendor copy soon

**Comment by abertelrud** [comment]
Absolutely agreed.  I think that the PR to remove it is only blocked on https://github.com/apple/swift-tools-support-core/pull/150.

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
Merging this PR to unblock Swift PR testing.

**Pull request merged**
