### PR TITLE
Adopt initial split of Foundation into multiple modules

### PR DESCRIPTION
**Pull request by millenomi**
Ensure that component module libraries are now picked up alongside Foundation’s.

### CODE REVIEW

**Comment by millenomi** [comment]
cfr. https://github.com/apple/swift-corelibs-foundation/pull/1799

**Comment by millenomi** [comment]
Please test with the following:
https://github.com/apple/swift-clang/pull/245
https://github.com/apple/swift-corelibs-foundation/pull/1799
https://github.com/apple/swift/pull/21234

@swift-ci please test

**Comment by millenomi** [comment]
_tiny sigh_

**Comment by millenomi** [comment]
Please test with the following:
https://github.com/apple/swift-clang/pull/245
https://github.com/apple/swift-corelibs-foundation/pull/1799
https://github.com/apple/swift/pull/21234
https://github.com/apple/swift-lldb/pull/1187

@swift-ci please test

**Comment by millenomi** [comment]
There was a failure to check out the PRs.

**Comment by millenomi** [comment]
Please test with the following:
https://github.com/apple/swift-clang/pull/245
https://github.com/apple/swift-corelibs-foundation/pull/1799
https://github.com/apple/swift/pull/21234
https://github.com/apple/swift-lldb/pull/1187

@swift-ci please test

**Comment by millenomi** [comment]
Please test with the following:
https://github.com/apple/swift-clang/pull/245
https://github.com/apple/swift-corelibs-foundation/pull/1799
https://github.com/apple/swift/pull/21234
https://github.com/apple/swift-lldb/pull/1187

@swift-ci please test

**Comment by millenomi** [comment]
Please test with the following:
https://github.com/apple/swift-clang/pull/245
https://github.com/apple/swift-corelibs-foundation/pull/1799
https://github.com/apple/swift/pull/21234
https://github.com/apple/swift-lldb/pull/1187

@swift-ci please test

**Comment by millenomi** [comment]
Please test with the following:
https://github.com/apple/swift-clang/pull/245
https://github.com/apple/swift-corelibs-foundation/pull/1799
https://github.com/apple/swift/pull/21234
https://github.com/apple/swift-lldb/pull/1187

@swift-ci please test

**Comment by tomerd** [comment]
hi @millenomi is this still relevant?

**Comment by tomerd** [comment]
based on @millenomi (on slack):  _this is obsolete — it’s a different split. it can be closed._

**Pull request closed without merging**
