### PR TITLE
Commands: split SwiftPackageTool into multiple files

### PR DESCRIPTION
**Pull request by MaxDesiatov**
### Motivation:

`SwiftPackageTool.swift` is quite big, it would be great to split it into multiple files for easier maintenance.

### Modifications:

Moved `SwiftPackageTool` subcommands into separate files of new `PackageTools` subdirectory.

### Result:

It's easier to look up a specific subcommand and maintain separate files than one big file.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
good ideas 👍

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Pull request merged**
