### PR TITLE
Revert "Adopt the ArgumentParser library for the command-line tools

### PR DESCRIPTION
**Pull request by CodaFi**
Speculatively reverting on the premise that this is causing the entire set of Linux bots to fall over

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by abertelrud** [comment]
The fix in https://github.com/apple/swift-package-manager/pull/2893 has been merged, and hopefully will address the failure without having to revert the adoption of argument parser.

**Pull request closed without merging**
