### PR TITLE
Package plugins can't use the UniformTypeIdentifiers module

### PR DESCRIPTION
**Pull request by ian-twilightcoder**
Add the com.apple.lsd.mapdb Mach service to the macOS sandbox

### Motivation:

Swift package plugins can't use the Uniform Type Identifier API, such as to get a file's type identifier, because they don't have the right entitlement which is normally provided by the App Sandbox.

### Modifications:

Allow looking up the com.apple.lsd.mapdb Mach service in the macOS sandbox.

### Result:

Swift package plugins are able to use the Uniform Type Identifier APIs.

### CODE REVIEW

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
thanks @ian-twilightcoder

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by neonichu** [comment]
@swift-ci smoke test windows

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test windows

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test
@swift-ci smoke test windows

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test windows

**Pull request merged**
