### PR TITLE
Backport fedora support

### PR DESCRIPTION
**Pull request by drexin**
Depends on https://github.com/apple/swift-tools-support-core/pull/61

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by drexin** [comment]
@neonichu Thanks for taking a look. I think the above mentioned PR to swift-tools-support-core has to be merged first.

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci test linux

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Comment by drexin** [comment]
@swift-ci clean smoke test

**Comment by rballard** [comment]
@neonichu checked that the Swift Test Linux Platform (self hosted) tests are failing without this change.
This diff has already landed in ToolsSupportCore, so this is the same diff going into SwiftPM's copy.
Approved.

**Comment by drexin** [comment]
Theory as to why the test fails is that it runs against the lates development snapshot, instead of the 5.2 build. For the master branch that certainly makes a lot of sense, as it would indicate an actual issue, but here we think that it is not relevant, as it is a different version from which this will ship with.

**Pull request merged**
