### PR TITLE
[Workspace] Fix indentation in test file generated for libraries

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by abertelrud** [comment]
Linux test failure seems to be an unrelated problem in CFString.c.

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Pull request closed without merging**
