### PR TITLE
[5.9] Update registry service spec per SE-0391

### PR DESCRIPTION
**Pull request by yim-lee**
Cherry pick https://github.com/apple/swift-package-manager/pull/6275 to 5.9

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Review by tomerd — APPROVED** [review]
not required to go into the 5.9 branch

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Pull request merged**
