### PR TITLE
[Commands] add common SwiftTool protocol

### PR DESCRIPTION
**Pull request by kostiakoval**
All the 3 swift tools have many in common. It would be nice to extract common logic in 1 place, in a  `SwiftTool`

Would love to hear your feedback.

### CODE REVIEW

**Comment by ddunbar** [comment]
Seems reasonable, but how much common code do we actually have?

**Comment by abertelrud** [comment]
I agree that we don't have a lot of commonality at the moment, but there are a few things that might be useful.  For example, we should make sure that each of the commands implements `--version` properly (currently `build` and `package` do but `test` doesn't).  There was a little discussion of that on Slack, and I don't know if it would have to wait for a proper implementation of version strings in SwiftPM.

Having a protocol might also be useful since it makes it obvious where to declare any future common behavior so that any new tool has a baseline of functionality.

**Comment by ddunbar** [comment]
@kostiakoval did you plan additional extensions to this?

**Comment by kostiakoval** [comment]
Not at the moment (in this PR). Also there are common arguments and compiler flags handling in every tools. I hope those could be refactored to

**Comment by ddunbar** [comment]
Ok, let's take it in the interest of encouraging common code.

@swift-ci please test

**Comment by kostiakoval** [comment]
Some unrelated `swift-corelibs-libdispatch` issue :/ 
Shall we try once more

@swift-ci please test

**Pull request merged**
