### PR TITLE
Implement per target swift version selection

### PR DESCRIPTION
**Pull request by xedin**
[Swift Forums pitch thread](https://forums.swift.org/t/pitch-swiftpm-swift-language-version-per-target/71067)

Add a new Swift target setting API, similar to `enable{Upcoming, Experimental}Feature`,
to specify a Swift language version that should be used to build the target, if such
version is not specified, fallback to the current language version determination logic.

Resolves: rdar://125732014

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]
Thanks!

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please clean test macos

**Review by jakepetroules — APPROVED** [review]

**Review by francescomikulis — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test windows platform

**Pull request merged**
