### PR TITLE
Improve _format command

### PR DESCRIPTION
**Pull request by keith**
This makes 2 changes to `_format`:

1. Only invoke `swift-format` once, this is helpful for larger projects
2. Include the `Package.swift` file for formatting

### CODE REVIEW

**Review by neonichu — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by keith** [comment]
I don't believe the failure here is related

**Comment by tomerd** [comment]
@abertelrud this is something we should refactor out a plugin when the framework is ready. could you please review in that light.

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Seems like this failure is new and reproduces, but unrelated to this PR:

```10:56:17 Test Suite 'Selected tests' started at 2021-08-23 10:55:27.219
10:56:17 Test Suite 'IntegrationTestsPackageTests.xctest' started at 2021-08-23 10:55:27.220
10:56:17 Test Suite 'XCBuildTests' started at 2021-08-23 10:55:27.220
10:56:17 Test Case '-[IntegrationTests.XCBuildTests testLibraryProductsAndTargets]' started.
10:56:17 
/Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift:228: error: -[IntegrationTests.XCBuildTests testLibraryProductsAndTargets] : failed - Command failed with exit code: terminated(code: 1) - command: /Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/x86_64-apple-macosx/debug/swift-build --package-path /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/XCBuild_Libraries.WGF8ry/Foo --build-system xcode --target FooLib```

**Comment by neonichu** [comment]
I can repro the failure locally.

**Comment by neonichu** [comment]
Looks like some of the builds are simply failing, but we aren't propagating the errors from XCBuild correctly.

**Comment by neonichu** [comment]
The underlying error is: `Found multiple targets named 'FooLib'` which is true, there a package product target and a standard target with that name, but this doesn't seem like something we recently changed? Possibly Xcode on CI was an older version and this error exists for a while?

**Comment by neonichu** [comment]
Seems like this indeed works when using 12.5 as the installed Xcode, so this isn't due to any changes to SwiftPM.

**Comment by neonichu** [comment]
I think the most reasonable thing for now is to change the test so that it doesn't hit this and then figure out whether SwiftPM and/or XCBuild should change separately. We should also fix SwiftPM's parsing of XCBuild's output so that we don't drop the error on the floor.

**Comment by abertelrud** [comment]
> @abertelrud this is something we should refactor out a plugin when the framework is ready. could you please review in that light.

Absolutely — I didn't actually realize there was a command for this already; the mentioning of `swift-format` as an example subcommand plugin was based on use cases, not an awareness of this code.  This diff seems totally finally in relation to the existing code; when implemented as a plugin, it should have more robust emitting of output, and I'll also want to look closer at what it's using the PackageBuilder output for, since that isn't something plugins have access to now.

**Review by abertelrud — APPROVED** [review]

**Comment by abertelrud** [comment]
> > @abertelrud this is something we should refactor out a plugin when the framework is ready. could you please review in that light.
> 
> Absolutely — I didn't actually realize there was a command for this already; the mentioning of `swift-format` as an example subcommand plugin was based on use cases, not an awareness of this code. This diff seems totally finally in relation to the existing code; when implemented as a plugin, it should have more robust emitting of output, and I'll also want to look closer at what it's using the PackageBuilder output for, since that isn't something plugins have access to now.

Oh wait, PackageBuilder just construct the memory model of a package, it doesn't actually create a build system for building the package — name is confusing.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by keith** [comment]
Thanks!

**Comment by tomerd** [comment]
thank you @keith

**Pull request merged**
