### PR TITLE
Cleanup PackageGraphLoader.load implementation

### PR DESCRIPTION
**Pull request by krzyzanowskim**

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
@aciidb0mb3r appreciate review here

**Comment by aciidb0mb3r** [comment]
I am not really sure what's the advantage of the proposed changes here. I don't necessarily think we should make every single thing functional when the non-functional approach is localized and provides better readability.

**Comment by krzyzanowskim** [comment]
it's mostly about extracting 'takeAllManifests' and  provide more direct names for intermediate variables, plus some comments I found useful to understand the flow. It's not about 'functional' that  think didn't change much from the original code though.

**Comment by aciidb0mb3r** [comment]
Can you make comment only changes in PackageGraphLoader if you're finding it harder to read? It probably boils down to personal preferences but all these `compactMap`s seems unnecessary complexity to me. The `typealias` change in PackageReference looks good 👍

**Comment by tomerd** [comment]
@krzyzanowskim is this still something you would like to pursue?

**Comment by krzyzanowskim** [comment]
@tomerd I don't know, to be honest. It's been a year

**Comment by tomerd** [comment]
@krzyzanowskim I know, sorry about that. let me know if you prefer we close or rebase and we can review / discuss

**Comment by tomerd** [comment]
@krzyzanowskim lets close for now, feel free to resubmit if you decided to pursue again

**Pull request closed without merging**
