### PR TITLE
Use `-print-target-info` instead of a hardcoded triple

### PR DESCRIPTION
**Pull request by neonichu**
This has been present since the initial commit of SwiftPM and may have been needed back then, but isn't necessary anymore today. This brings the added bonus of compiling the manifest for the host architecture instead of a hardcoded x86_64.

### CODE REVIEW

**Comment by neonichu** [comment]
Yep, I wasn't really thinking about the fact that developers can use arbitrary APIs in the manifest.

**Comment by abertelrud** [comment]
Is there a way to keep the deployment target as it is without also having to specify the architecture (leaving it to the compiler to select the host, so SwiftPM doesn't need to reimplement that logic)?  At some point one might want to build for a different architecture than what the host supports, but for the moment, it seems better to specify the deployment target and leave out the architecture.

**Comment by neonichu** [comment]
Yah, that would be nice, but I don't think there's a way to do so. Open for any suggestions. Right now I'm planning to update this to essentially use `-print-target-info`.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
> /Users/buildnode/jenkins/workspace/swift-package-manager-PR-osx-smoke-test/branch-master/swiftpm: error: manifest parse error(s):
11:03:12 <unknown>:0: error: Swift requires a minimum deployment target of OS X 10.9

Looks like something is going wrong in the bootstrapped SwiftPM, we're probably constructing the wrong `-target`.

**Comment by neonichu** [comment]
Ah yes, the triple string was constructed completely wrong 🤦‍♂️

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Linux failure doesn't look related:

```12:21:54 make[1]: Leaving directory '/home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/build/buildbot_incremental/libicu-linux-x86_64/data'
12:21:54 Makefile:153: recipe for target 'install-recursive' failed
12:21:54 make: *** [install-recursive] Error 2```

**Comment by neonichu** [comment]
@swift-ci please smoke test linux

**Pull request merged**
