### PR TITLE
build: repair the Windows build after #3040, #3058

### PR DESCRIPTION
**Pull request by compnerd**
Repair the Windows builds after the breakage introduced by #3040 and 3058.

_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @tomerd

**Comment by tomerd** [comment]
thanks @compnerd, hopefully we can get CI on this soon

the CI testing for https://github.com/apple/swift-package-manager/pull/3063 is nearly done, I suggest we wait with this one until its merged as it needs similar treatment, then we can dont need to run both long smoke tests

**Review by neonichu — APPROVED** [review]

**Comment by compnerd** [comment]
Since #3063 is complete, if you can merge that, Ill update this change.

**Comment by tomerd** [comment]
> Since #3063 is complete, if you can merge that, Ill update this change. 

done

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Pull request merged**
