### PR TITLE
[5.9] Fix Swift SDK bundles not working due to quarantine

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Cherry-picked from https://github.com/apple/swift-package-manager/commit/738f5f34b9a7eb9bf5d9603392c235228abf6aee

When using `swift experimental-sdk install` subcommand with bundle archives or bundles unpacked from archives downloaded manually in the browser, installed executables are quarantined and trigger an error message when used by `swift build`

Steps To Reproduce:
1. Download a destination bundle archive
2. Unpack and install the bundle with `swift experimental-destination install`
3. Confirm that the destination is installed and note its ID with `swift experimental-destination list`
4. Build using the newly installed destination with `swift build --experimental-destination-selector <destination-id>`

Actual result:
Building with this destination triggers an error: "`swift-driver` cannot be opened because the developer cannot be verified."

rdar://107392863

### Modifications:

Running `xattr -r -d -s com.apple.quarantine` on the installed bundle fixes the error. The reason is that bundles downloaded in the browser get a quarantine attribute assigned and unpacking such bundles preserves it.

### CODE REVIEW

**Review by tomerd — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
Converting to a draft as it's blocked by https://github.com/apple/swift-tools-support-core/pull/419 and https://github.com/apple/swift-tools-support-core/pull/412

**Review by neonichu — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
