### PR TITLE
CoreCommands: make `SwiftToolObservabilityHandler` public

### PR DESCRIPTION
**Pull request by MaxDesiatov**
### Motivation:

There are certain commands that can't conform to `protocol SwiftCommand`, as this protocol restricts conforming commands to running only in a directory that has a `Package.swift` manifest. Not all commands need this hard requirement to work. At the same time, such commands would still benefit from initializing `ObservabilityScope` with the same standard `DiagnosticsHandler` that `SwiftToolObservabilityHandler` provides. 

### Modifications:

Moved `SwiftToolObservabilityHandler` and related declarations to a separate file, made `SwiftToolObservabilityHandler` public.

### Result:

`SwiftToolObservabilityHandler` can be initialized and used for creating an `ObservabilityScope` outside of `CoreCommands` module.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Pull request merged**
