### PR TITLE
[5.5] run trie generation thread with QOS set to background

### PR DESCRIPTION
**Pull request by tomerd**
brings #3502 to 5.5

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please test

**Review by yim-lee — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please test linux

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Pull request merged**
