### PR TITLE
[5.0] [Xcodeproj] Add $(inherited) to OTHER_SWIFT_FLAGS

### PR DESCRIPTION
**Pull request by oc243**
<rdar://problem/50768026>
https://bugs.swift.org/browse/SR-10804

(cherry picked from commit 6ebfec3fedd58bfadd672fc4981eea3d7d4bba75)

### CODE REVIEW

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci smoke test

**Comment by weissi** [comment]
@aciidb0mb3r hmm, CI failed with

```
10:43:49 
build-script: error: unrecognized arguments: --cmake-c-launcher --cmake-cxx-launcher /usr/local/bin/sccache
```

which should be unrelated. Seen this before?

**Comment by aciidb0mb3r** [comment]
@shahmishal ?

**Comment by shahmishal** [comment]
We don't currently support PR testing for Swift 5.0 branch on this repository. I will look into adding the support.

**Comment by weissi** [comment]
thank you @shahmishal

**Comment by shahmishal** [comment]
@swift-ci test 5.0 macOS

**Comment by shahmishal** [comment]
@swift-ci test 5.0 macOS

**Comment by weissi** [comment]
@shahmishal any updates here? Because the merge window closes today.

**Comment by weissi** [comment]
@swift-ci test 5.0 macOS

**Comment by shahmishal** [comment]
@swift-ci test 5.0 macOS

**Pull request merged**
