### PR TITLE
Fix `-fmodule-map-file` pointing to non-existent path

### PR DESCRIPTION
**Pull request by neonichu**
We were passing this unconditionally which would break in the case where we weren't generated a module map because an explicit one exists.

rdar://74115399

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Tested locally to verify that this fixes the issue mentioned in #3246

**Review by abertelrud — COMMENTED** [review]
The change LGTM.  Does this have a unit test that should be extended?

**Review by yim-lee — APPROVED** [review]
I verified that this fixes the error I was seeing locally. Need to wait for CI (https://github.com/apple/swift/pull/35202) to see if it fixes the build issue we saw with the source compat suite in https://github.com/apple/swift/pull/35503.

**Comment by neonichu** [comment]
We should probably add a test, I was just trying to have a PR quickly.

**Comment by tomerd** [comment]
```
/Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/Tests/XCBuildSupportTests/PIFBuilderTests.swift:1248: error: -[XCBuildSupportTests.PIFBuilderTests testLibraryTargets] : XCTAssertEqual failed: ("nil") is not equal to ("Optional(["$(inherited)", "-fmodule-map-file=$(OBJROOT)/GeneratedModuleMaps/$(PLATFORM_NAME)/FooLib1.modulemap"])")
```

@neonichu looks like a test needs to be updated?

**Comment by neonichu** [comment]
Looks like the test is correct, but the fix isn't. We still need to impart for Swift targets. The only case where we shouldn't is for clang targets with an explicit module map.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]
code changes seems reasonable, not familiar with the business logic tho

**Review by abertelrud — APPROVED** [review]
Looks good to me, and agree that a test can follow in a separate PR in the interest of quickly fixing this.

**Comment by yim-lee** [comment]
CI passes: https://ci.swift.org/job/swift-PR-toolchain-osx/867/

**Pull request merged**
