### PR TITLE
enhance configuraiton for authentication providers 

### PR DESCRIPTION
**Pull request by tomerd**
motivation: support custom authentican providers, not just netrc

changes:
* reafactor and seperate out the auth data model from the loading/saving mutation utility
* adjust call sites
* add tests

### CODE REVIEW

**Comment by tomerd** [comment]
needs #3670 first

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
ci issue?!

@swift-ci please smoke test

**Comment by tomerd** [comment]
unrelated compiler crash

@swift-ci please smoke test macOS

**Comment by tomerd** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
