### PR TITLE
tools-version APIs refactoring

### PR DESCRIPTION
**Pull request by tomerd**
motivation: make code using tools-version base logic easier to reason about

* rename SwiftVersion::currentVersion -> SwiftVersion::curent
* rename ToolsVersion::curentToolsVersion -> ToolsVersion::curent
* deprecate ToolsVersionLoaderProtocol which had no functional use (redundant abstraction)
* deprecate ToolsVersionLoader and refactor it as ToolsVersionParser, a stateless utility
* rename and refactor the Manifest::path extension to ManifestLoader::findManifest and clarify its expected usage and argument
* move global function rewriteToolsVersionSpecification into a stateless utility ToolsVersionSpecificationWriter::rewriteSpecification
* Simplify and clarify the ManifestLoaderProtocol::load API, focusing it on loading the manifest at a given path
* Create a new API in ManifestLoaderProtocol to load a manifest from a package directory, which includes finding the correct manifest based on the active tools-version. deprecate duplicate code at the call sites that did the same in favor of this centralized function
* adjust workspace tests to not rely on a hack where a missing manifest would default on the current tools-version
* update call sites and tests

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please test package compatibility

**Pull request merged**
