### PR TITLE
Add missing swift build --clean shorthand "-k" & change 'artefact' to US spelling

### PR DESCRIPTION
**Pull request by runhum**

### CODE REVIEW

**Comment by ddunbar** [comment]
I don't think '-k' is a good shorthand here (e.g. It has a completely different meaning to make or Ninja)... I'm also not really sure we need one.

**Comment by runhum** [comment]
I see, I'll just go ahead and close this one then 👍

**Comment by kostiakoval** [comment]
@runhum @ddunbar  then we should remove `-k` flag in `usage` 
```swift 
print("  --clean[=<mode>]               Delete artifacts (build|dist)")
```

**Comment by kostiakoval** [comment]
LGTM. @ddunbar agree to merge it ?

**Pull request merged**
