### PR TITLE
Improve TOML parser

### PR DESCRIPTION
**Pull request by onevcat**
This p-r mainly:

1. Add `Float` support and `e`, `_` support for number item, as well as tests for them.
2. Convert parameter of `consumeIf` to `@autoclosure` for better readability.
3. Fix a document mistake on commenting `]` to  `[`.
4. Some indent fix for to align code and comment better.

### CODE REVIEW

**Comment by mxcl** [comment]
Looks good to me /cc @ddunbar

**Comment by ddunbar** [comment]
This is an awesome PR, thanks @onevcat! I would rather not take the @autoclosure change, but aside from that LGTM. Can you separate that commit out (and into a separate PR, if you want to continue discussing it or go the approach I propose) and rebase this one?

**Comment by onevcat** [comment]
Hi, @ddunbar 

Thanks for the reviewing. I don't think `@autoclosure` is any magic at all since it is introduced the first day of Swift published in WWDC last year, as well as widely used in the standard library. But I admit that you are right here. Original implementation is more flexible if we really need execute a block, otherwise we could only use a `BOOL` instead of a closure.

I am closing it and will open another p-r for the other parts.

Thanks.

**Comment by onevcat** [comment]
@ddunbar 
I opened a new pull request here: #65

**Comment by ddunbar** [comment]
Yeah, I meant "magic" in the sense of obvious to reader of the code.

What did you think of my suggestion about making a consumeIf() method which checks for a particular type?

**Pull request closed without merging**
