### PR TITLE
Modified some functions to computed properties for API style

### PR DESCRIPTION
**Pull request by jaesung-0o0**
I modified some functions to computed properties for better API design.

### Motivation:

These methods returns a state or a simple value rather than performing an action such as `isDarwin()`, `isApple()` or `withoutVersion`
I modified some methods to the computed properties for better API design.
However, these changes depend on your style.

### Modifications:

**DispatchTimeInterval**

| As-is | To-be |
| --- | --- |
| timeInterval() | timeInterval |
| nanoseconds() | nanoseconds |
| milliseconds() | milliseconds |
| seconds() | seconds |

**Tripple extensions**
| As-is | To-be |
| --- | --- |
| isApple() | isApple |
| isAndroid() | isAndroid |
| isDarwin() | isDarwin |
| isLinux() | isLinux |
| isWindows() | isWindows |
| isWASI() | isWASI |
| isOpenBSD() | isOpenBSD |
| withoutVersion() | withoutVersion |

### CODE REVIEW

**Comment by rauhul** [comment]
I would expect computed properties to behave near identically to simple functions, with the only difference coming from changes in inlining. Have you measured any performance improvement from this change?

**Comment by jaesung-0o0** [comment]
> I would expect computed properties to behave near identically to simple functions, with the only difference coming from changes in inlining. Have you measured any performance improvement from this change?

Oh you're right. There's technically no difference in performance in this PR. My initial description had incorrect information on the modification.

The modification is related to the API style, not the performance.

Some methods return a state or a simple value rather than performing an action. Similar to `isEmpty` in collection types, using computed properties feels like a better API style.

**Comment by tomerd** [comment]
personally I prefer the computed property style for these

cc @neonichu

**Comment by rauhul** [comment]
I do as well, but I would recommend we figure out a better story for where to put a swift-triple package/library instead of maintaining a duplicate codebase with the swift-driver before making the triple changes (imo)

**Comment by MaxDesiatov** [comment]
Additionally, I don't think that changing a function to a property with the same name is source-compatible, and that would break users of libSwiftPM if not done in a graceful manner.

**Comment by jaesung-0o0** [comment]
Even if the previous are not officially offered, since they are public, 
is it unacceptable? or requires more discussion?

**Pull request closed without merging**
