### PR TITLE
Bring back "Refactor `Commands` module"

### PR DESCRIPTION
**Pull request by neonichu**
This reverts commit cf19c646cc667876ca0f41c3544a602ed4437651 and restores the `--build-path` option. It also switches the `bootstrap` script back to using it so that we have an easy check that the option is still present.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please test package compatibility

**Comment by neonichu** [comment]
Doing a toolchain build and package compatibility run since we needed to revert this the first time.

**Comment by tomerd** [comment]
why not use `--scratch-path` instead?

**Comment by neonichu** [comment]
> why not use --scratch-path instead?

Don't think we should block this change on removing `--build-path`, it was just an unrelated cleanup that I snuck in here. It can happen as a separate PR instead.

**Comment by neonichu** [comment]
Looks like there's `UPASS: rdar://101685791, swift-protobuf-plugin-example, 5.0, 85bec0, Swift Package` which is probably because we merged https://github.com/apple/swift-package-manager/pull/5855

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Looks like the toolchain build passed, so I think this should be ready to merge, but I'll double-check tomorrow.

**Comment by MaxDesiatov** [comment]
Ah, sorry about the conflict! 🙈

**Comment by neonichu** [comment]
Rebased.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
Toolchain build passed as well, merging...

**Pull request merged**
