### PR TITLE
Prefix public stdlib extensions with spm_

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Extensions are very easily leaked into the clients. Since Swift doesn't
have the concept of private imports at this point, it is not safe to
have public stdlib extensions as it can easily cause collisions in the
downstream clients even though they might not directly depend on
SwiftPM. This patch prefixes most of the public stdlib extensions in the
SwiftPM codebase. All future additions should also have the prefix.

About using "spm" as the prefix:
While it makes sense to use "swiftpm" for marketing purpooses, it is way
too long to be used as a prefix. The max prefix length that I've seen is 4.

<rdar://problem/45200636> SwiftPM should not be exporting Swift stdlib additions

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by SDGGiesbrecht** [comment]
> Extensions are very easily leaked into the clients. Since Swift doesn't
have the concept of private imports at this point, it is not safe to
have public stdlib extensions as it can easily cause collisions in the
downstream clients even though they might not directly depend on
SwiftPM. This patch prefixes most of the public stdlib extensions in the
SwiftPM codebase. All future additions should also have the prefix.

Are you sure this was necessary? It just looks like extra clutter to me. In the event that methods *do* clash, it is fully within the client’s power to disambiguate like this:

```swift
// FileA.swift
import SwiftPM
extension StandardLibrary {
    internal func makeSwiftPMDoSomething() {
        doSomething()
    }
}
```
```swift
// FileB.swift
import OtherDependency
extension StandardLibrary {
    internal func makeOtherDependencyDoSomething() {
        doSomething()
    }
}
```
```swift
// FileC.swift
extension StandardLibrary {
    func relyOnBoth() {
        makeSwiftPMDoSomething()
        makeOtherDependencyDoSomething()
    }
}
```

> Swift doesn't have the concept of private imports at this point

Aren’t *all* imports private? As in, they are only available in the same file? (Barring `@_exported` of course.)

**Pull request merged**
