### PR TITLE
Fix a spelling mistake in the source files generated for a new package

### PR DESCRIPTION
**Pull request by abertelrud**
### Motivation:

New packages shouldn't have spelling mistakes in source code comments.

### Modifications:

Change the text in a string emitted as new source code.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
cc @bitjammer

**Review by tomerd — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]
Thanks!

**Comment by abertelrud** [comment]
@swift-ci please test linux

**Comment by abertelrud** [comment]
@swift-ci please smoke test linux

**Comment by abertelrud** [comment]
Linux self hosted failure looked like infrastructure, rerunning (is there a way to rerun just the self hosted test? couldn't find anything on https://github.com/apple/swift/blob/main/docs/ContinuousIntegration.md)

**Comment by tomerd** [comment]
> is there a way to rerun just the self hosted test? 

not that I know

**Pull request merged**
