### PR TITLE
Add release configuration

### PR DESCRIPTION
**Pull request by AquaGeek**

### CODE REVIEW

**Comment by mxcl** [comment]
Great stuff.

Probably I should try to add some tests for the project generation before merging this however.

**Comment by mxcl** [comment]
If you fix the merge we can CI this and get it merged. I added a preliminary regression test yesterday so now I'm happy to get this merged.

**Comment by AquaGeek** [comment]
Rebased

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
The failure is correct.

**Comment by AquaGeek** [comment]
Fixed the test. Sorry about that.

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
np, I added the test *after* your PR. Deliberately because I wanted something to validate that nothing had broken. Sorry back! :)

**Pull request merged**
