### PR TITLE
Use manifest compiler path for PackageDescription libraries

### PR DESCRIPTION
**Pull request by krzyzanowskim**
Since `compiler` and `manifest` toolchains may be different, use `manifest` libraries by default (unless overwritten with `SWIFTPM_PD_LIBS`)

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Good catch!

**Comment by aciidb0mb3r** [comment]
Is this difficult to unit test? We can probably construct a fake toolchain and override `SWIFT_EXEC_MANIFEST` to test this, right?

**Comment by krzyzanowskim** [comment]
In the meantime https://github.com/apple/swift-package-manager/pull/2205 made it worse. Can't we fix it instead?

**Comment by SDGGiesbrecht** [comment]
I [wrote in more detail](https://github.com/apple/swift-package-manager/pull/2201#issuecomment-508950501) in answer to your question over on #2201, but your merge of `master` looks right to me.

**Comment by krzyzanowskim** [comment]
@SDGGiesbrecht thanks! hopefully, this fix will get in soon.

**Comment by aciidb0mb3r** [comment]
This looks good to me. Thanks!

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by krzyzanowskim** [comment]
Closing due to no response from maintainers. No interest in the fix.

**Pull request closed without merging**
