### PR TITLE
[ManifestLoader] Restrict the sandbox profile

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Remove (allow mach*) and import system.sb

-- <rdar://problem/31213658> Further restrict SwiftPM's sandbox

### CODE REVIEW

**Comment by ddunbar** [comment]
This can land right?

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test OS X

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test linux

**Pull request merged**
