### PR TITLE
Migrate entirely to new color-diagnostics flag

### PR DESCRIPTION
**Pull request by keith**
(cherry picked from commit da393401075397d16e7be7504d7bbf8d0068272e)

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
```
/Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/swiftpm/Sources/Build/BuildPlan.swift:498:12: error: static member 'isTTY' cannot be used on instance of type 'BuildParameters'
16:16:23         if buildParameters.isTTY {
16:16:23            ^~~~~~~~~~~~~~~
16:16:23            BuildParameters.

```

**Comment by keith** [comment]
Sorry fixed, I assumed the API changed since everything around it has the other name with the other case, but I see now this is a static method

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Pull request merged**
