### PR TITLE
Rely on autolinking for SQLite on macOS in TSC

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
> /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-master/swift-corelibs-libdispatch/src/swift/Dispatch.swift:13:19: error: no such module 'Dispatch'

**Comment by neonichu** [comment]
@swift-ci please smoke test linux

**Comment by neonichu** [comment]
@swift-ci please smoke test linux

**Comment by abertelrud** [comment]
I think we've seen that Dispatch thing as a transient error in the past, and the same (non-vendored) change seems to have built successfully in the original tools-support-core repository.  We shouldn't merge with errors, but I suspect that it isn't actually fallout from this one.

**Comment by neonichu** [comment]
TSC's own CI actually doesn't test the cmake build, this was my main reason to make the vendored change immediately as well. I'll follow up with Mishal as well to get the cmake build into TSC's CI.

**Pull request merged**
