### PR TITLE
Fix and simplify Range.constrain(:)

### PR DESCRIPTION
**Pull request by an0**
If self is completely within constraint it should return self but now it returns nil.

### CODE REVIEW

**Comment by mxcl** [comment]
Can we add a test to prevent this regressing in future?

**Comment by an0** [comment]
@mxcl I've added some tests but they cause conflicts since Tests/dep/GetTests.swift has been updated in upstream. Can you help resolve it or should I resubmit a new PR based on the current upstream code?

**Comment by mxcl** [comment]
I can resolve it.

**Comment by an0** [comment]
@mxcl thanks:)

**Comment by mxcl** [comment]
Merged: https://github.com/apple/swift-package-manager/commit/df7736e3962bfe183451d52b9b865b92f4f9ab26

**Pull request closed without merging**
