### PR TITLE
Revert "Support macros when cross-compiling"

### PR DESCRIPTION
**Pull request by DougGregor**
Reverts apple/swift-package-manager#7118. It is causing the swift-syntax Examples to fail to build. See https://ci.swift.org/job/oss-swift-incremental-RA-macos/4247/

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@MaxDesiatov the swift-syntax "Examples" package is failing to build with this error:

/home/build-user/swift-syntax/Examples/Tests/MacroExamples/Implementation/ComplexMacros/DictionaryIndirectionMacroTests.swift:13:8: error: no such module 'MacroExamplesImplementation'
import MacroExamplesImplementation
       ^
note: module 'MacroExamplesImplementation' is a macro, and cannot be imported by tests and other targets
error: fatalError
Error: Command failed with non-zero exit code 1:

**Comment by MaxDesiatov** [comment]
I think I can come up with a proper fix for this quickly and we can avoid revert this 🙏

**Comment by MaxDesiatov** [comment]
I've have a fix that doesn't require a revert for it here https://github.com/apple/swift-package-manager/pull/7350

**Comment by MaxDesiatov** [comment]
That error is no longer reproducible for me locally when running SwiftPM on the `swift-syntax/Examples` packager, and also with the full `utils/build-script` invocation identical to the one used on CI. Maybe there's something cached there? I've triggered clean builds on an impacted `apple/swift-syntax` PR.

**Comment by MaxDesiatov** [comment]
As this accumulated conflicts, I'm closing it in favor of a bigger revert in https://github.com/apple/swift-package-manager/pull/7349

**Pull request closed without merging**
