### PR TITLE
Update current version to 5.8

### PR DESCRIPTION
**Pull request by elsh**
Resolves rdar://102284175

### CODE REVIEW

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by neonichu** [comment]
Looks like `disambiguateByProductIDs` ends up breaking some tests, maybe we should separate that out from the general PR?

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by neonichu** [comment]
@elsh I think we also need to change some of the new tests back to use `.vNext` for now.

**Review by tomerd — APPROVED** [review]

**Pull request merged**
