### PR TITLE
Move down `walk()` and friends from `Utility` to `Basics`

### PR DESCRIPTION
**Pull request by abertelrud**
Move down `walk()` and friends from `Utility` to `Basics` and adjust unit tests.  Comment cleanup and name normalization to follow in separate checkins, for easier diffability.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
Linux failure is real, will debug on Ubuntu and fix.

**Comment by abertelrud** [comment]
@swift-ci please test linux

**Comment by abertelrud** [comment]
Linux test didn't actually fail, instead it was cancelled.  Restarting.  A local Linux test on 15.10 succeeds.

**Comment by abertelrud** [comment]
@swift-ci please test linux

**Comment by aciidb0mb3r** [comment]
@swift-ci please test os x

**Comment by abertelrud** [comment]
macOS failure is still unrelated.

**Comment by ddunbar** [comment]
LGTM, do you want me to test and merge on TOT?

**Comment by abertelrud** [comment]
No, I tested locally.  Thanks.

**Pull request merged**
