### PR TITLE
Fix `availableCommandPlugins()`

### PR DESCRIPTION
**Pull request by neonichu**
According to the [original proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0332-swiftpm-command-plugins.md#discovering-command-plugins), only plugin products from direct dependencies should be included here. The proposal doesn't mention root packages directly, but I think it makes sense to include any plugin targets from them, regardless of whether they're exposed via a product or not.

In addition, this method was just returning all plugin targets, we should limit it to those that define a command plugin, as the name suggests.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
add test?

**Comment by tomerd** [comment]
maybe we can expand an existing test

**Comment by neonichu** [comment]
As far as I can see, in terms of existing tests we have `testCommandPlugin()` which already seems too big and is of course also an integration test. Extending that with a larger package graph doesn't seem like a good idea to me. 

I really think we should make this code testable (also the code of other commands) and then create targeted tests which are maintainable and fast.

**Comment by neonichu** [comment]
Going to merge this as-is as discussed offline, https://github.com/apple/swift-package-manager/pull/6827 will stay open to improve test infra and add test coverage for `plugin --list`.

**Pull request merged**
