### PR TITLE
Updated netrc authentication feature with code review feedback 

### PR DESCRIPTION
**Pull request by sstadelman**

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by sstadelman** [comment]
looks like failures are unrelated.

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by sstadelman** [comment]
@tomerd there seems to be a CMAKE configuration issue: 

```
02:32:42 -- Configuring done
02:32:42 You have changed variables that require your cache to be deleted.
02:32:42 Configure will be re-run and you may have to reset some variables.
02:32:42 The following variables have changed:
02:32:42 CMAKE_CXX_COMPILER= /Users/buildnode/jenkins/workspace/swift-package-manager-PR-osx/buildbot_incremental/llvm-macosx-x86_64/bin/clang++
02:32:42 
02:32:43 CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
02:32:43 -- Configuring incomplete, errors occurred!
02:32:43 See also "/Users/buildnode/jenkins/workspace/swift-package-manager-PR-osx/buildbot_incremental/llbuild-macosx-x86_64/CMakeFiles/CMakeOutput.log".
02:32:43 Building the standard library for: swift-stdlib-macosx-x86_64
02:32:43 Running Swift tests for: check-swift-validation-macosx-x86_64
02:32:43 ERROR: command terminated with a non-zero exit status 1, aborting
02:32:43 
02:32:43 ERROR: command terminated with a non-zero exit status 1, aborting
```

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Thanks a lot for these changes, @sstadelman

**Review by neonichu — APPROVED** [review]

**Comment by sstadelman** [comment]
Hi Boris, can I keep this in your queue?

**Comment by neonichu** [comment]
I think we can merge this, thanks @sstadelman

**Comment by sstadelman** [comment]
Thanks!! 🍻

**Pull request merged**
