### PR TITLE
[TSCBasic] Improve SynchronizedQueue by using a linked-list storage

### PR DESCRIPTION
**Pull request by YuAo**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Thanks for PR! 

@YuAo do you think you could do some performance measurements to check if and what kind of performance wins this brings? If you're on a mac, you can open SwiftPM as a package in Xcode and use the perf scheme: https://github.com/apple/swift-package-manager/blob/master/Documentation/Development.md#developing-using-xcode

**Comment by YuAo** [comment]
Sure, @aciidb0mb3r Looks like there's no performance test for `SynchronizedQueue`. So I added one to the TSCBasicPerformanceTests.

I pulled the array backed `SynchronizedQueue` code and run some tests side by side with the linked list implementation. Here's the result:

Screen Shot 2020-03-19 at 10 06 26

With 100 elements: array wins, linked list is about 14% slower. 🐌 
With 1000 elements: linked list wins, about 20% faster. 🐰 
With 10000 elements: linked list wins, about 250% faster. 🚀

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
We're holding this PR until the Swift 5.3 branch gets created.

**Pull request merged**
