### PR TITLE
[Collections] Signing (part 2): signed collections

### PR DESCRIPTION
**Pull request by yim-lee**
This is part 2 of a series of PRs to support package collection signing.

[Part 1](#3238)

Modifications:

- Add support for signing with EC and RSA keys
- Add `Signature`, which is similar to JWS
- Introduce `CertificatePolicy` protocol (more on this in part 3)
- `PackageCollectionsSigning` - given a package collection, certificate and its private key, generate a "signed" collection; and reverse that process to validate collection signature.

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
```
13:17:30 Test Suite 'Selected tests' started at 2021-02-06 21:16:17.512
13:17:30 Test Suite 'SignatureTests' started at 2021-02-06 21:16:17.516
13:17:30 Test Case 'SignatureTests.test_RS256_generateAndValidate_happyCase' started at 2021-02-06 21:16:17.516
13:17:30 
/home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-main/swiftpm/Tests/PackageCollectionsSigningTests/SignatureTests.swift:20: error: SignatureTests.test_RS256_generateAndValidate_happyCase : failed - bioConversionFailure
13:17:30 Test Case 'SignatureTests.test_RS256_generateAndValidate_happyCase' failed (0.331 seconds)
```

@yim-lee not sure why it failed on the smoked-test only

**Comment by yim-lee** [comment]
@swift-ci please smoke test

>  @yim-lee not sure why it failed on the smoked-test only

Yeah not sure. Trying to figure out.

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
I don't see which changes in this PR would cause the CI problems. Will redo it.

**Pull request closed without merging**
