### PR TITLE
Remove myself from CODEOWNERS

### PR DESCRIPTION
**Pull request by neonichu**
Seems like a good time to ship this since I am wrapping up my last few PRs and this way I don't get added as reviewer to new PRs which will set the correct expectation that I won't be doing any future code reviews.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
The Windows CI node has some objections...

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
