### PR TITLE
[5.9] improve diagnostics when registry configuration is broken

### PR DESCRIPTION
**Pull request by tomerd**
5.9 cherry-pick of #6331

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
@swift-ci smoke test windows

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci smoke test macOS

**Comment by tomerd** [comment]
@swift-ci smoke test macOS

**Comment by tomerd** [comment]
@swift-ci smoke test macOS

**Review by abertelrud — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci smoke test macOS

**Pull request merged**
