### PR TITLE
 Enable use of product ID to distinguish duplicate product names

### PR DESCRIPTION
**Pull request by elsh**
Enable it for 5.8

### CODE REVIEW

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Pull request merged**
