### PR TITLE
Enable code coverage

### PR DESCRIPTION
**Pull request by AquaGeek**
Is this what the TODO was for? Seems too easy to be true…

### CODE REVIEW

**Comment by mxcl** [comment]
Yes, probably. I added this myself but then the swift compiler crashed while creating the binaries. Not crashing is kind of key.

**Comment by AquaGeek** [comment]
Ha. Yeah, not crashing is a good thing. This works for me with the 03/01 snapshot toolchain.

**Comment by mxcl** [comment]
When trying to run the tests for SwiftPM with code coverage enabled I get:

```
Assertion failed: (FuncNamePtr && "No function name pointer for counter update"), function emitBuiltinCall, file /Users/mxcl/src/swift/lib/IRGen/GenFunc.cpp, line 1820.
0  swiftc                   0x0000000109ac309b llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 43
1  swiftc                   0x0000000109ac22c6 llvm::sys::RunSignalHandlers() + 70
2  swiftc                   0x0000000109ac38f1 SignalHandler(int) + 641
3  libsystem_platform.dylib 0x00007fff84a0f52a _sigtramp + 26
4  swiftc                   0x000000010a55d2b1 FirstTarget + 72569
5  swiftc                   0x0000000109ac35c6 abort + 22
6  swiftc                   0x0000000109ac35a1 __assert_rtn + 81
7  swiftc                   0x0000000106ec08b7 swift::irgen::emitBuiltinCall(swift::irgen::IRGenFunction&, swift::Identifier, swift::SILType, swift::irgen::Explosion&, swift::irgen::Explosion&, llvm::ArrayRef<swift::Substitution>) + 28583
8  swiftc                   0x0000000106f6ee74 swift::SILVisitor<(anonymous namespace)::IRGenSILFunction, void>::visit(swift::ValueBase*) + 24388
9  swiftc                   0x0000000106f654ab (anonymous namespace)::IRGenSILFunction::emitSILFunction() + 9691
10 swiftc                   0x0000000106f62aac swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 1164
11 swiftc                   0x0000000106e7636c swift::irgen::IRGenModuleDispatcher::emitGlobalTopLevel() + 428
12 swiftc                   0x0000000106f442f1 performIRGeneration(swift::IRGenOptions&, swift::ModuleDecl*, swift::SILModule*, llvm::StringRef, llvm::LLVMContext&, swift::SourceFile*, unsigned int) + 1137
13 swiftc                   0x0000000106f448c5 swift::performIRGeneration(swift::IRGenOptions&, swift::SourceFile&, swift::SILModule*, llvm::StringRef, llvm::LLVMContext&, unsigned int) + 69
14 swiftc                   0x0000000106dc9bc8 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 16216
15 swiftc                   0x0000000106dc4e3f frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2879
16 swiftc                   0x0000000106dbffad main + 2637
17 libdyld.dylib            0x00007fff93b6f5ad start + 1
Stack dump:
0.	Program arguments: /Users/mxcl/Library/Developer/Toolchains/swift-mxcl.xctoolchain/usr/bin/swiftc -frontend -c /Users/mxcl/src/swiftpm/Sources/PackageDescription/Package.swift /Users/mxcl/src/swiftpm/Sources/PackageDescription/Product.swift /Users/mxcl/src/swiftpm/Sources/PackageDescription/Target.swift /Users/mxcl/src/swiftpm/Sources/PackageDescription/TOMLConvertible.swift /Users/mxcl/src/swiftpm/Sources/PackageDescription/Version+StringLiteralConvertible.swift -primary-file /Users/mxcl/src/swiftpm/Sources/PackageDescription/Version.swift -target x86_64-apple-macosx10.10 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I /dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Products/Debug -F /dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Products/Debug -enable-testing -g -module-cache-path /dd/ModuleCache -profile-generate -profile-coverage-mapping -D Xcode -serialize-debugging-options -Xcc -I/dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Intermediates/SwiftPM.build/Debug/PackageDescription.build/swift-overrides.hmap -Xcc -I/dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Intermediates/SwiftPM.build/Debug/PackageDescription.build/libPackageDescription.hmap -Xcc -I/dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Products/Debug/include -Xcc -I/dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Intermediates/SwiftPM.build/Debug/PackageDescription.build/DerivedSources/x86_64 -Xcc -I/dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Intermediates/SwiftPM.build/Debug/PackageDescription.build/DerivedSources -Xcc -working-directory/Users/mxcl/src/swiftpm -emit-module-doc-path /dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Intermediates/SwiftPM.build/Debug/PackageDescription.build/Objects-normal/x86_64/Version~partial.swiftdoc -Onone -module-name PackageDescription -emit-module-path /dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Intermediates/SwiftPM.build/Debug/PackageDescription.build/Objects-normal/x86_64/Version~partial.swiftmodule -serialize-diagnostics-path /dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Intermediates/SwiftPM.build/Debug/PackageDescription.build/Objects-normal/x86_64/Version.dia -emit-dependencies-path /dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Intermediates/SwiftPM.build/Debug/PackageDescription.build/Objects-normal/x86_64/Version.d -emit-reference-dependencies-path /dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Intermediates/SwiftPM.build/Debug/PackageDescription.build/Objects-normal/x86_64/Version.swiftdeps -o /dd/SwiftPM-gmutbftysditrhbbxwaujshbqwfn/Build/Intermediates/CodeCoverage/Intermediates/SwiftPM.build/Debug/PackageDescription.build/Objects-normal/x86_64/Version.o 
1.	While emitting IR SIL function @_TFV18PackageDescription7Versiong5majorSi for getter for major at /Users/mxcl/src/swiftpm/Sources/PackageDescription/Version.swift:15:17
```

If this is just a bug in Swift IRGen then we can merge (and I'll report the bug), but I wondered if we are just doing it wrong.

**Comment by mxcl** [comment]
Can you confirm that you can run some project and not have it crash in compile?

**Comment by AquaGeek** [comment]
When you say run the tests, do you mean in Xcode?

For reference, here's the steps I followed when creating this patch:
1. Created a sample project via `swift-build --init library`
2. Added some basic logic and tests
3. Created an Xcode project via `swift-build --generate-xcodeproj`
4. Opened the Xcode project, ran the tests, and ensured coverage works

**Comment by mxcl** [comment]
> 4. Opened the Xcode project, ran the tests, and ensured coverage works

Yes, this is what I meant. OK I'll look into why it crashes for SwiftPM itself. Bug in the toolchain no doubt.

Once I have a handle we can merge in some form.

**Comment by ddunbar** [comment]
Is there a bug for that? Any compiler crash is a bug, even if we are "doing it wrong"...

**Comment by mxcl** [comment]
Not yet, but I'll file it after my current tasks.

**Comment by mxcl** [comment]
Sadly still crashes. But I am assured there are tickets to fix this stuff.

**Comment by mxcl** [comment]
Now the problem is that code coverage won’t work with a downloadable toolchain… :-{

**Comment by ddunbar** [comment]
I'm not aware of any outstanding bugs on in this area, can you dig up what is blocking this and make sure whoever owns it is aware?

**Comment by mxcl** [comment]
It's radar’d and assigned.

**Comment by paulofaria** [comment]
If I understand correctly this is being blocked by an external dependency? Any updates?

**Comment by S0215** [comment]
Otlichno

**Comment by ddunbar** [comment]
I believe we can enable this now that Xcode 8 is available.

**Comment by AquaGeek** [comment]
I got an email that the Ubuntu build is failing because of this.

**Pull request merged**
