### PR TITLE
Remove non-inclusive language

### PR DESCRIPTION
**Pull request by neonichu**
rdar://problem/69396992

### CODE REVIEW

**Comment by neonichu** [comment]
https://github.com/apple/swift-tools-support-core/pull/134
@swift-ci please smoke test

**Comment by neonichu** [comment]
I guess the self hosted jobs won't actually use changes from the cross-repo PR.

**Comment by neonichu** [comment]
apple/swift-tools-support-core#134
@swift-ci please smoke test

**Comment by neonichu** [comment]
apple/swift-tools-support-core#134
@swift-ci please smoke test

**Comment by neonichu** [comment]
apple/swift-tools-support-core#134
@swift-ci please smoke test

**Comment by neonichu** [comment]
apple/swift-tools-support-core#134
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
Seems like the latest failure was swift driver related, let's re-run again.

**Comment by neonichu** [comment]
apple/swift-tools-support-core#134
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Pull request merged**
