### PR TITLE
[5.6] Adjust command plugin implementation to match SE-0332 amendments

### PR DESCRIPTION
**Pull request by abertelrud**
This is a cherry-pick of the #3898 commits to the 5.6 branch.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
Putting in Draft, this is missing a commit.

**Comment by abertelrud** [comment]
Restored the missing commit and opened a mainline PR for the same at #3946

**Comment by abertelrud** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Pull request merged**
