### PR TITLE
[Workspace] Elimiate creating symlinks in Packages/

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This is no longer needed.

### CODE REVIEW

**Comment by ddunbar** [comment]
Are you sure we shouldn't keep this around for a bit as we transition over, in case users have other things expecting the packages in those locations? It would allow us to differentiate between a dependency on that and other problems with the new implementation.

**Comment by aciidb0mb3r** [comment]
I can email swift-build-dev asking if anyone is using this directory directly, otherwise I don't think we should keep it unless needed. Also, edit and this can't coexist unless we want to chose some other directory for editable packages

**Comment by ddunbar** [comment]
Ok, I'm fine ditching it... esp since it seems like this makes sense for editable packages.

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Pull request merged**
