### PR TITLE
Rename nested Package.swift files

### PR DESCRIPTION
**Pull request by keith**
These files break sourcekit-lsp since it expects any nested
Package.swift files to define packages.

### CODE REVIEW

**Comment by keith** [comment]
naming is hard, happy to change to whatever!

**Comment by keith** [comment]
I imagine sourcekit-lsp could ignore invalid package.swift files, but that might cause more trouble than it fixes since it might hide real issues

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
> I imagine sourcekit-lsp could ignore invalid package.swift files, but that might cause more trouble than it fixes since it might hide real issues

It could do something simple like check for `import PackageDescription` in the file, if that's not present, it is not going to be a manifest.

**Comment by tomerd** [comment]
@Keith probably need to update the CMake setup as well, which is what the smoke tests use

**Comment by keith** [comment]
yea thanks, currently debugging why the build-with-cmake script doesn't work

**Comment by keith** [comment]
@swift-ci smoke test

**Comment by keith** [comment]
probably builds now, but if you'd prefer the sourcekit-lsp fix we don't have to merge this one, although it would be helpful in the meantime

**Comment by neonichu** [comment]
Yah, I think we can merge this to avoid the issue independently of making a sourcekit-lsp change.

**Comment by tomerd** [comment]
thanks @keith

**Comment by keith** [comment]
Thanks!

**Pull request merged**
