### PR TITLE
[Xcodeproj] Quote target names in case they contain spaces

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by kostiakoval** [comment]
LGTM

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
Thanks for fixing this, @aciidb0mb3r.  To be robust for paths that contain single quotes and backslashes, each of these strings should ideally be passed through a quote-for-needed method.  But because the quoting rules are different for plists than for shells, this will do for now.  Eventually the Xcode project generation logic should have a quoter that all strings go through, but the change in this pull request is a definite improvement.

**Comment by aciidb0mb3r** [comment]
is there any performance disadvantage of quoting when it's not needed?

**Comment by abertelrud** [comment]
No, in the way it's done here, there's isn't any noticeable performance impact.  If you were to have an API that returned a string like this: `return "'" + name + "'"` then it would most likely have had some cost (though the optimizer can do a lot if it can know that it has seen all the call sites).

I didn't actually mean that you should check if quotes are needed and only quote the string in that case (I realize that the term "quote-if-needed" in my previous message was misleading).  What I implied, but didn't explain properly, is that whenever you quote a string, some characters in it might need to be escaped.  In this case, `'` and `\` characters would need to be escaped, or names containing those character won't work.  That's what I meant, that those characters need to be escaped when you put quotes around the string.

**Comment by aciidb0mb3r** [comment]
ah that makes sense! cool

**Pull request merged**
