### PR TITLE
rename enums to lowerCamelCase

### PR DESCRIPTION
**Pull request by kostiakoval**
Follow the Swift 3.0 naming convention for enums.
cjduzt3xaaa17f4

Change: 
- Make all enum cases lowercase.
- Add `Target` method to `Target.Dependency` because it's used in Manifest files, we don't make  breaking changes.
```swift 
public static func Target(name: String) -> Dependency {
  return .target(name: name)
}
```
- Left  `case Init(InitMode)` as UpperCase. It has conflicts with `init` method 
- use \`\`  for  case \`static\`

### CODE REVIEW

**Comment by ddunbar** [comment]
Thanks!

I hit a couple build errors though:
```
swiftpm/Package.swift:109:56: error: type 'ProductType' has no member 'Library'
let dylib = Product(name: "PackageDescription", type: .Library(.Dynamic), modules: "PackageDescription")
                                                       ^~~~~~~
```

We shouldn't "just rename" PackageDescription yet, this will break packages. Let's put that in a separate PR and discuss how we can mitigate the impact on users.

Another failure I hit:
```
swiftpm/Sources/Utility/File.swift:29:23: error: type 'Error' has no member 'CouldNotCreateFile'                                                                                                 
                throw Error.CouldNotCreateFile(path: path)                                                                                                                                                                          
                      ^~~~~ ~~~~~~~~~~~~~~~~~~   
```

**Comment by kostiakoval** [comment]
@dabrahams 👍. I've reverted changes in `PackageDescription` and fixed these 2 issue that you mentioned.

**Comment by gribozavr** [comment]
@ddunbar You can use this pattern:

```
enum TheEnum {
  case foo

  @available(*, deprecated, renamed: "foo")
  static var Foo: TheEnum { return .foo }
}

func acceptsTheEnum(_: TheEnum) {}
acceptsTheEnum(.foo)
acceptsTheEnum(.Foo)
```

**Comment by ddunbar** [comment]
Thanks @gribozavr!

**Pull request merged**
