### PR TITLE
trimmed whitespace

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
Thanks for the PR, @adamnemecek! While this is definitely more correct for this project, I don't think we should merge this patch. It makes the `git author` for line diffs difficult to follow, which can be really useful when trying to understand when and why certain code change was added or changed. We could, however, try to get some automation in place that will allow us to catch issues like this in the future commits. Thanks!

**Comment by jakepetroules** [comment]
> It makes the git author for line diffs difficult to follow

That's not true, there is `git blame -w` for this.

**Comment by hartbit** [comment]
@aciidb0mb3r Following @jakepetroules's comment, should we merge this once the merge conflicts are resolved, or should it be closed?

**Comment by aciidb0mb3r** [comment]
I think we can take this after resolving conflicts but we should also need to add a linter-like test to ensure this doesn't break again. I'll close this for now but feel free to introduce a test that checks for whitespaces (probably belongs in the bootstrap script).

**Pull request closed without merging**
