### PR TITLE
reduce use of byte string

### PR DESCRIPTION
**Pull request by tomerd**
motivation: prepare to deprecating byte string

changes:
* use strings when writing files
* improve file writing utility to create directory first (add TSC inconsistency)
* update call sites, mostly in tests

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
@swift-ci moke test

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by MaxDesiatov — APPROVED** [review]
This is great, thanks! I was going to do the same, but you beat me to it 🙂

**Comment by tomerd** [comment]
@swift-ci smoke test windows

**Pull request merged**
