### PR TITLE
Remove #if to avoid a Linux compiler bug which has been resolved

### PR DESCRIPTION
**Pull request by hartbit**

### CODE REVIEW

**Comment by hartbit** [comment]
@swift-ci please smoke test

**Comment by hartbit** [comment]
@swift-ci please smoke test

**Comment by hartbit** [comment]
@aciidb0mb3r Can't reproduce the test failure on Docker. Let me know if you have an idea.

**Comment by aciidb0mb3r** [comment]
Looks like Linux is fine but a bunch of macOS tests received a signal?

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test macOS

**Pull request closed without merging**
