### PR TITLE
Crypto API changes

### PR DESCRIPTION
**Pull request by compnerd**
_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @yim-lee

I would like to know what you think is reasonable here @yim-lee.  I think that adopting the API early is not too terrible, we will simply need to add some casting to go between the typed and untyped pointer.  This would be something that we could easily undo when we update swift-crypto.

**Comment by yim-lee** [comment]
Thanks for staying on top this @compnerd. I am testing with swift-crypto 2.0.0-beta.2 locally to make sure these are all the adjustments we'd need.

> I think that adopting the API early is not too terrible

I agree. I think the less code changes we'd have to make when we actually switch to 2.x, the better. Or put it differently, the sooner we can establish the fact that the code will work with swift-crypto 2.x, the better. 

For reference, we are tracking work associated with swift-crypto 2.x upgrade with rdar://82934196.

**Comment by yim-lee** [comment]
What do people think of https://github.com/apple/swift-package-manager/compare/main...yim-lee:crypto-2.x-prep-1?expand=1, specifically https://github.com/apple/swift-package-manager/commit/006e6edb2e28dc18d0555a4edf13cb2a0c10f960?

**Comment by compnerd** [comment]
FWIW, the changes are sufficient to allow building against the latest crypto on Windows, but I haven't made much use of it.

**Comment by yim-lee** [comment]
> the changes are sufficient to allow building against the latest crypto on Windows

Yes, I verified that this PR as-is builds with swift-crypto 2.0.0-beta.2 on macOS and Linux and tests are passing. It's not compatible with 1.x so we must bump the version, which in turn requires changing https://github.com/apple/swift-source-compat-suite/blob/main/common.py and https://github.com/apple/swift/blob/main/utils/update_checkout/update-checkout-config.json.

**Comment by compnerd** [comment]
@yim-lee Im not sure if we want to just jump immediately.  I think that having a staged approach would be nice where we can build against both versions of the API.  That was we can separate the decision to bump the dependency from the actual API changes and continue to test against newer releases without impacting stability.

**Comment by yim-lee** [comment]
> I think that having a staged approach would be nice where we can build against both versions of the API. That was we can separate the decision to bump the dependency from the actual API changes and continue to test against newer releases without impacting stability.

@compnerd I think we are on the same page. Ideally when we bump the version it's just a matter of updating `Package.swift`. I want the code for both API versions to coexist in `main` branch such that we can switch and test them easily, that's why I propose https://github.com/apple/swift-package-manager/commit/006e6edb2e28dc18d0555a4edf13cb2a0c10f960. Testing out new swift-crypto versions on CI would be tedious because it requires us changing all these other files, but maybe we can create a `crypto-2.x` branch that uses 2.x and the v2 flag enabled (it stays current with `main`, and the only changes are in `Package.swift`), and at the minimum I will test it locally on macOS and Linux whenever there is a new 2.x release. Maybe folks can think of a better way. @tomerd @abertelrud @neonichu?

I don't think we should bump to 2.x officially until it's out of beta, maybe even > 2.0.

**Comment by neonichu** [comment]
@yim-lee I think you can test on CI by just doing a cross-repo test changing https://github.com/apple/swift/blob/main/utils/update_checkout/update-checkout-config.json, since the version in the manifest doesn't matter for building the toolchain.

**Comment by yim-lee** [comment]
@compnerd I will take this over with https://github.com/apple/swift-package-manager/pull/3759 if you don't mind?

**Pull request closed without merging**
