### PR TITLE
[5.4] change manifest loading deduping logic to be based on identity instead of manifest name

### PR DESCRIPTION
**Pull request by tomerd**
same as #3165, needs #3179 to be merged first

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please test

**Review by abertelrud — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
```
unknown>:0: error: module file '/home/buildnode/.cache/clang/ModuleCache/1F9E9UQ6QU3J6/SwiftShims-X4QFX1KNP0ZQ.pcm' is out of date and needs to be rebuilt: signature mismatch
14:51:48 <unknown>:0: note: imported by module 'SwiftOverlayShims' in '/home/buildnode/.cache/clang/ModuleCache/1F9E9UQ6QU3J6/SwiftOverlayShims-X4QFX1KNP0ZQ.pcm'
14:51:48 <unknown>:0: error: missing required module 'SwiftOverlayShims'
14:51:48 
14:51:48 error: command failed with exit status: 1
14:51:48
```

cc @shahmishal

**Comment by tomerd** [comment]
@swift-ci please test linux

**Comment by shahmishal** [comment]
> ```
> unknown>:0: error: module file '/home/buildnode/.cache/clang/ModuleCache/1F9E9UQ6QU3J6/SwiftShims-X4QFX1KNP0ZQ.pcm' is out of date and needs to be rebuilt: signature mismatch
> 14:51:48 <unknown>:0: note: imported by module 'SwiftOverlayShims' in '/home/buildnode/.cache/clang/ModuleCache/1F9E9UQ6QU3J6/SwiftOverlayShims-X4QFX1KNP0ZQ.pcm'
> 14:51:48 <unknown>:0: error: missing required module 'SwiftOverlayShims'
> 14:51:48 
> 14:51:48 error: command failed with exit status: 1
> 14:51:48
> ```
> 
> 
> cc @shahmishal

Recently we have been seeing this issue, can you file a bug report on this?

**Pull request merged**
