### PR TITLE
Run swift-format in parallel mode

### PR DESCRIPTION
**Pull request by keith**
This has a significant performance boost when running on large projects

### CODE REVIEW

**Comment by keith** [comment]
that PR is merged so this is probably worth doing on main

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Comment by keith** [comment]
thanks!

**Comment by neonichu** [comment]
Thanks, @keith

**Pull request merged**
