### PR TITLE
[bootstrap] Add support for cross compile hosts flag

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
cc: @neonichu

**Comment by buttaface** [comment]
Interesting, @neonichu, I have [a patch that I use to cross-compile SPM itself from linux x86_64 to Android AArch64](https://github.com/termux/termux-packages/blob/master/packages/swift/swiftpm-Utilities-bootstrap) by invoking SPM from an official build of Swift 5.2.5 for Ubuntu with [a destination JSON file set up to use the Android NDK](https://github.com/termux/termux-packages/blob/master/packages/swift/swiftpm-android-flags.json). Once this pull is in, would you be interested in a pull that generalized that patch and adapted it to this new flag?

**Comment by neonichu** [comment]
Don't think we need both, using an env var was just me misunderstanding swift's `build-script`

**Pull request merged**
