### PR TITLE
Make the build output path configurable

### PR DESCRIPTION
**Pull request by mxcl**
This flag makes the build output location of SwiftPM configurable.

We should consider removing SWIFT_BUILD_PATH since variables like this that can unexpectedly change your build products location can be very un-fun.

However maybe we should keep it, and instead warn.

### CODE REVIEW

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Comment by ddunbar** [comment]
I like the idea of ditching SWIFT_BUILD_PATH in favor of this.

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Comment by mxcl** [comment]
@shahmishal nothing will pass, tried three times, the build output is unrevealing, any ideas?

**Comment by mxcl** [comment]
Hmm, well the other PRs passed.

**Comment by shahmishal** [comment]
Its failing due to change in this PR: 

```
/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux@2/swiftpm/Sources/OptionsParser/OptionsParser.swift:45:19: error: value of type 'String' has no member 'hasPrefix'
        } else if arg.hasPrefix("-") {
                  ^~~ ~~~~~~~~~
/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux@2/swiftpm/Sources/OptionsParser/OptionsParser.swift:49:20: error: value of type 'String' has no member 'hasPrefix'
            guard !arg.hasPrefix("--") else { throw Error.UnknownArgument(arg) }
                   ^~~ ~~~~~~~~~
<unknown>:0: error: build had 1 command failures
```

**Comment by mxcl** [comment]
Thanks, I guess I don't know how to navigate Jenkins.

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Pull request merged**
