### PR TITLE
[bootstrap] Replace old bootstrap with new bootstrap

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
We've successfully switched to the new bootstrap script so we can get
rid of the old bootstrap code now.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by dan-zheng** [comment]
@aciidb0mb3r: I noticed that the new bootstrap strip no longer adds the `@executable_path/../lib/swift/macosx` RPATH to SwiftPM tool binaries like `swift-build` and `swift-package`.

This led to RPATH issues for toolchains built using [`build-toolchain-tensorflow`](https://github.com/apple/swift/blob/tensorflow/utils/build-toolchain-tensorflow) (adapted from [`build-toolchain`](https://github.com/apple/swift/blob/tensorflow/utils/build-toolchain)): 
```
$ swift build
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2019-12-19-a.xctoolchain/usr/bin/swift-build
  Reason: image not found
[1]    45688 abort      swift build
```

I wonder if you encountered any similar issues?

---

A temporary fix was us is to re-add the `@executable_path/../lib/swift/macosx` RPATH for SwiftPM tool binaries.
```
$ sudo install_name_tool -add_rpath "@executable_path/../lib/swift/macosx" /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2019-12-19-a.xctoolchain/usr/bin/swift-build
$ sudo install_name_tool -add_rpath "@executable_path/../lib/swift/macosx" /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2019-12-19-a.xctoolchain/usr/bin/swift-package
$ sudo install_name_tool -add_rpath "@executable_path/../lib/swift/macosx" /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2019-12-19-a.xctoolchain/usr/bin/swift-run
$ sudo install_name_tool -add_rpath "@executable_path/../lib/swift/macosx" /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2019-12-19-a.xctoolchain/usr/bin/swift-test
```
The discussion at https://github.com/tensorflow/swift/issues/347 has more context.

**Comment by dan-zheng** [comment]
I did some more investigation.

`/usr/lib/swift` is added as an RPATH for toolchains built from `apple/swift:tensorflow` branch, but not for toolchains built from `apple/swift:master`. This seems related to the [`build-script` `-toolchain-stdlib-rpath` flag](https://github.com/apple/swift/pull/27206), which is true by default on `tensorflow` branch but false on `master` branch: [code here](https://github.com/apple/swift/blob/b3e4951094868ecaee873fd830d4dc59a1b3efda/lib/Driver/DarwinToolChains.cpp#L393-L413).

To support toolchains built with `-toolchain-stdlib-rpath=true` (non-Swift-in-the-OS use cases), perhaps [re-adding the `@executable_path/../lib/swift/macosx` RPATH in `Utilities/bootstrap`](https://github.com/apple/swift-package-manager/pull/2462/files#diff-296aa080a049a48a75c47e0a2926fde0L1302) for SwiftPM tool binaries is a robust solution.

@aciidb0mb3r: does this solution make sense to you? SR-1967 seems like a related issue.

**Comment by ematejska** [comment]
@aciidb0mb3r: What do you think?  Right now using the package manager is busted for Swift for Tensorflow toolchains due to this.

**Comment by ematejska** [comment]
Specifically what about the use-case of using a third-party toolchain on Darwin?  They would not be using the OS version of the swift libs since they provide their own.

**Comment by aciidb0mb3r** [comment]
I think we can add a flag in the bootstrap script to add the rpath. Will that work for tensor flow?

**Pull request merged**
