### PR TITLE
Add a fast path for normalize(absolute:).

### PR DESCRIPTION
**Pull request by ddunbar**
- This method is super expensive because of its trivial implementation. Rather
   than complicate the implementation, this just adds a fast path to early exit
   in the common case where the string doesn't need normalization.

### CODE REVIEW

**Comment by ddunbar** [comment]
I tested this by enumerating all interesting strings of 7 characters, which I think should be sufficient:
```
for a0 in ["a", "/", "."] {
    for a1 in ["a", "/", "."] {
        for a2 in ["a", "/", "."] {
            for a3 in ["a", "/", "."] {
                for a4 in ["a", "/", "."] {
                    for a5 in ["a", "/", "."] {
                        for a6 in ["a", "/", "."] {
                            let s = "/"+a0+a1+a2+a3+a4+a5+a6
                            let needs1 = normalize(absolute: s) != s
                            let needs2 = mayNeedNormalization(absolute: s)
                            if needs1, !needs2 {
                                fatalError("broken normalization for '\(s)' (\(needs1) vs \(needs2))")
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
Should we have a unit and perf test?

**Comment by ddunbar** [comment]
I presumed we already should have unit test coverage, perf test would be nice but I don’t personally have the time atm

**Pull request merged**
