### PR TITLE
Renaming Streamable => TextOutputStreamable [Do not merge]

### PR DESCRIPTION
**Pull request by dabrahams**
This commit can be merged once apple/swift#4130 is auto-merged

### CODE REVIEW

**Comment by ddunbar** [comment]
Is this change destined for the swift-3.0 branch as well?

**Comment by moiseev** [comment]
@ddunbar Yes, I will open a new PR agains the branch shortly, now that the proposal has been approved.

**Comment by moiseev** [comment]
Oh... Never mind, the changes have already been merged into the swift-3.0-branch as far as I can tell.

**Comment by dabrahams** [comment]
on Mon Aug 08 2016, Daniel Dunbar <notifications-AT-github.com> wrote:

> Is this change destined for the swift-3.0 branch as well?

That's the plan.  I have to get it through -evolution first though.

-- 
-Dave

**Pull request merged**
