### PR TITLE
[Collections] Honor --config-path and --cache-path options

### PR DESCRIPTION
**Pull request by yim-lee**
Package collections configuration and storage paths should be customizable via `--config-path` and `--cache-path` options.

rdar://74887473

### CODE REVIEW

**Comment by yim-lee** [comment]
cc @friedbunny 

@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]
<3

**Comment by tomerd** [comment]
would be good to bring over to release/5.6!

**Comment by yim-lee** [comment]
Hiccup maybe?

```
17:40:51 -- ABI list file not generated for configuration x86_64-unknown-linux-gnu.default.v1.stable.exceptions.no_new_in_libcxx, `check-cxx-abilist` will not be available.
17:40:51 -- Configuring done
17:40:51 CMake Error in benchmarks/CMakeLists.txt:
17:40:51   The compiler feature "cxx_std_20" is not known to CXX compiler
17:40:51 
17:40:51   "Clang"
17:40:51 
17:40:51   version 4.0.0.
```

@swift-ci please smoke test Linux

**Comment by yim-lee** [comment]
@swift-ci please smoke test Linux

**Comment by tomerd** [comment]
@swift-ci please smoke test Linux

**Comment by yim-lee** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
