### PR TITLE
[5.9] Enable package visibility feature in tools-version 5.9

### PR DESCRIPTION
**Pull request by elsh**
The package visibility proposal has officially been accepted: https://forums.swift.org/t/accepted-se-0386-package-access-modifier/64904
Resolves rdar://109152010

### CODE REVIEW

**Comment by elsh** [comment]
main https://github.com/apple/swift-package-manager/pull/6534

**Comment by elsh** [comment]
@swift-ci smoke test

**Review by nkcsgexi — APPROVED** [review]

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test windows

**Review by MaxDesiatov — APPROVED** [review]

**Review by neonichu — APPROVED** [review]

**Review by tomerd — APPROVED** [review]

**Pull request merged**
