### PR TITLE
Update CODEOWNERS for master

### PR DESCRIPTION
**Pull request by abertelrud**

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci smoke test

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please smoke test linux

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by friedbunny** [comment]
If we find ourselves updating this more frequently or having to cherry-pick it across branches, GitHub also allows for groups to be specified as code-owners. That way, something like `@apple/swiftpm-team` could be used to manage membership.

**Comment by abertelrud** [comment]
Agreed.  In this particular case, Rick is also added to the owners for the 5.3 branch (since he is the release manager) but is not on added for master.  So in this case it wasn't a cherry-pick, but maybe we could make this list more versatile using groups.

**Pull request merged**
