### PR TITLE
[5.9] Add templates for build tool plugins and command plugins (#6111)

### PR DESCRIPTION
**Pull request by abertelrud**
This is a cherry-pick of #6111 for nomination to 5.9.

rdar://107288352

Co-authored-by: Anders Bertelrud <anders@apple.com>
(cherry picked from commit f25e1381d288176cd71a91324f7988253456a7f0)

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci test

**Comment by abertelrud** [comment]
@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
(swift-server-bot approval was me logged in with the wrong account)

**Comment by abertelrud** [comment]
@swift-ci smoke test macOS platform

**Comment by abertelrud** [comment]
Looks like the macOS CI can't find an available node.

**Comment by abertelrud** [comment]
@swift-ci smoke test macos platform

**Pull request merged**
