### PR TITLE
[5.6] Update the Swift version to 5.6.2

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
https://github.com/apple/swift/pull/59204

@swift-ci smoke test

**Review by neonichu — APPROVED** [review]

**Comment by shahmishal** [comment]
@compnerd is the Windows failure known for 5.6?

**Comment by compnerd** [comment]
Nope, its not expected; this seems odd:
```
CMake Error at C:/Users/swift-ci/jenkins/workspace/swiftpm-PR-windows/swift-corelibs-foundation/cmake/modules/XCTestAddTests.cmake:45 (message):
  Error running test executable.

    Path: 'T:/4/TestFoundation.app/TestFoundation.exe'
    Result: Process terminated due to timeout
```

This could just be a flake.

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by shahmishal** [comment]
Hopefully we are not missing changes on https://github.com/apple/swift-installer-scripts.git release/5.6 branch cc: @compnerd

**Comment by shahmishal** [comment]
The failure looks unrelated to the change in this PR.

**Pull request merged**
