### PR TITLE
Improve diagnostic when automatic resolution is disabled

### PR DESCRIPTION
**Pull request by neonichu**
- Show the exact path where we looked for a resolved file
- Special case if there wasn't a file to begin with

rdar://81172549

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
There are probably some tests that need updating, I didn't run the suite locally 😬

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
> 11:22:27 error: signalled(6): /Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/usr/libexec/swift/pm/swiftpm-xctest-helper /Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/TemporaryFile.tAiaIg output:
> 11:22:27     dyld: Library not loaded: @rpath/XCTest.framework/Versions/A/XCTest
> 11:22:27       Referenced from: /Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/usr/libexec/swift/pm/swiftpm-xctest-helper
> 11:22:27       Reason: image not found

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
Self-hosted macOS is failing due to unrelated reasons, so this can be merged.

**Pull request merged**
