### PR TITLE
[5.8] Pass through the package identity as a parameter to `willLoadManifest`/`didLoadManifest` callbacks (#6019

### PR DESCRIPTION
**Pull request by abertelrud**
This is the 5.8 nomination of https://github.com/apple/swift-package-manager/pull/6019

### CODE REVIEW

**Review by tomerd — APPROVED** [review]

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
@swift-ci smoke test

**Comment by abertelrud** [comment]
Looks like there is a small difference between `main` and `5.8` so that `MinimalWorkspaceDelegate` (only present in 5.8) also needs to have its delegate method signature adjusted.  Trivial change.

**Comment by abertelrud** [comment]
@swift-ci smoke test

**Pull request merged**
