### PR TITLE
Unit test should handle both SwiftArgParser 0.3.x and 0.4.x output

### PR DESCRIPTION
**Pull request by abertelrud**
rdar://75172724

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by artemcm** [comment]
@swift-ci please smoke test linux

**Review by neonichu — APPROVED** [review]

**Pull request merged**
