### PR TITLE
Disable the bootstrap checking for explicit target dependencies and remove wrong llbuild dependency

### PR DESCRIPTION
**Pull request by finagolfin**
This is currently flagging wrong dependencies, enable it again once it works.

@neonichu, reverting for now as you suggested.

### CODE REVIEW

**Review by neonichu — APPROVED** [review]

**Comment by finagolfin** [comment]
@MaxDesiatov, a CI run here and we can get this in? I will submit for 5.10 next.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by finagolfin** [comment]
Windows CI failed after checking out source, obviously unrelated to this pull.

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
We're in the process of setting up an automerger from main to 5.10, so submitting separately should not be necessary.

**Pull request merged**
