### PR TITLE
Add a PerfTests module and Xcode scheme

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This commits creates a PerfTests module in Tests, however the tests will
still be disabled by default.
It also adds a PerfTests scheme in Utilties/ which is copied to Xcode
project when it is generated with --enable-perf-tests option.

### CODE REVIEW

**Comment by ddunbar** [comment]
Can we have per-module PerfTests modules? I like continuing that division so it is always obvious where a performance test should go.

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
Linux is unrelated, tested locally

**Pull request merged**
