### PR TITLE
Override the module cache directory for SwiftPM's test

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by rballard** [comment]
Approved for the Swift 3.1 branch (though this is post 3.1-GM tag).

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test OS X

**Comment by aciidb0mb3r** [comment]
@swift-ci please test OS X

**Pull request merged**
