### PR TITLE
[performance] reduce amount of dispatch queues

### PR DESCRIPTION
**Pull request by tomerd**
motivation: improve performance, reduce complexity

changes:
* define single shared concurrent queue and update code that runs async operation to use it.
* replace cases where dispatch queue is used "as a lock" with a lock

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]
This is great.  LGTM!

**Comment by abertelrud** [comment]
Especially glad to see conceptual distinction between queues and locks, which I think makes everything more understandable.

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Pull request merged**
