### PR TITLE
fix build after #242

### PR DESCRIPTION
**Pull request by goloveychuk**
after #242 master is not compilling

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
I don't think this is desired, master should be compiling wrt swift master and not necessarily the toolchain. #242 was done due to proposal SE-0046 which is merged to swift master but isn't in toolchain yet. However I do think #242 should have been CI'ed.

**Comment by goloveychuk** [comment]
So you saying that 
```swift
func f(_ arg: Int)
f(arg: 2)
```
will build in `swift/master`?
My pr mostly fix this mistakes

**Comment by mxcl** [comment]
I can build swiftpm master against swift master without this patch.

**Comment by goloveychuk** [comment]
@mxcl ok, if not needed - can close it. New toolchain will be with master swift. So it wouldn't a problem

**Pull request closed without merging**
