### PR TITLE
build: repair build after apple/swift-tools-support-core#117

### PR DESCRIPTION
**Pull request by compnerd**
Remove `Triple.swift` as tools-support-core now has this defined.  This repairs the CMake based build.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
I was planning to fix this in #2883, but ran out of time yesterday.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
I think this is superseded by #2883 now.

**Pull request closed without merging**
