### PR TITLE
restore generate-linux-main for backwards compatibility

### PR DESCRIPTION
**Pull request by tomerd**
motivation: users made the point that while deprecating generate-linux-main makes sense, we should not deprecate it too quickly so they can support SwiftPM < 5.1 more easily

changes:
* restore LinuxMainGenerator command
* resotre plumbing to call LinuxMainGenerator on --generate-linux-main while retaining the deprecation warning
* add test to test both deprecation warning and that the generated code is created

rdar://72160848

### CODE REVIEW

**Comment by tomerd** [comment]
code here is restored from https://github.com/apple/swift-package-manager/pull/3053 where this was removed. no significant changes made to the code.

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
we need to bring this in 5.4 as well once merged

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Review by neonichu — APPROVED** [review]

**Pull request merged**
