### PR TITLE
Basics: remove `AsyncFileSystem` as unused

### PR DESCRIPTION
**Pull request by MaxDesiatov**
### Motivation:

Since `FileSystem` is now `Sendable`, we no longer need to keep `AsyncFileSystem`, which served only as a workaround for non-sendability. It wasn't non-blocking under the hood anyway, and a blocking FS I/O API would have to be designed from scratch anyway, not as a wrapper for the existing blocking APIs.

### Modifications:

`AsyncFileSystem` actor declaration and its uses were removed. `FileSystem` can be used directly in our async code instead.

### Result:

Reduced the amount of redundant code, FS code is now easier to understand when `async`/`await` are used.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS self hosted

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS self hosted

**Review by tomerd — APPROVED** [review]

**Review by neonichu — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Pull request merged**
