### PR TITLE
Rewrite and unit test PIFBuilder to be more modular

### PR DESCRIPTION
**Pull request by hartbit**
Supports all kinds of products and targets

### CODE REVIEW

**Comment by hartbit** [comment]
@aciidb0mb3r This is the new PR for PIFBuilder. I added support for system targets, added more tests, and did the change you requests to create a `PIFBuilderParameter` struct.

**Comment by hartbit** [comment]
@swift-ci smoke test self hosted

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by hartbit** [comment]
@swift-ci smoke test

**Comment by hartbit** [comment]
@swift-ci smoke test

**Comment by hartbit** [comment]
@swift-ci smoke test

**Pull request merged**
