### PR TITLE
Disallow static linking core libraries in `swift test`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This is currently not supported and we should show a proper error message in this case.

Resolves rdar://117908112.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
cc @grynspan this may need to be updated when `swift-testing` support lands, unless you can confirm that it doesn't support static linking either?

**Comment by grynspan** [comment]
> cc @grynspan this may need to be updated when `swift-testing` support lands, unless you can confirm that it doesn't support static linking either?

swift-testing is agnostic here. As it's also just a package, it only needs the symbols it uses to eventually exist, and isn't too concerned with the state of the linker.

**Comment by MaxDesiatov** [comment]
Great, then you'll just need to make this static linking check specific to XCTest in your `swift-testing` PR, in case mine is merged first 🙂

**Comment by neonichu** [comment]
Hm, why aren't we just removing the option? It seems a bit weird to have an option that 100% leads to an error.

**Comment by MaxDesiatov** [comment]
We can't remove it since it's a linker option shared with `swift build`.

**Comment by neonichu** [comment]
In that case, I think we should move the option so that we can have it only apply to `build`

**Comment by MaxDesiatov** [comment]
> In that case, I think we should move the option so that we can have it only apply to `build`

What's the best place to move it? `SwiftTestTool` has access to `GlobalOptions`, which contains both `BuildOptions` and `LinkerOptions`.

**Comment by neonichu** [comment]
I think we would move it to `BuildToolOptions`?

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
> I think we would move it to `BuildToolOptions`?

Doesn't seem to be currently possible, as we construct `BuildParameters` in `SwiftTool.swift`, before `BuildToolOptions` are even available. Are there any alternatives, or should I just revert the last commit to get back to the initial error message implementation of this?

**Comment by neonichu** [comment]
One option could be moving the static stdlib option to `createBuildSystem()` like the other build-only options such as `explicitProduct`.

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by neonichu — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
