### PR TITLE
Drop support for Swift 4.0

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
Since Swift 4.1 is released, I don't think we need to maintain support for Swift 4.0. @ddunbar what do you think?

**Comment by vlm** [comment]
I'd vote for supporting two latest releases at the same time. Helps with bootstrapping/continuity.

**Comment by aciidb0mb3r** [comment]
Hmm, I don't really see a good advantage of keeping support for last two releases. OTOH its not a lot of code that we need to maintain.

**Comment by vlm** [comment]
@aciidb0mb3r my line of thinking is that since we're running on a tip, we might not be the best equipped users to actually recognize any advantage and/or rely upon it. Doesn't mean that there's no advantage or there aren't users for which dropping said support won't create a major inconvenience.

If we can live with this PR for another half a year or whatever the Swift release cadence is, there's very little downside to keeping said compatibility in for a while.

**Comment by hartbit** [comment]
IMHO, I think its fine to drop support for 4.0. By the time this PR make it to release it will be Swift 4.2, and we'd be supporting two releases.

**Comment by ddunbar** [comment]
I tend to agree with Lev here... dropping support early can be a huge pain -- if it doesn't have a large cost for us to maintain I would prefer that we keep wide support.

I can't say how many times I have had trouble debugging or bisecting things because one tool dropped support early, so you can no longer do an apples to apples comparison.

Keep in mind also that people doing server side Swift can very easily have "stable deployments" of 4.0 versions of things which they may need to support (e.g., if Swift itself drops support for a version of Ubuntu they require)... this can make compatibility windows stretch out much longer that what one expects of, say, a mobile application.

**Comment by aciidb0mb3r** [comment]
Note that this PR doesn't drop support for Swift 4.0 language, it drops support for SwiftPM itself building with a Swift 4.0 compiler.

**Comment by ddunbar** [comment]
Oh, I have no problem with that then... we've moved forward with that aggressively in the past and thats been ok.

**Comment by hartbit** [comment]
@aciidb0mb3r can this be merged?

**Pull request merged**
