### PR TITLE
Revert "simplify bootstrap build (#5939)"

### PR DESCRIPTION
**Pull request by neonichu**
This reverts commit 4111569c63698f1a6339dd053c9c4babb3e3ed95.

This is an alternative to https://github.com/apple/swift-package-manager/pull/5954 if that does not pan out.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Failures in linux self-hosted are expected, trying to fix in https://github.com/apple/swift-package-manager/pull/5952

**Comment by neonichu** [comment]
@swift-ci please smoke test linux

**Comment by Azoy** [comment]
Merging to unblock toolchain builds

**Pull request merged**
