### PR TITLE
Add module aliasing integration tests 

### PR DESCRIPTION
**Pull request by elsh**
Resolves rdar://91943961

### CODE REVIEW

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
Looks like this PR needs to wait for https://github.com/apple/swift-package-manager/pull/5600 to be part of the toolchain, so might have to push this to next week (or whenever it becomes part of it). cc @tomerd  @shahmishal

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test linux

**Review by neonichu — APPROVED** [review]

**Pull request merged**
