### PR TITLE
[DO NOT MERGE] Test commit to cross check swift-driver change

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Cross check https://github.com/apple/swift-driver/pull/1488 to make sure it doesn't break swiftpm

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/swift-driver/pull/1488

@swift-ci Please test

**Comment by MaxDesiatov** [comment]
I'm not entirely sure if this repo supports cross-repo testing, maybe worth creating one more PR at `apple/swift` and run tests there just to double check?

**Comment by cachemeifyoucan** [comment]
> I'm not entirely sure if this repo supports cross-repo testing, maybe worth creating one more PR at `apple/swift` and run tests there just to double check?

```
Creating working copy for https://github.com/apple/swift-driver.git
Working copy of https://github.com/apple/swift-driver.git resolved at main (916bf4b)
```
Indeed, seems no cross repo testing. Just double check what tests from `apple/swift` has this coverage? If I just start a full test with the swift-driver PR, it will cover swiftpm build?
Also I remember swiftpm builds in `Test Source Compatibility` test too, maybe I can start that as well.

**Comment by MaxDesiatov** [comment]
@shahmishal would you have a moment to clarify what's the best way to test this as a cross-repo PR?

**Comment by cachemeifyoucan** [comment]
Try swift repo here: https://github.com/apple/swift/pull/70051

**Comment by cachemeifyoucan** [comment]
The other PR is testing cross repo correctly and I verify all the configuration I broke last time builds correctly now. Closing this.

**Pull request closed without merging**
