### PR TITLE
Bump swift-system to 1.2.1

### PR DESCRIPTION
**Pull request by yim-lee**

### CODE REVIEW

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65938
https://github.com/apple/swift-tools-support-core/pull/358

@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]

**Comment by yim-lee** [comment]
Error in self-hosted CI:

```
error: Dependencies could not be resolved because root depends on 'swift-system' 1.2.1..<1.3.0 and 'swift-tools-support-core' depends on 'swift-system' 1.1.1..<1.2.0.
```

Assuming this is because cross-repo testing not supported in these environments.

**Comment by tomerd** [comment]
yes "self hosted" jobs do not support cross repo testing

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65938
https://github.com/apple/swift-tools-support-core/pull/358

@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65938
https://github.com/apple/swift-tools-support-core/pull/358

@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65938
https://github.com/apple/swift-tools-support-core/pull/358

@swift-ci please smoke test

**Comment by yim-lee** [comment]
No longer needed per https://github.com/apple/swift-tools-support-core/pull/358#issuecomment-1832836933

**Pull request closed without merging**
