### PR TITLE
refactor PackageDependencyDescription towards identity changes

### PR DESCRIPTION
**Pull request by tomerd**
motivation: improve code infrastrucuture towards fixing correctness issues with identity

changes:
* rename PackageDependencyDescription::url to PackageDependencyDescription::location to reflect its true meaning
* rename PackageDependencyDescription::name to PackageDependencyDescription::nameForTargetDependencyResolutionOnly to make sure its not used for wrong reasons
* move "file://" prefix handing from PackageDependencyDescription::init to PackageDependencyDescription::init(json) which where all the other location validation is done
* addjsut call-sites
* adjust and add tests

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
```
/home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test@2/branch-main/build/buildbot_incremental/libdispatch-linux-x86_64/libBlocksRuntime.so && :
20:47:00 
<unknown>:0: error: module file '/home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test@2/branch-main/build/buildbot_incremental/xctest-linux-x86_64/module-cache/2MWQC4BFSBUP5/SwiftShims-2TKFFX38VHX6U.pcm' is out of date and needs to be rebuilt: signature mismatch
```
cc @shahmishal

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by abertelrud** [comment]
Reviewed this as part of https://github.com/apple/swift-package-manager/pull/3244, which includes these changes.

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
