### PR TITLE
[Documentation] Tidy up reference section.

### PR DESCRIPTION
**Pull request by ddunbar**
This tidies up the reference section some, fixing a few errors and adds additional clarification in some places.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
👌

**Comment by aciidb0mb3r** [comment]
Unrelated to this PR; do you think we should make it easier to reach this reference page?
Right now if you go to https://github.com/apple/swift-package-manager/tree/master/Documentation 
I am more likely to click `Building Swift Modules` or `Usage`,
the only way to reach this page is by clicking `Reference` which I think is not very obvious.

**Comment by ddunbar** [comment]
I agree, I think we should at least have more links in some places.

**Comment by abertelrud** [comment]
The diffs look good, but there is still one reference under Other Rules that at least implies (if not states) that the test modules under `Tests` should have the same name as the modules they test.  The new rule is that they have to have that name plus a `Tests` suffix.

**Comment by abertelrud** [comment]
Otherwise this looks good!

**Pull request merged**
