### PR TITLE
Link to issue tracker in contributing

### PR DESCRIPTION
**Pull request by alias1**
It would be useful to enable the issue tracker on GitHub, rather than only accepting PR's.

### CODE REVIEW

**Comment by gribozavr** [comment]
@alias1 You can report issues on our bug tracker, https://bugs.swift.org/ .

**Comment by alias1** [comment]
Ah, that makes more sense. Would be useful to include that in README/CONTRIBUTING.

**Comment by gribozavr** [comment]
@alias1 Would you mind submitting a PR?

**Comment by alias1** [comment]
No worries. How's that?

**Comment by gribozavr** [comment]
LGTM, but deferring to @ddunbar to approve.

**Pull request merged**
