### PR TITLE
Add option to only pull dependencies without compiling

### PR DESCRIPTION
**Pull request by dfirsht**
In my current workflow, I have packages that I would like to use the SwiftPM to pull down and track but contain only C code that the SwiftPM cannot compile. This option allows me to only pull down packages without attempting to compile. This feature should be included as it allows developers to more granularly specify what they want the SwiftPM to do.

### CODE REVIEW

**Comment by mxcl** [comment]
Maybe this should be `swift get`?

**Comment by dfirsht** [comment]
@mxcl yeah I can change it, I wasn't sure what the best terminology would be

**Comment by dfirsht** [comment]
@mxcl So I am looking into how to do this. I am thinking that we keep the --get option as a hidden option. Then we modify the bootstrap to (somehow) create a swift-get executable which when run, will call swift build --get. Does that sound like the best plan?

**Comment by mxcl** [comment]
Well I'm not saying it *should* be `swift get` yet, just opening it for discussion.

**Comment by ddunbar** [comment]
If we do want it to be spelled that way, I would propose implementing it by simply making "swift-get" a symlink to swift-build, and then dispatch based on argv[0]. We use this trick in both clang and swift (and llbuild, for that matter).

**Comment by mxcl** [comment]
Indeed, I enjoy this trick.

**Comment by billabt** [comment]
How about something like this?

```
% swift build --dependenciesOnly
```

Clear, concise and leaves no doubt about what it'll do.

**Comment by rfdickerson** [comment]
I really like Bill's idea. That's quite clear.

**Comment by mxcl** [comment]
I would expect that to build the dependencies.

**Comment by Memorion** [comment]
I feel like a lot of the problems naming this stem from the fact that you have to use `swift build` to use the package manager, the inclusion of build makes the naming really confusing, for example I would expect `swift build --clean` to clean and build, not just to clean.

I'd much rather use the package manager something like `spm build`, `spm clean,` `spm new hello_world` and model it more like [cargo](http://doc.crates.io/guide.html), in it's current form it feels a little more like a build tool than a package manager.

**Comment by billabt** [comment]
**mxcl** is right now that I look it.  That command does look like it would just build the dependencies...  That wouldn't be a bad one to add while we're at it. 😃

Here's another suggestion:
```
% swift build --downloadOnly
```
This command would just retrieve the package plus its' dependencies.

**Comment by dfirsht** [comment]
So there's a lot of discussion here but I really think we should close this. @mxcl and @ddunbar, you two seem to still want the `swift get` option. If we do this would that allow this to be accepted? If yes, I'd really appreciate if you two had advice on how to accomplish this.

**Comment by mxcl** [comment]
I've been thinking about:

    swift package --fetch

Basically, don't close this, the patch is good, but we should let our thoughts for the interface stew a little more.

**Comment by dfirsht** [comment]
@mxcl Hey Max, can we get an update on this?

**Comment by mxcl** [comment]
Hi, sorry I was absent, I was deep in refactoring and didn't want to risk distracting myself.

I think we should do `swift build --fetch`. I wasn't sold on “fetch” but I explored a lot of synonyms and couldn't find anything that was much better, while `fetch` has the advantage that it is the same as `git` and since we do git underneath, it fits IMO.

**Comment by mxcl** [comment]
I will merge this, since I feel bad about the delay and the fact I refactored so much code around it.

**Comment by mxcl** [comment]
Thank you for this contribution and I truly apologize for the delay in applying it 🖖🏻

**Comment by dfirsht** [comment]
thanks max, no problem. Should I open another PR to change the terminology to fetch though?

**Comment by mxcl** [comment]
I did that in the merge thanks. Let me know if it's what you expected.

**Comment by dfirsht** [comment]
ok, looks good

**Pull request merged**
