### PR TITLE
Fix indentations and remove invisibles

### PR DESCRIPTION
**Pull request by federicobucchi**
Fix indentations from 2 to 4 spaces, remove invisibles and tabs

### Motivation:

To have a consistent code style

### Modifications:

- Indentations with 2 spaces changed to 4 spaces.
- Invisibles removed
- Tabs replaced with spaces

### Result:

Code style more consistent (I might have missed some around)

### CODE REVIEW

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Comment by abertelrud** [comment]
@federicobucchi Seems that maybe some of the unit tests had dependencies on the indentation?

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Comment by federicobucchi** [comment]
@abertelrud I fixed the failing tests

**Comment by WowbaggersLiquidLunch** [comment]
> Indentations with 2 spaces changed to 4 spaces.

> Tabs replaced with spaces

This PR might conflict with #3153. I can withdraw #3153 if everything is covered in this PR.

**Comment by federicobucchi** [comment]
@WowbaggersLiquidLunch I made those changes everywhere in the project (also in the files of #3153 )

**Comment by WowbaggersLiquidLunch** [comment]
#3153 was merged about 30 minutes ago, and it seems that there is no conflict with this PR. All is well then.

**Comment by federicobucchi** [comment]
@WowbaggersLiquidLunch I can actually see a conflict for `Package.swift` that I am going to solve

**Comment by WowbaggersLiquidLunch** [comment]
I think the conflict might be from #3159 instead.

This does make me wonder if this PR will conflict with other open PRs, especially considering the number of lines changed.

**Comment by federicobucchi** [comment]
I have broken the PR rebasing.  I will open a new one.

**Pull request closed without merging**
