### PR TITLE
[tests] Create .travis.yml to enable continuous integration

### PR DESCRIPTION
**Pull request by eosrei**
Adds Travis CI to run tests for Ubuntu 14.04 LTS Linux architecture. This requires configuring this project on the Apple Travis CI account: https://travis-ci.org/apple 

A build status image has been added to the README.md. Example using this branch:  [Build Status](https://travis-ci.org/eosrei/swift-package-manager)

### CODE REVIEW

**Comment by kostiakoval** [comment]
:+1: Great

**Comment by onevcat** [comment]
It's cool.

**Comment by gribozavr** [comment]
Thank you, but we are working on setting up continuous integration for the whole swift.org project.  It is coming soon.

**Comment by eosrei** [comment]
Alright. swift-corelibs-foundation builds are currently failing due to lack of CI: https://github.com/apple/swift-corelibs-foundation/commit/972863924a978c993eee0bb44e3fd743a196af35#commitcomment-14812834. I hope this is fixed really soon.

**Pull request closed without merging**
