### PR TITLE
Avoid using `temp_await` in `SwiftTestTool.swift`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Follow up to https://github.com/apple/swift-package-manager/pull/7009, which provides the detailed motivation: we should avoid `temp_await` as it can lead to deadlocks when combined with Swift Concurrency.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by grynspan** [comment]
This probably needs tweaks with my recently-landed changes to add experimental swift-testing support.

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by AndrewHoos — APPROVED** [review]

**Pull request merged**
