### PR TITLE
[5.5] Fix swift package init --help printout

### PR DESCRIPTION
**Pull request by miggs597**
cherry picked from commit a52d4d82d2cc84ffaed3208877ccee03cc85357e

https://github.com/apple/swift-package-manager/pull/3407

### CODE REVIEW

**Comment by miggs597** [comment]
apple/swift-driver#534
apple/sourcekit-lsp#374
@swift-ci please smoke test

**Comment by miggs597** [comment]
apple/swift-driver#534
apple/sourcekit-lsp#374
@swift-ci please test

**Comment by neonichu** [comment]
apple/swift-driver#628
apple/sourcekit-lsp#391
@swift-ci please test

**Comment by miggs597** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
apple/swift-driver#628
apple/sourcekit-lsp#391
@swift-ci please test

**Comment by neonichu** [comment]
apple/swift-driver#628
apple/sourcekit-lsp#391
@swift-ci please test

**Comment by abertelrud** [comment]
`17:18:45 
/home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swiftpm/Sources/Commands/SwiftBuildTool.swift:86:35: error: argument passed to call that takes no arguments
17:18:45     @OptionGroup(_hiddenFromHelp: true)
17:18:45                                   ^~~~
17:18:45 /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swiftpm/Sources/Commands/SwiftBuildTool.swift:87:9: note: cannot automatically synthesize 'Decodable' because '<<error type>>' does not conform to 'Decodable'
17:18:45     var swiftOptions: SwiftToolOptions
17:18:45         ^
17:18:45 /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swiftpm/Sources/Commands/SwiftBuildTool.swift:77:15: error: type 'SwiftBuildTool' does not conform to protocol 'Decodable'
`

Does this suggest that it was doing the PR build with the wrong cross-repository branch?

**Comment by neonichu** [comment]
We need to update `update-checkout` first: https://github.com/apple/swift/blob/release/5.5/utils/update_checkout/update-checkout-config.json#L96

**Comment by miggs597** [comment]
apple/swift-driver#628
apple/sourcekit-lsp#391
@swift-ci please test

**Comment by shahmishal** [comment]
Swift update-checkout script will need to be updated, and also we have few job that need to be updated. Please don't merge this until all of the CI jobs are updated. If you don't mind, I can merge them all together to avoid breakage.

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
hi @shahmishal is this ready to merge?

**Comment by franco6788** [comment]
Yo no tengo un laniux tengo un Motorola e 5 play quiero ayuda[]() con ésto no ce si ce pueda

**Comment by miggs597** [comment]
apple/swift#37663
@swift-ci please test

**Comment by shahmishal** [comment]
apple/swift-driver#628
apple/sourcekit-lsp#391
apple/swift#37663

Both of these PRs are updating swift-argument-parser to 0.4.1, however the swift PR is updating the version to 0.4.3. Can we update all of them to same version?

**Comment by abertelrud** [comment]
> [apple/swift-driver#628](https://github.com/apple/swift-driver/pull/628)
> [apple/sourcekit-lsp#391](https://github.com/apple/sourcekit-lsp/pull/391)
> [apple/swift#37663](https://github.com/apple/swift/pull/37663)
> 
> Both of these PRs are updating swift-argument-parser to 0.4.1, however the swift PR is updating the version to 0.4.3. Can we update all of them to same version?

That's a good point.  Seems to me that these should all be 0.4.3.  @neonichu do you want to update the swift-driver and sourcekit-lsp PRs, or should I?

**Comment by neonichu** [comment]
I think it's fine for every package to specify the minimum version they need instead of agreeing on a fixed version based on the needs of another package, isn't that why we have a dependency resolver? However, if we really want to align them exactly for the purpose of the toolchain, I can update the PRs.

**Comment by abertelrud** [comment]
> I think it's fine for every package to specify the minimum version they need instead of agreeing on a fixed version based on the needs of another package, isn't that why we have a dependency resolver?
> 
> However, if we really want to align them exactly for the purpose of the toolchain, I can update the PRs.

That makes sense.  So the toolchain build script would check out 0.4.3 and then the others will all work because 0.4.3 satisfies the requirement.  Still, when building the toolchain I think it's what the script that checks out swift-argument-parser says that matters, right?  @shahmishal with that, can we change the toolchain checkout to 0.4.3?

**Comment by neonichu** [comment]
> Still, when building the toolchain I think it's what the script that checks out swift-argument-parser says that matters, right?

Yep, that's right, we have to make sure that the script checks out the newest required version amongst all packages that are part of the toolchain.

**Comment by neonichu** [comment]
apple/swift-driver#628
apple/sourcekit-lsp#391
@swift-ci please test

**Comment by neonichu** [comment]
Hm, looks like 0.4.1 is still being used for argument parser:

> 11:58:04 /Users/buildnode/jenkins/workspace/swift-package-manager-PR-macos/swift-argument-parser
> 11:58:04 HEAD is now at 831ed5e Update changelog for 0.4.1 release (#287)

**Comment by neonichu** [comment]
Oh, I think I see the issue, apple/swift#37663 targeted `release/5.5`, but we are actually using `update-checkout` from `main`:

> 11:51:07 + cd swift
> 11:51:07 + git checkout main
> 11:51:07 Already on 'main'
> 11:51:07 Your branch is up to date with 'origin/main'.

On `main`, 0.4.1 is still [being used](https://github.com/apple/swift/blob/main/utils/update_checkout/update-checkout-config.json#L108), so we need a new PR.

**Comment by abertelrud** [comment]
> On `main`, 0.4.1 is still [being used](https://github.com/apple/swift/blob/main/utils/update_checkout/update-checkout-config.json#L108), so we need a new PR or perhaps SwiftPM's CI config should change? @shahmishal

What's the latest here?  i.e. what is needed in order to get to place where we could merge this?  @neonichu  @shahmishal

**Comment by neonichu** [comment]
Not sure, we could update the 5.5 section of the config on `main` or we could change the CI to use the 5.5 branch to get the config. Either should work, I think @shahmishal is the best person to decide which one we should do at this point.

**Comment by shahmishal** [comment]
apple/swift-driver#628
apple/sourcekit-lsp#391
@swift-ci please test macOS

**Comment by shahmishal** [comment]
Updated CI job to checkout targeted branch for swift repo for update-checkout config. However, avoid issues for engineers switching from main -> release/5.5 branch. I would recommend also updating the config on main branch.

**Review by tomerd — APPROVED** [review]

**Pull request merged**
