### PR TITLE
remove deprecated code

### PR DESCRIPTION
**Pull request by tomerd**
motivation: cleanup

changes:
* remove check for < macOS 15 which is now the min target
* remove code deprecated in or before 5.4

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@benlangmuir I think this is failing since the delegate on LSP side is has the deprecated methods. can those be removed?

```
/Users/buildnode/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/sourcekit-lsp/Sources/SKSwiftPMWorkspace/SwiftPMWorkspace.swift:449:20: error: type 'BuildSettingProviderWorkspaceDelegate' does not conform to protocol 'WorkspaceDelegate'
```

**Comment by benlangmuir** [comment]
@tomerd yes, go ahead and remove them from sourcekit-lsp (or I can do it on Monday).  We only have these methods because they were required by the protocol and we only use the protocol because it was required to construct a `Workspace`.

**Comment by tomerd** [comment]
@benlangmuir https://github.com/apple/sourcekit-lsp/pull/371

**Review by abertelrud — APPROVED** [review]
Yay!

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Pull request merged**
