### PR TITLE
Add support for newer C++ language standards.

### PR DESCRIPTION
**Pull request by ddunbar**
* This adds support for two newer C++ standards.

### CODE REVIEW

**Comment by ddunbar** [comment]
What do I need to do here w.r.t. package versioning?

**Comment by neonichu** [comment]
You'll need availability annotations. I'm assuming we target 5.3 for this?

```
@available(_PackageDescription, introduced: 5.3)
case cxx17 = "c++17"
```

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Looks good, if this is also going to be merged into the 5.3 branch.  If it's just for master, the availability should be `vNext`.

**Comment by ddunbar** [comment]
Trunk is fine, will change to vNext.

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Pull request merged**
