### PR TITLE
Add distclean command line option

### PR DESCRIPTION
**Pull request by mikehenson**
Add --distclean, a more vigorous version of --clean that also removes
the Packages directory.

### CODE REVIEW

**Comment by Shimmen** [comment]
Sounds reasonable, however, I'm not sure "distclean" is the best possible name for it. Something like "FullClean" or similar would probably be more descriptive. Since it removes everything that is not recreatable by the package manager(?)

**Comment by kostiakoval** [comment]
I think the `distclean` keyword is ok, it's also used in the `make` so some users could be familiar with that termin.
 
`make distclean`
http://www.gnu.org/software/automake/manual/automake.html#Clean

**Comment by Shimmen** [comment]
Well, as long as the majority of Swift PM users understands what it means it should be okay.

**Comment by mxcl** [comment]
This is fine, but I'd prefer a flag that applies to `--clean`. `--clean` is a mode, so there shouldn't be another mode that does the same thing *but more*.

I would like `swift build -kk` in the spirit of `-v` which increases verbosity the more `v`s there are. And `-k` is already the shorthand for `--clean`.

**Comment by mikehenson** [comment]
In this case I think there's a good argument to be made that the "but more" part of the action, plus the fact that this is a *destructive* operation, justifies a separate command for usability reasons. The user might typo another 'k' into the command. It's highly unlikely they'll mistakenly type a full word.

**Comment by mxcl** [comment]
We are following the same usage model as `swiftc` where by modes are distinct and then their properties are modified with options.

Thus it must be a modifier to `--clean` for this to be merged.

**Comment by Nelyus** [comment]
@mxcl has a point, an option de `--clean` makes sense.

I add `--clean --all` and `--clean=all` to the suggestions

**Comment by mikehenson** [comment]
I refactored the code to implement the suggested pattern: --clean[=<mode>], where "build" is the default and "dist" selects the additional behavior.

Git became unhappy with me when I rebased from upstream. If I need to start a new pull request to get clean history, that's no problem.

**Comment by mxcl** [comment]
Thanks, I can rebase.

**Comment by mxcl** [comment]
FYI you never need to make a new PR, you can force push to your fork with the changed history.

**Comment by mxcl** [comment]
Merged: https://github.com/apple/swift-package-manager/commit/985ce46d9e48481cd27394958c44ab7d4bde2d10

**Pull request closed without merging**
