### PR TITLE
Change enum Arch case ppc64le to powerpc64le for PowerPC(ppc64le)

### PR DESCRIPTION
**Pull request by sarveshtamba**
Change enum Arch case ppc64le to powerpc64le for PowerPC(ppc64le)

### CODE REVIEW

**Comment by jakepetroules** [comment]
Please close this, it's redundant with my other pull request #1778

**Comment by sarveshtamba** [comment]
Hi @jakepetroules , any ETA for your pull request [#1778](https://github.com/apple/swift-package-manager/pull/1778) , considering that this is pending for quite a long time now? . The PR #1906 that I have raised is resolving a blocker while building swift toolchain on PowerPC64LE and is a bit urgent. Since this PR #1906 is a small change, chances are this might get merged sooner. Please suggest.

**Comment by aciidb0mb3r** [comment]
Let's take it for now.

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Pull request merged**
