### PR TITLE
[5.4] remove leftover debug print statement

### PR DESCRIPTION
**Pull request by tomerd**
same as #3167

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
Linux failure looks like an infra issue @shahmishal 

> 10:03:05 tar xzf ${WORKSPACE}/latest_toolchain.tar.gz -C ${WORKSPACE}/latest_toolchain
10:03:05 + tar xzf /home/buildnode/jenkins/workspace/swift-package-manager-self-hosted-Linux-smoke-test/branch-release/5.4/latest_toolchain.tar.gz -C /home/buildnode/jenkins/workspace/swift-package-manager-self-hosted-Linux-smoke-test/branch-release/5.4/latest_toolchain
10:03:05 
10:03:05 gzip: stdin: not in gzip format

**Comment by shahmishal** [comment]
I have not released 5.4 toolchains yet, it should be available later today.

**Review by federicobucchi — APPROVED** [review]

**Pull request merged**
