### PR TITLE
[PackageGraph] Diagnose duplicate manifests

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
The Swift 4 package manager does not have the package identity concept
so it is possible for two packages to have the same name. It may or may
not cause issues in practice but we should diagnose and report such
things.

- https://bugs.swift.org/browse/SR-5728
- <rdar://problem/34008219> [SR-5728]: Manifest duplicate command in 'commands' map

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
I'll change manifest to packages as that makes more sense. Also, `/Foo` is the package URL and not the path.

**Comment by aciidb0mb3r** [comment]
@rballard updated

**Comment by rballard** [comment]
Approved for the Swift-4 branch.

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Pull request merged**
