### PR TITLE
Eliminate POSIX

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
The POSIX module in SwiftPM was written before corelibs-foundation was mature enough. This module provided a great value but isn't good in the long term since we want SwiftPM to be as cross-platform as possible.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by aciidb0mb3r** [comment]
Dispatch keeps failing with:

```
15:08:59 <unknown>:0: warning: missing submodule '_SwiftDispatchOverlayShims'
15:08:59 /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/swift-corelibs-libdispatch/src/swift/Block.swift:14:8: error: no such module '_SwiftDispatchOverlayShims'
15:08:59 import _SwiftDispatchOverlayShims
```

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by aciidb0mb3r** [comment]
@swift-ci test

**Comment by aciidb0mb3r** [comment]
Ok, got the full swift test suite to run successfully.

**Comment by therealbnut** [comment]
@aciidb0mb3r Nice, almost entirely removed the POSIX dependency! 🎉

[Sources/swiftpm-manifest-tool/main.swift](https://github.com/aciidb0mb3r/swift-package-manager/blob/19aab0332bf37c40af583969083ab291e1d242b5/Sources/swiftpm-manifest-tool/main.swift) still contains `POSIX.exit`, could that also change to `SPMLibc.exit`?

After that the only remaining POSIX usage seems to be `import enum POSIX.SystemError`.

**Pull request merged**
