### PR TITLE
[Xcodeproj] Add search path to ClangModule's own include dir

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by abertelrud** [comment]
Looks good to me

**Comment by ddunbar** [comment]
Can we get the fix not depending on the other change? I think some details of the escaping need to be sorted out.

As for the fix here... I'm getting worried about fixing Xcode project details without having tests for them. I think we need to come up with a strategy here..

**Comment by aciidb0mb3r** [comment]
I had removed the dep, maybe not refreshed for you yet, try reloading

I agree we need to do something about tests here, suggestions?

**Comment by abertelrud** [comment]
Xcode project generation is fundamentally unwieldy to test in its current form.  I'm writing a simple rendition of the Xcode project model, which can then be independently serialized.  This will allow us to unit test the construction of the project model from input packages, and separately test the serialization of the project model.

**Comment by ddunbar** [comment]
@abertelrud awesome!

**Comment by ddunbar** [comment]
@aciidb0mb3r let's go ahead and get this in, and then get a JIRA on improving our Xcode project testing coverage and discuss there.

**Comment by aciidb0mb3r** [comment]
Tested locally
JIRA for Xcode here: https://bugs.swift.org/browse/SR-2531

**Pull request merged**
