### PR TITLE
Set development boolean to false in versioning

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by ddunbar** [comment]
We should find a way to automate this... I wonder if there are existing variables used on the GM builders we could look at.

**Comment by abertelrud** [comment]
I agree with Daniel — having to set this back and forth is super-error-prone.

**Comment by abertelrud** [comment]
Having said that, we probably need to take this particular diff to make sure that 3.1 is marked properly.  But there should at least be a JIRA to automate it.

**Comment by aciidb0mb3r** [comment]
Filed this: https://bugs.swift.org/browse/SR-4084

**Comment by rballard** [comment]
Approved for the Swift 3.1 branch.

**Comment by rballard** [comment]
Approved for the Swift 3.1 branch.

**Pull request merged**
