### PR TITLE
[PackageDescription] Adopt @available(_PackageDescription)

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This adopts the new _PackageDescription availability "platform" to drive
the available APIs across different tools versions.

<rdar://problem/49983872> Use @available(_PackageDescription) in runtime libraries

### CODE REVIEW

**Comment by jrose-apple** [comment]
Aren't we past version 5 by now?

**Comment by aciidb0mb3r** [comment]
Not yet, there is no API change since Swift 5.

**Comment by jrose-apple** [comment]
Oh. :-/ Are SwiftPM versions going to be different from Swift compiler versions, then?

**Comment by aciidb0mb3r** [comment]
The PackageDescription API is controlled by the compiler "tools version". You just need to specify a valid tools version and SwiftPM will do the right thing. For e.g., if you specify 5.1, you'll get the same 5.0 API (because there is no new addition there) but anyone who wants to build that package will require at least the 5.1 compiler.

**Comment by jrose-apple** [comment]
Ah…I understand now. These are all changes that were released with Swift 5.0, but which couldn't be annotated as such at the time. In that case this looks good.

**Comment by aciidb0mb3r** [comment]
Oh yeah. This PR is just adopting the new compiler feature. We were using manual checks before that I can now rip out.

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Pull request merged**
