### PR TITLE
[package] Update dependencies to 'main' branch

### PR DESCRIPTION
**Pull request by benlangmuir**

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
The following all need to land together:
https://github.com/apple/swift-driver/pull/272
https://github.com/apple/swift-package-manager/pull/2951
https://github.com/apple/sourcekit-lsp/pull/315

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Review by neonichu — APPROVED** [review]

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
@neonichu  is there a way to get the "self hosted" checks to pass?  Since they use `swift package update` so they're pulling swift-driver without the change from https://github.com/apple/swift-driver/pull/272.  Or do we need to force merge

**Comment by neonichu** [comment]
There's no way to get them to pass at the moment, self-hosted doesn't support cross-repo testing.

**Pull request merged**
