### PR TITLE
skip collection perf tests when not desired

### PR DESCRIPTION
**Pull request by tomerd**
motivation: tests too sensitive, need further work

changes: skip unless ENABLE_COLLECTION_PERF_TESTS is set

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Review by abertelrud — COMMENTED** [review]
Is the `get-pip.py` file intended to be in the PR?

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]
LGTM.  Thanks!

**Pull request merged**
