### PR TITLE
Remove `emitSwiftModuleSeparately` option

### PR DESCRIPTION
**Pull request by neonichu**
This option has always been off by default and there are no particular tests for it, so I think we should just remove it since it makes maintaining `SwiftTargetBuildDescription` unnecessarily difficult. From what I can gather, this was supposed to be an optimization for build times that maybe was supposed to be tested, but it ended up never being enabled.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
This will also resolve https://github.com/apple/swift-package-manager/issues/4549 and https://github.com/apple/swift-package-manager/issues/6577

**Comment by neonichu** [comment]
I'm also pretty sure this option hasn't fully worked in a while, there are all these odds differences between this mode and the "regular" one when looking at `SwiftTargetBuildDescription`.

**Comment by tomerd** [comment]
seems reasonable. can git history tell us when/who added it originally? maybe worth checking in and confirming the assumptions

**Comment by neonichu** [comment]
> seems reasonable. can git history tell us when/who added it originally? maybe worth checking in and confirming the assumptions

Yes, it was added in https://github.com/apple/swift-package-manager/pull/2391

**Review by MaxDesiatov — APPROVED** [review]
-185+0 LoC diff, nice 👍

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
For reference, I spoke to Doug and the conclusion was that not only this but also the current default mode should eventually go away and we should use the integrated driver. The refactoring that this is a part of should help us to eventually get there.

**Pull request merged**
