### PR TITLE
Rename Swift.Process to Swift.CommandLine

### PR DESCRIPTION
**Pull request by parkera**
As part of SE-0086, we are renaming Swift.Process to Swift.CommandLine. [Swift PR 3598](https://github.com/apple/swift/pull/3598) covers the standard library part. This covers swiftpm.

### CODE REVIEW

**Comment by ddunbar** [comment]
LGTM

**Comment by parkera** [comment]
@swift-ci Please test and merge

**Comment by parkera** [comment]
Looks like the failure is unrelated:

```
/Users/buildnode/jenkins/workspace/swift-package-manager-PR-osx/swift/test/1_stdlib/Intents.swift:19:37: error: 'INIntentErrorDomain' is only available on iOS 10.0 or newer
```

**Comment by ddunbar** [comment]
If I try this locally my build fails with:
```
/home/ddunbar/public/swift-project/swiftpm/Sources/PackageDescription/Package.swift:91:12: error: use of unresolved identifier 'CommandLine'
        if CommandLine.argc > 0 {
           ^~~~~~~~~~~
```

**Comment by parkera** [comment]
Can you double check that you've got swift `fe932663a8b9119636d8e61711df733f3c9f703e` or later?

https://github.com/apple/swift/commit/fe932663a8b9119636d8e61711df733f3c9f703e#diff-46e60cdf80fdd0f40328fe39481c2bb0R16

**Comment by ddunbar** [comment]
Ah, my mistake -- I had rebuilt compiler but my local toolchain which I use for development hadn't updated. Will test and merge shortly.

**Comment by parkera** [comment]
Thanks!

**Comment by ddunbar** [comment]
Merged in 1d278bb3d77cc1a761a16b6e13b9e5f56cb9d608 (accidentally rebased though so PR didn't update, sorry).

**Comment by parkera** [comment]
Works for me, thanks.

**Pull request closed without merging**
