### PR TITLE
[5.7] Speculatively work around issue with linking concurrency libs

### PR DESCRIPTION
**Pull request by neonichu**
It looks like `swift-build` started crashing in the nightly toolchains since we introduced concurrency into SwiftPM:

```
objc[47001]: Class _TtCs27_KeyedEncodingContainerBase is implemented in both /usr/lib/swift/libswiftCore.dylib (0x7ff851b7d558) and /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-04-23-a.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib (0x10467ed38). One of the two will be used. Which one is undefined.
```

Revert "update example to use async await APIs (#4263)"

This reverts commit 745ce767f82c6d4846f2b003533e8502f953939d.

### CODE REVIEW

**Comment by neonichu** [comment]
We should separately find out what's going on here, eventually we'd like to use concurrency. Also the change remains on `main` for now.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
interesting that the clash is on libswiftCore.dylib not libconcurrency.dylib

**Comment by neonichu** [comment]
> interesting that the clash is on libswiftCore.dylib not libconcurrency.dylib

The concurrency lib also shows up. There's a lot of output, I just truncated it to the first error.

**Pull request merged**
