### PR TITLE
A few fixes for building SwiftPM for MacCatalyst

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Windows build is failing:

```
C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\llvm-project\lldb\source\Plugins\TypeSystem\Swift\SwiftASTContext.cpp(2907): error C2664: 'swift::ASTContext *swift::ASTContext::get(swift::LangOptions &,swift::TypeCheckerOptions &,swift::SILOptions &,swift::SearchPathOptions &,swift::ClangImporterOptions &,swift::symbolgraphgen::SymbolGraphOptions &,swift::SourceManager &,swift::DiagnosticEngine &,llvm::IntrusiveRefCntPtr<llvm::vfs::OutputBackend>,std::function<bool (llvm::StringRef,bool)>)': cannot convert argument 9 from 'bool (__cdecl *)(llvm::StringRef,bool)' to 'llvm::IntrusiveRefCntPtr<llvm::vfs::OutputBackend>'
```

cc @compnerd

**Review by MaxDesiatov — APPROVED** [review]
Thanks!

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by neonichu** [comment]
@tomerd can we force merge this? It is blocking work and I believe we can easily know through code inspection that it won't affect Windows

**Pull request merged**
