### PR TITLE
[5.10] validate local repository has the correct remote

### PR DESCRIPTION
**Pull request by tomerd**
5.10 cherry-pick of #7079

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci test

**Review by MaxDesiatov — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]

**Comment by tomerd** [comment]
@compnerd windows failure seem unrelated. are yo aware?

**Comment by tomerd** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
