### PR TITLE
Add a workflow for shipping signing certificates with SwiftPM

### PR DESCRIPTION
**Pull request by neonichu**
This allows shipping signing certificates with SwiftPM easily, by embedding them into the binary. This uses SwiftPM's new `.embedInCode` feature, but since we cannot use that in production at the moment, we use a dummy package to generate the code and check it in for now.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by yim-lee — APPROVED** [review]

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
nice!

**Comment by neonichu** [comment]
Needed to update CMake config with new file.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
What's the purpose of `empty.sh` file here? It breaks our `soundness.sh` script.

**Comment by neonichu** [comment]
@MaxDesiatov it is needed to be able to establish a target, we don't allow a target with only generated source files today

**Comment by MaxDesiatov** [comment]
Would adding a license header to it to satisfy the soundness script be ok, or would you prefer me to add an exception to the script?

**Pull request merged**
