### PR TITLE
Improve package collection validation error message

### PR DESCRIPTION
**Pull request by yim-lee**
rdar://89172182

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Review by neonichu — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-ci please smoke test Linux

**Comment by yim-lee** [comment]
@swift-ci please smoke test Linux

**Comment by tomerd** [comment]
@swift-ci please smoke test Linux

**Comment by tomerd** [comment]
@swift-ci please smoke test Linux

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
