### PR TITLE
[tooling] improve docker setup & documentation

### PR DESCRIPTION
**Pull request by tomerd**
motivation: easier and more reliable way to test for linux using docker

changes
* remove custom docker file and bootstraping script
* add Dockerfile that is based on swift official docker files
* add docker-compose setup for various Ubuntu and Swift versions
* update contribution documentation

### CODE REVIEW

**Review by abertelrud — APPROVED** [review]
This is great!  Super-helpful especially to have the updated Docker documentation.

**Comment by neonichu** [comment]
Thanks for this, but I'm not sure I agree that it is easier than before :)

Could we retain a simple script for the "default" case like Ubuntu 20.04, Swift nightly that passes the right flags to docker compose?

**Review by neonichu — APPROVED** [review]

**Comment by abertelrud** [comment]
> Thanks for this, but I'm not sure I agree that it is easier than before :)
> 
> Could we retain a simple script for the "default" case like Ubuntu 20.04, Swift nightly that passes the right flags to docker compose? I would assume most people do not want to type out the new, longer commands, so we would be back in a situation where everyone makes their own scripts.

The problem for me was that being custom, even that simple script didn't easily map to any information that could be easily searched for on the web.  Using the docker-compose approach takes out some of the magic, even though there is more to copy and paste into Terminal.  So I prefer this approach.

**Comment by tomerd** [comment]
@neonichu so a real world example invocation would be:

```
docker-compose 
  -f Utilities/docker/docker-compose.yaml 
  -f Utilities/docker/docker-compose.1804.53.yaml 
  run test
```

which runs the tests on Ubuntu 18.04, swift version 5.3

Running on nightly would be:

```
docker-compose \ 
  -f Utilities/docker/docker-compose.yaml \
  -f Utilities/docker/docker-compose.2004.main.yaml \
  run test
```

which runs the tests on Ubuntu 20.04, latest snapshot swift version

---

I think you may be reacting to the docker-compose file chaining, which in our case is really long since the docker-compose files are "buried" in nested directories. we could also have a driver shell script to make it shorter, but this is how we use it in many other projects and usually folks do not have an issue with it.

Also fwiw, the existing setup we had was broken afaict. I started this because it was not usable.

**Comment by neonichu** [comment]
To be clear, my suggestion was adding a script in addition, but not to change the documentation. I don't have any strong feelings about this, though, I can always write my own script.

**Comment by tomerd** [comment]
@neonichu way about me merging this and you adding a driver script on top? feels like you may have something in mind already?

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Sounds good to me 👍

**Pull request merged**
