### PR TITLE
Add fish-tab-completion file

### PR DESCRIPTION
**Pull request by archmagees**
The new added `swift.fish` file is the key to support the fish-tab-completion, please support tab-completion for fish-shell.

### CODE REVIEW

**Comment by abertelrud** [comment]
Thanks for adding this.  My only concern would be that as more shell completions are added, there are more places to maintain whenever a new option is added to SwiftPM.  Would it make sense to contribute to https://github.com/apple/swift-argument-parser/issues/1 so that this completion file can be automatically generated, once SwiftPM adopts ArgumentParser?

**Comment by tomerd** [comment]
hey @archmagees - we are transitioning to using SwiftArgumentParser, so we can probably close this. wdyt?

**Comment by archmagees** [comment]
> hey @archmagees - we are transitioning to using SwiftArgumentParser, so we can probably close this. wdyt?

OK.

**Comment by tomerd** [comment]
@archmagees to echo @abertelrud suggestion above: 

> Would it make sense to contribute to apple/swift-argument-parser#1 so that this completion file can be automatically generated, once SwiftPM adopts ArgumentParser?

**Pull request closed without merging**
