### PR TITLE
--warning (@noescape moved to parameter)

### PR DESCRIPTION
**Pull request by mxcl**

### CODE REVIEW

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Comment by mxcl** [comment]
@swift-ci Please test and merge

**Comment by ddunbar** [comment]
This succeeded, there was just an unrelated failure on Linux.

**Pull request merged**
