### PR TITLE
[PackageGraph] Allow unsafe flags in local and branch-based dependencies

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
<rdar://problem/53557659>
SR-11225

This will lift the restriction of using unsafe flags from local and
branch-based dependencies.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by eonist** [comment]
Is this in Xcode 11.6? Im still getting: The package product 'Some-lib' cannot be used as a dependency of this target because it uses unsafe build flags. 😢

**Comment by bgromov** [comment]
@eonist If you happen to use unsafe flags for the linker `-L` options, have a look at [this workaround](https://stackoverflow.com/q/63064164/13647455).

**Comment by eonist** [comment]
@bgromov nope, I'm trying to use the package with optimisations enabled. I guess SPM isn't ready for optimised modules yet. Which is strange. As performance should be top of mind IMO
`let optimize = [SwiftSetting.unsafeFlags(["-cross-module-optimization", "-O"], .when(configuration: .debug))]`
`swiftSettings: optimize`

**Comment by eonist** [comment]
@bgromov I found a solution. Will share soon.

**Comment by mikolasstuchlik** [comment]
@eonist ping :)

**Comment by eonist** [comment]
Sorry. For reasons out of my hand. I can't share.

**Comment by RenatGafarov** [comment]
its bad(

**Pull request merged**
