### PR TITLE
fix an edge case where binary artifacts have already been downloaded and linger or disk, causing secondary attempt to fail

### PR DESCRIPTION
**Pull request by tomerd**
motivation: some users reported an edge case where the state is reset but the directory lingers, so that the secondary attempt to download and extract the ginary depedency fails

changes:
* extract the downloaded archive to a temporary location
* ensure the destination does not exist prior to moving it from the temporary extraction location to the desired location 
* adjust confusing (test only) function name 
* add and adjust tests

rdar://75975702
rdar://77011310

### CODE REVIEW

**Comment by tomerd** [comment]
cc @neonichu

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@neonichu had to make this a bit more complex, ptal

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Pull request merged**
