### PR TITLE
Allow developing SwiftPM without the bootstrap script

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This will allow building and using the swiftpm binary that was built
using swiftpm. The catch is that only one of the runtime
PackageDescription library will be used since we can't build both
runtimes together.

<rdar://problem/56865514>

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS

**Comment by shahmishal** [comment]
@swift-ci smoke test MaCoS self hosted

**Comment by shahmishal** [comment]
@swift-ci smoke test MaCoS self hosted

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS self hosted

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS self hosted

**Comment by aciidb0mb3r** [comment]
@swift-ci test self hosted

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test self hosted

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test self hosted

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test self hosted

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@benlangmuir Do you know if this is intermittent or did I actually break sourcekit-lsp?

```
20:39:10 Test Case '-[SourceKitTests.SwiftPMIntegrationTests testSwiftPMIntegration]' started.
20:39:10 <unknown>:0: error: -[SourceKitTests.SwiftPMIntegrationTests testSwiftPMIntegration] : failed: caught error: The operation couldn’t be completed. (Build.BuildPlan.Error error 1.)
20:39:10 Test Case '-[SourceKitTests.SwiftPMIntegrationTests testSwiftPMIntegration]' failed (0.081 seconds).
20:39:10 Test Suite 'SwiftPMIntegrationTests' failed at 2019-12-17 20:39:10.497.
20:39:10 	 Executed 1 test, with 1 failure (1 unexpected) in 0.081 (0.081) seconds
20:39:10 Test Suite 'SwiftPMWorkspaceTests' started at 2019-12-17 20:39:10.497
20:39:10 Test Case '-[SKSwiftPMWorkspaceTests.SwiftPMWorkspaceTests testBasicCXXArgs]' started.
20:39:10 Fatal error: 'try!' expression unexpectedly raised an error: the package does not contain a buildable target: file /Users/buildnode/jenkins/workspace/swift-package-manager-PR-osx-smoke-test/sourcekit-lsp/Tests/SKSwiftPMWorkspaceTests/SwiftPMWorkspaceTests.swift, line 327
20:39:10 E[20:39:10.564] Transport error: Input/output error
20:39:10 E[20:39:10.564] Transport error: Input/output error
20:39:10 E[20:39:10.564] Transport error: Input/output error
20:39:10 E[20:39:10.564] Transport error: Input/output error
20:39:10 Exited with signal code 4

```

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test macOS

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test self hosted

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test self hosted

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test macOS self hosted

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test macOS

**Pull request merged**
