### PR TITLE
[NFC] Update `.swiftformat` config for consistency

### PR DESCRIPTION
**Pull request by MaxDesiatov**
### Motivation:

`UserToolchain.swift` was formatted by `swift-format` with a config that's inconsistent with `.swiftformat` committed in the repository, primarily in its use of 2-space indentation.

### Modifications:

Reverted the commit that applies `swift-format`. Also updated `.swiftformat` with more tweaks that codify conventions already established in our repository. Applied new rules to `UserToolchain.swift`

### Result:

Automated formatting in `UserToolchain.swift` is applied.

### CODE REVIEW

**Review by tomerd — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test macOS

**Comment by MaxDesiatov** [comment]
@swift-ci test Windows

**Comment by MaxDesiatov** [comment]
Windows failure in llbuild looks unrelated to me.

**Pull request merged**
