### PR TITLE
Doc updates to module alias overriding

### PR DESCRIPTION
**Pull request by elsh**
Updates to overriding method
More detailed example

### CODE REVIEW

**Comment by elsh** [comment]
@swift-ci smoke test

**Review by neonichu — APPROVED** [review]
LGTM, but should we mention that we are allowing duplicated product names in certain scenarios, as well?

**Comment by elsh** [comment]
> LGTM, but should we mention that we are allowing duplicated product names in certain scenarios, as well?

Sg, will add

**Comment by elsh** [comment]
@swift-ci smoke test

**Pull request merged**
