### PR TITLE
[5.6] use idiomatic location for security directory and update location of configuration directory (#3942)

### PR DESCRIPTION
**Pull request by tomerd**
cherry-pick #3942, #3951, #3952 into 5.6

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci test

**Review by abertelrud — APPROVED** [review]

**Review by yim-lee — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
triggered self-hosted CI job by mistake, those failures are expected on this branch

**Comment by tomerd** [comment]
@swift-ci please test

**Pull request merged**
