### PR TITLE
Fix a crash if a checkout has no a manifest

### PR DESCRIPTION
**Pull request by neonichu**
Will update the PR with a test case if this change is desirable. I'm not sure if it would be better to fail at an earlier stage.

### CODE REVIEW

**Comment by mxcl** [comment]
We should indeed add a fixture for this. I can do it later unless you are keen.

**Comment by neonichu** [comment]
I'd like to do it to familiarise myself a bit with the test suite :)

**Comment by neonichu** [comment]
I added a new file for the test, because the only Git-related ones seemed to be part of the `FunctionalBuildTests`. Let me know if it fits somewhere else better.

**Comment by mxcl** [comment]
https://github.com/apple/swift-package-manager/commit/f86f87b49805ceaf34a937ff73275fd4e54e5d07

**Pull request closed without merging**
