### PR TITLE
Add two `Sendable` annotations to enable building SourceKit-LSP in Swift 6 mode

### PR DESCRIPTION
**Pull request by ahoppen**
- Mark `FileRuleDescription` as `Sendable`
- Make `Platform` sendable and make `Platform.current` a constant

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/sourcekit-lsp/pull/1276

@swift-ci Please test

**Review by xedin — APPROVED** [review]

**Pull request merged**
