### PR TITLE
Move PackageRegistryTool to async/await

### PR DESCRIPTION
**Pull request by AndrewHoos**
Move PackageRegistryTool to async/await

### Motivation:

Continue replacing older concurrency primitives with native async/await

### Modifications:

Replace all usage of temp_await with actual async/await in the PackageRegistryTool

### Result:

One additional executable target that is natively async/await

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]
👍

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by AndrewHoos** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
