### PR TITLE
Signed packages handling in RegistryClient (without swift-crypto)

### PR DESCRIPTION
**Pull request by yim-lee**
https://github.com/apple/swift-package-manager/pull/6184 without adding swift-crypto back to cmake build

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please test Windows

**Comment by yim-lee** [comment]
@swift-ci please test Windows platform

**Comment by yim-lee** [comment]
@swift-ci test Windows platform

**Review by neonichu — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci test Windows platform

**Comment by yim-lee** [comment]
@swift-ci test Windows platform

**Comment by yim-lee** [comment]
@swift-ci test Windows platform

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
@compnerd can you please see if you can help with the Windows build failure

**Comment by compnerd** [comment]
@tomerd that is an infrastructure issue (CC: @shahmishal) - it seems that smoke tests are not cleaning the build directory.

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
