### PR TITLE
restore manifest in-memory cache

### PR DESCRIPTION
**Pull request by tomerd**
motivation: better performance for operations that load manifest often

changes:
* add in-memory cache in ManifesLoader
* only cache JSON parser results and add package location to the cache key to address potential issues such as rdar://73462555 which made us remove such cache in the past
* add test

rdar://73521470
rdar://111346666

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
@swift-ci test

**Review by neonichu — APPROVED** [review]

**Comment by neonichu** [comment]
```
[1602/1602] Testing CommandsTests.TestToolTests/testSwiftTestSkip
Test Suite 'Selected tests' started at 2023-09-29 05:57:49.681Test Suite 'SwiftPMPackageTests.xctest' started at 2023-09-29 05:57:49.683Test Suite 'PackageDescription4_2LoadingTests' started at 2023-09-29 05:57:49.683Test Case '-[PackageLoadingTests.PackageDescription4_2LoadingTests testCaching]' started./Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift:682: error: -[PackageLoadingTests.PackageDescription4_2LoadingTests testCaching] : XCTAssertEqual failed: threw error "timeout waiting for parsing"Test Case '-[PackageLoadingTests.PackageDescription4_2LoadingTests testCaching]' failed (8.120 seconds).Test Suite 'PackageDescription4_2LoadingTests' failed at 2023-09-29 05:57:57.803.
	 Executed 1 test, with 1 failure (1 unexpected) in 8.120 (8.120) secondsTest Suite 'SwiftPMPackageTests.xctest' failed at 2023-09-29 05:57:57.803.
	 Execut
```

Probably related to the changes?

**Comment by tomerd** [comment]
@swift-ci test

**Comment by tomerd** [comment]
for reference, brings back https://github.com/apple/swift-package-manager/commit/48e477aec0a3856a6b7dfdc9c1c30117b0d91259

**Comment by tomerd** [comment]
@swift-ci test windows

**Pull request merged**
