### PR TITLE
[5.6] Fix issues caused by having the plugin subcommand be the default subcommand (#4060)

### PR DESCRIPTION
**Pull request by abertelrud**
This is a 5.6 cherry-pick of #4060. Details in that PR. Motivation: This improves package plugins, a new feature in SwiftPM 5.6.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by abertelrud** [comment]
Rebased and restarting test

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
Rebased and restarting build

**Comment by abertelrud** [comment]
@swift-ci please test

**Pull request merged**
