### PR TITLE
Add resolved* models

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
**on hold**

**Comment by abertelrud** [comment]
The diffs seem good, but could you briefly comment on what the essence of the change is?  Is this mainly a name change (if it is, I think it's a good one, since the multiple types having the same name have been quite confusing) or is it a semantic shift?  It looks like mainly a name change (with some factoring).

**Comment by aciidb0mb3r** [comment]
Yep, as discussed on chat, we used to use same object to represent a loaded (from disk) module and a resolved module. Now they're separate. Thanks for the review!

**Comment by abertelrud** [comment]
Fantastic; thanks for clarifying. 👍

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Pull request merged**
