### PR TITLE
Fix indentations and remove invisibles

### PR DESCRIPTION
**Pull request by federicobucchi**
Fix indentations from 2 to 4 spaces, remove invisibles and tabs

### Motivation:

To have a consistent code style

### Modifications:

- Indentations with 2 spaces changed to 4 spaces.
- Invisibles removed
- Tabs replaced with spaces

### Result:

Code style more consistent (I might have missed some around)

### CODE REVIEW

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Comment by federicobucchi** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Thanks for the cleanup.  My only concern with this is the effect it has on `git annotate` etc.  Also, I think there is now a `.swiftformat` rule file for SwiftPM, which should include taking care of this whitespace, so would it make sense to apply that on a file-by-file basis when they are touched rather than wholesale?

**Comment by federicobucchi** [comment]
@abertelrud I personally don't see an issue on either ways.  I am wondering what changed from the previous approval of the same PR.

**Comment by abertelrud** [comment]
I'm not disapproving it, but raising an alternate suggestion after thinking about it some more.  I'd be curious to hear what @neonichu and @tomerd think.

**Comment by tomerd** [comment]
closing due to age. I think we should reformat the project using `swiftformat` tho

**Pull request closed without merging**
