### PR TITLE
[Build] Add support for stale file removal

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
- <rdar://problem/34260450> Build failure after renaming a C library target

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
Do you think we will get this in 4.1? It would be super useful.

**Comment by aciidb0mb3r** [comment]
I am not sure, I’ll try!

**Comment by aciidb0mb3r** [comment]
Closing until I get time to work on this.

**Pull request closed without merging**
