### PR TITLE
Cleanup addition of swift-syntax

### PR DESCRIPTION
**Pull request by bnbarham**

### CODE REVIEW

**Comment by bnbarham** [comment]
https://github.com/apple/swift/pull/73267

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/apple/swift/pull/73267

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/apple/swift/pull/73267

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/apple/swift/pull/73267
https://github.com/apple/swift-syntax/pull/2628

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/2628

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/2628

@swift-ci please clean test

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/2628

@swift-ci please clean test Windows platform

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/2628

@swift-ci please clean test Windows platform

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/2628

@swift-ci please clean test Windows platform

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/2628

@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/2628

@swift-ci please test Windows

**Review by DougGregor — APPROVED** [review]
This seems to be passing everywhere, woo-hoo!

**Comment by DougGregor** [comment]
Just waiting on https://github.com/apple/swift-syntax/pull/2628 to merge first

**Pull request merged**
