### PR TITLE
Improve diagnostics for missing local package dependency (or other file system error)

### PR DESCRIPTION
**Pull request by abertelrud**
rdar://63478242

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by abertelrud** [comment]
Linux test failed because of:
`    <unknown>:0: error: compiled module was created by an older version of the compiler; rebuild 'XCTest' and try again: /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/XCTest.swiftmodule/x86_64-apple-macos.swiftmodule
    <unknown>:0: error: merge-module command failed with exit code 1 (use -v to see invocation)error: fatalError
`

**Comment by abertelrud** [comment]
@swift-ci please smoke test linux

**Comment by abertelrud** [comment]
@swift-ci please smoke test macos

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Pull request merged**
