### PR TITLE
Initial documentation restructuring.

### PR DESCRIPTION
**Pull request by benwaldie**
This is an initial pass at restructuring the Swift Package Manager documentation. Additional review, content changes, and restructuring pending.

### CODE REVIEW

**Comment by ddunbar** [comment]
This looks awesome, thank you!

**Comment by ddunbar** [comment]
I'll do a more detailed review at some point, but this already looks like it is a major improvement on our existing structure. I'll see if anyone else has an opinion, but I would lean towards merging this ASAP and continuing to iterate on it from there.

**Comment by aciidb0mb3r** [comment]
I agree, this look great direction

**Comment by abertelrud** [comment]
Nice!  I agree, the structure improvements are the most important thing to land as soon as possible, and then we can do the rest with incremental changes.  Thanks, Ben!

**Pull request merged**
