### PR TITLE
[Basic] Add Thread class.

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This class uses Foundation's Thread class to provide similar API on
Linux and OSX.

### CODE REVIEW

**Comment by ddunbar** [comment]
Seems like a reasonable start to me!

**Comment by ddunbar** [comment]
LGTM

**Comment by aciidb0mb3r** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@swift-ci please test linux

**Comment by ddunbar** [comment]
@swift-ci please test linux

**Comment by aciidb0mb3r** [comment]
Linux still broken ☹️

**Comment by aciidb0mb3r** [comment]
CI passed 😱

**Pull request merged**
