### PR TITLE
Remove Target packageAccess param default value

### PR DESCRIPTION
**Pull request by elsh**
Addresses comments from https://github.com/apple/swift-package-manager/pull/6463
Resolves rdar://108361064

### CODE REVIEW

**Comment by elsh** [comment]
@swift-ci smoke test

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
thanks @elsh

**Comment by elsh** [comment]
CI's having connection issues; to be tried again later

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Pull request merged**
