### PR TITLE
Fix typo in PackageDescription.md

### PR DESCRIPTION
**Pull request by tulushev**

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Review by federicobucchi — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]
Thanks for the fix, @tulushev!  Looks like the original source file is correct and it's just the .md that was wrong.

**Comment by abertelrud** [comment]
Not sure what happened with the Linux test.  Trying again.  This is just a .md change so the test failure is extremely likely to be unrelated.

**Comment by abertelrud** [comment]
@swift-ci please smoke test linux

**Pull request merged**
