### PR TITLE
WIP:  Provide libSwiftPM API to allow plugins to be compiled before they are invoked

### PR DESCRIPTION
**Pull request by abertelrud**
Split out compilation of package plugins so it can be done separately from invoking them (typically for collecting diagnostics up-front) and add a `PluginCompilationResult` type that can be returned to clients.

### Motivation:

This allows libSwiftPM clients (and at some point the SwiftPM CLI) to compile plugins separately from running them.

### Modifications:

- mark the compilation function public and clean it up a bit while changing it
- add a struct for returning the results of compiling the plugin (including path to .dia file)
- add a unit test for this functionality

### CODE REVIEW

**Review by tomerd — APPROVED** [review]

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
The `AsyncPackageTests` are failing on Linux...

**Comment by abertelrud** [comment]
> The `AsyncPackageTests` are failing on Linux...

@briancroom This looks related to https://github.com/apple/swift-package-manager/pull/3844?

**Comment by briancroom** [comment]
> > The `AsyncPackageTests` are failing on Linux...
> 
> @briancroom This looks related to #3844?

Yes, that’s right. See discussion:
https://github.com/apple/swift-package-manager/pull/3844#issuecomment-964756500
https://github.com/apple/swift-package-manager/pull/3844#issuecomment-965516667

**Comment by abertelrud** [comment]
> > > The `AsyncPackageTests` are failing on Linux...
> > 
> > 
> > @briancroom This looks related to #3844?
> 
> Yes, that’s right. See discussion: [#3844 (comment)](https://github.com/apple/swift-package-manager/pull/3844#issuecomment-964756500) [#3844 (comment)](https://github.com/apple/swift-package-manager/pull/3844#issuecomment-965516667)

Thanks, Brian!  Sorry, missed those comments.

**Comment by abertelrud** [comment]
> > > > The `AsyncPackageTests` are failing on Linux...
> > > 
> > > 
> > > @briancroom This looks related to #3844?
> > 
> > 
> > Yes, that’s right. See discussion: [#3844 (comment)](https://github.com/apple/swift-package-manager/pull/3844#issuecomment-964756500) [#3844 (comment)](https://github.com/apple/swift-package-manager/pull/3844#issuecomment-965516667)
> 
> Thanks, Brian! Sorry, missed those comments. So that failure alone shouldn't block merging this? (to be clear this PR is still a work in progress, but hopefully soon won't be)

Actually I forgot that I added the unit test already to this PR, so it's ready.

**Comment by abertelrud** [comment]
The failure in the self-hosted test on Linux is known and unrelated (see comments above) and should be resolved when a newer toolchain is used by CI.

**Pull request merged**
