### PR TITLE
Removes nesting inside swift modules

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Removes nesting in swift modules causing these tests to fail
```
FunctionalTestSuite.InvalidLayoutsTestCase/testInvalidLayout4
FunctionalTestSuite.ValidLayoutsTestCase/testMultipleModulesLibraries
```
This will fix the test cases but these are things that can be done : 
* Make nesting invalid layout (currently it fails due to mkdir i think)
* re-support nesting
* do nothing for now

### CODE REVIEW

**Comment by mxcl** [comment]
I have no test failures. Why do you?

**Comment by aciidb0mb3r** [comment]
```
─aciid@AciidHome  ~/mycode/swift.org/swift-package-manager/Fixtures/InvalidLayouts/Generic4  ‹master*›
╰─$ sb
Compiling Swift Module 'Foo' (1 sources)
<unknown>:0: error: error opening '/Users/aciid/mycode/swift.org/swift-package-manager/Fixtures/InvalidLayouts/Generic4/.build/debug/Foo.build/Bar/Foo.swift.o' for output: No such file or directory
<unknown>:0: error: build had 1 command failures
error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-03-11-a.xctoolchain/usr/bin/swift-build-tool -f /Users/aciid/mycode/swift.org/swift-package-manager/Fixtures/InvalidLayouts/Generic4/.build/debug.yaml default
```

**Comment by aciidb0mb3r** [comment]
might be because of outdated toolchain, checking.

**Comment by aciidb0mb3r** [comment]
Yeah, looks like this is now taken care by llbuild and was in newer toolchain, sorry.

**Comment by mxcl** [comment]
np, this was my bad, I should have advised that this may happen when I created commands for `mkdir` in the yaml with a recent PR.

**Pull request closed without merging**
