### PR TITLE
[Collections] Support multiple cert pinning configs per domain

### PR DESCRIPTION
**Pull request by yim-lee**

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please smoke test macOS

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please smoke test macOS

**Comment by tomerd** [comment]
```
23:21:40 Undefined symbols for architecture x86_64:
23:21:40   "swift::swift51override_conformsToSwiftProtocol(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*, __swift::__runtime::llvm::StringRef, swift::TargetProtocolConformanceDescriptor<swift::InProcess> const* (*)(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*, __swift::__runtime::llvm::StringRef))", referenced from:
23:21:40       _Swift50Overrides in libswiftCompatibility50.a(Overrides.cpp.o)
23:21:40 ld: symbol(s) not found for architecture x86_64
23:21:40 
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

@shahmishal CI infra issues?

**Comment by shahmishal** [comment]
Can please share link to the failure?

**Comment by yim-lee** [comment]
@shahmishal https://ci.swift.org/job/swift-package-manager-PR-macos-smoke-test/3244/console

**Comment by shahmishal** [comment]
Sounds like it's flakiness, we should file a bug (bugs.swift.org).

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Pull request merged**
