### PR TITLE
build: explicitly specify the SwiftCrypto API version

### PR DESCRIPTION
**Pull request by compnerd**
Ensure that we indicate that we are using the Swift Crypto API v2 when building.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @yim-lee

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Review by yim-lee — APPROVED** [review]

**Comment by compnerd** [comment]
I _think_ that this gets further?  There is a separate PR for the `getpass` failure.

**Comment by compnerd** [comment]
I'm going to go ahead and merge this as we are dealing with the `getpass` separately.

**Pull request merged**
