### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by tomerd**
remove Ankit, add Tomer

### CODE REVIEW

**Review by abertelrud — APPROVED** [review]

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
We’ll probably need to get this into the 5.4 branch before we can merge PRs such as https://github.com/apple/swift-package-manager/pull/3177 with just your approval, but since I’m already listed as code owner, I can approve the cherrypick of this one to the 5.4 branch and then your approval for #3177 should be sufficient.

**Comment by abertelrud** [comment]
This looks good to me.  @tomerd should we merge this to main, then I’ll approve a 5.4 cherry-pick branch and then that should let use merge the other 5.4 PRs that have your approval?

**Comment by tomerd** [comment]
>  @tomerd should we merge this to main, then I’ll approve a 5.4 cherry-pick branch and then that should allow merging of the other 5.4 PRs that already have your approval? (so that this technicality doesn't hold up merging changes that have been approved in principle)

yes

**Pull request merged**
