### PR TITLE
Fix error message

### PR DESCRIPTION
**Pull request by valeriyvan**
### Motivation:

Following error message has word "sources" duplicated:

```
error: 'swift-png': target 'PNGUnitTests' has sources overlapping sources: /Users/*****/swift-png/tests/unit/XCTestManifests.swift, /Users/*****/swift-png/tests/unit/PNGTests.swift
```

### Modifications:

Fixed above error message into following:
```
error: 'swift-png': target 'PNGUnitTests' has overlapping sources: /Users/*****/swift-png/tests/unit/XCTestManifests.swift, /Users/*****/swift-png/tests/unit/PNGTests.swift
```

### Result:

👆🏻

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Looks like there is a test that needs updating, too:

```
Test Suite 'Selected tests' started at 2022-11-30 15:23:53.557Test Suite 'PackageBuilderTests' started at 2022-11-30 15:23:53.558Test Case 'PackageBuilderTests.testCustomTargetPathsOverlap' started at 2022-11-30 15:23:53.558[error]: target 'barTests' has overlapping sources: /target/bar/Tests/barTests.swift
/home/build-user/swiftpm/Tests/PackageLoadingTests/PackageBuilderTests.swift:710: error: PackageBuilderTests.testCustomTargetPathsOverlap : XCTAssertTrue failed - unexpected failure matching 'target 'barTests' has overlapping sources: /target/bar/Tests/barTests.swift' against pattern equal("target \'barTests\' has sources overlapping sources: /target/bar/Tests/barTests.swift")Test Case 'PackageBuilderTests.testCustomTargetPathsOverlap' failed (0.012 seconds)Test Suite 'PackageBuilderTests' failed at 2022-11-30 15:23:53.570Executed 1 test, with 1 failure (0 unexpected) in 0.012 (0.012) secondsTest Suite 'Selected tests' failed at 2022-11-30 15:23:53.570Executed 1 test, with 1 failure (0 unexpected) in 0.012 (0.012) seconds
```

**Comment by tomerd** [comment]
@swift-ci smoke test

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
thank you @valeriyvan

**Pull request merged**
