### PR TITLE
refactor signature handling validations

### PR DESCRIPTION
**Pull request by tomerd**
motivation: code cleanup

changes:
* extract signature validation to a seperate function
* use guards to improve readability

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
@yim-lee

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by yim-lee — APPROVED** [review]

**Pull request merged**
