### PR TITLE
Clean up non-core commands

### PR DESCRIPTION
**Pull request by neonichu**
This separates out the collections and registry commands from the `Commands` module, allowing to simplify the first stage of bootstrap:

- Moves the command implementations to new modules `PackageCollectionsTool` and `PackageRegistryTool`.
- Adds a new multi-tool entry point executable `swift-package-manager`. This used to be included in `swift-package`, but that would render the separation moot and also seems like a better structure. For installation into the toolchain, we're simply installing the new executable under the name `swift-package`, so nothing changes there.
- Remove package-collections related stuff from the CMake build, it was anyway completely unused.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
> * Moves the command implementations to new modules `PackageCollectionsTool` and `PackageRegistryTool`.

Based on this, would you like `experimental-destinations` command introduced in https://github.com/apple/swift-package-manager/pull/5911 to be moved to a separate module too?

**Comment by neonichu** [comment]
> Based on this, would you like experimental-destinations command introduced in https://github.com/apple/swift-package-manager/pull/5911 to be moved to a separate module too?

I think it's fine to be in `Commands` since it doesn't need further dependencies. The main goal of this is to thin out the number of things that need to be built with CMake and to ideally not grow them.

**Comment by neonichu** [comment]
> --- bootstrap: note: Installing /home/build-user/build/buildbot_incremental/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/release/swift-package-manager to /home/build-user/build/buildbot_incremental/toolchain-linux-x86_64/usr/bin/swift-package/swift-package-manager

Looks like the change to `bootstrap` is not quite right, it is creating a directory called `swift-package` 😆

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]
🥳

**Comment by tomerd** [comment]
cc @yim-lee

**Comment by neonichu** [comment]
@swift-ci please test package compatibility

**Comment by neonichu** [comment]
Hmmmm

> [/Users/ec2-user/jenkins/workspace-private/swift-package-manager-source-compat-suite-PR-macos/swift/utils/build-script] ERROR: can't find CMake (please install CMake)

Is that an infra issue, @shahmishal?

**Comment by neonichu** [comment]
@swift-ci please test package compatibility

**Comment by MaxDesiatov** [comment]
> * Adds a new multi-tool entry point executable `swift-package-manager`.

Is this new multi-tool entry point supposed to be the only one available? Is there much sense in declaring separate `executableTarget`s for new top-level commands, in addition to adding a case to this entrypoint?

**Comment by neonichu** [comment]
> Is this new multi-tool entry point supposed to be the only one available? Is there much sense in declaring separate executableTargets for new top-level commands, in addition to adding a case to this entry point?

Yes, for two reasons:
- not all platforms support symlinks in the way Unix-style platforms do, so e.g. on Windows we will not use the multi-tool but instead the individual binaries
- for local testing/debugging, it can be useful to just build and run the individual tools, especially because the symlinking is not something that we can currently express in SwiftPM, so only builds with the `bootstrap` scripts have them.

**Review by Lishkk — APPROVED** [review]

**Pull request merged**
