### PR TITLE
`PackageGraph.computeTestTargetsForExecutableTargets() is incorrectly affected by plugin usage

### PR DESCRIPTION
**Pull request by abertelrud**
A target's use of a plugin is represented as a kind of dependency, but this should not influence the test association.  Otherwise every test that depends on a library that uses a plugin seems to be associated with every other target that uses the plugin.

### Motivation

This function is returning wrong results, causing tests of targets that use plugins to be incorrectly associated with other targets that use those same plugins.

### Modifications

- filter out plugin target dependencies
- add a unit test

rdar://101564030

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by abertelrud** [comment]
This one doesn't look directly related to this change:
```
'dyld: lazy symbol binding failed: can'\''t resolve symbol _$ss13_runAsyncMainyyyyYaKcF in /var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/spm-tests-testPrebuildPluginShouldNotUseExecTarget.muvu8T/plugin-cache/X because dependent dylib /usr/lib/swift/libswift_Concurrency.dylib could not be loaded
dyld: can'\''t resolve symbol _$ss13_runAsyncMainyyyyYaKcF in /var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/spm-tests-testPrebuildPluginShouldNotUseExecTarget.muvu8T/plugin-cache/X because dependent dylib /usr/lib/swift/libswift_Concurrency.dylib could not be loaded
```

**Comment by abertelrud** [comment]
Seeing the same in all the PRs actually...

**Comment by neonichu** [comment]
Probably same as rdar://problem/101582542, https://github.com/apple/swift-package-manager/pull/5834 added some plugin tests that aren't guarded by `supportsSwiftConcurrency`

**Comment by abertelrud** [comment]
@swift-ci please smoke test macos

**Pull request merged**
