### PR TITLE
Add `subsetDescriptor` to completion message

### PR DESCRIPTION
**Pull request by neonichu**
If we build just a specific product or target, add a `subsetDescriptor` to the complete message. This improves the confusing output when plugins are using executables, because we end up with multiple 'Build complete' messages.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Looks like a few tests need updates.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
Looks like I missed something in `IntegrationTests`.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
@swift-ci please test linux

**Review by tomerd — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]
Nice!

**Pull request merged**
