### PR TITLE
Pass through shell script build phase environment and working directory for build tool commands

### PR DESCRIPTION
**Pull request by abertelrud**
Use the new LLBuildManifestWriter support to pass through shell script build phase environment and working directory for build tool commands.

This PR builds on https://github.com/apple/swift-package-manager/pull/3332

### Motivation:

Plugin-created commands should be able to specify environment and initial working directory for those commands.

### Modifications:

- make build tool commands write out the llbuild environment entries and initial working directory path using the support added in https://github.com/apple/swift-package-manager/pull/3332
- add a unit test that requires both of these features in order to build successfully

rdar://74663489

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Note: This should only be merged _after_ https://github.com/apple/swift-package-manager/pull/3332 since every PR is a squash now but the changes should be separate in the revision history.

**Comment by abertelrud** [comment]
Eek:

`error: command Generating foo.swift from foo.dat failed: working-directory unsupported on this platform`

Ok, that's disappointing.  That will require an `llbuild` fix.

**Comment by abertelrud** [comment]
Oh right, it's because it uses `pthread_chdir_np()` which is only supported on Darwin.  In this case we can probably work around it by wrapping it in a shell and prepending a `cd`.

**Comment by abertelrud** [comment]
It's a little annoying — supporting initial working directory is mostly for completeness.  Build tools should in general take full paths and not rely on a custom working directory.  We'll need to decide whether supporting relative paths (arguably an anti-pattern) is important enough to put in workarounds, or whether it's better to leave it out and just have the plugin form the path.

**Comment by abertelrud** [comment]
I think what I'm going to do here is to remove the working directory functionality for now.  It's not so important as to steal time from other things (such as better diagnostics, etc), and it is straightforward to add later.

**Comment by artemcm** [comment]
@swift-ci please smoke test linux

**Comment by abertelrud** [comment]
Updated to mark the ability to set a working directory as not yet available, and updated unit test.

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Pull request merged**
