### PR TITLE
fix silent crash when output from compiler is too large

### PR DESCRIPTION
**Pull request by tomerd**
motivation: silent crashes, confused uers

changes:
* change the order in swiftCompilerOutputParser such that print the stdout happens before any parsing attenpts are made
* constraint the parsing attempts to output < 10k, since otherwise they struggle to complete

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
```
00:58:45 Test Case '-[PackageCollectionsTests.PackageCollectionsTests testUpdateAuthTokens]' started.
00:58:45 Exited with signal code 11
00:58:45 Build step 'Execute shell' mar
```

cc @yim-lee

**Comment by tomerd** [comment]
@swift-ci please smoke test macOS

**Comment by yim-lee** [comment]
> seems like some race condition there?

I suppose it doesn't hurt to use `ThreadSafeKeyValueStore` instead: https://github.com/apple/swift-package-manager/pull/3479

**Review by neonichu — APPROVED** [review]

**Pull request merged**
