### PR TITLE
Move common build types to a new SPMBuildCore target

### PR DESCRIPTION
**Pull request by hartbit**

### CODE REVIEW

**Comment by hartbit** [comment]
@swift-ci smoke test

**Comment by hartbit** [comment]
@swift-ci smoke test

**Comment by hartbit** [comment]
Please test with following pull request:
apple/sourcekit-lsp#250

@swift-ci smoke test

**Comment by hartbit** [comment]
Please test with following pull request:
apple/sourcekit-lsp#250

@swift-ci smoke test

**Comment by hartbit** [comment]
Please test with following pull request:
apple/sourcekit-lsp#250

@swift-ci smoke test

**Comment by hartbit** [comment]
@aciidb0mb3r Ready to merge, but requires merging https://github.com/apple/sourcekit-lsp/pull/250 at the same time to avoid CI to fail.

**Comment by aciidb0mb3r** [comment]
This got into conflicts

**Comment by hartbit** [comment]
Please test with following pull request:
apple/sourcekit-lsp#250

@swift-ci smoke test

**Pull request merged**
