### PR TITLE
[5.9] Cross-compilation: fix support for `.tar.gz` bundles

### PR DESCRIPTION
**Pull request by MaxDesiatov**
### Motivation:

`swift experimental-destination install` subcommand fails when pointed to a destination bundle compressed with `.tar.gz` extension, compressed with tar and gzip. This archival format is vastly superior to zip in the context of cross-compilation destination bundles. In our typical scenario we see that `.tar.gz` archives are at least 4x better than `.zip`. Since in absolute terms this amounts to multiple gigabytes, this has substantial impact on the amount of time and traffic taken by downloading and installing such bundle archives.

rdar://107485048

### Modifications:

Added `TarArchiver` and `UniversalArchiver` types that support `.tar.gz` archives. `UniversalArchiver` is now used in `InstallDestination` instead of `ZipArchiver`.

### Risk

Low, since the change is isolated to the cross-compilation destinations feature and is covered with tests.

### Result:

`.tar.gz` destination bundle archives are now supported.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by tomerd — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by neonichu — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
