### PR TITLE
[Commands] Add option to skip updating dependency from remote

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
Nice! What will happen if a dependency had to be pulled to solve? Ideally I think this just only skips the optional updates, what do you think?

**Comment by aciidb0mb3r** [comment]
Yep, this will still pull the dependency if its not present. It just won't update it from its remote.

**Pull request merged**
