### PR TITLE
Make AbsolutePath adopt CustomStringConvertible instead of having a custom `asString` property

### PR DESCRIPTION
**Pull request by abertelrud**
Make AbsolutePath adopt CustomStringConvertible, adopting the standard `String(x)` form for accessing the path instead of having a special `asString` property.  This brings us in line with API guidelines for string representations.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
I'm not sure about this... is it really right to use the `description` of a `Path` as the canonical way to get its string? I think it is useful for a Path to report itself as such when rendered to text, and I think code should be explicit about when it is getting the string form of the Path -- in particular because this method should almost never be used, and so it is a useful signifier of "wait, is that really what you should be doing?"

**Comment by abertelrud** [comment]
I can see both ways.  One warning sign about an `asString` property is that almost no other class in stdlib or Foundation have an `as<Type>` property.

I would note that CustomStringConvertible isn't billed as a protocol to use for *display* strings, though it may be in practice.

I also disagree that it should almost never be used, as the conversation I've been doing shows:  there are lots of cases in which we, for example, pass paths on command lines.

So in this case I would suggest that we create a new protocol specifically for cases in which a string or a path can be passed, and that we make things like popen() or whatever take those.  I'm having to do a lot of "asString" in the code without any clear way around it.

**Comment by ddunbar** [comment]
I think in most of those cases we should be pushing `Path` down, though, not converting to a string. We should discuss more how to handle this w.r.t. the POSIX module... either via a protocol or by sinking `Path` lower.

I'm fine with finding a different name to represent the property other than `asString`.

The definition for `CustomStringConvertible` is a "textual representation of the object", not necessarily a conversion of the object to `String`. For example, the synthesized description for structs looks something like `Point(x: N, y: N)` (an example from the stdlib docs). I would expect the representation for path to be something like `Path("/foo/bar")`.

**Comment by abertelrud** [comment]
Yes, it's the pushing-down of `Path` that I'm talking about, and what those APIs would look like.

Setting aside for the moment whether it is advisable to have `popen()` at all, an API such as that would need to support `popen(["cc", "-c", inputPath, "-o", outputPath])` in order to avoid calls to `asString`.

What I was suggesting in my last paragraph in my previous comment was that the most sensible approach for that would be to have `popen()` not take an `[String]` but instead a new `[CommandLineArgStringConvertible]` or something like that, and then make `String` and `Path` both conform to it.

Without that, we're going to need a lot of `path.asString`.

I have also been wanting to come up with protocols to avoid having to think about quoting in the client code, and instead do so in the "consumer" of those paths.  But for the moment I want to make call sites that work with paths look as clean as possible.

**Comment by abertelrud** [comment]
Meanwhile, I am going to withdraw this pull request.

**Pull request closed without merging**
