### PR TITLE
Disable CMake bootstrap by default

### PR DESCRIPTION
**Pull request by neonichu**
It sounds as if we shouldn't need this anymore.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Review by MaxDesiatov — APPROVED** [review]

**Comment by finagolfin** [comment]
What is the intent of this pull? I added this bootstrap flag in #3000 three years ago, but it does nothing for the native CI when enabled. I checked the CI runs for this pull and it had no effect on linux or macOS (the Windows CI doesn't build SwiftPM or use the Python build scripts). There are three common scenarios when building SwiftPM:

1. Building a full native toolchain from source - this flag does nothing in that case, as shown on the CI.
2. Building SwiftPM alone with a prebuilt Swift toolchain that has a prebuilt SwiftPM - I showed how to do that with `build-script` in my original pull, and this change will get that working without the kind of additional patching shown there.
3. Cross-compiling a Swift toolchain by using a native Swift toolchain that has a native SwiftPM - this is the usecase I added this for, and I can remove [the invocation of this flag that I added for non-Darwin cross-compilation](https://github.com/apple/swift/blob/ae6ff02d1be440faa6e4e14296b04fbb02d341fb/utils/swift_build_support/swift_build_support/products/swiftpm.py#L104) now that it is enabled by default here.

If you want to enable 1. also, you will need some way for the bootstrap script to distinguish between the freshly-built trunk toolchain in `/home/build-user/build/buildbot_incremental/toolchain-linux-x86_64/`, which doesn't have SwiftPM, and the prebuilt 5.8.1 toolchain on the linux CI at `/opt/swift/5.8.1/`, which does. Currently, the bootstrap script isn't aware of and doesn't use the prebuilt 5.8.1 toolchain for the SwiftPM build at all, so simply changing this default does nothing on the CI.

**Comment by neonichu** [comment]
Thanks, good catch. I had only verified that this does what I expected locally but not on CI. So seems like this isn't a sufficient change.

**Comment by neonichu** [comment]
To answer your question about the intent, we'd like to remove the CMake portion of the build entirely at some point, I (mistakenly) thought this would be an easy way to preflight that idea in all workflows that use bootstrap.

**Comment by neonichu** [comment]
Going to revert this since it is incomplete as-is.

**Pull request merged**
