### PR TITLE
Require test methods to be contained in allTests

### PR DESCRIPTION
**Pull request by briancroom**
I've been thinking about how best to approach [SR-32](https://bugs.swift.org/browse/SR-32), and this is the best that I've come up with so far. I've created an `XCTestCase` subclass that is used on Mac which overrides `invokeTest` and emits a failure if the current test's selector doesn't have a corresponding entry in the class' `allTests` array.

It's not a terribly satisfactory solution to the bug mentioned above, because....
1. It only works if people creating new test cases remember to subclass/adopt `TestCase` instead of `XCTestCase`
2. It's specific to SPM and can't be automatically applied to other projects. Because folks running their tests where the dynamic discovery is available are linking with the system's `XCTest`, I don't know if there'd be any way to make this work out of the box unless Apple's internal `XCTest` takes it on.

...but I wanted to get this out there for discussion. I've caught lots of missing test entries while working on this, so I feel there is value in it already.

### CODE REVIEW

**Comment by mxcl** [comment]
Great! Thanks.

I wonder if a protocol extension could be used instead? We could extend `tearDown()` since I'm pretty sure the `XCTestCase` version is empty.

**Comment by briancroom** [comment]
Ooohh, great thinking. I've updated it to hook into the runner by adding an `XCTestCase` extension, removing the subclass. I'm pretty happy with this now!

**Comment by mxcl** [comment]
The history has gone awry here, can we rebase?

**Comment by briancroom** [comment]
Oh shoot, I did manage to botch things up pretty badly there somehow. It should be all cleaned up now @mxcl

**Comment by mxcl** [comment]
Testing this found one missing test already :)

**Comment by briancroom** [comment]
:tada: I'm happy to give up the job of watching for missing tests 😆

**Comment by ddunbar** [comment]
Thanks Brian!!! :clap:

**Pull request merged**
