### PR TITLE
[5.8] Fix product lookup

### PR DESCRIPTION
**Pull request by neonichu**
For module aliasing, we changed the product lookup to include package identity, but product references can use a local identity as specified by the `name` attribute of the package dependency declaration. So for packages where the local `name` attribute didn't match the identity, we would not longer find the corresponding products at all. This switches us back to use the local identity that is also called `explicitNameForTargetDependencyResolutionOnly` in package reference.

rdar://107841270

(cherry picked from commit afcd86a76b62b382f8ed98ec87b7ce5a67884b19)

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
The new test needs to be fixed to work with 5.8

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
I didn't commit my test changes...

**Comment by neonichu** [comment]
@swift-ci please smoke test windows

**Comment by neonichu** [comment]
@swift-ci please smoke test windows

**Comment by neonichu** [comment]
Closing since we’re not taking this in 5.8

**Pull request closed without merging**
