### PR TITLE
move global functions to a namespace

### PR DESCRIPTION
**Pull request by tomerd**
motivation: namespaced code is good code

changes: move global funcitons in the XcodeProject module to a namespace

### CODE REVIEW

**Comment by tomerd** [comment]
this got in the way of https://github.com/apple/swift-package-manager/pull/4173, but doing a separate PR to keep scope down

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test Linux

**Review by neonichu — APPROVED** [review]

**Pull request merged**
