### PR TITLE
Update the Swift version to 5.6.3

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Review by tomerd — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Comment by shahmishal** [comment]
```
CMake Error at C:/Users/swift-ci/jenkins/workspace/swiftpm-PR-windows/swift-corelibs-foundation/cmake/modules/XCTestAddTests.cmake:45 (message):
  Error running test executable.
```

Is this know issue with Windows on release/5.6? cc: @compnerd

**Comment by compnerd** [comment]
@shahmishal nope; that isn't a known issue.  Are the full toolchain builds working?  It seems like it could be a path issue?

**Comment by shahmishal** [comment]
@compnerd This is release/5.6 branch, not sure if it supports build toolchain script for windows. We currently only have post-merge CI for main branch for Windows.

**Comment by shahmishal** [comment]
@compnerd will you be able to look into this soon? Trying to figure out if I should merge the change or not. 

cc: @tomerd

**Comment by compnerd** [comment]
The change itself should be okay; the failure is to launch `TestFoundation` to enumerate tests.  We should look into why that is suddenly occurring, but won't get a chance to look into this for a few days likely.

**Review by compnerd — APPROVED** [review]
I'd say that this change is definitely not responsible for that, and should be quite safe to merge even for Windows.

**Pull request merged**
