### PR TITLE
rename flags for repositories cache

### PR DESCRIPTION
**Pull request by tomerd**
motivation: clearer flags, happier users

changes:
* deprecate global "skip-cache" flag
* introduce "--disable-repositories-cache" flag for disabling repositories cache
* update flag help
* adjust call-site

### CODE REVIEW

**Review by abertelrud — APPROVED** [review]
Looks good to me!

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
cc @neonichu

**Review by neonichu — APPROVED** [review]

**Pull request merged**
