### PR TITLE
[WIP] add --chdir argument to swift-test

### PR DESCRIPTION
**Pull request by kostiakoval**
Add ability to change directory before running tests. 
I think it would be very useful, because we can do similar when running `swift-build`

Example: `swift-test --chdir myProject/A`

### CODE REVIEW

**Comment by mxcl** [comment]
We shouldn't duplicate all this code.

**Comment by kostiakoval** [comment]
I wanted to refactor and reuse Cruncher and Options for both swift-build and swift-test in the future. But I can try to do it now.

**Comment by czechboy0** [comment]
If this goes in it'll **really** help me with running `swift test` in tests in #213. Can I help here to bring it up to speed again? :blush:

**Comment by kostiakoval** [comment]
Sure. What option do you need to add ti `swift test`? I will start working it tomorrow. 
Need some time to enjoy Apple Event :)

**Comment by czechboy0** [comment]
`--chdir` so that I can easily switch to a fixture's root.

**Comment by czechboy0** [comment]
LGTM, but has conflicts. I'm really keen on getting this in - will allow for easier testing of package hierarchies for swift-test. @kostiakoval can you bring this branch up to speed please?

**Comment by mxcl** [comment]
I can probably find the time to DRY this.

**Comment by kostiakoval** [comment]
I've fixed the merge conflict. If it's ok with you to merge it and refactor it later then let's do it.

**Comment by aciidb0mb3r** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
We shouldn't intentionally copy and paste code.

**Comment by kostiakoval** [comment]
Ok, do you have any tips on implementing it. Should we reuse both Cruncher, Options and Mode bot for build and test?
Then the enum doesn't fits that need because we can't reuse signe `case` items. Like I want only to get 
`--chdir` Mode for `swift-test`

**Comment by mxcl** [comment]
I'll do it now.

**Comment by mxcl** [comment]
Closing as suceded by: https://github.com/apple/swift-package-manager/pull/241

**Pull request closed without merging**
