### PR TITLE
[5.4] fix "build complete" message

### PR DESCRIPTION
**Pull request by tomerd**
brings #3313, #3352, #3353 to 5.4

rdar://77669218

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
@shahmishal CI issues? https://ci.swift.org/job/swift-package-manager-PR-Linux/380/console

**Comment by tomerd** [comment]
@swift-ci please test

**Review by abertelrud — APPROVED** [review]

**Comment by tomerd** [comment]
unrelated CI issue, @swift-ci please test Linux

**Pull request merged**
