### PR TITLE
[PackageLoading] replace Next with 5.4 according to notes left previously

### PR DESCRIPTION
**Pull request by WowbaggersLiquidLunch**
It's like #3170, but for the main branch.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Comment by WowbaggersLiquidLunch** [comment]
I left a comment in #3170 about a bit of code that might need some closer look at. Since both PRs are from the same branch, please _**do not**_ merge this yet.

**Comment by abertelrud** [comment]
Thanks @WowbaggersLiquidLunch.  Converting to Draft to make sure it doesn't get merged yet.  Will take a look at the other PR, though I don't have immediately the context here, so it will take a little digging.

**Comment by abertelrud** [comment]
@WowbaggersLiquidLunch Took a look at #3170 and based on the latest revisions, it seems correct now.  Do those edits need to be added here as well?

**Comment by abertelrud** [comment]
Actually, I see now that you already did, so do you feel that this is ready for review?

**Comment by WowbaggersLiquidLunch** [comment]
Yep, I think it's ready for review now. Thanks for checking #3170!

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please smoke test linux

**Comment by abertelrud** [comment]
This looks good now that the tests have passed, @WowbaggersLiquidLunch.  Is this ready to be merged (and then the other PR nominated to 5.4) as far as you are concerned?

**Comment by WowbaggersLiquidLunch** [comment]
Yep, this PR and #3170 are ready to be merged as far as I'm concerned. Thanks for getting the tests to pass!

**Comment by abertelrud** [comment]
Great, thanks!  Merging this one and will ask for 5.4 approval for https://github.com/apple/swift-package-manager/pull/3170.  Thanks for fixing this!

**Pull request merged**
