### PR TITLE
[Xcodeproj] Use NSDictionary/NSKeyedArchiver in generate()

### PR DESCRIPTION
**Pull request by ultramiraculous**
I'm looking at swapping out some of the manual file-building in the Xcodeproj. The current generators are manually building XML and, as noted in the TODO, manually build XML with string interpolation w/ no attempt at escaping.

Is this a reasonable goal to pursue?

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
I am not sure if we should do this, it'll make the project generation slower.
I think escaping string in TODO refers to handle edge cases like spaces in paths etc

**Comment by ddunbar** [comment]
I actually would love to move towards generating the Xcode project via more structured objects... it might be a little slower but in practice I don't think it should matter, and the benefits in terms of code maintainability and readability would be huge.

I would prefer that we do it by introducing actual strongly-typed objects to model the different kinds of objects. At that point the serialization itself should be mostly an implementation detail of those objects, and I do agree with @aciidb0mb3r I don't see a need to go through NSDictionary for it (in part because I would like to write out the old-style plist that Xcode uses to archive, which is not supported via the Foundation APIs).

@ultramiraculous do you feel like using this PR to go in that direction?

**Comment by ultramiraculous** [comment]
Yeah, for sure. 

I've actually got a bunch of other work done already doing object-based generation of the project file, which is mostly done. I was honestly just testing the waters here before I put more work into it/dropped a bunch of code. 

Also on the subject of the old plist style, Xcode will accept XML plists just fine (though it almost immediately rewrites them in the ASCII style). If you look at a project generated by [buck](https://github.com/facebook/buck), you can see this in action.

**Comment by ddunbar** [comment]
Woot, that is great news yes we would love to move that direction.

With regard to the XML plist I know that is true (and in fact also work on parts of Xcode responsible for loading), but it has never been officially supported and I would prefer we stick to the standard format. That is also because I know it is simple enough to generate the old-style format performantly, and I'm happy to help iterate on the code for it if you feel it is more burdensome versus using the Foundation APIs.

**Comment by aciidb0mb3r** [comment]
There is also the problem of Xcode reloading the file when the project is open. Right now we compare and regenerate the files on disk only if they need to be updated so Xcode doesn't reload the project.

**Comment by aciidb0mb3r** [comment]
I guess its not a big issue but users might find it annoying pehaps

**Comment by abertelrud** [comment]
Having an object-oriented way to generate both Xcode projects and scheme files would be great.  As Daniel explained, the way to do this is to have the specific text being rendered be just an implementation detail.

As for NSArchiver, that cannot technically be used, since Xcode project files aren't archives in the Foundation sense.

Over the long term, we probably don't want to have SwiftPM generating Xcode projects, since that necessarily puts some limitations on the level of integration we can achieve.  It would be great to clean this up, but just be aware that there's probably an expiration date on the code that generates Xcode projects by hand.

**Comment by ultramiraculous** [comment]
I'm fine with an expiration date if it comes alongside deeper integration 😛

**Comment by ddunbar** [comment]
Closing this for now just to keep the pending PR queue actionable. We can reopen or reuse once ready...

**Pull request closed without merging**
