### PR TITLE
Updates usages of ExternalCommand to conform to new signature

### PR DESCRIPTION
**Pull request by sergiocampama**
This is being added as part of https://github.com/apple/swift-llbuild/pull/619

### CODE REVIEW

**Comment by sergiocampama** [comment]
apple/swift-llbuild#619

@swift-ci Please smoke test

**Comment by aciidb0mb3r** [comment]
The self hosted bots don't support cross-repository testing so don't worry about them.

**Comment by sergiocampama** [comment]
apple/swift-llbuild#619

@swift-ci Please smoke test

**Comment by sergiocampama** [comment]
@swift-ci Please smoke test

**Comment by sergiocampama** [comment]
@swift-ci Please smoke test

**Pull request merged**
