### PR TITLE
Remove extraneous `#if os` checks when using JSONEncoder

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by jakepetroules** [comment]
By the way, why still using "OSX" and not "macOS" for #available? Do we still have to build with an older version of Swift?

**Comment by aciidb0mb3r** [comment]
"meh" Maybe the Swift compiler emit a warning ;)

**Pull request merged**
