### PR TITLE
Fix typo in comment in ResolvedModels.swift

### PR DESCRIPTION
**Pull request by MaxDesiatov**
exectutable -> executable

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
The self-hosted CI failure seems to be completely unrelated (`Xcode-beta.app`? 🤔)

```
01:02:16 error: terminated(1): /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec/swift/pm/swiftpm-xctest-helper /Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-master/swiftpm/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest 
/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/TemporaryFile.jhNCjW output:
01:02:16     error: unableToLoadBundle("/Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-master/swiftpm/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest")
01:02:16     2020-06-11 17:02:15.989 swiftpm-xctest-helper[4183:38485] 
Error loading /Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-master/swiftpm/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest/Contents/MacOS/SwiftPMPackageTests:  
dlopen(/Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-master/swiftpm/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest/Contents/MacOS/SwiftPMPackageTests, 265): 
Library not loaded: /System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit
01:02:16       Referenced from: /Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-master/swiftpm/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest/Contents/MacOS/SwiftPMPackageTests
01:02:16       Reason: image not found
01:02:16     
```

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Pull request merged**
