### PR TITLE
[PackageModel] Clean up some legacy uses of "module" term.

### PR DESCRIPTION
**Pull request by ddunbar**

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
omg, thank you

**Comment by aciidb0mb3r** [comment]
Note: there is no auto-merging to swift-4.1-branch, you may want to cherry-pick.

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Pull request merged**
