### PR TITLE
[5.2] Don't pass / as default sysroot on Linux

### PR DESCRIPTION
**Pull request by drexin**

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by abertelrud** [comment]
The build failures looks unrelated, but it would be good to understand what's going on there before merging.

**Comment by abertelrud** [comment]
Oh, and as this is 5.2, we would need release manager's approval anyway.

**Comment by abertelrud** [comment]
The build failures seem to be because the test is using the main branch version of the compiler and not the 5.2 version.

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Release manager has approved, but looks like the merging is still blocked (seems that @aciidb0mb3r must also approve, as the code owner listed for 5.2?).

**Comment by drexin** [comment]
@swift-ci test macos

**Comment by drexin** [comment]
@swift-ci smoke test macos

**Comment by shahmishal** [comment]
@swift-ci test 5.2 macOS

**Pull request merged**
