### PR TITLE
☣️ EXPERIMENTAL: Use ++ for concatenation

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
Related to https://github.com/apple/swift/pull/15054

**Comment by hartbit** [comment]
@moiseev 😳 is this an early April Fools joke?

**Comment by moiseev** [comment]
@hartbit not at all.

**Comment by moiseev** [comment]
Primarily because addition and concatenation are different operations, but there is also a chance that removing this `+` overload would help the type-checker to solve *too complex expressions*.

**Comment by hartbit** [comment]
Ah, right! Makes sense.

**Comment by hartbit** [comment]
@moiseev Should this PR still be open or does it need to be closed?

**Comment by moiseev** [comment]
@hartbit closing for now, since it needs a major rebase. Thanks!

**Pull request closed without merging**
