### PR TITLE
Handle both SwiftArgParser 0.3.x and 0.4.x output.

### PR DESCRIPTION
**Pull request by shahmishal**
Cherry-picking this change in release/5.4 to unblock Apple Silicon bot.

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by tomerd — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Comment by tomerd** [comment]
@shahmishal is this ready to be merged? also note we would need a corresponding PR for release/5.5 branch if this needs to make it into 5.5

**Comment by shahmishal** [comment]
@tomerd I thought this was merged before we branched for release/5.5

**Comment by tomerd** [comment]
@tomerd I thought this was merged before we branched for release/5.5

oh sorry, you are correct, I misread the target branch

**Pull request merged**
