### PR TITLE
Fix bugs in builds that are run from a command plugin

### PR DESCRIPTION
**Pull request by abertelrud**
Command plugins can call back to SwiftPM to build one or more targets.  But the parameters passed by the plugin weren't being passed through to the BuildOperation, which instead used the ones that had been set on the SwiftTool.  The set of returned built artifacts also wasn't fixed properly.

### Motivation:

This fixes bugs in the documented behavior or package command plugins, a new feature in SwiftPM 5.6.

### Modifications:

- add parameters to SwiftTool.createBuildOperation() to allow build parameters and log level to be customized
- pass through the parameters that had been been received by SwiftPackageTool
- filter the returned artifacts based on not just what could be built but what was requested to be built
- properly collect the log based on the verbosity level and pass it on back to the plugin
- add a unit test to check these bugfixes and also custom compiler flags

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]

**Comment by abertelrud** [comment]
Looks like the builder has 5.3.2:
```
22:46:24 swift --version
22:46:24 + swift --version
22:46:27 Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
22:46:27 Target: x86_64-apple-darwin19.6.0
22:46:27 
22:46:27 ./swiftpm/Utilities/build-using-self 
22:46:27 + ./swiftpm/Utilities/build-using-self
22:46:27 Current directory is /Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm
22:46:27 + swift package update
22:46:28 
/Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm: error: package at '/Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm' is using Swift tools version 5.5.0 but the installed version is 5.3.0
```
@shahmishal  That seems unexpected, do you know if there's a problem with the CI here?

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
https://github.com/apple/swift/pull/40954
@swift-ci please smoke test linux

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Looks like the macOS failure is still because the hosting toolchain is Swift 5.3 when SwiftPM now needs 5.5.  @shahmishal sorry to trouble you again, is it possible to fix this so that we use the 5.5 compiler that SwiftPM requires?  If there's something we can reconfigure on our end please let me know.  Thanks!

**Comment by abertelrud** [comment]
@swift-ci please smoke test macos platform

**Comment by abertelrud** [comment]
Looks like it found a builder with a new enough Xcode / SwiftPM on it this time.

**Pull request merged**
