### PR TITLE
[Collections] Export PackageCollectionsSigning as library

### PR DESCRIPTION
**Pull request by yim-lee**
We will add signing to [the set of collections tools](https://github.com/apple/swift-package-collection-generator), and for that we'd need `PackageCollectionsSigning`.

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Review by tomerd — APPROVED** [review]
@neonichu may have opinions on this

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Pull request merged**
